[
    {
        "number": 2,
        "created_at": "2024-05-19T17:26:29Z",
        "updated_at": "2024-05-19T17:26:30Z",
        "url": "https://api.github.com/repos/username/blaze/code-scanning/alerts/2",
        "html_url": "https://github.com/username/blaze/security/code-scanning/2",
        "state": "open",
        "fixed_at": null,
        "dismissed_by": null,
        "dismissed_at": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "rule": {
            "id": "py/stack-trace-exposure",
            "severity": "error",
            "description": "Information exposure through an exception",
            "name": "py/stack-trace-exposure",
            "tags": [
                "external/cwe/cwe-209",
                "external/cwe/cwe-497",
                "security"
            ],
            "security_severity_level": "medium"
        },
        "tool": {
            "name": "CodeQL",
            "guid": null,
            "version": "2.17.4"
        },
        "most_recent_instance": {
            "ref": "refs/heads/master",
            "analysis_key": ".github/workflows/codeql.yml:analyze",
            "environment": "{\"build-mode\":\"none\",\"language\":\"python\"}",
            "category": "/language:python",
            "state": "open",
            "commit_sha": "d7f64f373f61437474878aeeba914d7dda98b12b",
            "message": {
                "text": "Stack trace information flows to this location and may be exposed to an external user."
            },
            "location": {
                "path": "blaze/server/server.py",
                "start_line": 662,
                "end_line": 662,
                "start_column": 21,
                "end_column": 56
            },
            "classifications": []
        },
        "instances_url": "https://api.github.com/repos/username/blaze/code-scanning/alerts/2/instances"
    },
    {
        "number": 1,
        "created_at": "2024-05-19T17:26:29Z",
        "updated_at": "2024-05-19T17:26:30Z",
        "url": "https://api.github.com/repos/username/blaze/code-scanning/alerts/1",
        "html_url": "https://github.com/username/blaze/security/code-scanning/1",
        "state": "open",
        "fixed_at": null,
        "dismissed_by": null,
        "dismissed_at": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "rule": {
            "id": "py/stack-trace-exposure",
            "severity": "error",
            "description": "Information exposure through an exception",
            "name": "py/stack-trace-exposure",
            "tags": [
                "external/cwe/cwe-209",
                "external/cwe/cwe-497",
                "security"
            ],
            "security_severity_level": "medium"
        },
        "tool": {
            "name": "CodeQL",
            "guid": null,
            "version": "2.17.4"
        },
        "most_recent_instance": {
            "ref": "refs/heads/master",
            "analysis_key": ".github/workflows/codeql.yml:analyze",
            "environment": "{\"build-mode\":\"none\",\"language\":\"python\"}",
            "category": "/language:python",
            "state": "open",
            "commit_sha": "d7f64f373f61437474878aeeba914d7dda98b12b",
            "message": {
                "text": "Stack trace information flows to this location and may be exposed to an external user."
            },
            "location": {
                "path": "blaze/server/server.py",
                "start_line": 657,
                "end_line": 657,
                "start_column": 21,
                "end_column": 50
            },
            "classifications": []
        },
        "instances_url": "https://api.github.com/repos/username/blaze/code-scanning/alerts/1/instances"
    }
]