[
    {
        "number": 36,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "requests"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-9wx4-h78v-vm56",
            "cve_id": "CVE-2024-35195",
            "summary": "Requests `Session` object does not verify requests after making first request with verify=False",
            "description": "When making requests through a Requests `Session`, if the first request is made with `verify=False` to disable cert verification, all subsequent requests to the same origin will continue to ignore cert verification regardless of changes to the value of `verify`. This behavior will continue for the lifecycle of the connection in the connection pool.\n\n### Remediation\nAny of these options can be used to remediate the current issue, we highly recommend upgrading as the preferred mitigation.\n\n* Upgrade to `requests>=2.32.0`.\n* For `requests<2.32.0`, avoid setting `verify=False` for the first request to a host while using a Requests Session.\n* For `requests<2.32.0`, call `close()` on `Session` objects to clear existing connections if `verify=False` is used.\n\n### Related Links\n* https://github.com/psf/requests/pull/6655",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-9wx4-h78v-vm56",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-35195",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56"
                },
                {
                    "url": "https://github.com/psf/requests/pull/6655"
                },
                {
                    "url": "https://github.com/psf/requests/commit/a58d7f2ffb4d00b46dca2d70a3932a0b37e22fac"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-35195"
                },
                {
                    "url": "https://github.com/advisories/GHSA-9wx4-h78v-vm56"
                }
            ],
            "published_at": "2024-05-20T20:15:00Z",
            "updated_at": "2024-05-20T22:07:29Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "requests"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 2.32.0",
                    "first_patched_version": {
                        "identifier": "2.32.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N",
                "score": 5.6
            },
            "cwes": [
                {
                    "cwe_id": "CWE-670",
                    "name": "Always-Incorrect Control Flow Implementation"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "requests"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 2.32.0",
            "first_patched_version": {
                "identifier": "2.32.0"
            }
        },
        "url": "https://api.github.com/repos/username/minigrad/dependabot/alerts/36",
        "html_url": "https://github.com/username/minigrad/security/dependabot/36",
        "created_at": "2024-05-24T01:34:25Z",
        "updated_at": "2024-05-24T01:34:25Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 35,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "Jinja2"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-h75v-3vvj-5mfj",
            "cve_id": "CVE-2024-34064",
            "summary": "Jinja vulnerable to HTML attribute injection when passing user input as keys to xmlattr filter",
            "description": "The `xmlattr` filter in affected versions of Jinja accepts keys containing non-attribute characters. XML/HTML attributes cannot contain spaces, `/`, `>`, or `=`, as each would then be interpreted as starting a separate attribute. If an application accepts keys (as opposed to only values) as user input, and renders these in pages that other users see as well, an attacker could use this to inject other attributes and perform XSS. The fix for the previous GHSA-h5c8-rqwp-cp95 CVE-2024-22195 only addressed spaces but not other characters.\n\nAccepting keys as user input is now explicitly considered an unintended use case of the `xmlattr` filter, and code that does so without otherwise validating the input should be flagged as insecure, regardless of Jinja version. Accepting _values_ as user input continues to be safe.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-h75v-3vvj-5mfj",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-34064",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/pallets/jinja/security/advisories/GHSA-h75v-3vvj-5mfj"
                },
                {
                    "url": "https://github.com/pallets/jinja/commit/0668239dc6b44ef38e7a6c9f91f312fd4ca581cb"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-34064"
                },
                {
                    "url": "https://github.com/advisories/GHSA-h75v-3vvj-5mfj"
                }
            ],
            "published_at": "2024-05-06T14:20:59Z",
            "updated_at": "2024-05-06T16:17:32Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Jinja2"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 3.1.4",
                    "first_patched_version": {
                        "identifier": "3.1.4"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N",
                "score": 5.4
            },
            "cwes": [
                {
                    "cwe_id": "CWE-79",
                    "name": "Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "Jinja2"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 3.1.4",
            "first_patched_version": {
                "identifier": "3.1.4"
            }
        },
        "url": "https://api.github.com/repos/username/minigrad/dependabot/alerts/35",
        "html_url": "https://github.com/username/minigrad/security/dependabot/35",
        "created_at": "2024-05-24T01:34:25Z",
        "updated_at": "2024-05-24T01:34:25Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 34,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "scikit-learn"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-jjw5-xxj6-pcv5",
            "cve_id": "CVE-2020-13092",
            "summary": "scikit-learn Deserialization of Untrusted Data",
            "description": "scikit-learn (aka sklearn) through 0.23.0 can unserialize and execute commands from an untrusted file that is passed to the `joblib.load()` function, if `__reduce__` makes an `os.system call`.\nNOTE: third parties dispute this issue because the joblib.load() function is documented as unsafe and it is the user's responsibility to use the function in a secure manner.",
            "severity": "critical",
            "identifiers": [
                {
                    "value": "GHSA-jjw5-xxj6-pcv5",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2020-13092",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2020-13092"
                },
                {
                    "url": "https://github.com/0FuzzingQ/vuln/blob/master/sklearn%20unserialize.md"
                },
                {
                    "url": "https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations"
                },
                {
                    "url": "https://github.com/advisories/GHSA-jjw5-xxj6-pcv5"
                }
            ],
            "published_at": "2022-05-24T17:17:59Z",
            "updated_at": "2024-04-22T22:55:45Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "scikit-learn"
                    },
                    "severity": "critical",
                    "vulnerable_version_range": "<= 0.23.0",
                    "first_patched_version": null
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                "score": 9.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-502",
                    "name": "Deserialization of Untrusted Data"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "scikit-learn"
            },
            "severity": "critical",
            "vulnerable_version_range": "<= 0.23.0",
            "first_patched_version": null
        },
        "url": "https://api.github.com/repos/username/minigrad/dependabot/alerts/34",
        "html_url": "https://github.com/username/minigrad/security/dependabot/34",
        "created_at": "2024-05-24T01:34:24Z",
        "updated_at": "2024-05-24T01:34:24Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 33,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "idna"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-jjg7-2v4v-x38h",
            "cve_id": "CVE-2024-3651",
            "summary": "Internationalized Domain Names in Applications (IDNA) vulnerable to denial of service from specially crafted inputs to idna.encode",
            "description": "### Impact\nA specially crafted argument to the `idna.encode()` function could consume significant resources. This may lead to a denial-of-service.\n\n### Patches\nThe function has been refined to reject such strings without the associated resource consumption in version 3.7.\n\n### Workarounds\nDomain names cannot exceed 253 characters in length, if this length limit is enforced prior to passing the domain to the `idna.encode()` function it should no longer consume significant resources. This is triggered by arbitrarily large inputs that would not occur in normal usage, but may be passed to the library assuming there is no preliminary input validation by the higher-level application.\n\n### References\n* https://huntr.com/bounties/93d78d07-d791-4b39-a845-cbfabc44aadb",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-jjg7-2v4v-x38h",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-3651",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/kjd/idna/security/advisories/GHSA-jjg7-2v4v-x38h"
                },
                {
                    "url": "https://github.com/advisories/GHSA-jjg7-2v4v-x38h"
                }
            ],
            "published_at": "2024-04-11T21:32:40Z",
            "updated_at": "2024-04-11T21:32:40Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "idna"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 3.7",
                    "first_patched_version": {
                        "identifier": "3.7"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 6.2
            },
            "cwes": [
                {
                    "cwe_id": "CWE-400",
                    "name": "Uncontrolled Resource Consumption"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "idna"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 3.7",
            "first_patched_version": {
                "identifier": "3.7"
            }
        },
        "url": "https://api.github.com/repos/username/minigrad/dependabot/alerts/33",
        "html_url": "https://github.com/username/minigrad/security/dependabot/33",
        "created_at": "2024-05-24T01:34:24Z",
        "updated_at": "2024-05-24T01:34:24Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 32,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "jupyterlab"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-44cc-43rp-5947",
            "cve_id": "CVE-2024-22421",
            "summary": "JupyterLab vulnerable to potential authentication and CSRF tokens leak",
            "description": "### Impact\nUsers of JupyterLab who click on a malicious link may get their `Authorization` and `XSRFToken` tokens exposed to a third party when running an older `jupyter-server` version.\n\n### Patches\nJupyterLab 4.1.0b2, 4.0.11, and 3.6.7 were patched.\n\n### Workarounds\nNo workaround has been identified, however users should ensure to upgrade `jupyter-server` to version 2.7.2 or newer which includes a redirect vulnerability fix.\n\n### References\n\nVulnerability reported by user @davwwwx via the [bug bounty program](https://app.intigriti.com/programs/jupyter/jupyter/detail) [sponsored by the European Commission](https://commission.europa.eu/news/european-commissions-open-source-programme-office-starts-bug-bounties-2022-01-19_en) and hosted on the [Intigriti platform](https://www.intigriti.com/).\n",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-44cc-43rp-5947",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-22421",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/jupyterlab/jupyterlab/security/advisories/GHSA-44cc-43rp-5947"
                },
                {
                    "url": "https://github.com/jupyterlab/jupyterlab/commit/1ef7a4fa0202ebdf663e1cc0b45c8813a34a0b96"
                },
                {
                    "url": "https://github.com/jupyterlab/jupyterlab/commit/fccd83dc4441da0384ee3fd1322c3b2d9ad4caaa"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-22421"
                },
                {
                    "url": "https://github.com/jupyterlab/jupyterlab/commit/19bd9b96cb2e77170a67e43121637d0b5619e8c6"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/UQJKNRDRFMKGVRIYNNN6CKMNJDNYWO2H/"
                },
                {
                    "url": "https://github.com/advisories/GHSA-44cc-43rp-5947"
                }
            ],
            "published_at": "2024-01-19T20:28:10Z",
            "updated_at": "2024-02-10T05:07:37Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "jupyterlab"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 4.0.0, <= 4.0.10",
                    "first_patched_version": {
                        "identifier": "4.0.11"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "jupyterlab"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "<= 3.6.6",
                    "first_patched_version": {
                        "identifier": "3.6.7"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "notebook"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 7.0.0, <= 7.0.6",
                    "first_patched_version": {
                        "identifier": "7.0.7"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:L/A:L",
                "score": 7.6
            },
            "cwes": [
                {
                    "cwe_id": "CWE-200",
                    "name": "Exposure of Sensitive Information to an Unauthorized Actor"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "jupyterlab"
            },
            "severity": "high",
            "vulnerable_version_range": "<= 3.6.6",
            "first_patched_version": {
                "identifier": "3.6.7"
            }
        },
        "url": "https://api.github.com/repos/username/minigrad/dependabot/alerts/32",
        "html_url": "https://github.com/username/minigrad/security/dependabot/32",
        "created_at": "2024-05-24T01:34:24Z",
        "updated_at": "2024-05-24T01:34:24Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 31,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "jinja2"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-h5c8-rqwp-cp95",
            "cve_id": "CVE-2024-22195",
            "summary": "Jinja vulnerable to HTML attribute injection when passing user input as keys to xmlattr filter",
            "description": "The `xmlattr` filter in affected versions of Jinja accepts keys containing spaces. XML/HTML attributes cannot contain spaces, as each would then be interpreted as a separate attribute. If an application accepts keys (as opposed to only values) as user input, and renders these in pages that other users see as well, an attacker could use this to inject other attributes and perform XSS. Note that accepting keys as user input is not common or a particularly intended use case of the `xmlattr` filter, and an application doing so should already be verifying what keys are provided regardless of this fix.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-h5c8-rqwp-cp95",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-22195",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/pallets/jinja/security/advisories/GHSA-h5c8-rqwp-cp95"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-22195"
                },
                {
                    "url": "https://github.com/pallets/jinja/commit/716795349a41d4983a9a4771f7d883c96ea17be7"
                },
                {
                    "url": "https://github.com/pallets/jinja/releases/tag/3.1.3"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5XCWZD464AJJJUBOO7CMPXQ4ROBC6JX2/"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2024/01/msg00010.html"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DELCVUUYX75I5K4Q5WMJG4MUZJA6VAIP/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/O7YWRBX6JQCWC2XXCTZ55C7DPMGICCN3/"
                },
                {
                    "url": "https://github.com/advisories/GHSA-h5c8-rqwp-cp95"
                }
            ],
            "published_at": "2024-01-11T15:20:48Z",
            "updated_at": "2024-01-27T03:30:20Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "jinja2"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 3.1.3",
                    "first_patched_version": {
                        "identifier": "3.1.3"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:N",
                "score": 5.4
            },
            "cwes": [
                {
                    "cwe_id": "CWE-79",
                    "name": "Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "jinja2"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 3.1.3",
            "first_patched_version": {
                "identifier": "3.1.3"
            }
        },
        "url": "https://api.github.com/repos/username/minigrad/dependabot/alerts/31",
        "html_url": "https://github.com/username/minigrad/security/dependabot/31",
        "created_at": "2024-05-24T01:34:24Z",
        "updated_at": "2024-05-24T01:34:24Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 30,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "urllib3"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-g4mx-q9vg-27p4",
            "cve_id": "CVE-2023-45803",
            "summary": "urllib3's request body not stripped after redirect from 303 status changes request method to GET",
            "description": "urllib3 previously wouldn't remove the HTTP request body when an HTTP redirect response using status 303 \"See Other\" after the request had its method changed from one that could accept a request body (like `POST`) to `GET` as is required by HTTP RFCs. Although the behavior of removing the request body is not specified in the section for redirects, it can be inferred by piecing together information from different sections and we have observed the behavior in other major HTTP client implementations like curl and web browsers.\n\nFrom [RFC 9110 Section 9.3.1](https://www.rfc-editor.org/rfc/rfc9110.html#name-get):\n\n> A client SHOULD NOT generate content in a GET request unless it is made directly to an origin server that has previously indicated, in or out of band, that such a request has a purpose and will be adequately supported.\n\n## Affected usages\n\nBecause the vulnerability requires a previously trusted service to become compromised in order to have an impact on confidentiality we believe the exploitability of this vulnerability is low. Additionally, many users aren't putting sensitive data in HTTP request bodies, if this is the case then this vulnerability isn't exploitable.\n\nBoth of the following conditions must be true to be affected by this vulnerability:\n\n* If you're using urllib3 and submitting sensitive information in the HTTP request body (such as form data or JSON)\n* The origin service is compromised and starts redirecting using 303 to a malicious peer or the redirected-to service becomes compromised.\n\n## Remediation\n\nYou can remediate this vulnerability with any of the following steps:\n\n* Upgrade to a patched version of urllib3 (v1.26.18 or v2.0.7)\n* Disable redirects for services that you aren't expecting to respond with redirects with `redirects=False`.\n* Disable automatic redirects with `redirects=False` and handle 303 redirects manually by stripping the HTTP request body.\n",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-g4mx-q9vg-27p4",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-45803",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/urllib3/urllib3/security/advisories/GHSA-g4mx-q9vg-27p4"
                },
                {
                    "url": "https://github.com/urllib3/urllib3/commit/4e50fbc5db74e32cabd5ccc1ab81fc103adfe0b3"
                },
                {
                    "url": "https://github.com/urllib3/urllib3/commit/b594c5ceaca38e1ac215f916538fb128e3526a36"
                },
                {
                    "url": "https://github.com/urllib3/urllib3/releases/tag/1.26.18"
                },
                {
                    "url": "https://github.com/urllib3/urllib3/releases/tag/2.0.7"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-45803"
                },
                {
                    "url": "https://github.com/urllib3/urllib3/commit/4e98d57809dacab1cbe625fddeec1a290c478ea9"
                },
                {
                    "url": "https://www.rfc-editor.org/rfc/rfc9110.html#name-get"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PPDPLM6UUMN55ESPQWJFLLIZY4ZKCNRX/"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/urllib3/PYSEC-2023-212.yaml"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4R2Y5XK3WALSR3FNAGN7JBYV2B343ZKB/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5/"
                },
                {
                    "url": "https://github.com/advisories/GHSA-g4mx-q9vg-27p4"
                }
            ],
            "published_at": "2023-10-17T20:15:25Z",
            "updated_at": "2023-11-06T16:24:46Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "urllib3"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": ">= 2.0.0, < 2.0.7",
                    "first_patched_version": {
                        "identifier": "2.0.7"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "urllib3"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": ">= 0, < 1.26.18",
                    "first_patched_version": {
                        "identifier": "1.26.18"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:A/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N",
                "score": 4.2
            },
            "cwes": [
                {
                    "cwe_id": "CWE-200",
                    "name": "Exposure of Sensitive Information to an Unauthorized Actor"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "urllib3"
            },
            "severity": "medium",
            "vulnerable_version_range": ">= 0, < 1.26.18",
            "first_patched_version": {
                "identifier": "1.26.18"
            }
        },
        "url": "https://api.github.com/repos/username/minigrad/dependabot/alerts/30",
        "html_url": "https://github.com/username/minigrad/security/dependabot/30",
        "created_at": "2024-05-24T01:34:24Z",
        "updated_at": "2024-05-24T01:34:24Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 29,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "urllib3"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-v845-jxx5-vc9f",
            "cve_id": "CVE-2023-43804",
            "summary": "`Cookie` HTTP header isn't stripped on cross-origin redirects",
            "description": "urllib3 doesn't treat the `Cookie` HTTP header special or provide any helpers for managing cookies over HTTP, that is the responsibility of the user. However, it is possible for a user to specify a `Cookie` header and unknowingly leak information via HTTP redirects to a different origin if that user doesn't disable redirects explicitly.\n\nUsers **must** handle redirects themselves instead of relying on urllib3's automatic redirects to achieve safe processing of the `Cookie` header, thus we decided to strip the header by default in order to further protect users who aren't using the correct approach.\n\n## Affected usages\n\nWe believe the number of usages affected by this advisory is low. It requires all of the following to be true to be exploited:\n\n* Using an affected version of urllib3 (patched in v1.26.17 and v2.0.6)\n* Using the `Cookie` header on requests, which is mostly typical for impersonating a browser.\n* Not disabling HTTP redirects\n* Either not using HTTPS or for the origin server to redirect to a malicious origin.\n\n## Remediation\n\n* Upgrading to at least urllib3 v1.26.17 or v2.0.6\n* Disabling HTTP redirects using `redirects=False` when sending requests.\n* Not using the `Cookie` header.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-v845-jxx5-vc9f",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-43804",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/urllib3/urllib3/security/advisories/GHSA-v845-jxx5-vc9f"
                },
                {
                    "url": "https://github.com/urllib3/urllib3/commit/01220354d389cd05474713f8c982d05c9b17aafb"
                },
                {
                    "url": "https://github.com/urllib3/urllib3/commit/644124ecd0b6e417c527191f866daa05a5a2056d"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-43804"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2023/10/msg00012.html"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/urllib3/PYSEC-2023-192.yaml"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/I3PR7C6RJ6JUBQKIJ644DMIJSUP36VDY/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NDAGZXYJ7H2G3SB47M453VQVNAWKAEJJ/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5/"
                },
                {
                    "url": "https://github.com/advisories/GHSA-v845-jxx5-vc9f"
                }
            ],
            "published_at": "2023-10-02T23:27:05Z",
            "updated_at": "2023-11-04T00:30:22Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "urllib3"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": ">= 2.0.0, < 2.0.6",
                    "first_patched_version": {
                        "identifier": "2.0.6"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "urllib3"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 1.26.17",
                    "first_patched_version": {
                        "identifier": "1.26.17"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:H/A:N",
                "score": 5.9
            },
            "cwes": [
                {
                    "cwe_id": "CWE-200",
                    "name": "Exposure of Sensitive Information to an Unauthorized Actor"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "urllib3"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 1.26.17",
            "first_patched_version": {
                "identifier": "1.26.17"
            }
        },
        "url": "https://api.github.com/repos/username/minigrad/dependabot/alerts/29",
        "html_url": "https://github.com/username/minigrad/security/dependabot/29",
        "created_at": "2024-05-24T01:34:24Z",
        "updated_at": "2024-05-24T01:34:24Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 28,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "certifi"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-xqr8-7jwr-rhp7",
            "cve_id": "CVE-2023-37920",
            "summary": "Removal of e-Tugra root certificate",
            "description": "Certifi 2023.07.22 removes root certificates from \"e-Tugra\" from the root store. These are in the process of being removed from Mozilla's trust store.\n\n e-Tugra's root certificates are being removed pursuant to an investigation prompted by reporting of security issues in their systems. Conclusions of Mozilla's investigation can be found [here](https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/C-HrP1SEq1A).",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-xqr8-7jwr-rhp7",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-37920",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/certifi/python-certifi/security/advisories/GHSA-xqr8-7jwr-rhp7"
                },
                {
                    "url": "https://github.com/certifi/python-certifi/commit/8fb96ed81f71e7097ed11bc4d9b19afd7ea5c909"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-37920"
                },
                {
                    "url": "https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/C-HrP1SEq1A"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/certifi/PYSEC-2023-135.yaml"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5EX6NG7WUFNUKGFHLM35KHHU3GAKXRTG/"
                },
                {
                    "url": "https://github.com/advisories/GHSA-xqr8-7jwr-rhp7"
                }
            ],
            "published_at": "2023-07-25T14:43:53Z",
            "updated_at": "2023-11-09T05:05:47Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "certifi"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 2015.4.28, < 2023.7.22",
                    "first_patched_version": {
                        "identifier": "2023.7.22"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-345",
                    "name": "Insufficient Verification of Data Authenticity"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "certifi"
            },
            "severity": "high",
            "vulnerable_version_range": ">= 2015.4.28, < 2023.7.22",
            "first_patched_version": {
                "identifier": "2023.7.22"
            }
        },
        "url": "https://api.github.com/repos/username/minigrad/dependabot/alerts/28",
        "html_url": "https://github.com/username/minigrad/security/dependabot/28",
        "created_at": "2024-05-24T01:34:24Z",
        "updated_at": "2024-05-24T01:34:24Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 27,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "tornado"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-qppv-j76h-2rpx",
            "cve_id": null,
            "summary": "Tornado vulnerable to HTTP request smuggling via improper parsing of `Content-Length` fields and chunk lengths",
            "description": "## Summary\nTornado interprets `-`, `+`, and `_` in chunk length and `Content-Length` values, which are not allowed by the HTTP RFCs. This can result in request smuggling when Tornado is deployed behind certain proxies that interpret those non-standard characters differently. This is known to apply to older versions of haproxy, although the current release is not affected.\n\n## Details\nTornado uses the `int` constructor to parse the values of `Content-Length` headers and chunk lengths in the following locations:\n### `tornado/http1connection.py:445`\n```python3\n            self._expected_content_remaining = int(headers[\"Content-Length\"])\n```\n### `tornado/http1connection.py:621`\n```python3\n                content_length = int(headers[\"Content-Length\"])  # type: Optional[int]\n```\n### `tornado/http1connection.py:671`\n```python3\n            chunk_len = int(chunk_len_str.strip(), 16)\n```\nBecause `int(\"0_0\") == int(\"+0\") == int(\"-0\") == int(\"0\")`, using the `int` constructor to parse and validate strings that should contain only ASCII digits is not a good strategy. \n\n",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-qppv-j76h-2rpx",
                    "type": "GHSA"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/tornadoweb/tornado/security/advisories/GHSA-qppv-j76h-2rpx"
                },
                {
                    "url": "https://github.com/tornadoweb/tornado/commit/b7a5dd29bb02950303ae96055082c12a1ea0a4fe"
                },
                {
                    "url": "https://github.com/advisories/GHSA-qppv-j76h-2rpx"
                }
            ],
            "published_at": "2023-08-14T21:34:17Z",
            "updated_at": "2023-09-07T20:25:28Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tornado"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 6.3.3",
                    "first_patched_version": {
                        "identifier": "6.3.3"
                    }
                }
            ],
            "cvss": {
                "vector_string": null,
                "score": 0.0
            },
            "cwes": [
                {
                    "cwe_id": "CWE-444",
                    "name": "Inconsistent Interpretation of HTTP Requests ('HTTP Request/Response Smuggling')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "tornado"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 6.3.3",
            "first_patched_version": {
                "identifier": "6.3.3"
            }
        },
        "url": "https://api.github.com/repos/username/minigrad/dependabot/alerts/27",
        "html_url": "https://github.com/username/minigrad/security/dependabot/27",
        "created_at": "2024-05-24T01:34:24Z",
        "updated_at": "2024-05-24T01:34:24Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 26,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "Pygments"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-mrwq-x4v8-fh7p",
            "cve_id": "CVE-2022-40896",
            "summary": "Pygments vulnerable to ReDoS",
            "description": "A ReDoS issue was discovered in `pygments/lexers/smithy.py` in Pygments until 2.15.0 via SmithyLexer.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-mrwq-x4v8-fh7p",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2022-40896",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-40896"
                },
                {
                    "url": "https://github.com/pygments/pygments/blob/master/pygments/lexers/smithy.py#L61"
                },
                {
                    "url": "https://github.com/pygments/pygments/commit/97eb3d5ec7c1b3ea4fcf9dee30a2309cf92bd194"
                },
                {
                    "url": "https://github.com/pygments/pygments/commit/dd52102c38ebe78cd57748e09f38929fd283ad04"
                },
                {
                    "url": "https://github.com/pygments/pygments/commit/fdf182a7af85b1deeeb637ca970d31935e7c9d52"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/pygments/PYSEC-2023-117.yaml"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/EZGMXALE3HSP4OXC7UUWIKX3OXKZDTY3"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/VUZO4BQCIY2S2KZYHERQMKURB7AHXDBO"
                },
                {
                    "url": "https://pypi.org/project/Pygments"
                },
                {
                    "url": "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages-part-2"
                },
                {
                    "url": "https://github.com/advisories/GHSA-mrwq-x4v8-fh7p"
                }
            ],
            "published_at": "2023-07-19T15:30:26Z",
            "updated_at": "2024-03-28T13:28:18Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Pygments"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 2.15.0",
                    "first_patched_version": {
                        "identifier": "2.15.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
                "score": 5.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-434",
                    "name": "Unrestricted Upload of File with Dangerous Type"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "Pygments"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 2.15.0",
            "first_patched_version": {
                "identifier": "2.15.0"
            }
        },
        "url": "https://api.github.com/repos/username/minigrad/dependabot/alerts/26",
        "html_url": "https://github.com/username/minigrad/security/dependabot/26",
        "created_at": "2024-05-24T01:34:24Z",
        "updated_at": "2024-05-24T01:34:24Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 25,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "joblib"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-6hrg-qmvc-2xh8",
            "cve_id": "CVE-2022-21797",
            "summary": "joblib vulnerable to arbitrary code execution",
            "description": "The package joblib from 0 and before 1.2.0 is vulnerable to Arbitrary Code Execution via the `pre_dispatch` flag in `Parallel()` class due to the `eval()` statement.",
            "severity": "critical",
            "identifiers": [
                {
                    "value": "GHSA-6hrg-qmvc-2xh8",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2022-21797",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-21797"
                },
                {
                    "url": "https://github.com/joblib/joblib/issues/1128"
                },
                {
                    "url": "https://github.com/joblib/joblib/pull/1321"
                },
                {
                    "url": "https://github.com/joblib/joblib/commit/b90f10efeb670a2cc877fb88ebb3f2019189e059"
                },
                {
                    "url": "https://security.snyk.io/vuln/SNYK-PYTHON-JOBLIB-3027033"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/BVOMMW37OXZWU2EV5ONAAS462IQEHZOF/"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2022/11/msg00020.html"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MJ5XTJS6OKJRRVXWFN5J67K3BYPEOBDF/"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2023/03/msg00027.html"
                },
                {
                    "url": "https://github.com/joblib/joblib/pull/1327"
                },
                {
                    "url": "https://github.com/joblib/joblib/pull/1352"
                },
                {
                    "url": "https://github.com/joblib/joblib/commit/6638b9e9711ad1ebbf6dd95aa7cee0dca9897b42"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/joblib/PYSEC-2022-288.yaml"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/BVOMMW37OXZWU2EV5ONAAS462IQEHZOF/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/MJ5XTJS6OKJRRVXWFN5J67K3BYPEOBDF/"
                },
                {
                    "url": "https://security.gentoo.org/glsa/202401-01"
                },
                {
                    "url": "https://github.com/advisories/GHSA-6hrg-qmvc-2xh8"
                }
            ],
            "published_at": "2022-09-27T00:00:22Z",
            "updated_at": "2024-04-22T21:11:28Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "joblib"
                    },
                    "severity": "critical",
                    "vulnerable_version_range": "< 1.2.0",
                    "first_patched_version": {
                        "identifier": "1.2.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                "score": 9.8
            },
            "cwes": []
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "joblib"
            },
            "severity": "critical",
            "vulnerable_version_range": "< 1.2.0",
            "first_patched_version": {
                "identifier": "1.2.0"
            }
        },
        "url": "https://api.github.com/repos/username/minigrad/dependabot/alerts/25",
        "html_url": "https://github.com/username/minigrad/security/dependabot/25",
        "created_at": "2024-05-24T01:34:24Z",
        "updated_at": "2024-05-24T01:34:24Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 24,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "tornado"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-hj3f-6gcp-jg8j",
            "cve_id": "CVE-2023-28370",
            "summary": "Open redirect in Tornado",
            "description": "Open redirect vulnerability in Tornado versions 6.3.1 and earlier allows a remote unauthenticated attacker to redirect a user to an arbitrary web site and conduct a phishing attack by having user access a specially crafted URL.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-hj3f-6gcp-jg8j",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-28370",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-28370"
                },
                {
                    "url": "https://github.com/tornadoweb/tornado/releases/tag/v6.3.2"
                },
                {
                    "url": "https://jvn.jp/en/jp/JVN45127776/"
                },
                {
                    "url": "https://github.com/tornadoweb/tornado/commit/32ad07c54e607839273b4e1819c347f5c8976b2f"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/tornado/PYSEC-2023-75.yaml"
                },
                {
                    "url": "https://github.com/advisories/GHSA-hj3f-6gcp-jg8j"
                }
            ],
            "published_at": "2023-05-25T12:30:16Z",
            "updated_at": "2023-11-12T05:01:11Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tornado"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 6.3.2",
                    "first_patched_version": {
                        "identifier": "6.3.2"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
                "score": 6.1
            },
            "cwes": [
                {
                    "cwe_id": "CWE-601",
                    "name": "URL Redirection to Untrusted Site ('Open Redirect')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "tornado"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 6.3.2",
            "first_patched_version": {
                "identifier": "6.3.2"
            }
        },
        "url": "https://api.github.com/repos/username/minigrad/dependabot/alerts/24",
        "html_url": "https://github.com/username/minigrad/security/dependabot/24",
        "created_at": "2024-05-24T01:34:23Z",
        "updated_at": "2024-05-24T01:34:23Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 23,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "requests"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-j8r2-6x86-q33q",
            "cve_id": "CVE-2023-32681",
            "summary": "Unintended leak of Proxy-Authorization header in requests",
            "description": "### Impact\n\nSince Requests v2.3.0, Requests has been vulnerable to potentially leaking `Proxy-Authorization` headers to destination servers, specifically during redirects to an HTTPS origin. This is a product of how `rebuild_proxies` is used to recompute and [reattach the `Proxy-Authorization` header](https://github.com/psf/requests/blob/f2629e9e3c7ce3c3c8c025bcd8db551101cbc773/requests/sessions.py#L319-L328) to requests when redirected. Note this behavior has _only_ been observed to affect proxied requests when credentials are supplied in the URL user information component (e.g. `https://username:password@proxy:8080`).\n\n**Current vulnerable behavior(s):**\n\n1. HTTP → HTTPS: **leak**\n2. HTTPS → HTTP: **no leak**\n3. HTTPS → HTTPS: **leak**\n4. HTTP → HTTP: **no leak**\n\nFor HTTP connections sent through the proxy, the proxy will identify the header in the request itself and remove it prior to forwarding to the destination server. However when sent over HTTPS, the `Proxy-Authorization` header must be sent in the CONNECT request as the proxy has no visibility into further tunneled requests. This results in Requests forwarding the header to the destination server unintentionally, allowing a malicious actor to potentially exfiltrate those credentials.\n\nThe reason this currently works for HTTPS connections in Requests is the `Proxy-Authorization` header is also handled by urllib3 with our usage of the ProxyManager in adapters.py with [`proxy_manager_for`](https://github.com/psf/requests/blob/f2629e9e3c7ce3c3c8c025bcd8db551101cbc773/requests/adapters.py#L199-L235). This will compute the required proxy headers in `proxy_headers` and pass them to the Proxy Manager, avoiding attaching them directly to the Request object. This will be our preferred option going forward for default usage.\n\n### Patches\nStarting in Requests v2.31.0, Requests will no longer attach this header to redirects with an HTTPS destination. This should have no negative impacts on the default behavior of the library as the proxy credentials are already properly being handled by urllib3's ProxyManager.\n\nFor users with custom adapters, this _may_ be potentially breaking if you were already working around this behavior. The previous functionality of `rebuild_proxies` doesn't make sense in any case, so we would encourage any users impacted to migrate any handling of Proxy-Authorization directly into their custom adapter.\n\n### Workarounds\nFor users who are not able to update Requests immediately, there is one potential workaround.\n\nYou may disable redirects by setting `allow_redirects` to `False` on all calls through Requests top-level APIs. Note that if you're currently relying on redirect behaviors, you will need to capture the 3xx response codes and ensure a new request is made to the redirect destination.\n```\nimport requests\nr = requests.get('http://github.com/', allow_redirects=False)\n```\n\n### Credits\n\nThis vulnerability was discovered and disclosed by the following individuals.\n\nDennis Brinkrolf, Haxolot (https://haxolot.com/)\nTobias Funke, (tobiasfunke93@gmail.com)",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-j8r2-6x86-q33q",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-32681",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/psf/requests/security/advisories/GHSA-j8r2-6x86-q33q"
                },
                {
                    "url": "https://github.com/psf/requests/commit/74ea7cf7a6a27a4eeb2ae24e162bcc942a6706d5"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-32681"
                },
                {
                    "url": "https://github.com/psf/requests/releases/tag/v2.31.0"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/requests/PYSEC-2023-74.yaml"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2023/06/msg00018.html"
                },
                {
                    "url": "https://security.gentoo.org/glsa/202309-08"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/AW7HNFGYP44RT3DUDQXG2QT3OEV2PJ7Y"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KOYASTZDGQG2BWLSNBPL3TQRL2G7QYNZ"
                },
                {
                    "url": "https://github.com/advisories/GHSA-j8r2-6x86-q33q"
                }
            ],
            "published_at": "2023-05-22T20:36:32Z",
            "updated_at": "2024-03-27T20:09:55Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "requests"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": ">= 2.3.0, < 2.31.0",
                    "first_patched_version": {
                        "identifier": "2.31.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:H/I:N/A:N",
                "score": 6.1
            },
            "cwes": [
                {
                    "cwe_id": "CWE-200",
                    "name": "Exposure of Sensitive Information to an Unauthorized Actor"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "requests"
            },
            "severity": "medium",
            "vulnerable_version_range": ">= 2.3.0, < 2.31.0",
            "first_patched_version": {
                "identifier": "2.31.0"
            }
        },
        "url": "https://api.github.com/repos/username/minigrad/dependabot/alerts/23",
        "html_url": "https://github.com/username/minigrad/security/dependabot/23",
        "created_at": "2024-05-24T01:34:23Z",
        "updated_at": "2024-05-24T01:34:23Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 22,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "IPython"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-29gw-9793-fvw7",
            "cve_id": "CVE-2023-24816",
            "summary": "IPython vulnerable to command injection via set_term_title",
            "description": "IPython provides an interactive Python shell and Jupyter kernel to use Python interactively. Versions prior to 8.10.0 are vulnerable to command injection in the `set_term_title` [function](https://github.com/ipython/ipython/blob/3f0bf05f072a91b2a3042d23ce250e5e906183fd/IPython/utils/terminal.py#L103-L117) under specific conditions. This has been patched in version 8.10.0.\n\n### Impact \nUsers are only vulnerable when calling this function in Windows in a Python environment where [ctypes](https://docs.python.org/3/library/ctypes.html) is not available. The dependency on ctypes in `IPython.utils._process_win32` prevents the vulnerable code from ever being reached (making it effectively dead code). However, as a library that could be used by another tool, `set_term_title` could introduce a vulnerability for dependencies. Currently `set_term_title` is only called with (semi-)trusted input that contain the current working directory of the current IPython session. If an attacker can control directory names, and manage to get a user to `cd` into this directory, then the attacker can execute arbitrary commands contained in the folder names.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-29gw-9793-fvw7",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-24816",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/ipython/ipython/security/advisories/GHSA-29gw-9793-fvw7"
                },
                {
                    "url": "https://github.com/ipython/ipython/commit/385d69325319a5972ee9b5983638e3617f21cb1f"
                },
                {
                    "url": "https://github.com/ipython/ipython/commit/991849c247fc208628879e7ca2923b3c218a5a75"
                },
                {
                    "url": "https://github.com/Carreau/ipython/blob/7557ade0ed927475d5ab5b573d0ea4febfb22683/docs/source/whatsnew/version8.rst#ipython-810"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-24816"
                },
                {
                    "url": "https://github.com/ipython/ipython/blob/3f0bf05f072a91b2a3042d23ce250e5e906183fd/IPython/utils/terminal.py#L103-L117"
                },
                {
                    "url": "https://github.com/ipython/ipython/blob/56e6925dfa50e2c7f4a6471547b8176275db7c25/IPython/utils/_process_win32.py#L20"
                },
                {
                    "url": "https://github.com/advisories/GHSA-29gw-9793-fvw7"
                }
            ],
            "published_at": "2023-02-10T19:55:53Z",
            "updated_at": "2023-09-02T05:03:05Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "IPython"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 8.10",
                    "first_patched_version": {
                        "identifier": "8.10"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:H/PR:N/UI:R/S:U/C:L/I:L/A:L",
                "score": 4.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-20",
                    "name": "Improper Input Validation"
                },
                {
                    "cwe_id": "CWE-78",
                    "name": "Improper Neutralization of Special Elements used in an OS Command ('OS Command Injection')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "IPython"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 8.10",
            "first_patched_version": {
                "identifier": "8.10"
            }
        },
        "url": "https://api.github.com/repos/username/minigrad/dependabot/alerts/22",
        "html_url": "https://github.com/username/minigrad/security/dependabot/22",
        "created_at": "2024-05-24T01:34:23Z",
        "updated_at": "2024-05-24T01:34:23Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 21,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "future"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-v3c5-jqr6-7qm8",
            "cve_id": "CVE-2022-40899",
            "summary": "Python Charmers Future denial of service vulnerability",
            "description": "An issue discovered in Python Charmers Future 0.18.2 and earlier allows remote attackers to cause a denial of service via crafted Set-Cookie header from malicious web server. This issue has been patched in version 0.18.3.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-v3c5-jqr6-7qm8",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2022-40899",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-40899"
                },
                {
                    "url": "https://github.com/python/cpython/pull/17157"
                },
                {
                    "url": "https://github.com/PythonCharmers/python-future/blob/master/src/future/backports/http/cookiejar.py#L215"
                },
                {
                    "url": "https://pypi.org/project/future/"
                },
                {
                    "url": "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/"
                },
                {
                    "url": "https://github.com/PythonCharmers/python-future/commit/c91d70b34ef0402aef3e9d04364ba98509dca76f"
                },
                {
                    "url": "https://github.com/PythonCharmers/python-future/pull/610"
                },
                {
                    "url": "https://github.com/advisories/GHSA-v3c5-jqr6-7qm8"
                }
            ],
            "published_at": "2022-12-23T00:30:23Z",
            "updated_at": "2023-01-28T05:06:22Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "future"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "<= 0.18.2",
                    "first_patched_version": {
                        "identifier": "0.18.3"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": []
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "future"
            },
            "severity": "high",
            "vulnerable_version_range": "<= 0.18.2",
            "first_patched_version": {
                "identifier": "0.18.3"
            }
        },
        "url": "https://api.github.com/repos/username/minigrad/dependabot/alerts/21",
        "html_url": "https://github.com/username/minigrad/security/dependabot/21",
        "created_at": "2024-05-24T01:34:23Z",
        "updated_at": "2024-05-24T01:34:23Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 20,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "certifi"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-43fp-rhv2-5gv8",
            "cve_id": "CVE-2022-23491",
            "summary": "Certifi removing TrustCor root certificate",
            "description": "Certifi 2022.12.07 removes root certificates from \"TrustCor\" from the root store. These are in the process of being removed from Mozilla's trust store.\n\nTrustCor's root certificates are being removed pursuant to an investigation prompted by media reporting that TrustCor's ownership also operated a business that produced spyware. Conclusions of Mozilla's investigation can be found [here](https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/oxX69KFvsm4/m/yLohoVqtCgAJ).",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-43fp-rhv2-5gv8",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2022-23491",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/certifi/python-certifi/security/advisories/GHSA-43fp-rhv2-5gv8"
                },
                {
                    "url": "https://github.com/certifi/python-certifi/commit/9e9e840925d7b8e76c76fdac1fab7e6e88c1c3b8"
                },
                {
                    "url": "https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/oxX69KFvsm4/m/yLohoVqtCgAJ"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-23491"
                },
                {
                    "url": "https://github.com/advisories/GHSA-43fp-rhv2-5gv8"
                }
            ],
            "published_at": "2022-12-07T23:05:18Z",
            "updated_at": "2023-01-29T05:05:37Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "certifi"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": ">= 2017.11.05, < 2022.12.07",
                    "first_patched_version": {
                        "identifier": "2022.12.07"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:C/C:N/I:H/A:N",
                "score": 6.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-345",
                    "name": "Insufficient Verification of Data Authenticity"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "certifi"
            },
            "severity": "medium",
            "vulnerable_version_range": ">= 2017.11.05, < 2022.12.07",
            "first_patched_version": {
                "identifier": "2022.12.07"
            }
        },
        "url": "https://api.github.com/repos/username/minigrad/dependabot/alerts/20",
        "html_url": "https://github.com/username/minigrad/security/dependabot/20",
        "created_at": "2024-05-24T01:34:23Z",
        "updated_at": "2024-05-24T01:34:23Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 19,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "torch"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-47fc-vmwq-366v",
            "cve_id": "CVE-2022-45907",
            "summary": "PyTorch vulnerable to arbitrary code execution",
            "description": "In PyTorch before trunk/89695, torch.jit.annotations.parse_type_line can cause arbitrary code execution because eval is used unsafely. The fix for this issue is available in version 1.13.1. There is a release checker in [issue #89855](https://github.com/pytorch/pytorch/issues/89855).",
            "severity": "critical",
            "identifiers": [
                {
                    "value": "GHSA-47fc-vmwq-366v",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2022-45907",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-45907"
                },
                {
                    "url": "https://github.com/pytorch/pytorch/issues/88868"
                },
                {
                    "url": "https://github.com/pytorch/pytorch/commit/767f6aa49fe20a2766b9843d01e3b7f7793df6a3"
                },
                {
                    "url": "https://github.com/pytorch/pytorch/issues/89855"
                },
                {
                    "url": "https://github.com/pytorch/pytorch/pull/89189"
                },
                {
                    "url": "https://github.com/pytorch/pytorch/releases/tag/v1.13.1"
                },
                {
                    "url": "https://github.com/advisories/GHSA-47fc-vmwq-366v"
                }
            ],
            "published_at": "2022-11-26T03:30:27Z",
            "updated_at": "2023-01-30T05:01:22Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "torch"
                    },
                    "severity": "critical",
                    "vulnerable_version_range": "<= 1.13.0",
                    "first_patched_version": {
                        "identifier": "1.13.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                "score": 9.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-77",
                    "name": "Improper Neutralization of Special Elements used in a Command ('Command Injection')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "torch"
            },
            "severity": "critical",
            "vulnerable_version_range": "<= 1.13.0",
            "first_patched_version": {
                "identifier": "1.13.1"
            }
        },
        "url": "https://api.github.com/repos/username/minigrad/dependabot/alerts/19",
        "html_url": "https://github.com/username/minigrad/security/dependabot/19",
        "created_at": "2024-05-24T01:34:23Z",
        "updated_at": "2024-05-24T01:34:23Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 18,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "jupyter-core"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-m678-f26j-3hrp",
            "cve_id": "CVE-2022-39286",
            "summary": "Execution with Unnecessary Privileges in JupyterApp",
            "description": "### Impact\n_What kind of vulnerability is it? Who is impacted?_\nWe’d like to disclose an arbitrary code execution vulnerability in `jupyter_core` that stems from `jupyter_core` executing untrusted files in the current working directory. This vulnerability allows one user to run code as another.\n\n\n### Patches\n_Has the problem been patched? What versions should users upgrade to?_\nUsers should upgrade to `jupyter_core>=4.11.2`.\n\n### Workarounds\n_Is there a way for users to fix or remediate the vulnerability without upgrading?_\nNo\n\n### References\n_Are there any links users can visit to find out more?_\nSimilar advisory in [IPython](https://github.com/advisories/GHSA-pq7m-3gw7-gq5x)\n\n",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-m678-f26j-3hrp",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2022-39286",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/jupyter/jupyter_core/security/advisories/GHSA-m678-f26j-3hrp"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-39286"
                },
                {
                    "url": "https://github.com/jupyter/jupyter_core/commit/1118c8ce01800cb689d51f655f5ccef19516e283"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/jupyter-core/PYSEC-2022-42974.yaml"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2022/11/msg00022.html"
                },
                {
                    "url": "https://security.gentoo.org/glsa/202301-04"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KKMP5OXXIX2QAUNVNJZ5UEQFKDYYJVBA/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YIDN7JMLK6AOMBQI4QPSW4MBQGWQ5NIN/"
                },
                {
                    "url": "https://www.debian.org/security/2023/dsa-5422"
                },
                {
                    "url": "https://github.com/advisories/GHSA-m678-f26j-3hrp"
                }
            ],
            "published_at": "2022-10-26T22:07:00Z",
            "updated_at": "2023-09-02T05:06:18Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "jupyter-core"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 4.11.2",
                    "first_patched_version": {
                        "identifier": "4.11.2"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
                "score": 8.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-250",
                    "name": "Execution with Unnecessary Privileges"
                },
                {
                    "cwe_id": "CWE-269",
                    "name": "Improper Privilege Management"
                },
                {
                    "cwe_id": "CWE-427",
                    "name": "Uncontrolled Search Path Element"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "jupyter-core"
            },
            "severity": "high",
            "vulnerable_version_range": "< 4.11.2",
            "first_patched_version": {
                "identifier": "4.11.2"
            }
        },
        "url": "https://api.github.com/repos/username/minigrad/dependabot/alerts/18",
        "html_url": "https://github.com/username/minigrad/security/dependabot/18",
        "created_at": "2024-05-24T01:34:23Z",
        "updated_at": "2024-05-24T01:34:23Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 17,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "urllib3"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-q2q7-5pp4-w6pg",
            "cve_id": "CVE-2021-33503",
            "summary": "Catastrophic backtracking in URL authority parser when passed URL containing many @ characters",
            "description": "### Impact\n\nWhen provided with a URL containing many `@` characters in the authority component the authority regular expression exhibits catastrophic backtracking causing a denial of service if a URL were passed as a parameter or redirected to via an HTTP redirect.\n\n\n### Patches\n\nThe issue has been fixed in urllib3 v1.26.5.\n\n### References\n\n- [CVE-2021-33503](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-33503)\n- [JVNVU#92413403 (English)](https://jvn.jp/en/vu/JVNVU92413403/)\n- [JVNVU#92413403 (Japanese)](https://jvn.jp/vu/JVNVU92413403/)\n- [urllib3 v1.26.5](https://github.com/urllib3/urllib3/releases/tag/1.26.5)\n\n### For more information\nIf you have any questions or comments about this advisory:\n* Ask in our [community Discord](https://discord.gg/urllib3)\n* Email [sethmichaellarson@gmail.com](mailto:sethmichaellarson@gmail.com)\n",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-q2q7-5pp4-w6pg",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2021-33503",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/urllib3/urllib3/security/advisories/GHSA-q2q7-5pp4-w6pg"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-33503"
                },
                {
                    "url": "https://github.com/urllib3/urllib3/commit/2d4a3fee6de2fa45eb82169361918f759269b4ec"
                },
                {
                    "url": "https://github.com/advisories/GHSA-q2q7-5pp4-w6pg"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FMUGWEAUYGGHTPPXT6YBD53WYXQGVV73/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6SCV7ZNAHS3E6PBFLJGENCDRDRWRZZ6W/"
                },
                {
                    "url": "https://security.gentoo.org/glsa/202107-36"
                },
                {
                    "url": "https://www.oracle.com/security-alerts/cpuoct2021.html"
                },
                {
                    "url": "https://github.com/urllib3/urllib3/commit/5b047b645f5f93900d5e2fc31230848c25eb1f5f#diff-52026d639119bf1e0364836b4e8a18bd9ed3c95c6ba39b26534a5057a65e35bbR65"
                }
            ],
            "published_at": "2021-06-01T21:19:32Z",
            "updated_at": "2023-09-02T05:02:51Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "urllib3"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 1.25.4, < 1.26.5",
                    "first_patched_version": {
                        "identifier": "1.26.5"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-400",
                    "name": "Uncontrolled Resource Consumption"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "urllib3"
            },
            "severity": "high",
            "vulnerable_version_range": ">= 1.25.4, < 1.26.5",
            "first_patched_version": {
                "identifier": "1.26.5"
            }
        },
        "url": "https://api.github.com/repos/username/minigrad/dependabot/alerts/17",
        "html_url": "https://github.com/username/minigrad/security/dependabot/17",
        "created_at": "2024-05-24T01:34:23Z",
        "updated_at": "2024-05-24T01:34:23Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 16,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "nbconvert"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-9jmq-rx5f-8jwq",
            "cve_id": "CVE-2021-32862",
            "summary": "nbconvert vulnerable to cross-site scripting (XSS) via multiple exploit paths",
            "description": "Most of the fixes will be in this repo, though, so having it here gives us the private fork to work on patches\n\nBelow is currently a duplicate of the original report:\n\n----\n\nReceived on security@ipython.org unedited, I'm not sure if we want to make it separate advisories. \n\nPasted raw for now, feel free to edit or make separate advisories if you have the rights to. \n\nI think the most important is to switch back from nbviewer.jupyter.org -> nbviewer.org at the cloudflare level I guess ? There might be fastly involved as well.\n--- \n### Impact\n_What kind of vulnerability is it? Who is impacted?_\n\n### Patches\n_Has the problem been patched? What versions should users upgrade to?_\n\n### Workarounds\n_Is there a way for users to fix or remediate the vulnerability without upgrading?_\n\n### References\n_Are there any links users can visit to find out more?_\n\n### For more information\nIf you have any questions or comments about this advisory:\n* Open an issue in [example link to repo](http://example.com)\n* Email us at [example email address](mailto:example@example.com)\n\n--- \n\n# GitHub Security Lab (GHSL) Vulnerability Report\n\nThe [GitHub Security Lab](https://securitylab.github.com) team has identified potential security vulnerabilities in [nbconvert](https://github.com/jupyter/nbconvert).\n\nWe are committed to working with you to help resolve these issues. In this report you will find everything you need to effectively coordinate a resolution of these issues with the GHSL team.\n\nIf at any point you have concerns or questions about this process, please do not hesitate to reach out to us at `securitylab@github.com` (please include `GHSL-2021-1013`, `GHSL-2021-1014`, `GHSL-2021-1015`, `GHSL-2021-1016`, `GHSL-2021-1017`, `GHSL-2021-1018`, `GHSL-2021-1019`, `GHSL-2021-1020`, `GHSL-2021-1021`, `GHSL-2021-1022`, `GHSL-2021-1023`, `GHSL-2021-1024`, `GHSL-2021-1025`, `GHSL-2021-1026`, `GHSL-2021-1027` or `GHSL-2021-1028` as a reference).\n\nIf you are _NOT_ the correct point of contact for this report, please let us know!\n\n## Summary\n\nWhen using nbconvert to generate an HTML version of a user-controllable notebook, it is possible to inject arbitrary HTML which may lead to Cross-Site Scripting (XSS) vulnerabilities if these HTML notebooks are served by a web server (eg: nbviewer) \n\n## Product\n\nnbconvert\n\n## Tested Version\n\n[v5.5.0](https://github.com/jupyter/nbconvert/releases/tag/5.5.0)\n\n## Details\n\n### Issue 1: XSS in notebook.metadata.language_info.pygments_lexer (`GHSL-2021-1013`)\n\nAttacker in control of a notebook can inject arbitrary unescaped HTML in the `notebook.metadata.language_info.pygments_lexer` field such as the following:\n\n```json\n\"metadata\": {\n  \"language_info\": {\n   \"pygments_lexer\": \"ipython3-foo\\\"><script>alert(1)</script>\"\n  }\n}\n```\n\nThis node is read in the [`from_notebook_node`](https://github.com/jupyter/nbconvert/blob/3c0f82d1acbcf2264ae0fa892141a037563aabd0/nbconvert/exporters/html.py#L135-L140) method:\n\n```python\ndef from_notebook_node(self, nb, resources=None, **kw):\n  langinfo = nb.metadata.get('language_info', {})\n  lexer = langinfo.get('pygments_lexer', langinfo.get('name', None))\n  highlight_code = self.filters.get('highlight_code', Highlight2HTML(pygments_lexer=lexer, parent=self))\n  self.register_filter('highlight_code', highlight_code)\n  return super().from_notebook_node(nb, resources, **kw)\n```\n\nIt is then assigned to `language` var and passed down to [`_pygments_highlight`](https://github.com/jupyter/nbconvert/blob/3c0f82d1acbcf2264ae0fa892141a037563aabd0/nbconvert/filters/highlight.py#L90)\n\n```python\nfrom pygments.formatters import LatexFormatter\nif not language:\n  language=self.pygments_lexer\nlatex = _pygments_highlight(source, LatexFormatter(), language, metadata)\n```\n\nIn this method, the `language` variable is [concatenated to `highlight hl-` string to conform the `cssclass`](https://github.com/jupyter/nbconvert/blob/3c0f82d1acbcf2264ae0fa892141a037563aabd0/nbconvert/filters/highlight.py#L56) passed to the `HTMLFormatter` constructor:\n\n``` python\nreturn _pygments_highlight(source if len(source) > 0 else ' ',\n  # needed to help post processors:\n  HtmlFormatter(cssclass=\" highlight hl-\"+language),\n  language, metadata)\n```\n\nThe `cssclass` variable is then [concatenated in the outer div class attribute](https://github.com/pygments/pygments/blob/30cfa26201a27dee1f8e6b0d600cad1138e64507/pygments/formatters/html.py#L791)\n\n``` python\nyield 0, ('<div' + (self.cssclass and ' class=\"%s\"' % self.cssclass) + (style and (' style=\"%s\"' % style)) + '>')\n```\n\nNote that the `cssclass` variable is also used in other unsafe places such as [`'<table class=\"%stable\">' % self.cssclass + filename_tr +`](https://github.com/pygments/pygments/blob/30cfa26201a27dee1f8e6b0d600cad1138e64507/pygments/formatters/html.py#L711))\n\n### Issue 2: XSS in notebook.metadata.title (`GHSL-2021-1014`)\n\nThe `notebook.metadata.title` node is rendered directly to the [`index.html.j2`](https://github.com/jupyter/nbconvert/blob/3c0f82d1acbcf2264ae0fa892141a037563aabd0/share/jupyter/nbconvert/templates/lab/index.html.j2#L12-L13) HTML template with no escaping: \n\n```html\n{% set nb_title = nb.metadata.get('title', '') or resources['metadata']['name'] %}\n<title>{{nb_title}}</title>\n```\n\nThe following `notebook.metadata.title` node will execute arbitrary javascript:\n\n```json\n \"metadata\": {\n  \"title\": \"TITLE</title><script>alert(1)</script>\"\n }\n```\n\nNote: this issue also affect other templates, not just the `lab` one.\n\n### Issue 3: XSS in notebook.metadata.widgets(`GHSL-2021-1015`)\n\nThe `notebook.metadata.widgets` node is rendered directly to the [`base.html.j2`](https://github.com/jupyter/nbconvert/blob/3c0f82d1acbcf2264ae0fa892141a037563aabd0/share/jupyter/nbconvert/templates/lab/index.html.j2#L12-L13) HTML template with no escaping: \n\n```html\n{% set mimetype = 'application/vnd.jupyter.widget-state+json'%}\n{% if mimetype in nb.metadata.get(\"widgets\",{})%}\n<script type=\"{{ mimetype }}\">\n{{ nb.metadata.widgets[mimetype] | json_dumps }}\n</script>\n{% endif %}\n```\n\nThe following `notebook.metadata.widgets` node will execute arbitrary javascript:\n\n```json\n \"metadata\": {\n  \"widgets\": {\n    \"application/vnd.jupyter.widget-state+json\": {\"foo\": \"pwntester</script><script>alert(1);//\"}\n  }\n }\n```\n\nNote: this issue also affect other templates, not just the `lab` one.\n\n### Issue 4: XSS in notebook.cell.metadata.tags(`GHSL-2021-1016`)\n\nThe `notebook.cell.metadata.tags` nodes are output directly to the [`celltags.j2`](https://github.com/jupyter/nbconvert/blob/3c0f82d1acbcf2264ae0fa892141a037563aabd0/share/jupyter/nbconvert/templates/base/celltags.j2#L4) HTML template with no escaping: \n\n```\n{%- macro celltags(cell) -%}\n    {% if cell.metadata.tags | length > 0 -%}\n        {% for tag in cell.metadata.tags -%}\n            {{ ' celltag_' ~ tag -}}\n        {%- endfor -%}\n    {%- endif %}\n{%- endmacro %}\n```\n\nThe following `notebook.cell.metadata.tags` node will execute arbitrary javascript:\n\n```json\n  {\n   \"cell_type\": \"code\",\n   \"execution_count\": null,\n   \"id\": \"727d1a5f\",\n   \"metadata\": {\n     \"tags\": [\"FOO\\\"><script>alert(1)</script><div \\\"\"]\n   },\n   \"outputs\": [],\n   \"source\": []\n  }\n ],\n```\n\nNote: this issue also affect other templates, not just the `lab` one.\n\n### Issue 5: XSS in output data text/html cells(`GHSL-2021-1017`)\n\nUsing the `text/html` output data mime type allows arbitrary javascript to be executed when rendering an HTML notebook. This is probably by design, however, it would be nice to enable an option which uses an HTML sanitizer preprocessor to strip down all javascript elements:\n\nThe following is an example of a cell with `text/html` output executing arbitrary javascript code:\n\n```json\n  {\n   \"cell_type\": \"code\",\n   \"execution_count\": 5,\n   \"id\": \"b72e53fa\",\n   \"metadata\": {},\n   \"outputs\": [\n    {\n     \"data\": {\n      \"text/html\": [\n        \"<script>alert(1)</script>\"\n      ]\n     },\n     \"execution_count\": 5,\n     \"metadata\": {},\n     \"output_type\": \"execute_result\"\n    }\n   ],\n   \"source\": [\n    \"import os; os.system('touch /tmp/pwned')\"\n   ]\n  },\n```\n\n### Issue 6: XSS in output data image/svg+xml cells(`GHSL-2021-1018`)\n\nUsing the `image/svg+xml` output data mime type allows arbitrary javascript to be executed when rendering an HTML notebook. \n\nThe `cell.output.data[\"image/svg+xml\"]` nodes are rendered directly to the [`base.html.j2`](https://github.com/jupyter/nbconvert/blob/main/share/jupyter/nbconvert/templates/classic/base.html.j2) HTML template with no escaping\n\n```\n{%- else %}\n{{ output.data['image/svg+xml'] }}\n{%- endif %}\n```\n\nThe following `cell.output.data[\"image/svg+xml\"]` node will execute arbitrary javascript:\n\n```json\n    {\n     \"output_type\": \"execute_result\",\n     \"data\": {\n      \"image/svg+xml\": [\"<script>console.log(\\\"image/svg+xml output\\\")</script>\"]\n     },\n     \"execution_count\": null,\n     \"metadata\": {\n     }\n    }\n```\n\n### Issue 7: XSS in notebook.cell.output.svg_filename(`GHSL-2021-1019`)\n\nThe `cell.output.svg_filename` nodes are rendered directly to the [`base.html.j2`](https://github.com/jupyter/nbconvert/blob/main/share/jupyter/nbconvert/templates/classic/base.html.j2) HTML template with no escaping\n\n```\n{%- if output.svg_filename %}\n<img src=\"{{ output.svg_filename | posix_path }}\">\n```\n\nThe following `cell.output.svg_filename` node will escape the `img` tag context and execute arbitrary javascript:\n\n```json\n  {\n   \"cell_type\": \"code\",\n   \"execution_count\": null,\n   \"id\": \"b72e53fa\",\n   \"metadata\": {},\n   \"outputs\": [\n    {\n     \"output_type\": \"execute_result\",\n     \"svg_filename\": \"\\\"><script>alert(1)</script>\",\n     \"data\": {\n      \"image/svg+xml\": [\"\"]\n     },\n     \"execution_count\": null,\n     \"metadata\": {\n     }\n    }\n   ],\n   \"source\": [\"\"]\n  },\n```\n\n### Issue 8: XSS in output data text/markdown cells(`GHSL-2021-1020`)\n\nUsing the `text/markdown` output data mime type allows arbitrary javascript to be executed when rendering an HTML notebook. \n\nThe `cell.output.data[\"text/markdown\"]` nodes are rendered directly to the [`base.html.j2`](https://github.com/jupyter/nbconvert/blob/main/share/jupyter/nbconvert/templates/classic/base.html.j2) HTML template with no escaping\n\n```\n{{ output.data['text/markdown'] | markdown2html }}\n```\n\nThe following `cell.output.data[\"text/markdown\"]` node will execute arbitrary javascript:\n\n```\n    {\n     \"output_type\": \"execute_result\",\n     \"data\": {\n      \"text/markdown\": [\"<script>console.log(\\\"text/markdown output\\\")</script>\"]\n     },\n     \"execution_count\": null,\n     \"metadata\": {}\n    }\n```\n\n### Issue 9: XSS in output data application/javascript cells(`GHSL-2021-1021`)\n\nUsing the `application/javascript` output data mime type allows arbitrary javascript to be executed when rendering an HTML notebook. This is probably by design, however, it would be nice to enable an option which uses an HTML sanitizer preprocessor to strip down all javascript elements:\n\nThe `cell.output.data[\"application/javascript\"]` nodes are rendered directly to the [`base.html.j2`](https://github.com/jupyter/nbconvert/blob/main/share/jupyter/nbconvert/templates/classic/base.html.j2) HTML template with no escaping\n\n```\n<script type=\"text/javascript\">\nvar element = document.getElementById('{{ div_id }}');\n{{ output.data['application/javascript'] }}\n</script>\n```\n\nThe following `cell.output.data[\"application/javascript\"]` node will execute arbitrary javascript:\n\n```\n    {\n     \"output_type\": \"execute_result\",\n     \"data\": {\n      \"application/javascript\": [\"console.log(\\\"application/javascript output\\\")\"]\n     },\n     \"execution_count\": null,\n     \"metadata\": {}\n    }\n```\n\n### Issue 10: XSS is output.metadata.filenames image/png and image/jpeg(`GHSL-2021-1022`)\n\nThe `cell.output.metadata.filenames[\"images/png\"]` and `cell.metadata.filenames[\"images/jpeg\"]` nodes are rendered directly to the [`base.html.j2`](https://github.com/jupyter/nbconvert/blob/main/share/jupyter/nbconvert/templates/classic/base.html.j2) HTML template with no escaping:\n\n```\n{%- if 'image/png' in output.metadata.get('filenames', {}) %}\n<img src=\"{{ output.metadata.filenames['image/png'] | posix_path }}\"\n```\n\nThe following `filenames` node will execute arbitrary javascript:\n\n```json\n    {\n     \"output_type\": \"execute_result\",\n     \"data\": {\n      \"image/png\": [\"\"]\n     },\n     \"execution_count\": null,\n     \"metadata\": {\n       \"filenames\": {\n          \"image/png\": \"\\\"><script>console.log(\\\"output.metadata.filenames.image/png injection\\\")</script>\" \n       }\n     }\n    }\n```\n\n### Issue 11: XSS in output data image/png and image/jpeg cells(`GHSL-2021-1023`)\n\nUsing the `image/png` or `image/jpeg` output data mime type allows arbitrary javascript to be executed when rendering an HTML notebook. \n\nThe `cell.output.data[\"images/png\"]` and `cell.output.data[\"images/jpeg\"]` nodes are rendered directly to the [`base.html.j2`](https://github.com/jupyter/nbconvert/blob/main/share/jupyter/nbconvert/templates/classic/base.html.j2) HTML template with no escaping:\n\n```\n{%- else %}\n<img src=\"data:image/png;base64,{{ output.data['image/png'] }}\"\n{%- endif %}\n```\n\nThe following `cell.output.data[\"image/png\"]` node will execute arbitrary javascript:\n\n```json\n    {\n     \"output_type\": \"execute_result\",\n     \"data\": {\n      \"image/png\": [\"\\\"><script>console.log(\\\"image/png output\\\")</script>\"]\n     },\n     \"execution_count\": null,\n     \"metadata\": {}\n    }\n```\n\n### Issue 12: XSS is output.metadata.width/height image/png and image/jpeg(`GHSL-2021-1024`)\n\nThe `cell.output.metadata.width` and `cell.output.metadata.height` nodes of both `image/png` and `image/jpeg` cells are rendered directly to the [`base.html.j2`](https://github.com/jupyter/nbconvert/blob/main/share/jupyter/nbconvert/templates/classic/base.html.j2) HTML template with no escaping:\n\n```\n{%- set width=output | get_metadata('width', 'image/png') -%}\nwidth={{ width }}\n{%- set height=output | get_metadata('height', 'image/png') -%}\nheight={{ height }}\n```\n\nThe following `output.metadata.width` node will execute arbitrary javascript:\n\n```json\n    {\n     \"output_type\": \"execute_result\",\n     \"data\": {\n      \"image/png\": [\"abcd\"]\n     },\n     \"execution_count\": null,\n     \"metadata\": {\n        \"width\": \"><script>console.log(\\\"output.metadata.width png injection\\\")</script>\"\n     }\n    }\n```\n\n### Issue 13: XSS in output data application/vnd.jupyter.widget-state+json cells(`GHSL-2021-1025`)\n\nThe `cell.output.data[\"application/vnd.jupyter.widget-state+json\"]` nodes are rendered directly to the [`base.html.j2`](https://github.com/jupyter/nbconvert/blob/main/share/jupyter/nbconvert/templates/classic/base.html.j2) HTML template with no escaping:\n\n```\n{% set datatype_list = output.data | filter_data_type %}\n{% set datatype = datatype_list[0]%}\n<script type=\"{{ datatype }}\">\n{{ output.data[datatype] | json_dumps }}\n</script>\n```\n\nThe following `cell.output.data[\"application/vnd.jupyter.widget-state+json\"]` node will execute arbitrary javascript:\n\n```json\n    {\n     \"output_type\": \"execute_result\",\n     \"data\": {\n      \"application/vnd.jupyter.widget-state+json\": \"\\\"</script><script>console.log('output.data.application/vnd.jupyter.widget-state+json injection')//\"\n     },\n     \"execution_count\": null,\n     \"metadata\": {}\n    }\n```\n\n### Issue 14: XSS in output data application/vnd.jupyter.widget-view+json cells(`GHSL-2021-1026`)\n\nThe `cell.output.data[\"application/vnd.jupyter.widget-view+json\"]` nodes are rendered directly to the [`base.html.j2`](https://github.com/jupyter/nbconvert/blob/main/share/jupyter/nbconvert/templates/classic/base.html.j2) HTML template with no escaping:\n\n```\n{% set datatype_list = output.data | filter_data_type %}\n{% set datatype = datatype_list[0]%}\n<script type=\"{{ datatype }}\">\n{{ output.data[datatype] | json_dumps }}\n</script>\n```\n\nThe following `cell.output.data[\"application/vnd.jupyter.widget-view+json\"]` node will execute arbitrary javascript:\n\n```json\n    {\n     \"output_type\": \"execute_result\",\n     \"data\": {\n      \"application/vnd.jupyter.widget-view+json\": \"\\\"</script><script>console.log('output.data.application/vnd.jupyter.widget-view+json injection')//\"\n     },\n     \"execution_count\": null,\n     \"metadata\": {}\n    }\n```\n\n\n### Issue 15: XSS in raw cells(`GHSL-2021-1027`)\n\nUsing a `raw` cell type allows arbitrary javascript to be executed when rendering an HTML notebook. This is probably by design, however, it would be nice to enable an option which uses an HTML sanitizer preprocessor to strip down all javascript elements:\n\nThe following is an example of a `raw` cell executing arbitrary javascript code:\n\n```json\n  {\n   \"cell_type\": \"raw\",\n   \"id\": \"372c2bf1\",\n   \"metadata\": {},\n   \"source\": [\n    \"Payload in raw cell <script>alert(1)</script>\"\n   ]\n  }\n```\n\n### Issue 16: XSS in markdown cells(`GHSL-2021-1028`)\n\nUsing a `markdown` cell type allows arbitrary javascript to be executed when rendering an HTML notebook. This is probably by design, however, it would be nice to enable an option which uses an HTML sanitizer preprocessor to strip down all javascript elements:\n\nThe following is an example of a `markdown` cell executing arbitrary javascript code:\n\n```json\n  {\n   \"cell_type\": \"markdown\",\n   \"id\": \"2d42de4a\",\n   \"metadata\": {},\n   \"source\": [\n     \"<script>alert(1)</script>\"\n   ]\n  },\n```\n\n### Proof of Concept\n\nThese vulnerabilities may affect any server using nbconvert to generate HTML and not using a secure content-security-policy (CSP) policy. For example [nbviewer](https://nbviewer.jupyter.org) is vulnerable to the above mentioned XSS issues:\n\n1. Create Gist with payload. eg:\n- `https://gist.github.com/pwntester/ff027d91955369b85f99bb1768b7f02c`\n\n2. Then load gist on nbviewer. eg:\n- `https://nbviewer.jupyter.org/gist/pwntester/ff027d91955369b85f99bb1768b7f02c`\n\nNote: response is served with `content-security-policy: connect-src 'none';`\n\n## GitHub Security Advisories\n\nWe recommend you create a private [GitHub Security Advisory](https://help.github.com/en/github/managing-security-vulnerabilities/creating-a-security-advisory) for these findings. This also allows you to invite the GHSL team to collaborate and further discuss these findings in private before they are [published](https://help.github.com/en/github/managing-security-vulnerabilities/publishing-a-security-advisory).\n\n## Credit\n\nThese issues were discovered and reported by GHSL team member [@pwntester (Alvaro Muñoz)](https://github.com/pwntester).\n\n## Contact\n\nYou can contact the GHSL team at `securitylab@github.com`, please include a reference to `GHSL-2021-1013`, `GHSL-2021-1014`, `GHSL-2021-1015`, `GHSL-2021-1016`, `GHSL-2021-1017`, `GHSL-2021-1018`, `GHSL-2021-1019`, `GHSL-2021-1020`, `GHSL-2021-1021`, `GHSL-2021-1022`, `GHSL-2021-1023`, `GHSL-2021-1024`, `GHSL-2021-1025`, `GHSL-2021-1026`, `GHSL-2021-1027` or `GHSL-2021-1028` in any communication regarding these issues.\n\n\n## Disclosure Policy\n\nThis report is subject to our [coordinated disclosure policy](https://securitylab.github.com/advisories#policy).\n",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-9jmq-rx5f-8jwq",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2021-32862",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/jupyter/nbconvert/security/advisories/GHSA-9jmq-rx5f-8jwq"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-32862"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/nbconvert/PYSEC-2022-249.yaml"
                },
                {
                    "url": "https://github.com/jupyter/nbviewer/security/advisories/GHSA-h274-fcvj-h2wm"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2023/06/msg00003.html"
                },
                {
                    "url": "https://github.com/advisories/GHSA-9jmq-rx5f-8jwq"
                }
            ],
            "published_at": "2022-08-10T17:51:53Z",
            "updated_at": "2024-01-25T22:10:35Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "nbconvert"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 6.5.1",
                    "first_patched_version": {
                        "identifier": "6.5.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:C/C:L/I:L/A:N",
                "score": 5.4
            },
            "cwes": [
                {
                    "cwe_id": "CWE-79",
                    "name": "Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "nbconvert"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 6.5.1",
            "first_patched_version": {
                "identifier": "6.5.1"
            }
        },
        "url": "https://api.github.com/repos/username/minigrad/dependabot/alerts/16",
        "html_url": "https://github.com/username/minigrad/security/dependabot/16",
        "created_at": "2024-05-24T01:34:23Z",
        "updated_at": "2024-05-24T01:34:23Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 15,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "numpy"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-fpfv-jqm9-f5jm",
            "cve_id": "CVE-2021-34141",
            "summary": "Incorrect Comparison in NumPy",
            "description": "Incomplete string comparison in the numpy.core component in NumPy1.9.x, which allows attackers to fail the APIs via constructing specific string objects.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-fpfv-jqm9-f5jm",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2021-34141",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-34141"
                },
                {
                    "url": "https://github.com/numpy/numpy/issues/18993"
                },
                {
                    "url": "https://www.oracle.com/security-alerts/cpujul2022.html"
                },
                {
                    "url": "https://github.com/numpy/numpy/issues/18993#issuecomment-1010735102"
                },
                {
                    "url": "https://github.com/advisories/GHSA-fpfv-jqm9-f5jm"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/numpy/PYSEC-2021-855.yaml"
                }
            ],
            "published_at": "2021-12-18T00:00:41Z",
            "updated_at": "2023-01-27T05:07:10Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "numpy"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 1.22",
                    "first_patched_version": {
                        "identifier": "1.22"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
                "score": 5.3
            },
            "cwes": [
                {
                    "cwe_id": "CWE-697",
                    "name": "Incorrect Comparison"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "numpy"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 1.22",
            "first_patched_version": {
                "identifier": "1.22"
            }
        },
        "url": "https://api.github.com/repos/username/minigrad/dependabot/alerts/15",
        "html_url": "https://github.com/username/minigrad/security/dependabot/15",
        "created_at": "2024-05-24T01:34:23Z",
        "updated_at": "2024-05-24T01:34:23Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 14,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "numpy"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-5545-2q6w-2gh6",
            "cve_id": "CVE-2021-41495",
            "summary": "NumPy NULL Pointer Dereference",
            "description": "Null Pointer Dereference vulnerability exists in numpy.sort in NumPy &lt and 1.19 in the PyArray_DescrNew function due to missing return-value validation, which allows attackers to conduct DoS attacks by repetitively creating sort arrays.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-5545-2q6w-2gh6",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2021-41495",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-41495"
                },
                {
                    "url": "https://github.com/numpy/numpy/issues/19038"
                },
                {
                    "url": "https://www.oracle.com/security-alerts/cpujul2022.html"
                },
                {
                    "url": "https://github.com/advisories/GHSA-5545-2q6w-2gh6"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/numpy/PYSEC-2021-856.yaml"
                }
            ],
            "published_at": "2022-02-08T00:00:56Z",
            "updated_at": "2023-01-29T05:01:55Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "numpy"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "<= 1.18.5",
                    "first_patched_version": {
                        "identifier": "1.19"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-476",
                    "name": "NULL Pointer Dereference"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "numpy"
            },
            "severity": "high",
            "vulnerable_version_range": "<= 1.18.5",
            "first_patched_version": {
                "identifier": "1.19"
            }
        },
        "url": "https://api.github.com/repos/username/minigrad/dependabot/alerts/14",
        "html_url": "https://github.com/username/minigrad/security/dependabot/14",
        "created_at": "2024-05-24T01:34:22Z",
        "updated_at": "2024-05-24T01:34:22Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 13,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "numpy"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-f7c7-j99h-c22f",
            "cve_id": "CVE-2021-41496",
            "summary": "Buffer Copy without Checking Size of Input in NumPy",
            "description": "Buffer overflow in the array_from_pyobj function of fortranobject.c in NumPy < 1.19, which allows attackers to conduct a Denial of Service attacks by carefully constructing an array with negative values.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-f7c7-j99h-c22f",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2021-41496",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-41496"
                },
                {
                    "url": "https://github.com/numpy/numpy/issues/19000"
                },
                {
                    "url": "https://www.oracle.com/security-alerts/cpujul2022.html"
                },
                {
                    "url": "https://github.com/advisories/GHSA-f7c7-j99h-c22f"
                }
            ],
            "published_at": "2022-02-08T00:00:56Z",
            "updated_at": "2023-01-27T05:02:20Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "numpy"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "<= 1.18.5",
                    "first_patched_version": {
                        "identifier": "1.19"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
                "score": 5.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-120",
                    "name": "Buffer Copy without Checking Size of Input ('Classic Buffer Overflow')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "numpy"
            },
            "severity": "medium",
            "vulnerable_version_range": "<= 1.18.5",
            "first_patched_version": {
                "identifier": "1.19"
            }
        },
        "url": "https://api.github.com/repos/username/minigrad/dependabot/alerts/13",
        "html_url": "https://github.com/username/minigrad/security/dependabot/13",
        "created_at": "2024-05-24T01:34:22Z",
        "updated_at": "2024-05-24T01:34:22Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 12,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "notebook"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-v7vq-3x77-87vg",
            "cve_id": "CVE-2022-29238",
            "summary": "Token bruteforcing.",
            "description": "### Impact\n_What kind of vulnerability is it? Who is impacted?_\n\nAuthenticated requests to the notebook server with `ContentsManager.allow_hidden = False` only prevented listing the contents of hidden directories, not accessing individual hidden files or files in hidden directories (i.e. hidden files were 'hidden' but not 'inaccessible'). This could lead to notebook configurations allowing authenticated access to files that may reasonably be expected to be disallowed.\n\nBecause fully authenticated requests are required, this is of relatively low impact. But if a server's root directory contains sensitive files whose only protection from the server is being hidden (e.g. `~/.ssh` while serving $HOME), then any authenticated requests could access files if their names are guessable. Such contexts also necessarily have full access to the server and therefore execution permissions, which also generally grants access to all the same files. So this does not generally result in any privilege escalation or increase in information access, only an additional, unintended _means_ by which the files could be accessed.\n\n### Patches\n_Has the problem been patched? What versions should users upgrade to?_\n\nnotebook 6.4.12\n\n### Workarounds\n_Is there a way for users to fix or remediate the vulnerability without upgrading?_\n\n- Do not run the notebook server in a directory with hidden files, use subdirectories\n- Use a custom ContentsManager with additional checks for `self.is_hidden(path)` prior to completing actions\n\n### References\n_Are there any links users can visit to find out more?_\n\n### For more information\nIf you have any questions or comments about this advisory:\n* Open an issue in [example link to repo](http://example.com)\n* Email us at [example email address](mailto:example@example.com)\n",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-v7vq-3x77-87vg",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2022-29238",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/jupyter/notebook/security/advisories/GHSA-v7vq-3x77-87vg"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-29238"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/notebook/PYSEC-2022-212.yaml"
                },
                {
                    "url": "https://github.com/advisories/GHSA-v7vq-3x77-87vg"
                }
            ],
            "published_at": "2022-06-16T23:10:10Z",
            "updated_at": "2023-01-27T05:04:37Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "notebook"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 6.4.12",
                    "first_patched_version": {
                        "identifier": "6.4.12"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:N/A:N",
                "score": 4.3
            },
            "cwes": [
                {
                    "cwe_id": "CWE-425",
                    "name": "Direct Request ('Forced Browsing')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "notebook"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 6.4.12",
            "first_patched_version": {
                "identifier": "6.4.12"
            }
        },
        "url": "https://api.github.com/repos/username/minigrad/dependabot/alerts/12",
        "html_url": "https://github.com/username/minigrad/security/dependabot/12",
        "created_at": "2024-05-24T01:34:22Z",
        "updated_at": "2024-05-24T01:34:22Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 11,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "notebook"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-m87f-39q9-6f55",
            "cve_id": "CVE-2022-24758",
            "summary": "Sensitive Auth & Cookie data stored in Jupyter server logs",
            "description": "Anytime a 5xx error is triggered, the auth cookie and other header values are recorded in Jupyter server logs by default. Considering these logs do not require root access, an attacker can monitor these logs, steal sensitive auth/cookie information, and gain access to the Jupyter server.\n\nUpgrade to notebook version 6.4.10\n\n### For more information\n\nIf you have any questions or comments about this advisory, or vulnerabilities to report, please email our security list [security@ipython.org](mailto:security@ipython.org).\n\nCredit: @3coins for reporting. Thank you!\n\n",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-m87f-39q9-6f55",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2022-24758",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/jupyter/notebook/security/advisories/GHSA-m87f-39q9-6f55"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-24758"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/notebook/PYSEC-2022-180.yaml"
                },
                {
                    "url": "https://github.com/advisories/GHSA-m87f-39q9-6f55"
                }
            ],
            "published_at": "2022-04-05T17:47:26Z",
            "updated_at": "2023-01-27T05:01:25Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "notebook"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 6.4.10",
                    "first_patched_version": {
                        "identifier": "6.4.10"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-532",
                    "name": "Insertion of Sensitive Information into Log File"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "notebook"
            },
            "severity": "high",
            "vulnerable_version_range": "< 6.4.10",
            "first_patched_version": {
                "identifier": "6.4.10"
            }
        },
        "url": "https://api.github.com/repos/username/minigrad/dependabot/alerts/11",
        "html_url": "https://github.com/username/minigrad/security/dependabot/11",
        "created_at": "2024-05-24T01:34:22Z",
        "updated_at": "2024-05-24T01:34:22Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 10,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "ipython"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-pq7m-3gw7-gq5x",
            "cve_id": "CVE-2022-21699",
            "summary": "Execution with Unnecessary Privileges in ipython",
            "description": "We’d like to disclose an arbitrary code execution vulnerability in IPython that stems from IPython executing untrusted files in CWD. This vulnerability allows one user to run code as another.\n \nProof of concept\n\nUser1:\n```\nmkdir -m 777 /tmp/profile_default\nmkdir -m 777 /tmp/profile_default/startup\necho 'print(\"stealing your private secrets\")' > /tmp/profile_default/startup/foo.py\n```\n\nUser2:\n```\ncd /tmp\nipython\n```\n\n \n\nUser2 will see:\n```\nPython 3.9.7 (default, Oct 25 2021, 01:04:21)\nType 'copyright', 'credits' or 'license' for more information\nIPython 7.29.0 -- An enhanced Interactive Python. Type '?' for help.\nstealing your private secrets\n```\n\n\n## Patched release and documentation\n\nSee https://ipython.readthedocs.io/en/stable/whatsnew/version8.html#ipython-8-0-1-cve-2022-21699, \n\nVersion 8.0.1, 7.31.1 for current Python version are recommended. \nVersion 7.16.3 has also been published for Python 3.6 users, \nVersion 5.11 (source only, 5.x branch on github) for older Python versions.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-pq7m-3gw7-gq5x",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2022-21699",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/ipython/ipython/security/advisories/GHSA-pq7m-3gw7-gq5x"
                },
                {
                    "url": "https://github.com/ipython/ipython/commit/46a51ed69cdf41b4333943d9ceeb945c4ede5668"
                },
                {
                    "url": "https://ipython.readthedocs.io/en/stable/whatsnew/version8.html#ipython-8-0-1-cve-2022-21699"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-21699"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2022/01/msg00021.html"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/CRQRTWHYXMLDJ572VGVUZMUPEOTPM3KB/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DZ7LVZBB4D7KVSFNEQUBEHFO3JW6D2ZK/"
                },
                {
                    "url": "https://github.com/advisories/GHSA-pq7m-3gw7-gq5x"
                }
            ],
            "published_at": "2022-01-21T18:55:30Z",
            "updated_at": "2023-02-03T05:04:56Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "ipython"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 5.11",
                    "first_patched_version": {
                        "identifier": "5.11"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "ipython"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 6.0.0, < 7.16.3",
                    "first_patched_version": {
                        "identifier": "7.16.3"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "ipython"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 7.17.0, < 7.31.1",
                    "first_patched_version": {
                        "identifier": "7.31.1"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "ipython"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 8.0.0, < 8.0.1",
                    "first_patched_version": {
                        "identifier": "8.0.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:L/PR:L/UI:R/S:C/C:H/I:H/A:H",
                "score": 8.3
            },
            "cwes": [
                {
                    "cwe_id": "CWE-250",
                    "name": "Execution with Unnecessary Privileges"
                },
                {
                    "cwe_id": "CWE-269",
                    "name": "Improper Privilege Management"
                },
                {
                    "cwe_id": "CWE-279",
                    "name": "Incorrect Execution-Assigned Permissions"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "ipython"
            },
            "severity": "high",
            "vulnerable_version_range": ">= 6.0.0, < 7.16.3",
            "first_patched_version": {
                "identifier": "7.16.3"
            }
        },
        "url": "https://api.github.com/repos/username/minigrad/dependabot/alerts/10",
        "html_url": "https://github.com/username/minigrad/security/dependabot/10",
        "created_at": "2024-05-24T01:34:22Z",
        "updated_at": "2024-05-24T01:34:22Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 9,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "numpy"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-6p56-wp2h-9hxr",
            "cve_id": "CVE-2021-33430",
            "summary": "NumPy Buffer Overflow (Disputed)",
            "description": "A Buffer Overflow vulnerability exists in NumPy 1.9.x in the PyArray_NewFromDescr_int function of ctors.c when specifying arrays of large dimensions (over 32) from Python code, which could let a malicious user cause a Denial of Service.\n\nNOTE: The vendor does not agree this is a vulnerability; In (very limited) circumstances a user may be able provoke the buffer overflow, the user is most likely already privileged to at least provoke denial of service by exhausting memory. Triggering this further requires the use of uncommon API (complicated structured dtypes), which is very unlikely to be available to an unprivileged user.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-6p56-wp2h-9hxr",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2021-33430",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-33430"
                },
                {
                    "url": "https://github.com/numpy/numpy/issues/18939"
                },
                {
                    "url": "https://github.com/numpy/numpy/commit/ae317fd9ff3e79c0eac357d723bfc29cbd625f2e"
                },
                {
                    "url": "https://github.com/advisories/GHSA-6p56-wp2h-9hxr"
                }
            ],
            "published_at": "2022-01-07T00:09:39Z",
            "updated_at": "2024-01-11T21:28:19Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "numpy"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": ">= 1.9.0, < 1.21",
                    "first_patched_version": {
                        "identifier": "1.21"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:N/I:N/A:H",
                "score": 5.3
            },
            "cwes": [
                {
                    "cwe_id": "CWE-120",
                    "name": "Buffer Copy without Checking Size of Input ('Classic Buffer Overflow')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "numpy"
            },
            "severity": "medium",
            "vulnerable_version_range": ">= 1.9.0, < 1.21",
            "first_patched_version": {
                "identifier": "1.21"
            }
        },
        "url": "https://api.github.com/repos/username/minigrad/dependabot/alerts/9",
        "html_url": "https://github.com/username/minigrad/security/dependabot/9",
        "created_at": "2024-05-24T01:34:22Z",
        "updated_at": "2024-05-24T01:34:22Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 8,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "notebook"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-4952-p58q-6crx",
            "cve_id": "CVE-2021-32797",
            "summary": "JupyterLab: XSS due to lack of sanitization of the action attribute of an html <form>",
            "description": "### Impact\n\nUntrusted notebook can execute code on load. This is a remote code execution, but requires user action to open a notebook.\n\n### Patches\n\nPatched in the following versions: 3.1.4, 3.0.17, 2.3.2, 2.2.10, 1.2.21.\n\n### References\n\n[OWASP Page on Restricting Form Submissions](https://cheatsheetseries.owasp.org/cheatsheets/Content_Security_Policy_Cheat_Sheet.html)\n\n### For more information\n\nIf you have any questions or comments about this advisory, or vulnerabilities to report, please email our security list security@ipython.org.\n\nCredit: Guillaume Jeanne from Google\n",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-4952-p58q-6crx",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2021-32797",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/jupyterlab/jupyterlab/security/advisories/GHSA-4952-p58q-6crx"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-32797"
                },
                {
                    "url": "https://github.com/jupyterlab/jupyterlab/commit/504825938c0abfa2fb8ff8d529308830a5ae42ed"
                },
                {
                    "url": "https://github.com/google/security-research/security/advisories/GHSA-c469-p3jp-2vhx"
                },
                {
                    "url": "https://github.com/advisories/GHSA-4952-p58q-6crx"
                }
            ],
            "published_at": "2021-08-23T19:40:22Z",
            "updated_at": "2023-02-01T05:06:05Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "jupyterlab"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 1.2.21",
                    "first_patched_version": {
                        "identifier": "1.2.21"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "jupyterlab"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 2.0.0, < 2.2.10",
                    "first_patched_version": {
                        "identifier": "2.2.10"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "jupyterlab"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 2.3.0, < 2.3.2",
                    "first_patched_version": {
                        "identifier": "2.3.2"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "jupyterlab"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 3.0.0, < 3.0.17",
                    "first_patched_version": {
                        "identifier": "3.0.17"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "jupyterlab"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 3.1.0, < 3.1.4",
                    "first_patched_version": {
                        "identifier": "3.1.4"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "notebook"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 5.7.11",
                    "first_patched_version": {
                        "identifier": "5.7.11"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "notebook"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 6.0.0, < 6.4.1",
                    "first_patched_version": {
                        "identifier": "6.4.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:H/I:N/A:N",
                "score": 7.4
            },
            "cwes": [
                {
                    "cwe_id": "CWE-75",
                    "name": "Failure to Sanitize Special Elements into a Different Plane (Special Element Injection)"
                },
                {
                    "cwe_id": "CWE-79",
                    "name": "Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')"
                },
                {
                    "cwe_id": "CWE-87",
                    "name": "Improper Neutralization of Alternate XSS Syntax"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "notebook"
            },
            "severity": "high",
            "vulnerable_version_range": ">= 6.0.0, < 6.4.1",
            "first_patched_version": {
                "identifier": "6.4.1"
            }
        },
        "url": "https://api.github.com/repos/username/minigrad/dependabot/alerts/8",
        "html_url": "https://github.com/username/minigrad/security/dependabot/8",
        "created_at": "2024-05-24T01:34:22Z",
        "updated_at": "2024-05-24T01:34:22Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 7,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "notebook"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-hwvq-6gjx-j797",
            "cve_id": "CVE-2021-32798",
            "summary": "Special Element Injection in notebook",
            "description": "### Impact\n\nUntrusted notebook can execute code on load. This is a remote code execution, but requires user action to open a notebook.\n\n### Patches\n\n5.7.11, 6.4.1\n\n### References\n\n[OWASP Page on Injection Prevention](https://cheatsheetseries.owasp.org/cheatsheets/Injection_Prevention_Cheat_Sheet.html#injection-prevention-rules)\n\n### For more information\n\nIf you have any questions or comments about this advisory, or vulnerabilities to report, please email our security list security@ipython.org.\n\nCredit: Guillaume Jeanne from Google\n\n\n### Example:\n\nA notebook with the following content in a cell and it would display an alert when opened for the first time in Notebook (in an untrusted state):\n\n```\n{ \"cell_type\": \"code\", \"execution_count\": 0, \"metadata\": {}, \"outputs\": [ { \"data\": { \"text/html\": [ \"<select><iframe></select><img src=x: onerror=alert('xss')>\\n\"], \"text/plain\": [] }, \"metadata\": {}, \"output_type\": \"display_data\" } ], \"source\": [ \"\" ] }\n````",
            "severity": "critical",
            "identifiers": [
                {
                    "value": "GHSA-hwvq-6gjx-j797",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2021-32798",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/jupyter/notebook/security/advisories/GHSA-hwvq-6gjx-j797"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-32798"
                },
                {
                    "url": "https://github.com/jupyter/notebook/commit/79fc76e890a8ec42f73a3d009e44ef84c14ef0d5"
                },
                {
                    "url": "https://github.com/advisories/GHSA-hwvq-6gjx-j797"
                }
            ],
            "published_at": "2021-08-23T19:40:38Z",
            "updated_at": "2023-02-01T05:06:05Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "notebook"
                    },
                    "severity": "critical",
                    "vulnerable_version_range": "< 5.7.11",
                    "first_patched_version": {
                        "identifier": "5.7.11"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "notebook"
                    },
                    "severity": "critical",
                    "vulnerable_version_range": ">= 6.0.0, < 6.4.1",
                    "first_patched_version": {
                        "identifier": "6.4.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:N",
                "score": 10.0
            },
            "cwes": [
                {
                    "cwe_id": "CWE-79",
                    "name": "Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "notebook"
            },
            "severity": "critical",
            "vulnerable_version_range": ">= 6.0.0, < 6.4.1",
            "first_patched_version": {
                "identifier": "6.4.1"
            }
        },
        "url": "https://api.github.com/repos/username/minigrad/dependabot/alerts/7",
        "html_url": "https://github.com/username/minigrad/security/dependabot/7",
        "created_at": "2024-05-24T01:34:22Z",
        "updated_at": "2024-05-24T01:34:22Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 6,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "jupyterlab"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-4952-p58q-6crx",
            "cve_id": "CVE-2021-32797",
            "summary": "JupyterLab: XSS due to lack of sanitization of the action attribute of an html <form>",
            "description": "### Impact\n\nUntrusted notebook can execute code on load. This is a remote code execution, but requires user action to open a notebook.\n\n### Patches\n\nPatched in the following versions: 3.1.4, 3.0.17, 2.3.2, 2.2.10, 1.2.21.\n\n### References\n\n[OWASP Page on Restricting Form Submissions](https://cheatsheetseries.owasp.org/cheatsheets/Content_Security_Policy_Cheat_Sheet.html)\n\n### For more information\n\nIf you have any questions or comments about this advisory, or vulnerabilities to report, please email our security list security@ipython.org.\n\nCredit: Guillaume Jeanne from Google\n",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-4952-p58q-6crx",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2021-32797",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/jupyterlab/jupyterlab/security/advisories/GHSA-4952-p58q-6crx"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-32797"
                },
                {
                    "url": "https://github.com/jupyterlab/jupyterlab/commit/504825938c0abfa2fb8ff8d529308830a5ae42ed"
                },
                {
                    "url": "https://github.com/google/security-research/security/advisories/GHSA-c469-p3jp-2vhx"
                },
                {
                    "url": "https://github.com/advisories/GHSA-4952-p58q-6crx"
                }
            ],
            "published_at": "2021-08-23T19:40:22Z",
            "updated_at": "2023-02-01T05:06:05Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "jupyterlab"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 1.2.21",
                    "first_patched_version": {
                        "identifier": "1.2.21"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "jupyterlab"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 2.0.0, < 2.2.10",
                    "first_patched_version": {
                        "identifier": "2.2.10"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "jupyterlab"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 2.3.0, < 2.3.2",
                    "first_patched_version": {
                        "identifier": "2.3.2"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "jupyterlab"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 3.0.0, < 3.0.17",
                    "first_patched_version": {
                        "identifier": "3.0.17"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "jupyterlab"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 3.1.0, < 3.1.4",
                    "first_patched_version": {
                        "identifier": "3.1.4"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "notebook"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 5.7.11",
                    "first_patched_version": {
                        "identifier": "5.7.11"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "notebook"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 6.0.0, < 6.4.1",
                    "first_patched_version": {
                        "identifier": "6.4.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:H/I:N/A:N",
                "score": 7.4
            },
            "cwes": [
                {
                    "cwe_id": "CWE-75",
                    "name": "Failure to Sanitize Special Elements into a Different Plane (Special Element Injection)"
                },
                {
                    "cwe_id": "CWE-79",
                    "name": "Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')"
                },
                {
                    "cwe_id": "CWE-87",
                    "name": "Improper Neutralization of Alternate XSS Syntax"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "jupyterlab"
            },
            "severity": "high",
            "vulnerable_version_range": ">= 2.0.0, < 2.2.10",
            "first_patched_version": {
                "identifier": "2.2.10"
            }
        },
        "url": "https://api.github.com/repos/username/minigrad/dependabot/alerts/6",
        "html_url": "https://github.com/username/minigrad/security/dependabot/6",
        "created_at": "2024-05-24T01:34:22Z",
        "updated_at": "2024-05-24T01:34:22Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 5,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "Pygments"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-9w8r-397f-prfh",
            "cve_id": "CVE-2021-20270",
            "summary": "Infinite Loop in Pygments",
            "description": "An infinite loop in SMLLexer in Pygments versions 1.5 to 2.7.3 may lead to denial of service when performing syntax highlighting of a Standard ML (SML) source file, as demonstrated by input that only contains the \"exception\" keyword.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-9w8r-397f-prfh",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2021-20270",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-20270"
                },
                {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1922136"
                },
                {
                    "url": "https://www.debian.org/security/2021/dsa-4889"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2021/05/msg00003.html"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2021/05/msg00006.html"
                },
                {
                    "url": "https://www.oracle.com/security-alerts/cpuoct2021.html"
                },
                {
                    "url": "https://github.com/pygments/pygments/commit/f91804ff4772e3ab41f46e28d370f57898700333"
                },
                {
                    "url": "https://github.com/advisories/GHSA-9w8r-397f-prfh"
                }
            ],
            "published_at": "2021-04-20T16:35:47Z",
            "updated_at": "2023-08-16T05:02:15Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Pygments"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 1.5, < 2.7.4",
                    "first_patched_version": {
                        "identifier": "2.7.4"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-835",
                    "name": "Loop with Unreachable Exit Condition ('Infinite Loop')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "Pygments"
            },
            "severity": "high",
            "vulnerable_version_range": ">= 1.5, < 2.7.4",
            "first_patched_version": {
                "identifier": "2.7.4"
            }
        },
        "url": "https://api.github.com/repos/username/minigrad/dependabot/alerts/5",
        "html_url": "https://github.com/username/minigrad/security/dependabot/5",
        "created_at": "2024-05-24T01:34:21Z",
        "updated_at": "2024-05-24T01:34:21Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 4,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "Pygments"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-pq64-v7f5-gqh8",
            "cve_id": "CVE-2021-27291",
            "summary": "Pygments vulnerable to Regular Expression Denial of Service (ReDoS)",
            "description": "In pygments 1.1+, fixed in 2.7.4, the lexers used to parse programming languages rely heavily on regular expressions. Some of the regular expressions have exponential or cubic worst-case complexity and are vulnerable to ReDoS. By crafting malicious input, an attacker can cause a denial of service.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-pq64-v7f5-gqh8",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2021-27291",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-27291"
                },
                {
                    "url": "https://github.com/pygments/pygments/commit/2e7e8c4a7b318f4032493773732754e418279a14"
                },
                {
                    "url": "https://gist.github.com/b-c-ds/b1a2cc0c68a35c57188575eb496de5ce"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2021/03/msg00024.html"
                },
                {
                    "url": "https://www.debian.org/security/2021/dsa-4878"
                },
                {
                    "url": "https://www.debian.org/security/2021/dsa-4889"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2021/05/msg00003.html"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2021/05/msg00006.html"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/GSJRFHALQ7E3UV4FFMFU2YQ6LUDHAI55/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WSLD67LFGXOX2K5YNESSWAS4AGZIJTUQ/"
                },
                {
                    "url": "https://github.com/advisories/GHSA-pq64-v7f5-gqh8"
                }
            ],
            "published_at": "2021-03-29T16:33:03Z",
            "updated_at": "2023-08-16T05:02:24Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Pygments"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 1.1, < 2.7.4",
                    "first_patched_version": {
                        "identifier": "2.7.4"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-400",
                    "name": "Uncontrolled Resource Consumption"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "Pygments"
            },
            "severity": "high",
            "vulnerable_version_range": ">= 1.1, < 2.7.4",
            "first_patched_version": {
                "identifier": "2.7.4"
            }
        },
        "url": "https://api.github.com/repos/username/minigrad/dependabot/alerts/4",
        "html_url": "https://github.com/username/minigrad/security/dependabot/4",
        "created_at": "2024-05-24T01:34:21Z",
        "updated_at": "2024-05-24T01:34:21Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 3,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "jinja2"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-g3rq-g295-4j3m",
            "cve_id": "CVE-2020-28493",
            "summary": "Regular Expression Denial of Service (ReDoS) in Jinja2",
            "description": "This affects the package jinja2 from 0.0.0 and before 2.11.3. The ReDOS vulnerability of the regex is mainly due to the sub-pattern [a-zA-Z0-9._-]+.[a-zA-Z0-9._-]+ This issue can be mitigated by Markdown to format user content instead of the urlize filter, or by implementing request timeouts and limiting process memory.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-g3rq-g295-4j3m",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2020-28493",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2020-28493"
                },
                {
                    "url": "https://github.com/pallets/jinja/pull/1343"
                },
                {
                    "url": "https://github.com/pallets/jinja/blob/ab81fd9c277900c85da0c322a2ff9d68a235b2e6/src/jinja2/utils.py%23L20"
                },
                {
                    "url": "https://snyk.io/vuln/SNYK-PYTHON-JINJA2-1012994"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PVAKCOO7VBVUBM3Q6CBBTPBFNP5NDXF4/"
                },
                {
                    "url": "https://security.gentoo.org/glsa/202107-19"
                },
                {
                    "url": "https://github.com/pallets/jinja/commit/15ef8f09b659f9100610583938005a7a10472d4d"
                },
                {
                    "url": "https://github.com/advisories/GHSA-g3rq-g295-4j3m"
                }
            ],
            "published_at": "2021-03-19T21:28:05Z",
            "updated_at": "2023-09-07T19:35:25Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "jinja2"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 2.11.3",
                    "first_patched_version": {
                        "identifier": "2.11.3"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
                "score": 5.3
            },
            "cwes": [
                {
                    "cwe_id": "CWE-400",
                    "name": "Uncontrolled Resource Consumption"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "jinja2"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 2.11.3",
            "first_patched_version": {
                "identifier": "2.11.3"
            }
        },
        "url": "https://api.github.com/repos/username/minigrad/dependabot/alerts/3",
        "html_url": "https://github.com/username/minigrad/security/dependabot/3",
        "created_at": "2024-05-24T01:34:21Z",
        "updated_at": "2024-05-24T01:34:21Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 2,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "bleach"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-vv2x-vrpj-qqpq",
            "cve_id": "CVE-2021-23980",
            "summary": "Cross-site scripting in Bleach",
            "description": "### Impact                                                                                                                                                                                                                                                    \n\nA [mutation XSS](https://cure53.de/fp170.pdf) affects users calling `bleach.clean` with all of:\n\n* `svg` or `math` in the allowed tags\n* `p` or `br` in allowed tags\n* `style`, `title`, `noscript`, `script`, `textarea`, `noframes`, `iframe`, or `xmp` in allowed tags\n* the keyword argument `strip_comments=False`\n\nNote: none of the above tags are in the default allowed tags and `strip_comments` defaults to `True`.\n\n### Patches\n\nUsers are encouraged to upgrade to bleach v3.3.0 or greater.\n\nNote: bleach v3.3.0 introduces a breaking change to escape HTML comments by default.\n\n### Workarounds\n\n* modify `bleach.clean` calls to at least one of:\n  * not allow the `style`, `title`, `noscript`, `script`, `textarea`, `noframes`, `iframe`, or `xmp` tag\n  * not allow `svg` or `math` tags\n  * not allow `p` or `br` tags\n  * set `strip_comments=True`\n\n* A strong [Content-Security-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) without `unsafe-inline` and `unsafe-eval` [`script-src`s](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src)) will also help mitigate the risk.\n\n### References\n\n* https://bugzilla.mozilla.org/show_bug.cgi?id=1689399\n* https://advisory.checkmarx.net/advisory/CX-2021-4303\n* https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-23980\n* https://cure53.de/fp170.pdf\n\n### Credits\n\n* Reported by [Yaniv Nizry](https://twitter.com/ynizry) from the CxSCA AppSec group at Checkmarx\n* Additional eject tags not mentioned in the original advisory and the CSP mitigation line being truncated in the revised advisory reported by [Michał Bentkowski](https://twitter.com/SecurityMB) at Securitum\n\n### For more information\n\nIf you have any questions or comments about this advisory:\n\n* Open an issue at [https://github.com/mozilla/bleach/issues](https://github.com/mozilla/bleach/issues)\n* Email us at [security@mozilla.org](mailto:security@mozilla.org)",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-vv2x-vrpj-qqpq",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2021-23980",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/mozilla/bleach/security/advisories/GHSA-vv2x-vrpj-qqpq"
                },
                {
                    "url": "https://github.com/mozilla/bleach/commit/79b7a3c5e56a09d1d323a5006afa59b56162eb13"
                },
                {
                    "url": "https://bugzilla.mozilla.org/show_bug.cgi?id=1689399"
                },
                {
                    "url": "https://cure53.de/fp170.pdf"
                },
                {
                    "url": "https://github.com/mozilla/bleach/blob/79b7a3c5e56a09d1d323a5006afa59b56162eb13/CHANGES#L4"
                },
                {
                    "url": "https://pypi.org/project/bleach/"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-23980"
                },
                {
                    "url": "https://bugzilla.mozilla.org/show_bug.cgi?id=CVE-2021-23980"
                },
                {
                    "url": "https://github.com/advisories/GHSA-vv2x-vrpj-qqpq"
                }
            ],
            "published_at": "2021-02-02T17:58:40Z",
            "updated_at": "2023-09-07T20:44:31Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "bleach"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 3.3.0",
                    "first_patched_version": {
                        "identifier": "3.3.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
                "score": 6.1
            },
            "cwes": [
                {
                    "cwe_id": "CWE-79",
                    "name": "Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "bleach"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 3.3.0",
            "first_patched_version": {
                "identifier": "3.3.0"
            }
        },
        "url": "https://api.github.com/repos/username/minigrad/dependabot/alerts/2",
        "html_url": "https://github.com/username/minigrad/security/dependabot/2",
        "created_at": "2024-05-24T01:34:21Z",
        "updated_at": "2024-05-24T01:34:21Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 1,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "notebook"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-c7vm-f5p4-8fqh",
            "cve_id": "CVE-2020-26215",
            "summary": "Open redirect in Jupyter Notebook",
            "description": "[localhost](http://localhost:8888)\n\n### Impact\n_What kind of vulnerability is it? Who is impacted?_\n\nOpen redirect vulnerability - a maliciously crafted link to a notebook server could redirect the browser to a different website.\n\nAll notebook servers are technically affected, however, these maliciously crafted links can only be reasonably made for known notebook server hosts. A link to your notebook server may *appear* safe, but ultimately redirect to a spoofed server on the public internet.\n\n### Patches\n\n_Has the problem been patched? What versions should users upgrade to?_\n\nPatched in notebook 6.1.5\n\n\n### References\n\n[OWASP page on open redirects](https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html)\n\n### For more information\n\nIf you have any questions or comments about this advisory, or vulnerabilities to report, please email our security list [security@ipython.org](mailto:security@ipython.org).\n\nCredit: zhuonan li of Alibaba Application Security Team",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-c7vm-f5p4-8fqh",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2020-26215",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/jupyter/notebook/security/advisories/GHSA-c7vm-f5p4-8fqh"
                },
                {
                    "url": "https://github.com/jupyter/notebook/commit/3cec4bbe21756de9f0c4bccf18cf61d840314d74"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2020-26215"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2020/12/msg00004.html"
                },
                {
                    "url": "https://github.com/advisories/GHSA-c7vm-f5p4-8fqh"
                }
            ],
            "published_at": "2020-11-18T21:06:36Z",
            "updated_at": "2023-01-09T05:04:16Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "notebook"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "<= 6.1.4",
                    "first_patched_version": {
                        "identifier": "6.1.5"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:H/PR:L/UI:R/S:C/C:N/I:L/A:L",
                "score": 4.4
            },
            "cwes": [
                {
                    "cwe_id": "CWE-601",
                    "name": "URL Redirection to Untrusted Site ('Open Redirect')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "notebook"
            },
            "severity": "medium",
            "vulnerable_version_range": "<= 6.1.4",
            "first_patched_version": {
                "identifier": "6.1.5"
            }
        },
        "url": "https://api.github.com/repos/username/minigrad/dependabot/alerts/1",
        "html_url": "https://github.com/username/minigrad/security/dependabot/1",
        "created_at": "2024-05-24T01:34:21Z",
        "updated_at": "2024-05-24T01:34:21Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    }
]