[
    {
        "number": 25,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "requests"
            },
            "manifest_path": "setup.py",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-9wx4-h78v-vm56",
            "cve_id": "CVE-2024-35195",
            "summary": "Requests `Session` object does not verify requests after making first request with verify=False",
            "description": "When making requests through a Requests `Session`, if the first request is made with `verify=False` to disable cert verification, all subsequent requests to the same origin will continue to ignore cert verification regardless of changes to the value of `verify`. This behavior will continue for the lifecycle of the connection in the connection pool.\n\n### Remediation\nAny of these options can be used to remediate the current issue, we highly recommend upgrading as the preferred mitigation.\n\n* Upgrade to `requests>=2.32.0`.\n* For `requests<2.32.0`, avoid setting `verify=False` for the first request to a host while using a Requests Session.\n* For `requests<2.32.0`, call `close()` on `Session` objects to clear existing connections if `verify=False` is used.\n\n### Related Links\n* https://github.com/psf/requests/pull/6655",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-9wx4-h78v-vm56",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-35195",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56"
                },
                {
                    "url": "https://github.com/psf/requests/pull/6655"
                },
                {
                    "url": "https://github.com/psf/requests/commit/a58d7f2ffb4d00b46dca2d70a3932a0b37e22fac"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-35195"
                },
                {
                    "url": "https://github.com/advisories/GHSA-9wx4-h78v-vm56"
                }
            ],
            "published_at": "2024-05-20T20:15:00Z",
            "updated_at": "2024-05-20T22:07:29Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "requests"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 2.32.0",
                    "first_patched_version": {
                        "identifier": "2.32.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N",
                "score": 5.6
            },
            "cwes": [
                {
                    "cwe_id": "CWE-670",
                    "name": "Always-Incorrect Control Flow Implementation"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "requests"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 2.32.0",
            "first_patched_version": {
                "identifier": "2.32.0"
            }
        },
        "url": "https://api.github.com/repos/username/superset/dependabot/alerts/25",
        "html_url": "https://github.com/username/superset/security/dependabot/25",
        "created_at": "2024-05-20T20:31:31Z",
        "updated_at": "2024-05-20T20:31:31Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 24,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "gunicorn"
            },
            "manifest_path": "setup.py",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-w3h3-4rj7-4ph4",
            "cve_id": "CVE-2024-1135",
            "summary": "Request smuggling leading to endpoint restriction bypass in Gunicorn",
            "description": "Gunicorn fails to properly validate Transfer-Encoding headers, leading to HTTP Request Smuggling (HRS) vulnerabilities. By crafting requests with conflicting Transfer-Encoding headers, attackers can bypass security restrictions and access restricted endpoints. This issue is due to Gunicorn's handling of Transfer-Encoding headers, where it incorrectly processes requests with multiple, conflicting Transfer-Encoding headers, treating them as chunked regardless of the final encoding specified. This vulnerability has been shown to allow access to endpoints restricted by gunicorn. This issue has been addressed in version 22.0.0.\n\nTo be affected users must have a network path which does not filter out invalid requests. These users are advised to block access to restricted endpoints via a firewall or other mechanism if they are unable to update.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-w3h3-4rj7-4ph4",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-1135",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-1135"
                },
                {
                    "url": "https://huntr.com/bounties/22158e34-cfd5-41ad-97e0-a780773d96c1"
                },
                {
                    "url": "https://github.com/benoitc/gunicorn/commit/ac29c9b0a758d21f1e0fb3b3457239e523fa9f1d"
                },
                {
                    "url": "https://github.com/benoitc/gunicorn/releases/tag/22.0.0"
                },
                {
                    "url": "https://github.com/advisories/GHSA-w3h3-4rj7-4ph4"
                }
            ],
            "published_at": "2024-04-16T00:30:32Z",
            "updated_at": "2024-05-24T19:21:23Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "gunicorn"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 22.0.0",
                    "first_patched_version": {
                        "identifier": "22.0.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:H/A:N",
                "score": 8.2
            },
            "cwes": [
                {
                    "cwe_id": "CWE-444",
                    "name": "Inconsistent Interpretation of HTTP Requests ('HTTP Request/Response Smuggling')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "gunicorn"
            },
            "severity": "high",
            "vulnerable_version_range": "< 22.0.0",
            "first_patched_version": {
                "identifier": "22.0.0"
            }
        },
        "url": "https://api.github.com/repos/username/superset/dependabot/alerts/24",
        "html_url": "https://github.com/username/superset/security/dependabot/24",
        "created_at": "2024-05-16T16:50:01Z",
        "updated_at": "2024-05-16T16:50:01Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 23,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "sqlparse"
            },
            "manifest_path": "setup.py",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-2m57-hf25-phgg",
            "cve_id": "CVE-2024-4340",
            "summary": "sqlparse parsing heavily nested list leads to Denial of Service",
            "description": "### Summary\nPassing a heavily nested list to sqlparse.parse() leads to a Denial of Service due to RecursionError.\n\n### Details + PoC\nRunning the following code will raise Maximum recursion limit exceeded exception:\n```py\nimport sqlparse\nsqlparse.parse('[' * 10000 + ']' * 10000)\n```\nWe expect a traceback of RecursionError:\n```py\nTraceback (most recent call last):\n  File \"trigger_sqlparse_nested_list.py\", line 3, in <module>\n    sqlparse.parse('[' * 10000 + ']' * 10000)\n  File \"/home/uriya/.local/lib/python3.10/site-packages/sqlparse/__init__.py\", line 30, in parse\n    return tuple(parsestream(sql, encoding))\n  File \"/home/uriya/.local/lib/python3.10/site-packages/sqlparse/engine/filter_stack.py\", line 36, in run\n    stmt = grouping.group(stmt)\n  File \"/home/uriya/.local/lib/python3.10/site-packages/sqlparse/engine/grouping.py\", line 428, in group\n    func(stmt)\n  File \"/home/uriya/.local/lib/python3.10/site-packages/sqlparse/engine/grouping.py\", line 53, in group_brackets\n    _group_matching(tlist, sql.SquareBrackets)\n  File \"/home/uriya/.local/lib/python3.10/site-packages/sqlparse/engine/grouping.py\", line 48, in _group_matching\n    tlist.group_tokens(cls, open_idx, close_idx)\n  File \"/home/uriya/.local/lib/python3.10/site-packages/sqlparse/sql.py\", line 328, in group_tokens\n    grp = grp_cls(subtokens)\n  File \"/home/uriya/.local/lib/python3.10/site-packages/sqlparse/sql.py\", line 161, in __init__\n    super().__init__(None, str(self))\n  File \"/home/uriya/.local/lib/python3.10/site-packages/sqlparse/sql.py\", line 165, in __str__\n    return ''.join(token.value for token in self.flatten())\n  File \"/home/uriya/.local/lib/python3.10/site-packages/sqlparse/sql.py\", line 165, in <genexpr>\n    return ''.join(token.value for token in self.flatten())\n  File \"/home/uriya/.local/lib/python3.10/site-packages/sqlparse/sql.py\", line 214, in flatten\n    yield from token.flatten()\n  File \"/home/uriya/.local/lib/python3.10/site-packages/sqlparse/sql.py\", line 214, in flatten\n    yield from token.flatten()\n  File \"/home/uriya/.local/lib/python3.10/site-packages/sqlparse/sql.py\", line 214, in flatten\n    yield from token.flatten()\n  [Previous line repeated 983 more times]\nRecursionError: maximum recursion depth exceeded\n```\n\n### Fix suggestion\nThe [flatten()](https://github.com/andialbrecht/sqlparse/blob/master/sqlparse/sql.py#L207) function of TokenList class should limit the recursion to a maximal depth:\n```py\nfrom sqlparse.exceptions import SQLParseError\n\nMAX_DEPTH = 100\n\n    def flatten(self, depth=1):\n        \"\"\"Generator yielding ungrouped tokens.\n\n        This method is recursively called for all child tokens.\n        \"\"\"\n    if depth >= MAX_DEPTH:\n        raise SQLParseError('Maximal depth reached')\n        for token in self.tokens:\n            if token.is_group:\n                yield from token.flatten(depth + 1)\n            else:\n                yield token\n```\n\n### Impact\nDenial of Service (the impact depends on the use).\nAnyone parsing a user input with sqlparse.parse() is affected.\n",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-2m57-hf25-phgg",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-4340",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/andialbrecht/sqlparse/security/advisories/GHSA-2m57-hf25-phgg"
                },
                {
                    "url": "https://github.com/andialbrecht/sqlparse/commit/b4a39d9850969b4e1d6940d32094ee0b42a2cf03"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-4340"
                },
                {
                    "url": "https://research.jfrog.com/vulnerabilities/sqlparse-stack-exhaustion-dos-jfsa-2024-001031292"
                },
                {
                    "url": "https://github.com/advisories/GHSA-2m57-hf25-phgg"
                }
            ],
            "published_at": "2024-04-15T20:21:25Z",
            "updated_at": "2024-05-01T11:09:13Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "sqlparse"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 0.5.0",
                    "first_patched_version": {
                        "identifier": "0.5.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-674",
                    "name": "Uncontrolled Recursion"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "sqlparse"
            },
            "severity": "high",
            "vulnerable_version_range": "< 0.5.0",
            "first_patched_version": {
                "identifier": "0.5.0"
            }
        },
        "url": "https://api.github.com/repos/username/superset/dependabot/alerts/23",
        "html_url": "https://github.com/username/superset/security/dependabot/23",
        "created_at": "2024-05-16T16:50:01Z",
        "updated_at": "2024-05-16T16:50:01Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 22,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "Flask-AppBuilder"
            },
            "manifest_path": "setup.py",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-j2pw-vp55-fqqj",
            "cve_id": "CVE-2024-25128",
            "summary": "Flask-AppBuilder vulnerable to incorrect authentication when using auth type OpenID ",
            "description": "### Impact\nWhen Flask-AppBuilder is set to AUTH_TYPE AUTH_OID, allows an attacker to forge an HTTP request, that could deceive the backend into using any requested OpenID service. This vulnerability could grant an attacker unauthorised privilege access if a custom OpenID service is deployed by the attacker and accessible by the backend. \n\nThis vulnerability is only exploitable when the application is using the old (deprecated 10 years ago) OpenID 2.0 authorization protocol (which is very different from the popular OIDC - Open ID Connect - popular protocol used today). Currently, this protocol is regarded as legacy, with significantly reduced usage and not supported for several years by major authorization providers.\n\n### Patches\nUpgrade to Flask-AppBuilder 4.3.11\n\n### Workarounds\nIf upgrade is not possible add the following to your config:\n\n```\nfrom flask import flash, redirect\nfrom flask_appbuilder import expose\nfrom flask_appbuilder.security.sqla.manager import SecurityManager\nfrom flask_appbuilder.security.views import AuthOIDView\nfrom flask_appbuilder.security.forms import LoginForm_oid\n\nbasedir = os.path.abspath(os.path.dirname(__file__))\n\n\nclass FixedOIDView(AuthOIDView):\n    @expose(\"/login/\", methods=[\"GET\", \"POST\"])\n    def login(self, flag=True):\n        form = LoginForm_oid()\n        if form.validate_on_submit():\n            identity_url = None\n            for provider in self.appbuilder.sm.openid_providers:\n                if provider.get(\"url\") == form.openid.data:\n                    identity_url = form.openid.data\n            if identity_url is None:\n                flash(self.invalid_login_message, \"warning\")\n                return redirect(self.appbuilder.get_url_for_login)\n        return super().login(flag=flag)\n\nclass FixedSecurityManager(SecurityManager):\n    authoidview = FixedOIDView\n\n\nFAB_SECURITY_MANAGER_CLASS = \"config.FixedSecurityManager\"\n```",
            "severity": "critical",
            "identifiers": [
                {
                    "value": "GHSA-j2pw-vp55-fqqj",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-25128",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/dpgaspar/Flask-AppBuilder/security/advisories/GHSA-j2pw-vp55-fqqj"
                },
                {
                    "url": "https://github.com/dpgaspar/Flask-AppBuilder/commit/6336456d83f8f111c842b2b53d1e89627f2502c8"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-25128"
                },
                {
                    "url": "https://github.com/advisories/GHSA-j2pw-vp55-fqqj"
                }
            ],
            "published_at": "2024-02-28T18:37:06Z",
            "updated_at": "2024-03-04T14:38:05Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Flask-AppBuilder"
                    },
                    "severity": "critical",
                    "vulnerable_version_range": "< 4.3.11",
                    "first_patched_version": {
                        "identifier": "4.3.11"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
                "score": 9.1
            },
            "cwes": [
                {
                    "cwe_id": "CWE-287",
                    "name": "Improper Authentication"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "Flask-AppBuilder"
            },
            "severity": "critical",
            "vulnerable_version_range": "< 4.3.11",
            "first_patched_version": {
                "identifier": "4.3.11"
            }
        },
        "url": "https://api.github.com/repos/username/superset/dependabot/alerts/22",
        "html_url": "https://github.com/username/superset/security/dependabot/22",
        "created_at": "2024-05-16T16:50:00Z",
        "updated_at": "2024-05-16T16:50:00Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 21,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "cryptography"
            },
            "manifest_path": "setup.py",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-9v9h-cgj8-h64p",
            "cve_id": "CVE-2024-0727",
            "summary": "Null pointer dereference in PKCS12 parsing",
            "description": "Issue summary: Processing a maliciously formatted PKCS12 file may lead OpenSSL\nto crash leading to a potential Denial of Service attack\n\nImpact summary: Applications loading files in the PKCS12 format from untrusted\nsources might terminate abruptly.\n\nA file in PKCS12 format can contain certificates and keys and may come from an\nuntrusted source. The PKCS12 specification allows certain fields to be NULL, but\nOpenSSL does not correctly check for this case. This can lead to a NULL pointer\ndereference that results in OpenSSL crashing. If an application processes PKCS12\nfiles from an untrusted source using the OpenSSL APIs then that application will\nbe vulnerable to this issue.\n\nOpenSSL APIs that are vulnerable to this are: PKCS12_parse(),\nPKCS12_unpack_p7data(), PKCS12_unpack_p7encdata(), PKCS12_unpack_authsafes()\nand PKCS12_newpass().\n\nWe have also fixed a similar issue in SMIME_write_PKCS7(). However since this\nfunction is related to writing data we do not consider it security significant.\n\nThe FIPS modules in 3.2, 3.1 and 3.0 are not affected by this issue.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-9v9h-cgj8-h64p",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-0727",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-0727"
                },
                {
                    "url": "https://github.com/openssl/openssl/commit/09df4395b5071217b76dc7d3d2e630eb8c5a79c2"
                },
                {
                    "url": "https://github.com/openssl/openssl/commit/775acfdbd0c6af9ac855f34969cdab0c0c90844a"
                },
                {
                    "url": "https://github.com/openssl/openssl/commit/d135eeab8a5dbf72b3da5240bab9ddb7678dbd2c"
                },
                {
                    "url": "https://github.openssl.org/openssl/extended-releases/commit/03b3941d60c4bce58fab69a0c22377ab439bc0e8"
                },
                {
                    "url": "https://github.openssl.org/openssl/extended-releases/commit/aebaa5883e31122b404e450732dc833dc9dee539"
                },
                {
                    "url": "https://www.openssl.org/news/secadv/20240125.txt"
                },
                {
                    "url": "https://github.com/github/advisory-database/pull/3472"
                },
                {
                    "url": "https://github.com/openssl/openssl/pull/23362"
                },
                {
                    "url": "https://github.com/alexcrichton/openssl-src-rs/commit/add20f73b6b42be7451af2e1044d4e0e778992b2"
                },
                {
                    "url": "https://github.com/pyca/cryptography/commit/3519591d255d4506fbcd0d04037d45271903c64d"
                },
                {
                    "url": "https://security.netapp.com/advisory/ntap-20240208-0006"
                },
                {
                    "url": "http://www.openwall.com/lists/oss-security/2024/03/11/1"
                },
                {
                    "url": "https://github.com/advisories/GHSA-9v9h-cgj8-h64p"
                }
            ],
            "published_at": "2024-01-26T09:30:23Z",
            "updated_at": "2024-05-12T05:03:47Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "cryptography"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 42.0.2",
                    "first_patched_version": {
                        "identifier": "42.0.2"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
                "score": 5.5
            },
            "cwes": []
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "cryptography"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 42.0.2",
            "first_patched_version": {
                "identifier": "42.0.2"
            }
        },
        "url": "https://api.github.com/repos/username/superset/dependabot/alerts/21",
        "html_url": "https://github.com/username/superset/security/dependabot/21",
        "created_at": "2024-05-16T16:50:00Z",
        "updated_at": "2024-05-16T16:50:00Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 20,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "cryptography"
            },
            "manifest_path": "setup.py",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-3ww4-gg4f-jr7f",
            "cve_id": "CVE-2023-50782",
            "summary": "Python Cryptography package vulnerable to Bleichenbacher timing oracle attack",
            "description": "A flaw was found in the python-cryptography package. This issue may allow a remote attacker to decrypt captured messages in TLS servers that use RSA key exchanges, which may lead to exposure of confidential or sensitive data.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-3ww4-gg4f-jr7f",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-50782",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-50782"
                },
                {
                    "url": "https://access.redhat.com/security/cve/CVE-2023-50782"
                },
                {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2254432"
                },
                {
                    "url": "https://github.com/pyca/cryptography/issues/9785"
                },
                {
                    "url": "https://github.com/advisories/GHSA-3ww4-gg4f-jr7f"
                }
            ],
            "published_at": "2024-02-05T21:30:31Z",
            "updated_at": "2024-02-14T21:31:39Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "cryptography"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 42.0.0",
                    "first_patched_version": {
                        "identifier": "42.0.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-203",
                    "name": "Observable Discrepancy"
                },
                {
                    "cwe_id": "CWE-208",
                    "name": "Observable Timing Discrepancy"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "cryptography"
            },
            "severity": "high",
            "vulnerable_version_range": "< 42.0.0",
            "first_patched_version": {
                "identifier": "42.0.0"
            }
        },
        "url": "https://api.github.com/repos/username/superset/dependabot/alerts/20",
        "html_url": "https://github.com/username/superset/security/dependabot/20",
        "created_at": "2024-05-16T16:50:00Z",
        "updated_at": "2024-05-16T16:50:00Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 19,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "cryptography"
            },
            "manifest_path": "setup.py",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-jm77-qphf-c4w8",
            "cve_id": null,
            "summary": "pyca/cryptography's wheels include vulnerable OpenSSL",
            "description": "pyca/cryptography's wheels include a statically linked copy of OpenSSL. The versions of OpenSSL included in cryptography 0.8-41.0.2 are vulnerable to several security issues. More details about the vulnerabilities themselves can be found in https://www.openssl.org/news/secadv/20230731.txt, https://www.openssl.org/news/secadv/20230719.txt, and https://www.openssl.org/news/secadv/20230714.txt.\n\nIf you are building cryptography source (\"sdist\") then you are responsible for upgrading your copy of OpenSSL. Only users installing from wheels built by the cryptography project (i.e., those distributed on PyPI) need to update their cryptography versions.",
            "severity": "low",
            "identifiers": [
                {
                    "value": "GHSA-jm77-qphf-c4w8",
                    "type": "GHSA"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/pyca/cryptography/security/advisories/GHSA-jm77-qphf-c4w8"
                },
                {
                    "url": "https://github.com/pyca/cryptography/commit/b22271cf3c3dd8dc8978f8f4b00b5c7060b6538d"
                },
                {
                    "url": "https://github.com/pyca/cryptography/commit/bfa4d95f0f356f2d535efd5c775e0fb3efe90ef2"
                },
                {
                    "url": "https://www.openssl.org/news/secadv/20230714.txt"
                },
                {
                    "url": "https://www.openssl.org/news/secadv/20230719.txt"
                },
                {
                    "url": "https://www.openssl.org/news/secadv/20230731.txt"
                },
                {
                    "url": "https://github.com/advisories/GHSA-jm77-qphf-c4w8"
                }
            ],
            "published_at": "2023-08-01T22:34:41Z",
            "updated_at": "2023-08-01T22:34:41Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "cryptography"
                    },
                    "severity": "low",
                    "vulnerable_version_range": ">= 0.8, < 41.0.3",
                    "first_patched_version": {
                        "identifier": "41.0.3"
                    }
                }
            ],
            "cvss": {
                "vector_string": null,
                "score": 0.0
            },
            "cwes": []
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "cryptography"
            },
            "severity": "low",
            "vulnerable_version_range": ">= 0.8, < 41.0.3",
            "first_patched_version": {
                "identifier": "41.0.3"
            }
        },
        "url": "https://api.github.com/repos/username/superset/dependabot/alerts/19",
        "html_url": "https://github.com/username/superset/security/dependabot/19",
        "created_at": "2024-05-16T16:50:00Z",
        "updated_at": "2024-05-16T16:50:00Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 18,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "Flask-AppBuilder"
            },
            "manifest_path": "setup.py",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-jhpr-j7cq-3jp3",
            "cve_id": "CVE-2023-34110",
            "summary": "Flask-AppBuilder vulnerable to possible disclosure of sensitive information on user error",
            "description": "### Impact\nAn authenticated malicious actor with Admin privileges, could by adding a special character on the add, edit User forms trigger a database error, this error is surfaced back to this actor on the UI. On certain database engines this error can include the entire user row including the pbkdf2:sha256 hashed password.\n \n### Patches\nFixed on 4.3.2\n",
            "severity": "low",
            "identifiers": [
                {
                    "value": "GHSA-jhpr-j7cq-3jp3",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-34110",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/dpgaspar/Flask-AppBuilder/security/advisories/GHSA-jhpr-j7cq-3jp3"
                },
                {
                    "url": "https://github.com/dpgaspar/Flask-AppBuilder/pull/2045"
                },
                {
                    "url": "https://github.com/dpgaspar/Flask-AppBuilder/commit/ae25ad4c87a9051ebe4a4e8f02aee73232642626"
                },
                {
                    "url": "https://github.com/dpgaspar/Flask-AppBuilder/releases/tag/v4.3.2"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-34110"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/flask-appbuilder/PYSEC-2023-94.yaml"
                },
                {
                    "url": "https://github.com/advisories/GHSA-jhpr-j7cq-3jp3"
                }
            ],
            "published_at": "2023-06-22T19:59:03Z",
            "updated_at": "2023-11-07T05:01:25Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Flask-AppBuilder"
                    },
                    "severity": "low",
                    "vulnerable_version_range": "< 4.3.2",
                    "first_patched_version": {
                        "identifier": "4.3.2"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:U/C:L/I:N/A:N",
                "score": 2.7
            },
            "cwes": [
                {
                    "cwe_id": "CWE-209",
                    "name": "Generation of Error Message Containing Sensitive Information"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "Flask-AppBuilder"
            },
            "severity": "low",
            "vulnerable_version_range": "< 4.3.2",
            "first_patched_version": {
                "identifier": "4.3.2"
            }
        },
        "url": "https://api.github.com/repos/username/superset/dependabot/alerts/18",
        "html_url": "https://github.com/username/superset/security/dependabot/18",
        "created_at": "2024-05-16T16:50:00Z",
        "updated_at": "2024-05-16T16:50:00Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 17,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "cryptography"
            },
            "manifest_path": "setup.py",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-5cpq-8wj7-hf2v",
            "cve_id": null,
            "summary": "Vulnerable OpenSSL included in cryptography wheels",
            "description": "pyca/cryptography's wheels include a statically linked copy of OpenSSL. The versions of OpenSSL included in cryptography 0.5-40.0.2 are vulnerable to a security issue. More details about the vulnerability itself can be found in https://www.openssl.org/news/secadv/20230530.txt.\n\nIf you are building cryptography source (\"sdist\") then you are responsible for upgrading your copy of OpenSSL. Only users installing from wheels built by the cryptography project (i.e., those distributed on PyPI) need to update their cryptography versions.",
            "severity": "low",
            "identifiers": [
                {
                    "value": "GHSA-5cpq-8wj7-hf2v",
                    "type": "GHSA"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/pyca/cryptography/security/advisories/GHSA-5cpq-8wj7-hf2v"
                },
                {
                    "url": "https://github.com/pyca/cryptography/commit/8708245ccdeaff21d65eea68a4f8d2a7c5949a22"
                },
                {
                    "url": "https://cryptography.io/en/latest/changelog/#v41-0-0"
                },
                {
                    "url": "https://github.com/advisories/GHSA-5cpq-8wj7-hf2v"
                }
            ],
            "published_at": "2023-06-02T17:13:10Z",
            "updated_at": "2023-06-02T17:13:11Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "cryptography"
                    },
                    "severity": "low",
                    "vulnerable_version_range": ">= 0.5, <= 40.0.2",
                    "first_patched_version": {
                        "identifier": "41.0.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": null,
                "score": 0.0
            },
            "cwes": []
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "cryptography"
            },
            "severity": "low",
            "vulnerable_version_range": ">= 0.5, <= 40.0.2",
            "first_patched_version": {
                "identifier": "41.0.0"
            }
        },
        "url": "https://api.github.com/repos/username/superset/dependabot/alerts/17",
        "html_url": "https://github.com/username/superset/security/dependabot/17",
        "created_at": "2024-05-16T16:50:00Z",
        "updated_at": "2024-05-16T16:50:00Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 16,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "requests"
            },
            "manifest_path": "setup.py",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-j8r2-6x86-q33q",
            "cve_id": "CVE-2023-32681",
            "summary": "Unintended leak of Proxy-Authorization header in requests",
            "description": "### Impact\n\nSince Requests v2.3.0, Requests has been vulnerable to potentially leaking `Proxy-Authorization` headers to destination servers, specifically during redirects to an HTTPS origin. This is a product of how `rebuild_proxies` is used to recompute and [reattach the `Proxy-Authorization` header](https://github.com/psf/requests/blob/f2629e9e3c7ce3c3c8c025bcd8db551101cbc773/requests/sessions.py#L319-L328) to requests when redirected. Note this behavior has _only_ been observed to affect proxied requests when credentials are supplied in the URL user information component (e.g. `https://username:password@proxy:8080`).\n\n**Current vulnerable behavior(s):**\n\n1. HTTP → HTTPS: **leak**\n2. HTTPS → HTTP: **no leak**\n3. HTTPS → HTTPS: **leak**\n4. HTTP → HTTP: **no leak**\n\nFor HTTP connections sent through the proxy, the proxy will identify the header in the request itself and remove it prior to forwarding to the destination server. However when sent over HTTPS, the `Proxy-Authorization` header must be sent in the CONNECT request as the proxy has no visibility into further tunneled requests. This results in Requests forwarding the header to the destination server unintentionally, allowing a malicious actor to potentially exfiltrate those credentials.\n\nThe reason this currently works for HTTPS connections in Requests is the `Proxy-Authorization` header is also handled by urllib3 with our usage of the ProxyManager in adapters.py with [`proxy_manager_for`](https://github.com/psf/requests/blob/f2629e9e3c7ce3c3c8c025bcd8db551101cbc773/requests/adapters.py#L199-L235). This will compute the required proxy headers in `proxy_headers` and pass them to the Proxy Manager, avoiding attaching them directly to the Request object. This will be our preferred option going forward for default usage.\n\n### Patches\nStarting in Requests v2.31.0, Requests will no longer attach this header to redirects with an HTTPS destination. This should have no negative impacts on the default behavior of the library as the proxy credentials are already properly being handled by urllib3's ProxyManager.\n\nFor users with custom adapters, this _may_ be potentially breaking if you were already working around this behavior. The previous functionality of `rebuild_proxies` doesn't make sense in any case, so we would encourage any users impacted to migrate any handling of Proxy-Authorization directly into their custom adapter.\n\n### Workarounds\nFor users who are not able to update Requests immediately, there is one potential workaround.\n\nYou may disable redirects by setting `allow_redirects` to `False` on all calls through Requests top-level APIs. Note that if you're currently relying on redirect behaviors, you will need to capture the 3xx response codes and ensure a new request is made to the redirect destination.\n```\nimport requests\nr = requests.get('http://github.com/', allow_redirects=False)\n```\n\n### Credits\n\nThis vulnerability was discovered and disclosed by the following individuals.\n\nDennis Brinkrolf, Haxolot (https://haxolot.com/)\nTobias Funke, (tobiasfunke93@gmail.com)",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-j8r2-6x86-q33q",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-32681",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/psf/requests/security/advisories/GHSA-j8r2-6x86-q33q"
                },
                {
                    "url": "https://github.com/psf/requests/commit/74ea7cf7a6a27a4eeb2ae24e162bcc942a6706d5"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-32681"
                },
                {
                    "url": "https://github.com/psf/requests/releases/tag/v2.31.0"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/requests/PYSEC-2023-74.yaml"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2023/06/msg00018.html"
                },
                {
                    "url": "https://security.gentoo.org/glsa/202309-08"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/AW7HNFGYP44RT3DUDQXG2QT3OEV2PJ7Y"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KOYASTZDGQG2BWLSNBPL3TQRL2G7QYNZ"
                },
                {
                    "url": "https://github.com/advisories/GHSA-j8r2-6x86-q33q"
                }
            ],
            "published_at": "2023-05-22T20:36:32Z",
            "updated_at": "2024-03-27T20:09:55Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "requests"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": ">= 2.3.0, < 2.31.0",
                    "first_patched_version": {
                        "identifier": "2.31.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:H/I:N/A:N",
                "score": 6.1
            },
            "cwes": [
                {
                    "cwe_id": "CWE-200",
                    "name": "Exposure of Sensitive Information to an Unauthorized Actor"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "requests"
            },
            "severity": "medium",
            "vulnerable_version_range": ">= 2.3.0, < 2.31.0",
            "first_patched_version": {
                "identifier": "2.31.0"
            }
        },
        "url": "https://api.github.com/repos/username/superset/dependabot/alerts/16",
        "html_url": "https://github.com/username/superset/security/dependabot/16",
        "created_at": "2024-05-16T16:50:00Z",
        "updated_at": "2024-05-16T16:50:00Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 15,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "sqlparse"
            },
            "manifest_path": "setup.py",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-rrm6-wvj7-cwh2",
            "cve_id": "CVE-2023-30608",
            "summary": "sqlparse contains a regular expression that is vulnerable to Regular Expression Denial of Service",
            "description": "### Impact\nThe SQL parser contains a regular expression that is vulnerable to [ReDoS](https://owasp.org/www-community/attacks/Regular_expression_Denial_of_Service_-_ReDoS) (Regular Expression Denial of Service). The vulnerability may lead to Denial of Service (DoS).\n\n### Patches\nThis issues has been fixed in sqlparse 0.4.4.\n\n### Workarounds\nNone. \n\n### References\nThis issue was discovered and reported by GHSL team member [@erik-krogh (Erik Krogh Kristensen)](https://github.com/erik-krogh).\n- Commit that introduced the vulnerability: e75e35869473832a1eb67772b1adfee2db11b85a\n",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-rrm6-wvj7-cwh2",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-30608",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/andialbrecht/sqlparse/security/advisories/GHSA-rrm6-wvj7-cwh2"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-30608"
                },
                {
                    "url": "https://github.com/andialbrecht/sqlparse/commit/c457abd5f097dd13fb21543381e7cfafe7d31cfb"
                },
                {
                    "url": "https://github.com/andialbrecht/sqlparse/commit/e75e35869473832a1eb67772b1adfee2db11b85a"
                },
                {
                    "url": "https://owasp.org/www-community/attacks/Regular_expression_Denial_of_Service_-_ReDoS"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2023/05/msg00017.html"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/sqlparse/PYSEC-2023-87.yaml"
                },
                {
                    "url": "https://github.com/advisories/GHSA-rrm6-wvj7-cwh2"
                }
            ],
            "published_at": "2023-04-21T20:24:21Z",
            "updated_at": "2023-11-11T05:06:31Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "sqlparse"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": ">= 0.1.15, < 0.4.4",
                    "first_patched_version": {
                        "identifier": "0.4.4"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
                "score": 5.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-1333",
                    "name": "Inefficient Regular Expression Complexity"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "sqlparse"
            },
            "severity": "medium",
            "vulnerable_version_range": ">= 0.1.15, < 0.4.4",
            "first_patched_version": {
                "identifier": "0.4.4"
            }
        },
        "url": "https://api.github.com/repos/username/superset/dependabot/alerts/15",
        "html_url": "https://github.com/username/superset/security/dependabot/15",
        "created_at": "2024-05-16T16:50:00Z",
        "updated_at": "2024-05-16T16:50:00Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 14,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "Flask-AppBuilder"
            },
            "manifest_path": "setup.py",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-9hcr-9hcv-x6pv",
            "cve_id": "CVE-2023-29005",
            "summary": "Flask-AppBuilder Has No Rate Limiting on Login AUTH DB",
            "description": "### Impact\nLack of rate limiting will allow an attacker to brute-force user credentials.\n\n### Patches\nAbility to enable rate limiting on Flask-AppBuilder >=  4.3.0. Use `AUTH_RATE_LIMITED = True` and `RATELIMIT_ENABLED = True` set the limit itself by using `AUTH_RATE_LIMIT`. Will apply only to database authentication.\n\n### Workarounds\nImplement rate limiting using a reverse proxy or other strategies. ",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-9hcr-9hcv-x6pv",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-29005",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/dpgaspar/Flask-AppBuilder/security/advisories/GHSA-9hcr-9hcv-x6pv"
                },
                {
                    "url": "https://github.com/dpgaspar/Flask-AppBuilder/pull/1976"
                },
                {
                    "url": "https://flask-limiter.readthedocs.io/en/stable/configuration.html"
                },
                {
                    "url": "https://github.com/dpgaspar/Flask-AppBuilder/releases/tag/v4.3.0"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-29005"
                },
                {
                    "url": "https://github.com/advisories/GHSA-9hcr-9hcv-x6pv"
                }
            ],
            "published_at": "2023-04-10T16:37:40Z",
            "updated_at": "2023-04-19T17:12:24Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Flask-AppBuilder"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 4.3.0",
                    "first_patched_version": {
                        "identifier": "4.3.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-307",
                    "name": "Improper Restriction of Excessive Authentication Attempts"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "Flask-AppBuilder"
            },
            "severity": "high",
            "vulnerable_version_range": "< 4.3.0",
            "first_patched_version": {
                "identifier": "4.3.0"
            }
        },
        "url": "https://api.github.com/repos/username/superset/dependabot/alerts/14",
        "html_url": "https://github.com/username/superset/security/dependabot/14",
        "created_at": "2024-05-16T16:50:00Z",
        "updated_at": "2024-05-16T16:50:00Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 13,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "cryptography"
            },
            "manifest_path": "setup.py",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-x4qr-2fvf-3mr5",
            "cve_id": "CVE-2023-0286",
            "summary": "Vulnerable OpenSSL included in cryptography wheels",
            "description": "pyca/cryptography's wheels include a statically linked copy of OpenSSL. The versions of OpenSSL included in cryptography 0.8.1-39.0.0  are vulnerable to a security issue. More details about the vulnerabilities themselves can be found in https://www.openssl.org/news/secadv/20221213.txt and https://www.openssl.org/news/secadv/20230207.txt.\n\nIf you are building cryptography source (\"sdist\") then you are responsible for upgrading your copy of OpenSSL. Only users installing from wheels built by the cryptography project (i.e., those distributed on PyPI) need to update their cryptography versions.\n\n",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-x4qr-2fvf-3mr5",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-0286",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/pyca/cryptography/security/advisories/GHSA-x4qr-2fvf-3mr5"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-0286"
                },
                {
                    "url": "https://rustsec.org/advisories/RUSTSEC-2023-0006.html"
                },
                {
                    "url": "https://www.openssl.org/news/secadv/20230207.txt"
                },
                {
                    "url": "https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=2c6c9d439b484e1ba9830d8454a34fa4f80fdfe9"
                },
                {
                    "url": "https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=2f7530077e0ef79d98718138716bc51ca0cad658"
                },
                {
                    "url": "https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=fd2af07dc083a350c959147097003a14a5e8ac4d"
                },
                {
                    "url": "https://access.redhat.com/security/cve/cve-2023-0286"
                },
                {
                    "url": "https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-3.6.2-relnotes.txt"
                },
                {
                    "url": "https://ftp.openbsd.org/pub/OpenBSD/patches/7.2/common/018_x509.patch.sig"
                },
                {
                    "url": "https://security.gentoo.org/glsa/202402-08"
                },
                {
                    "url": "https://github.com/advisories/GHSA-x4qr-2fvf-3mr5"
                }
            ],
            "published_at": "2023-02-08T22:17:06Z",
            "updated_at": "2024-02-05T20:44:21Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "cryptography"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 0.8.1, < 39.0.1",
                    "first_patched_version": {
                        "identifier": "39.0.1"
                    }
                },
                {
                    "package": {
                        "ecosystem": "rust",
                        "name": "openssl-src"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 111.25.0",
                    "first_patched_version": {
                        "identifier": "111.25.0"
                    }
                },
                {
                    "package": {
                        "ecosystem": "rust",
                        "name": "openssl-src"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 300.0.0, < 300.0.12",
                    "first_patched_version": {
                        "identifier": "300.0.12"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:H",
                "score": 7.4
            },
            "cwes": [
                {
                    "cwe_id": "CWE-843",
                    "name": "Access of Resource Using Incompatible Type ('Type Confusion')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "cryptography"
            },
            "severity": "high",
            "vulnerable_version_range": ">= 0.8.1, < 39.0.1",
            "first_patched_version": {
                "identifier": "39.0.1"
            }
        },
        "url": "https://api.github.com/repos/username/superset/dependabot/alerts/13",
        "html_url": "https://github.com/username/superset/security/dependabot/13",
        "created_at": "2024-05-16T16:49:59Z",
        "updated_at": "2024-05-16T16:49:59Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 12,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "future"
            },
            "manifest_path": "setup.py",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-v3c5-jqr6-7qm8",
            "cve_id": "CVE-2022-40899",
            "summary": "Python Charmers Future denial of service vulnerability",
            "description": "An issue discovered in Python Charmers Future 0.18.2 and earlier allows remote attackers to cause a denial of service via crafted Set-Cookie header from malicious web server. This issue has been patched in version 0.18.3.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-v3c5-jqr6-7qm8",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2022-40899",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-40899"
                },
                {
                    "url": "https://github.com/python/cpython/pull/17157"
                },
                {
                    "url": "https://github.com/PythonCharmers/python-future/blob/master/src/future/backports/http/cookiejar.py#L215"
                },
                {
                    "url": "https://pypi.org/project/future/"
                },
                {
                    "url": "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/"
                },
                {
                    "url": "https://github.com/PythonCharmers/python-future/commit/c91d70b34ef0402aef3e9d04364ba98509dca76f"
                },
                {
                    "url": "https://github.com/PythonCharmers/python-future/pull/610"
                },
                {
                    "url": "https://github.com/advisories/GHSA-v3c5-jqr6-7qm8"
                }
            ],
            "published_at": "2022-12-23T00:30:23Z",
            "updated_at": "2023-01-28T05:06:22Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "future"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "<= 0.18.2",
                    "first_patched_version": {
                        "identifier": "0.18.3"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": []
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "future"
            },
            "severity": "high",
            "vulnerable_version_range": "<= 0.18.2",
            "first_patched_version": {
                "identifier": "0.18.3"
            }
        },
        "url": "https://api.github.com/repos/username/superset/dependabot/alerts/12",
        "html_url": "https://github.com/username/superset/security/dependabot/12",
        "created_at": "2024-05-16T16:49:59Z",
        "updated_at": "2024-05-16T16:49:59Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 11,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "Flask-AppBuilder"
            },
            "manifest_path": "setup.py",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-32ff-4g79-vgfc",
            "cve_id": "CVE-2022-31177",
            "summary": "Flask-AppBuilder before v4.1.3 allows inference of sensitive information through query strings",
            "description": "### Impact\nAn authenticated Admin user could craft HTTP requests to filter users by their salted and hashed passwords strings. These filters could be made by using partial hashed password strings. The response would not include the hashed passwords, but an attacker could infer partial password hashes and their respective users.\n\nOnly when using `AUTH_DB` database authentication option.\n\n### Patches\nFixed on 4.1.3\n\n### For more information\nIf you have any questions or comments about this advisory:\n* Open an issue in [example link to repo](http://example.com)\n* Email us at [example email address](mailto:example@example.com)\n",
            "severity": "low",
            "identifiers": [
                {
                    "value": "GHSA-32ff-4g79-vgfc",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2022-31177",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/dpgaspar/Flask-AppBuilder/security/advisories/GHSA-32ff-4g79-vgfc"
                },
                {
                    "url": "https://github.com/dpgaspar/Flask-AppBuilder/releases/tag/v4.1.3"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-31177"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/flask-appbuilder/PYSEC-2022-247.yaml"
                },
                {
                    "url": "https://github.com/advisories/GHSA-32ff-4g79-vgfc"
                }
            ],
            "published_at": "2022-07-29T22:28:12Z",
            "updated_at": "2023-01-30T05:01:17Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Flask-AppBuilder"
                    },
                    "severity": "low",
                    "vulnerable_version_range": "< 4.1.3",
                    "first_patched_version": {
                        "identifier": "4.1.3"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:U/C:L/I:N/A:N",
                "score": 2.7
            },
            "cwes": [
                {
                    "cwe_id": "CWE-200",
                    "name": "Exposure of Sensitive Information to an Unauthorized Actor"
                },
                {
                    "cwe_id": "CWE-916",
                    "name": "Use of Password Hash With Insufficient Computational Effort"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "Flask-AppBuilder"
            },
            "severity": "low",
            "vulnerable_version_range": "< 4.1.3",
            "first_patched_version": {
                "identifier": "4.1.3"
            }
        },
        "url": "https://api.github.com/repos/username/superset/dependabot/alerts/11",
        "html_url": "https://github.com/username/superset/security/dependabot/11",
        "created_at": "2024-05-16T16:49:59Z",
        "updated_at": "2024-05-16T16:49:59Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 10,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "Flask-AppBuilder"
            },
            "manifest_path": "setup.py",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-2ccw-7px8-vmpf",
            "cve_id": "CVE-2022-24776",
            "summary": "Open Redirect in Flask-AppBuilder",
            "description": "Flask-AppBuilder is an application development framework built on top of Flask. Versions prior to 3.4.5 contain an open redirect vulnerability when using the database authentication login page. There are no known workarounds. Users are recommended to upgrade to version 3.4.5 or later.\n\n### For more information\nIf you have any questions or comments about this advisory:\n* Open an issue in [Flask-AppBuilder](https://github.com/dpgaspar/Flask-AppBuilder)\n",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-2ccw-7px8-vmpf",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2022-24776",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/dpgaspar/Flask-AppBuilder/security/advisories/GHSA-2ccw-7px8-vmpf"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-24776"
                },
                {
                    "url": "https://github.com/dpgaspar/Flask-AppBuilder/pull/1804"
                },
                {
                    "url": "https://github.com/dpgaspar/Flask-AppBuilder/releases/tag/v3.4.5"
                },
                {
                    "url": "https://github.com/dpgaspar/Flask-AppBuilder/pull/1804/commits/5214d975ebad2ff32057443d2cc20fef1c04d0ea"
                },
                {
                    "url": "https://github.com/advisories/GHSA-2ccw-7px8-vmpf"
                }
            ],
            "published_at": "2022-03-25T19:27:39Z",
            "updated_at": "2023-01-27T05:01:02Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Flask-AppBuilder"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 3.4.5",
                    "first_patched_version": {
                        "identifier": "3.4.5"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
                "score": 6.1
            },
            "cwes": [
                {
                    "cwe_id": "CWE-601",
                    "name": "URL Redirection to Untrusted Site ('Open Redirect')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "Flask-AppBuilder"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 3.4.5",
            "first_patched_version": {
                "identifier": "3.4.5"
            }
        },
        "url": "https://api.github.com/repos/username/superset/dependabot/alerts/10",
        "html_url": "https://github.com/username/superset/security/dependabot/10",
        "created_at": "2024-05-16T16:49:59Z",
        "updated_at": "2024-05-16T16:49:59Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 9,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "Flask-AppBuilder"
            },
            "manifest_path": "setup.py",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-wfjw-w6pv-8p7f",
            "cve_id": "CVE-2022-21659",
            "summary": "Observable Response Discrepancy in Flask-AppBuilder",
            "description": "### Impact\nUser enumeration in database authentication in Flask-AppBuilder  < 3.4.4. Allows for a non authenticated user to enumerate existing accounts by timing the response time from the server when you are logging in.\n\n### Patches\nUpgrade to 3.4.4\n\n### Workarounds\n\n### References\n\n### For more information\nIf you have any questions or comments about this advisory:\n* Open an issue in [example link to repo](http://example.com)\n* Email us at [example email address](mailto:example@example.com)\n",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-wfjw-w6pv-8p7f",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2022-21659",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/dpgaspar/Flask-AppBuilder/security/advisories/GHSA-wfjw-w6pv-8p7f"
                },
                {
                    "url": "https://github.com/dpgaspar/Flask-AppBuilder/pull/1775"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-21659"
                },
                {
                    "url": "https://github.com/advisories/GHSA-wfjw-w6pv-8p7f"
                }
            ],
            "published_at": "2022-02-01T00:47:53Z",
            "updated_at": "2023-02-03T05:05:34Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Flask-AppBuilder"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 3.4.4",
                    "first_patched_version": {
                        "identifier": "3.4.4"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
                "score": 5.3
            },
            "cwes": [
                {
                    "cwe_id": "CWE-203",
                    "name": "Observable Discrepancy"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "Flask-AppBuilder"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 3.4.4",
            "first_patched_version": {
                "identifier": "3.4.4"
            }
        },
        "url": "https://api.github.com/repos/username/superset/dependabot/alerts/9",
        "html_url": "https://github.com/username/superset/security/dependabot/9",
        "created_at": "2024-05-16T16:49:59Z",
        "updated_at": "2024-05-16T16:49:59Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 8,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "celery"
            },
            "manifest_path": "setup.py",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-q4xr-rc97-m4xx",
            "cve_id": "CVE-2021-23727",
            "summary": "OS Command Injection in celery",
            "description": "This affects the package celery before 5.2.2. It by default trusts the messages and metadata stored in backends (result stores). When reading task metadata from the backend, the data is deserialized. Given that an attacker can gain access to, or somehow manipulate the metadata within a celery backend, they could trigger a stored command injection vulnerability and potentially gain further access to the system.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-q4xr-rc97-m4xx",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2021-23727",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-23727"
                },
                {
                    "url": "https://github.com/celery/celery/blob/master/Changelog.rst%23522"
                },
                {
                    "url": "https://snyk.io/vuln/SNYK-PYTHON-CELERY-2314953"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/SYXRGHWHD2WWMHBWCVD5ULVINPKNY3P5/"
                },
                {
                    "url": "https://github.com/celery/celery/commit/1f7ad7e6df1e02039b6ab9eec617d283598cad6b"
                },
                {
                    "url": "https://github.com/advisories/GHSA-q4xr-rc97-m4xx"
                }
            ],
            "published_at": "2022-01-06T22:22:02Z",
            "updated_at": "2023-09-27T20:52:36Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "celery"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 5.2.2",
                    "first_patched_version": {
                        "identifier": "5.2.2"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:H/I:H/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-77",
                    "name": "Improper Neutralization of Special Elements used in a Command ('Command Injection')"
                },
                {
                    "cwe_id": "CWE-78",
                    "name": "Improper Neutralization of Special Elements used in an OS Command ('OS Command Injection')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "celery"
            },
            "severity": "high",
            "vulnerable_version_range": "< 5.2.2",
            "first_patched_version": {
                "identifier": "5.2.2"
            }
        },
        "url": "https://api.github.com/repos/username/superset/dependabot/alerts/8",
        "html_url": "https://github.com/username/superset/security/dependabot/8",
        "created_at": "2024-05-16T16:49:59Z",
        "updated_at": "2024-05-16T16:49:59Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 7,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "Flask-AppBuilder"
            },
            "manifest_path": "setup.py",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-m3rf-7m4w-r66q",
            "cve_id": "CVE-2021-41265",
            "summary": "Improper Authentication in Flask-AppBuilder",
            "description": "### Impact\nImproper authentication on the REST API. Allows for a malicious actor with a carefully crafted request to successfully authenticate and gain access to existing protected REST API endpoints. Only affects non database authentication types, and new REST API endpoints.\n\n### Patches\nUpgrade to Flask-AppBuilder 3.3.4\n\n### For more information\nIf you have any questions or comments about this advisory:\n* Open an issue in https://github.com/dpgaspar/Flask-AppBuilder\n",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-m3rf-7m4w-r66q",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2021-41265",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/dpgaspar/Flask-AppBuilder/security/advisories/GHSA-m3rf-7m4w-r66q"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-41265"
                },
                {
                    "url": "https://github.com/dpgaspar/Flask-AppBuilder/commit/eba517aab121afa3f3f2edb011ec6bc4efd61fbc"
                },
                {
                    "url": "https://github.com/dpgaspar/Flask-AppBuilder/releases/tag/v3.3.4"
                },
                {
                    "url": "https://github.com/advisories/GHSA-m3rf-7m4w-r66q"
                }
            ],
            "published_at": "2021-12-09T19:09:07Z",
            "updated_at": "2023-02-01T05:06:59Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Flask-AppBuilder"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 3.3.4",
                    "first_patched_version": {
                        "identifier": "3.3.4"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N",
                "score": 8.1
            },
            "cwes": [
                {
                    "cwe_id": "CWE-287",
                    "name": "Improper Authentication"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "Flask-AppBuilder"
            },
            "severity": "high",
            "vulnerable_version_range": "< 3.3.4",
            "first_patched_version": {
                "identifier": "3.3.4"
            }
        },
        "url": "https://api.github.com/repos/username/superset/dependabot/alerts/7",
        "html_url": "https://github.com/username/superset/security/dependabot/7",
        "created_at": "2024-05-16T16:49:59Z",
        "updated_at": "2024-05-16T16:49:59Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 6,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "Flask-AppBuilder"
            },
            "manifest_path": "setup.py",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-624f-cqvr-3qw4",
            "cve_id": "CVE-2021-32805",
            "summary": "URL Redirection to Untrusted Site ('Open Redirect') in Flask-AppBuilder",
            "description": "### Impact\nIf using Flask-AppBuilder OAuth, an attacker can share a carefully crafted URL with a trusted domain for an application built with Flask-AppBuilder, this URL can redirect a user to a malicious site. This is an open redirect vulnerability \n\n### Patches\nInstall Flask-AppBuilder 3.2.2 or above\n\n### Workarounds\nFilter HTTP traffic containing `?next={next-site}` where the `next-site` domain is different from the application you are protecting\n",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-624f-cqvr-3qw4",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2021-32805",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/dpgaspar/Flask-AppBuilder/security/advisories/GHSA-624f-cqvr-3qw4"
                },
                {
                    "url": "https://github.com/dpgaspar/Flask-AppBuilder/commit/6af28521589599b1dbafd6313256229ee9a4fa74"
                },
                {
                    "url": "https://github.com/dpgaspar/Flask-AppBuilder/releases/tag/v3.3.2"
                },
                {
                    "url": "https://pypi.org/project/Flask-AppBuilder/"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-32805"
                },
                {
                    "url": "https://github.com/advisories/GHSA-624f-cqvr-3qw4"
                }
            ],
            "published_at": "2021-09-08T21:11:14Z",
            "updated_at": "2023-02-01T05:06:25Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Flask-AppBuilder"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 3.3.2",
                    "first_patched_version": {
                        "identifier": "3.3.2"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:L/I:L/A:N",
                "score": 7.2
            },
            "cwes": [
                {
                    "cwe_id": "CWE-601",
                    "name": "URL Redirection to Untrusted Site ('Open Redirect')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "Flask-AppBuilder"
            },
            "severity": "high",
            "vulnerable_version_range": "< 3.3.2",
            "first_patched_version": {
                "identifier": "3.3.2"
            }
        },
        "url": "https://api.github.com/repos/username/superset/dependabot/alerts/6",
        "html_url": "https://github.com/username/superset/security/dependabot/6",
        "created_at": "2024-05-16T16:49:59Z",
        "updated_at": "2024-05-16T16:49:59Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 5,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "Flask-AppBuilder"
            },
            "manifest_path": "setup.py",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-434h-p4gx-jm89",
            "cve_id": "CVE-2021-29621",
            "summary": "Observable Response Discrepancy in Flask-AppBuilder",
            "description": "### Impact\nUser enumeration in database authentication in Flask-AppBuilder <= 3.2.3. Allows for a non authenticated user to enumerate existing accounts by timing the response time from the server when you are logging in.\n\n### Patches\nUpgrade to 3.3.0\n\n### For more information\nIf you have any questions or comments about this advisory:\n* Open an issue in [Flask-AppBuilder](https://github.com/dpgaspar/Flask-AppBuilder)\n\n",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-434h-p4gx-jm89",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2021-29621",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/dpgaspar/Flask-AppBuilder/security/advisories/GHSA-434h-p4gx-jm89"
                },
                {
                    "url": "https://github.com/dpgaspar/Flask-AppBuilder/commit/780bd0e8fbf2d36ada52edb769477e0a4edae580"
                },
                {
                    "url": "https://pypi.org/project/Flask-AppBuilder/"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-29621"
                },
                {
                    "url": "https://lists.apache.org/thread.html/r5b754118ba4e996adf03863705d34168bffec202da5c6bdc9bf3add5@%3Cannounce.apache.org%3E"
                },
                {
                    "url": "https://lists.apache.org/thread.html/r466759f377651f0a690475d5a52564d0e786e82c08d5a5730a4f8352@%3Cannounce.apache.org%3E"
                },
                {
                    "url": "https://lists.apache.org/thread.html/r91067f953906d93aaa1c69fe2b5472754019cc6bd4f1ba81349d62a0@%3Ccommits.airflow.apache.org%3E"
                },
                {
                    "url": "https://github.com/advisories/GHSA-434h-p4gx-jm89"
                }
            ],
            "published_at": "2021-05-27T18:38:36Z",
            "updated_at": "2023-02-01T05:05:56Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Flask-AppBuilder"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 3.3.0",
                    "first_patched_version": {
                        "identifier": "3.3.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N",
                "score": 5.3
            },
            "cwes": [
                {
                    "cwe_id": "CWE-203",
                    "name": "Observable Discrepancy"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "Flask-AppBuilder"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 3.3.0",
            "first_patched_version": {
                "identifier": "3.3.0"
            }
        },
        "url": "https://api.github.com/repos/username/superset/dependabot/alerts/5",
        "html_url": "https://github.com/username/superset/security/dependabot/5",
        "created_at": "2024-05-16T16:49:58Z",
        "updated_at": "2024-05-16T16:49:58Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 4,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "cryptography"
            },
            "manifest_path": "setup.py",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-hggm-jpg3-v476",
            "cve_id": "CVE-2020-25659",
            "summary": "RSA decryption vulnerable to Bleichenbacher timing vulnerability",
            "description": "RSA decryption was vulnerable to Bleichenbacher timing vulnerabilities, which would impact people using RSA decryption in online scenarios. This is fixed in cryptography 3.2. ",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-hggm-jpg3-v476",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2020-25659",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/pyca/cryptography/security/advisories/GHSA-hggm-jpg3-v476"
                },
                {
                    "url": "https://github.com/pyca/cryptography/commit/58494b41d6ecb0f56b7c5f05d5f5e3ca0320d494"
                },
                {
                    "url": "https://pypi.org/project/cryptography/"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2020-25659"
                },
                {
                    "url": "https://github.com/pyca/cryptography/pull/5507/commits/ce1bef6f1ee06ac497ca0c837fbd1c7ef6c2472b"
                },
                {
                    "url": "https://www.oracle.com/security-alerts/cpuapr2022.html"
                },
                {
                    "url": "https://www.oracle.com/security-alerts/cpujul2022.html"
                },
                {
                    "url": "https://github.com/advisories/GHSA-hggm-jpg3-v476"
                }
            ],
            "published_at": "2020-10-27T20:33:13Z",
            "updated_at": "2024-02-02T22:03:07Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "cryptography"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 3.2",
                    "first_patched_version": {
                        "identifier": "3.2"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N",
                "score": 5.9
            },
            "cwes": [
                {
                    "cwe_id": "CWE-385",
                    "name": "Covert Timing Channel"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "cryptography"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 3.2",
            "first_patched_version": {
                "identifier": "3.2"
            }
        },
        "url": "https://api.github.com/repos/username/superset/dependabot/alerts/4",
        "html_url": "https://github.com/username/superset/security/dependabot/4",
        "created_at": "2024-05-16T16:49:58Z",
        "updated_at": "2024-05-16T16:49:58Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 3,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "SQLAlchemy"
            },
            "manifest_path": "setup.py",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-887w-45rq-vxgf",
            "cve_id": "CVE-2019-7164",
            "summary": "SQLAlchemy vulnerable to SQL Injection via order_by parameter",
            "description": "SQLAlchemy through 1.2.17 and 1.3.x through 1.3.0b2 allows SQL Injection via the order_by parameter.",
            "severity": "critical",
            "identifiers": [
                {
                    "value": "GHSA-887w-45rq-vxgf",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2019-7164",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-7164"
                },
                {
                    "url": "https://github.com/sqlalchemy/sqlalchemy/issues/4481"
                },
                {
                    "url": "https://access.redhat.com/errata/RHSA-2019:0981"
                },
                {
                    "url": "https://access.redhat.com/errata/RHSA-2019:0984"
                },
                {
                    "url": "https://github.com/advisories/GHSA-887w-45rq-vxgf"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2019/03/msg00020.html"
                },
                {
                    "url": "https://www.oracle.com/security-alerts/cpujan2021.html"
                },
                {
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00087.html"
                },
                {
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00010.html"
                },
                {
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00016.html"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2021/11/msg00005.html"
                },
                {
                    "url": "https://github.com/sqlalchemy/sqlalchemy/commit/30307c4616ad67c01ddae2e1e8e34fabf6028414"
                }
            ],
            "published_at": "2019-04-16T15:50:41Z",
            "updated_at": "2023-09-01T09:50:01Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "SQLAlchemy"
                    },
                    "severity": "critical",
                    "vulnerable_version_range": "< 1.3.0",
                    "first_patched_version": {
                        "identifier": "1.3.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                "score": 9.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-89",
                    "name": "Improper Neutralization of Special Elements used in an SQL Command ('SQL Injection')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "SQLAlchemy"
            },
            "severity": "critical",
            "vulnerable_version_range": "< 1.3.0",
            "first_patched_version": {
                "identifier": "1.3.0"
            }
        },
        "url": "https://api.github.com/repos/username/superset/dependabot/alerts/3",
        "html_url": "https://github.com/username/superset/security/dependabot/3",
        "created_at": "2024-05-16T16:49:58Z",
        "updated_at": "2024-05-16T16:49:58Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 2,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "SQLAlchemy"
            },
            "manifest_path": "setup.py",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-38fc-9xqv-7f7q",
            "cve_id": "CVE-2019-7548",
            "summary": "SQLAlchemy is vulnerable to SQL Injection via group_by parameter ",
            "description": "SQLAlchemy 1.2.17 has SQL Injection when the group_by parameter can be controlled.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-38fc-9xqv-7f7q",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2019-7548",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-7548"
                },
                {
                    "url": "https://github.com/sqlalchemy/sqlalchemy/issues/4481#issuecomment-461204518"
                },
                {
                    "url": "https://access.redhat.com/errata/RHSA-2019:0981"
                },
                {
                    "url": "https://access.redhat.com/errata/RHSA-2019:0984"
                },
                {
                    "url": "https://github.com/advisories/GHSA-38fc-9xqv-7f7q"
                },
                {
                    "url": "https://github.com/no-security/sqlalchemy_test"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2019/03/msg00020.html"
                },
                {
                    "url": "https://www.oracle.com/security-alerts/cpujan2021.html"
                },
                {
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00087.html"
                },
                {
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00010.html"
                },
                {
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00016.html"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2021/11/msg00005.html"
                }
            ],
            "published_at": "2019-04-16T15:50:39Z",
            "updated_at": "2023-09-01T09:56:01Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "SQLAlchemy"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 1.3.0",
                    "first_patched_version": {
                        "identifier": "1.3.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.0/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
                "score": 7.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-89",
                    "name": "Improper Neutralization of Special Elements used in an SQL Command ('SQL Injection')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "SQLAlchemy"
            },
            "severity": "high",
            "vulnerable_version_range": "< 1.3.0",
            "first_patched_version": {
                "identifier": "1.3.0"
            }
        },
        "url": "https://api.github.com/repos/username/superset/dependabot/alerts/2",
        "html_url": "https://github.com/username/superset/security/dependabot/2",
        "created_at": "2024-05-16T16:49:58Z",
        "updated_at": "2024-05-16T16:49:58Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 1,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "requests"
            },
            "manifest_path": "setup.py",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-x84v-xcm2-53pg",
            "cve_id": "CVE-2018-18074",
            "summary": "Insufficiently Protected Credentials in Requests",
            "description": "The Requests package through 2.19.1 before 2018-09-14 for Python sends an HTTP Authorization header to an http URI upon receiving a same-hostname https-to-http redirect, which makes it easier for remote attackers to discover credentials by sniffing the network.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-x84v-xcm2-53pg",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2018-18074",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2018-18074"
                },
                {
                    "url": "https://github.com/requests/requests/issues/4716"
                },
                {
                    "url": "https://github.com/requests/requests/pull/4718"
                },
                {
                    "url": "https://github.com/requests/requests/commit/c45d7c49ea75133e52ab22a8e9e13173938e36ff"
                },
                {
                    "url": "https://access.redhat.com/errata/RHSA-2019:2035"
                },
                {
                    "url": "https://bugs.debian.org/910766"
                },
                {
                    "url": "https://github.com/advisories/GHSA-x84v-xcm2-53pg"
                },
                {
                    "url": "https://usn.ubuntu.com/3790-1/"
                },
                {
                    "url": "https://usn.ubuntu.com/3790-2/"
                },
                {
                    "url": "http://docs.python-requests.org/en/master/community/updates/#release-and-version-history"
                },
                {
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2019-07/msg00024.html"
                },
                {
                    "url": "https://www.oracle.com/security-alerts/cpujul2022.html"
                }
            ],
            "published_at": "2018-10-29T19:06:46Z",
            "updated_at": "2023-02-01T05:04:21Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "requests"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "<= 2.19.1",
                    "first_patched_version": {
                        "identifier": "2.20.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-522",
                    "name": "Insufficiently Protected Credentials"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "requests"
            },
            "severity": "high",
            "vulnerable_version_range": "<= 2.19.1",
            "first_patched_version": {
                "identifier": "2.20.0"
            }
        },
        "url": "https://api.github.com/repos/username/superset/dependabot/alerts/1",
        "html_url": "https://github.com/username/superset/security/dependabot/1",
        "created_at": "2024-05-16T16:49:58Z",
        "updated_at": "2024-05-16T16:49:58Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    }
]