[
    {
        "number": 96,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "requests"
            },
            "manifest_path": "requirements.min.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-9wx4-h78v-vm56",
            "cve_id": "CVE-2024-35195",
            "summary": "Requests `Session` object does not verify requests after making first request with verify=False",
            "description": "When making requests through a Requests `Session`, if the first request is made with `verify=False` to disable cert verification, all subsequent requests to the same origin will continue to ignore cert verification regardless of changes to the value of `verify`. This behavior will continue for the lifecycle of the connection in the connection pool.\n\n### Remediation\nAny of these options can be used to remediate the current issue, we highly recommend upgrading as the preferred mitigation.\n\n* Upgrade to `requests>=2.32.0`.\n* For `requests<2.32.0`, avoid setting `verify=False` for the first request to a host while using a Requests Session.\n* For `requests<2.32.0`, call `close()` on `Session` objects to clear existing connections if `verify=False` is used.\n\n### Related Links\n* https://github.com/psf/requests/pull/6655",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-9wx4-h78v-vm56",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-35195",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56"
                },
                {
                    "url": "https://github.com/psf/requests/pull/6655"
                },
                {
                    "url": "https://github.com/psf/requests/commit/a58d7f2ffb4d00b46dca2d70a3932a0b37e22fac"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-35195"
                },
                {
                    "url": "https://github.com/advisories/GHSA-9wx4-h78v-vm56"
                }
            ],
            "published_at": "2024-05-20T20:15:00Z",
            "updated_at": "2024-05-20T22:07:29Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "requests"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 2.32.0",
                    "first_patched_version": {
                        "identifier": "2.32.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N",
                "score": 5.6
            },
            "cwes": [
                {
                    "cwe_id": "CWE-670",
                    "name": "Always-Incorrect Control Flow Implementation"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "requests"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 2.32.0",
            "first_patched_version": {
                "identifier": "2.32.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/evidently/dependabot/alerts/96",
        "html_url": "https://github.com/fcas/evidently/security/dependabot/96",
        "created_at": "2024-05-24T01:34:19Z",
        "updated_at": "2024-05-24T01:34:19Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 95,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "requests"
            },
            "manifest_path": "examples/integrations/streamlit_dashboard/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-9wx4-h78v-vm56",
            "cve_id": "CVE-2024-35195",
            "summary": "Requests `Session` object does not verify requests after making first request with verify=False",
            "description": "When making requests through a Requests `Session`, if the first request is made with `verify=False` to disable cert verification, all subsequent requests to the same origin will continue to ignore cert verification regardless of changes to the value of `verify`. This behavior will continue for the lifecycle of the connection in the connection pool.\n\n### Remediation\nAny of these options can be used to remediate the current issue, we highly recommend upgrading as the preferred mitigation.\n\n* Upgrade to `requests>=2.32.0`.\n* For `requests<2.32.0`, avoid setting `verify=False` for the first request to a host while using a Requests Session.\n* For `requests<2.32.0`, call `close()` on `Session` objects to clear existing connections if `verify=False` is used.\n\n### Related Links\n* https://github.com/psf/requests/pull/6655",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-9wx4-h78v-vm56",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-35195",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56"
                },
                {
                    "url": "https://github.com/psf/requests/pull/6655"
                },
                {
                    "url": "https://github.com/psf/requests/commit/a58d7f2ffb4d00b46dca2d70a3932a0b37e22fac"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-35195"
                },
                {
                    "url": "https://github.com/advisories/GHSA-9wx4-h78v-vm56"
                }
            ],
            "published_at": "2024-05-20T20:15:00Z",
            "updated_at": "2024-05-20T22:07:29Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "requests"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 2.32.0",
                    "first_patched_version": {
                        "identifier": "2.32.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N",
                "score": 5.6
            },
            "cwes": [
                {
                    "cwe_id": "CWE-670",
                    "name": "Always-Incorrect Control Flow Implementation"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "requests"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 2.32.0",
            "first_patched_version": {
                "identifier": "2.32.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/evidently/dependabot/alerts/95",
        "html_url": "https://github.com/fcas/evidently/security/dependabot/95",
        "created_at": "2024-05-24T01:34:19Z",
        "updated_at": "2024-05-24T01:34:19Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 94,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "streamlit"
            },
            "manifest_path": "examples/integrations/streamlit_dashboard/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-8qw9-gf7w-42x5",
            "cve_id": null,
            "summary": "Minor fix to previous patch for CVE-2022-35918",
            "description": "### Impact\n\nThe initial vulnerability identified in Streamlit apps using custom components, allowing for directory traversal attacks, was addressed in version 1.11.1. However, a minor issue persisted, which could still potentially expose certain files on the server file-system under specific conditions.\n\n### Patches\n\nWe released an update in version 1.30.0 to further tighten security measures. Users are strongly advised to update to version 1.30.0 immediately for optimal security.\n\n### Workarounds\n\nNo additional workarounds are necessary once the update to version 1.30.0 is applied.\n\n### For more information\n\nIf you have any questions or comments about this advisory:\n* Email us at [security@streamlit.io](mailto:security@streamlit.io)",
            "severity": "low",
            "identifiers": [
                {
                    "value": "GHSA-8qw9-gf7w-42x5",
                    "type": "GHSA"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/streamlit/streamlit/security/advisories/GHSA-8qw9-gf7w-42x5"
                },
                {
                    "url": "https://github.com/streamlit/streamlit/commit/bd0a8996c4c7ec55b9c6557e7b168b0c13a25b90"
                },
                {
                    "url": "https://github.com/advisories/GHSA-8qw9-gf7w-42x5"
                }
            ],
            "published_at": "2024-01-12T17:35:21Z",
            "updated_at": "2024-01-12T17:35:23Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "streamlit"
                    },
                    "severity": "low",
                    "vulnerable_version_range": ">= 0.63.0, < 1.30.0",
                    "first_patched_version": {
                        "identifier": "1.30.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": null,
                "score": 0.0
            },
            "cwes": []
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "streamlit"
            },
            "severity": "low",
            "vulnerable_version_range": ">= 0.63.0, < 1.30.0",
            "first_patched_version": {
                "identifier": "1.30.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/evidently/dependabot/alerts/94",
        "html_url": "https://github.com/fcas/evidently/security/dependabot/94",
        "created_at": "2024-05-24T01:34:19Z",
        "updated_at": "2024-05-24T01:34:19Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 93,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "pyarrow"
            },
            "manifest_path": "examples/integrations/streamlit_dashboard/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-5wvp-7f3h-6wmm",
            "cve_id": "CVE-2023-47248",
            "summary": "PyArrow: Arbitrary code execution when loading a malicious data file",
            "description": "Deserialization of untrusted data in IPC and Parquet readers in PyArrow versions 0.14.0 to 14.0.0 allows arbitrary code execution. An application is vulnerable if it reads Arrow IPC, Feather or Parquet data from untrusted sources (for example user-supplied input files).\n\nThis vulnerability only affects PyArrow, not other Apache Arrow implementations or bindings.\n\nIt is recommended that users of PyArrow upgrade to 14.0.1. Similarly, it is recommended that downstream libraries upgrade their dependency requirements to PyArrow 14.0.1 or later. PyPI packages are already available, and we hope that conda-forge packages will be available soon.\n\nIf it is not possible to upgrade, maintainers provide a separate package `pyarrow-hotfix` that disables the vulnerability on older PyArrow versions. See https://pypi.org/project/pyarrow-hotfix/  for instructions.",
            "severity": "critical",
            "identifiers": [
                {
                    "value": "GHSA-5wvp-7f3h-6wmm",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-47248",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-47248"
                },
                {
                    "url": "https://lists.apache.org/thread/yhy7tdfjf9hrl9vfrtzo8p2cyjq87v7n"
                },
                {
                    "url": "https://pypi.org/project/pyarrow-hotfix/"
                },
                {
                    "url": "https://github.com/apache/arrow/commit/f14170976372436ec1d03a724d8d3f3925484ecf"
                },
                {
                    "url": "https://github.com/advisories/GHSA-5wvp-7f3h-6wmm"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/pyarrow/PYSEC-2023-238.yaml"
                },
                {
                    "url": "https://www.cve.org/CVERecord?id=CVE-2023-47248"
                },
                {
                    "url": "https://www.openwall.com/lists/oss-security/2023/11/08/7"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FR34AIPXVTMB3XPRU5ULV5HHWPMRE33X/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MAGWEAJDWO2ACYATUQCPXLSYY5C3L3XU/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MWFYXLVBTBHNKYRXI572RFX7IJDDQGBL/"
                }
            ],
            "published_at": "2023-11-09T09:30:26Z",
            "updated_at": "2023-11-29T03:30:23Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "pyarrow"
                    },
                    "severity": "critical",
                    "vulnerable_version_range": ">= 0.14.0, < 14.0.1",
                    "first_patched_version": {
                        "identifier": "14.0.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                "score": 9.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-502",
                    "name": "Deserialization of Untrusted Data"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "pyarrow"
            },
            "severity": "critical",
            "vulnerable_version_range": ">= 0.14.0, < 14.0.1",
            "first_patched_version": {
                "identifier": "14.0.1"
            }
        },
        "url": "https://api.github.com/repos/fcas/evidently/dependabot/alerts/93",
        "html_url": "https://github.com/fcas/evidently/security/dependabot/93",
        "created_at": "2024-05-24T01:34:19Z",
        "updated_at": "2024-05-24T01:34:19Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 92,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "requests"
            },
            "manifest_path": "examples/integrations/streamlit_dashboard/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-j8r2-6x86-q33q",
            "cve_id": "CVE-2023-32681",
            "summary": "Unintended leak of Proxy-Authorization header in requests",
            "description": "### Impact\n\nSince Requests v2.3.0, Requests has been vulnerable to potentially leaking `Proxy-Authorization` headers to destination servers, specifically during redirects to an HTTPS origin. This is a product of how `rebuild_proxies` is used to recompute and [reattach the `Proxy-Authorization` header](https://github.com/psf/requests/blob/f2629e9e3c7ce3c3c8c025bcd8db551101cbc773/requests/sessions.py#L319-L328) to requests when redirected. Note this behavior has _only_ been observed to affect proxied requests when credentials are supplied in the URL user information component (e.g. `https://username:password@proxy:8080`).\n\n**Current vulnerable behavior(s):**\n\n1. HTTP → HTTPS: **leak**\n2. HTTPS → HTTP: **no leak**\n3. HTTPS → HTTPS: **leak**\n4. HTTP → HTTP: **no leak**\n\nFor HTTP connections sent through the proxy, the proxy will identify the header in the request itself and remove it prior to forwarding to the destination server. However when sent over HTTPS, the `Proxy-Authorization` header must be sent in the CONNECT request as the proxy has no visibility into further tunneled requests. This results in Requests forwarding the header to the destination server unintentionally, allowing a malicious actor to potentially exfiltrate those credentials.\n\nThe reason this currently works for HTTPS connections in Requests is the `Proxy-Authorization` header is also handled by urllib3 with our usage of the ProxyManager in adapters.py with [`proxy_manager_for`](https://github.com/psf/requests/blob/f2629e9e3c7ce3c3c8c025bcd8db551101cbc773/requests/adapters.py#L199-L235). This will compute the required proxy headers in `proxy_headers` and pass them to the Proxy Manager, avoiding attaching them directly to the Request object. This will be our preferred option going forward for default usage.\n\n### Patches\nStarting in Requests v2.31.0, Requests will no longer attach this header to redirects with an HTTPS destination. This should have no negative impacts on the default behavior of the library as the proxy credentials are already properly being handled by urllib3's ProxyManager.\n\nFor users with custom adapters, this _may_ be potentially breaking if you were already working around this behavior. The previous functionality of `rebuild_proxies` doesn't make sense in any case, so we would encourage any users impacted to migrate any handling of Proxy-Authorization directly into their custom adapter.\n\n### Workarounds\nFor users who are not able to update Requests immediately, there is one potential workaround.\n\nYou may disable redirects by setting `allow_redirects` to `False` on all calls through Requests top-level APIs. Note that if you're currently relying on redirect behaviors, you will need to capture the 3xx response codes and ensure a new request is made to the redirect destination.\n```\nimport requests\nr = requests.get('http://github.com/', allow_redirects=False)\n```\n\n### Credits\n\nThis vulnerability was discovered and disclosed by the following individuals.\n\nDennis Brinkrolf, Haxolot (https://haxolot.com/)\nTobias Funke, (tobiasfunke93@gmail.com)",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-j8r2-6x86-q33q",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-32681",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/psf/requests/security/advisories/GHSA-j8r2-6x86-q33q"
                },
                {
                    "url": "https://github.com/psf/requests/commit/74ea7cf7a6a27a4eeb2ae24e162bcc942a6706d5"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-32681"
                },
                {
                    "url": "https://github.com/psf/requests/releases/tag/v2.31.0"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/requests/PYSEC-2023-74.yaml"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2023/06/msg00018.html"
                },
                {
                    "url": "https://security.gentoo.org/glsa/202309-08"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/AW7HNFGYP44RT3DUDQXG2QT3OEV2PJ7Y"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KOYASTZDGQG2BWLSNBPL3TQRL2G7QYNZ"
                },
                {
                    "url": "https://github.com/advisories/GHSA-j8r2-6x86-q33q"
                }
            ],
            "published_at": "2023-05-22T20:36:32Z",
            "updated_at": "2024-03-27T20:09:55Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "requests"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": ">= 2.3.0, < 2.31.0",
                    "first_patched_version": {
                        "identifier": "2.31.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:H/I:N/A:N",
                "score": 6.1
            },
            "cwes": [
                {
                    "cwe_id": "CWE-200",
                    "name": "Exposure of Sensitive Information to an Unauthorized Actor"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "requests"
            },
            "severity": "medium",
            "vulnerable_version_range": ">= 2.3.0, < 2.31.0",
            "first_patched_version": {
                "identifier": "2.31.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/evidently/dependabot/alerts/92",
        "html_url": "https://github.com/fcas/evidently/security/dependabot/92",
        "created_at": "2024-05-24T01:34:18Z",
        "updated_at": "2024-05-24T01:34:18Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 91,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "pyyaml"
            },
            "manifest_path": "examples/integrations/streamlit_dashboard/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-3pqx-4fqf-j49f",
            "cve_id": "CVE-2019-20477",
            "summary": "Deserialization of Untrusted Data in PyYAML",
            "description": "PyYAML 5.1 through 5.1.2 has insufficient restrictions on the load and load_all functions because of a class deserialization issue, e.g., Popen is a class in the subprocess module. NOTE: this issue exists because of an incomplete fix for CVE-2017-18342.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-3pqx-4fqf-j49f",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2019-20477",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-20477"
                },
                {
                    "url": "https://github.com/yaml/pyyaml/blob/master/CHANGES"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/33VBUY73AA6CTTYL3LRWHNFDULV7PFPN/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/52N5XS73Z5S4ZN7I7R56ICCPCTKCUV4H/"
                },
                {
                    "url": "https://www.exploit-db.com/download/47655"
                },
                {
                    "url": "https://github.com/advisories/GHSA-3pqx-4fqf-j49f"
                }
            ],
            "published_at": "2021-04-20T16:40:42Z",
            "updated_at": "2023-02-01T05:05:14Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "pyyaml"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 5.1, < 5.2",
                    "first_patched_version": {
                        "identifier": "5.2"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                "score": 9.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-502",
                    "name": "Deserialization of Untrusted Data"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "pyyaml"
            },
            "severity": "high",
            "vulnerable_version_range": ">= 5.1, < 5.2",
            "first_patched_version": {
                "identifier": "5.2"
            }
        },
        "url": "https://api.github.com/repos/fcas/evidently/dependabot/alerts/91",
        "html_url": "https://github.com/fcas/evidently/security/dependabot/91",
        "created_at": "2024-05-24T01:34:18Z",
        "updated_at": "2024-05-24T01:34:18Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 90,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "pyyaml"
            },
            "manifest_path": "examples/integrations/streamlit_dashboard/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-6757-jp84-gxfx",
            "cve_id": "CVE-2020-1747",
            "summary": "Improper Input Validation in PyYAML",
            "description": "A vulnerability was discovered in the PyYAML library in versions before 5.3.1, where it is susceptible to arbitrary code execution when it processes untrusted YAML files through the full_load method or with the FullLoader loader. Applications that use the library to process untrusted input may be vulnerable to this flaw. An attacker could use this flaw to execute arbitrary code on the system by abusing the python/object/new constructor.",
            "severity": "critical",
            "identifiers": [
                {
                    "value": "GHSA-6757-jp84-gxfx",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2020-1747",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2020-1747"
                },
                {
                    "url": "https://github.com/yaml/pyyaml/pull/386"
                },
                {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-1747"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/7PPAS6C4SZRDQLR7C22A5U3QOLXY33JX/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/K5HEPD7LEVDPCITY5IMDYWXUMX37VFMY/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MMQXSZXNJT6ERABJZAAICI3DQSQLCP3D/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WORRFHPQVAFKKXXWLSSW6XKUYLWM6CSH/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZBJA3SGNJKCAYPSHOHWY3KBCWNM5NYK2/"
                },
                {
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00017.html"
                },
                {
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2020-05/msg00017.html"
                },
                {
                    "url": "https://www.oracle.com/security-alerts/cpujul2022.html"
                },
                {
                    "url": "https://github.com/yaml/pyyaml/commit/5080ba513377b6355a0502104846ee804656f1e0"
                },
                {
                    "url": "https://github.com/advisories/GHSA-6757-jp84-gxfx"
                }
            ],
            "published_at": "2021-04-20T16:14:24Z",
            "updated_at": "2023-08-25T00:08:24Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "pyyaml"
                    },
                    "severity": "critical",
                    "vulnerable_version_range": "< 5.3.1",
                    "first_patched_version": {
                        "identifier": "5.3.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                "score": 9.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-20",
                    "name": "Improper Input Validation"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "pyyaml"
            },
            "severity": "critical",
            "vulnerable_version_range": "< 5.3.1",
            "first_patched_version": {
                "identifier": "5.3.1"
            }
        },
        "url": "https://api.github.com/repos/fcas/evidently/dependabot/alerts/90",
        "html_url": "https://github.com/fcas/evidently/security/dependabot/90",
        "created_at": "2024-05-24T01:34:18Z",
        "updated_at": "2024-05-24T01:34:18Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 89,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "PyYAML"
            },
            "manifest_path": "examples/integrations/streamlit_dashboard/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-8q59-q68h-6hv4",
            "cve_id": "CVE-2020-14343",
            "summary": "Improper Input Validation in PyYAML",
            "description": "A vulnerability was discovered in the PyYAML library in versions before 5.4, where it is susceptible to arbitrary code execution when it processes untrusted YAML files through the full_load method or with the FullLoader loader. Applications that use the library to process untrusted input may be vulnerable to this flaw. This flaw allows an attacker to execute arbitrary code on the system by abusing the python/object/new constructor. This flaw is due to an incomplete fix for CVE-2020-1747.",
            "severity": "critical",
            "identifiers": [
                {
                    "value": "GHSA-8q59-q68h-6hv4",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2020-14343",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2020-14343"
                },
                {
                    "url": "https://github.com/yaml/pyyaml/commit/a001f2782501ad2d24986959f0239a354675f9dc"
                },
                {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1860466"
                },
                {
                    "url": "https://pypi.org/project/PyYAML/"
                },
                {
                    "url": "https://github.com/yaml/pyyaml/issues/420#issuecomment-663673966"
                },
                {
                    "url": "https://www.oracle.com/security-alerts/cpuapr2022.html"
                },
                {
                    "url": "https://www.oracle.com/security-alerts/cpujul2022.html"
                },
                {
                    "url": "https://github.com/SeldonIO/seldon-core/issues/2252"
                },
                {
                    "url": "https://github.com/yaml/pyyaml/issues/420"
                },
                {
                    "url": "https://github.com/advisories/GHSA-8q59-q68h-6hv4"
                }
            ],
            "published_at": "2021-03-25T21:26:26Z",
            "updated_at": "2023-08-23T23:02:02Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "PyYAML"
                    },
                    "severity": "critical",
                    "vulnerable_version_range": "< 5.4",
                    "first_patched_version": {
                        "identifier": "5.4"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                "score": 9.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-20",
                    "name": "Improper Input Validation"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "PyYAML"
            },
            "severity": "critical",
            "vulnerable_version_range": "< 5.4",
            "first_patched_version": {
                "identifier": "5.4"
            }
        },
        "url": "https://api.github.com/repos/fcas/evidently/dependabot/alerts/89",
        "html_url": "https://github.com/fcas/evidently/security/dependabot/89",
        "created_at": "2024-05-24T01:34:18Z",
        "updated_at": "2024-05-24T01:34:18Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 88,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "prefect"
            },
            "manifest_path": "examples/integrations/prefect_evidently_ui/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-4hh5-2678-83fx",
            "cve_id": "CVE-2023-6022",
            "summary": "Cross-Site Request Forgery vulnerability in Prefect",
            "description": "An attacker is able to steal secrets and potentially gain remote code execution via CSRF using a self-hosted, open source Prefect API.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-4hh5-2678-83fx",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-6022",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-6022"
                },
                {
                    "url": "https://huntr.com/bounties/dab47d99-551c-4355-9ab1-c99cb90235af"
                },
                {
                    "url": "https://github.com/PrefectHQ/prefect/blob/main/RELEASE-NOTES.md#release-2165"
                },
                {
                    "url": "https://github.com/prefecthq/prefect/commit/227dfcc7e3374c212a4bcd68b14e090b1c02d9d3"
                },
                {
                    "url": "https://github.com/advisories/GHSA-4hh5-2678-83fx"
                }
            ],
            "published_at": "2023-11-16T18:30:31Z",
            "updated_at": "2024-05-15T14:24:51Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "prefect"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 2.0.0, < 2.16.5",
                    "first_patched_version": {
                        "identifier": "2.16.5"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
                "score": 8.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-352",
                    "name": "Cross-Site Request Forgery (CSRF)"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "prefect"
            },
            "severity": "high",
            "vulnerable_version_range": ">= 2.0.0, < 2.16.5",
            "first_patched_version": {
                "identifier": "2.16.5"
            }
        },
        "url": "https://api.github.com/repos/fcas/evidently/dependabot/alerts/88",
        "html_url": "https://github.com/fcas/evidently/security/dependabot/88",
        "created_at": "2024-05-24T01:34:18Z",
        "updated_at": "2024-05-24T01:34:18Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 87,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "pyarrow"
            },
            "manifest_path": "examples/integrations/prefect_evidently_ui/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-5wvp-7f3h-6wmm",
            "cve_id": "CVE-2023-47248",
            "summary": "PyArrow: Arbitrary code execution when loading a malicious data file",
            "description": "Deserialization of untrusted data in IPC and Parquet readers in PyArrow versions 0.14.0 to 14.0.0 allows arbitrary code execution. An application is vulnerable if it reads Arrow IPC, Feather or Parquet data from untrusted sources (for example user-supplied input files).\n\nThis vulnerability only affects PyArrow, not other Apache Arrow implementations or bindings.\n\nIt is recommended that users of PyArrow upgrade to 14.0.1. Similarly, it is recommended that downstream libraries upgrade their dependency requirements to PyArrow 14.0.1 or later. PyPI packages are already available, and we hope that conda-forge packages will be available soon.\n\nIf it is not possible to upgrade, maintainers provide a separate package `pyarrow-hotfix` that disables the vulnerability on older PyArrow versions. See https://pypi.org/project/pyarrow-hotfix/  for instructions.",
            "severity": "critical",
            "identifiers": [
                {
                    "value": "GHSA-5wvp-7f3h-6wmm",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-47248",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-47248"
                },
                {
                    "url": "https://lists.apache.org/thread/yhy7tdfjf9hrl9vfrtzo8p2cyjq87v7n"
                },
                {
                    "url": "https://pypi.org/project/pyarrow-hotfix/"
                },
                {
                    "url": "https://github.com/apache/arrow/commit/f14170976372436ec1d03a724d8d3f3925484ecf"
                },
                {
                    "url": "https://github.com/advisories/GHSA-5wvp-7f3h-6wmm"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/pyarrow/PYSEC-2023-238.yaml"
                },
                {
                    "url": "https://www.cve.org/CVERecord?id=CVE-2023-47248"
                },
                {
                    "url": "https://www.openwall.com/lists/oss-security/2023/11/08/7"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FR34AIPXVTMB3XPRU5ULV5HHWPMRE33X/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MAGWEAJDWO2ACYATUQCPXLSYY5C3L3XU/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MWFYXLVBTBHNKYRXI572RFX7IJDDQGBL/"
                }
            ],
            "published_at": "2023-11-09T09:30:26Z",
            "updated_at": "2023-11-29T03:30:23Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "pyarrow"
                    },
                    "severity": "critical",
                    "vulnerable_version_range": ">= 0.14.0, < 14.0.1",
                    "first_patched_version": {
                        "identifier": "14.0.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                "score": 9.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-502",
                    "name": "Deserialization of Untrusted Data"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "pyarrow"
            },
            "severity": "critical",
            "vulnerable_version_range": ">= 0.14.0, < 14.0.1",
            "first_patched_version": {
                "identifier": "14.0.1"
            }
        },
        "url": "https://api.github.com/repos/fcas/evidently/dependabot/alerts/87",
        "html_url": "https://github.com/fcas/evidently/security/dependabot/87",
        "created_at": "2024-05-24T01:34:18Z",
        "updated_at": "2024-05-24T01:34:18Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 86,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "prefect"
            },
            "manifest_path": "examples/integrations/postgres_grafana_batch_monitoring/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-4hh5-2678-83fx",
            "cve_id": "CVE-2023-6022",
            "summary": "Cross-Site Request Forgery vulnerability in Prefect",
            "description": "An attacker is able to steal secrets and potentially gain remote code execution via CSRF using a self-hosted, open source Prefect API.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-4hh5-2678-83fx",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-6022",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-6022"
                },
                {
                    "url": "https://huntr.com/bounties/dab47d99-551c-4355-9ab1-c99cb90235af"
                },
                {
                    "url": "https://github.com/PrefectHQ/prefect/blob/main/RELEASE-NOTES.md#release-2165"
                },
                {
                    "url": "https://github.com/prefecthq/prefect/commit/227dfcc7e3374c212a4bcd68b14e090b1c02d9d3"
                },
                {
                    "url": "https://github.com/advisories/GHSA-4hh5-2678-83fx"
                }
            ],
            "published_at": "2023-11-16T18:30:31Z",
            "updated_at": "2024-05-15T14:24:51Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "prefect"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 2.0.0, < 2.16.5",
                    "first_patched_version": {
                        "identifier": "2.16.5"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
                "score": 8.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-352",
                    "name": "Cross-Site Request Forgery (CSRF)"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "prefect"
            },
            "severity": "high",
            "vulnerable_version_range": ">= 2.0.0, < 2.16.5",
            "first_patched_version": {
                "identifier": "2.16.5"
            }
        },
        "url": "https://api.github.com/repos/fcas/evidently/dependabot/alerts/86",
        "html_url": "https://github.com/fcas/evidently/security/dependabot/86",
        "created_at": "2024-05-24T01:34:18Z",
        "updated_at": "2024-05-24T01:34:18Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 85,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "pyarrow"
            },
            "manifest_path": "examples/integrations/postgres_grafana_batch_monitoring/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-5wvp-7f3h-6wmm",
            "cve_id": "CVE-2023-47248",
            "summary": "PyArrow: Arbitrary code execution when loading a malicious data file",
            "description": "Deserialization of untrusted data in IPC and Parquet readers in PyArrow versions 0.14.0 to 14.0.0 allows arbitrary code execution. An application is vulnerable if it reads Arrow IPC, Feather or Parquet data from untrusted sources (for example user-supplied input files).\n\nThis vulnerability only affects PyArrow, not other Apache Arrow implementations or bindings.\n\nIt is recommended that users of PyArrow upgrade to 14.0.1. Similarly, it is recommended that downstream libraries upgrade their dependency requirements to PyArrow 14.0.1 or later. PyPI packages are already available, and we hope that conda-forge packages will be available soon.\n\nIf it is not possible to upgrade, maintainers provide a separate package `pyarrow-hotfix` that disables the vulnerability on older PyArrow versions. See https://pypi.org/project/pyarrow-hotfix/  for instructions.",
            "severity": "critical",
            "identifiers": [
                {
                    "value": "GHSA-5wvp-7f3h-6wmm",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-47248",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-47248"
                },
                {
                    "url": "https://lists.apache.org/thread/yhy7tdfjf9hrl9vfrtzo8p2cyjq87v7n"
                },
                {
                    "url": "https://pypi.org/project/pyarrow-hotfix/"
                },
                {
                    "url": "https://github.com/apache/arrow/commit/f14170976372436ec1d03a724d8d3f3925484ecf"
                },
                {
                    "url": "https://github.com/advisories/GHSA-5wvp-7f3h-6wmm"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/pyarrow/PYSEC-2023-238.yaml"
                },
                {
                    "url": "https://www.cve.org/CVERecord?id=CVE-2023-47248"
                },
                {
                    "url": "https://www.openwall.com/lists/oss-security/2023/11/08/7"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FR34AIPXVTMB3XPRU5ULV5HHWPMRE33X/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MAGWEAJDWO2ACYATUQCPXLSYY5C3L3XU/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MWFYXLVBTBHNKYRXI572RFX7IJDDQGBL/"
                }
            ],
            "published_at": "2023-11-09T09:30:26Z",
            "updated_at": "2023-11-29T03:30:23Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "pyarrow"
                    },
                    "severity": "critical",
                    "vulnerable_version_range": ">= 0.14.0, < 14.0.1",
                    "first_patched_version": {
                        "identifier": "14.0.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                "score": 9.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-502",
                    "name": "Deserialization of Untrusted Data"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "pyarrow"
            },
            "severity": "critical",
            "vulnerable_version_range": ">= 0.14.0, < 14.0.1",
            "first_patched_version": {
                "identifier": "14.0.1"
            }
        },
        "url": "https://api.github.com/repos/fcas/evidently/dependabot/alerts/85",
        "html_url": "https://github.com/fcas/evidently/security/dependabot/85",
        "created_at": "2024-05-24T01:34:18Z",
        "updated_at": "2024-05-24T01:34:18Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 84,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "mlflow"
            },
            "manifest_path": "examples/integrations/mlflow_monitoring/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-p4jx-q62p-x5jr",
            "cve_id": "CVE-2024-4263",
            "summary": "MLflow allows low privilege users to delete any artifact",
            "description": "A broken access control vulnerability exists in mlflow/mlflow versions before 2.10.1, where low privilege users with only EDIT permissions on an experiment can delete any artifacts. This issue arises due to the lack of proper validation for DELETE requests by users with EDIT permissions, allowing them to perform unauthorized deletions of artifacts. The vulnerability specifically affects the handling of artifact deletions within the application, as demonstrated by the ability of a low privilege user to delete a directory inside an artifact using a DELETE request, despite the official documentation stating that users with EDIT permission can only read and update artifacts, not delete them.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-p4jx-q62p-x5jr",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-4263",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-4263"
                },
                {
                    "url": "https://github.com/mlflow/mlflow/commit/b43e0e3de5b500554e13dc032ba2083b2d6c94b8"
                },
                {
                    "url": "https://huntr.com/bounties/bfa116d3-2af8-4c4a-ac34-ccde7491ae11"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/mlflow/PYSEC-2024-51.yaml"
                },
                {
                    "url": "https://github.com/advisories/GHSA-p4jx-q62p-x5jr"
                }
            ],
            "published_at": "2024-05-16T09:33:08Z",
            "updated_at": "2024-05-16T17:46:39Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "mlflow"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 2.10.1",
                    "first_patched_version": {
                        "identifier": "2.10.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:L/A:L",
                "score": 5.4
            },
            "cwes": [
                {
                    "cwe_id": "CWE-284",
                    "name": "Improper Access Control"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "mlflow"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 2.10.1",
            "first_patched_version": {
                "identifier": "2.10.1"
            }
        },
        "url": "https://api.github.com/repos/fcas/evidently/dependabot/alerts/84",
        "html_url": "https://github.com/fcas/evidently/security/dependabot/84",
        "created_at": "2024-05-24T01:34:18Z",
        "updated_at": "2024-05-24T01:34:18Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 83,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "tqdm"
            },
            "manifest_path": "examples/integrations/mlflow_monitoring/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-g7vv-2v7x-gj9p",
            "cve_id": "CVE-2024-34062",
            "summary": "tqdm CLI arguments injection attack",
            "description": "### Impact\nAny optional non-boolean CLI arguments (e.g. `--delim`, `--buf-size`, `--manpath`) are passed through python's `eval`, allowing arbitrary code execution. Example:\n\n```sh\npython -m tqdm --manpath=\"\\\" + str(exec(\\\"import os\\nos.system('echo hi && killall python3')\\\")) + \\\"\"\n```\n\n### Patches\nhttps://github.com/tqdm/tqdm/commit/4e613f84ed2ae029559f539464df83fa91feb316 released in `tqdm>=4.66.3`\n\n### Workarounds\nNone\n\n### References\n- https://github.com/tqdm/tqdm/releases/tag/v4.66.3",
            "severity": "low",
            "identifiers": [
                {
                    "value": "GHSA-g7vv-2v7x-gj9p",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-34062",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/tqdm/tqdm/security/advisories/GHSA-g7vv-2v7x-gj9p"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-34062"
                },
                {
                    "url": "https://github.com/tqdm/tqdm/commit/4e613f84ed2ae029559f539464df83fa91feb316"
                },
                {
                    "url": "https://github.com/advisories/GHSA-g7vv-2v7x-gj9p"
                }
            ],
            "published_at": "2024-05-03T19:33:28Z",
            "updated_at": "2024-05-03T19:33:29Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tqdm"
                    },
                    "severity": "low",
                    "vulnerable_version_range": ">= 4.4.0, < 4.66.3",
                    "first_patched_version": {
                        "identifier": "4.66.3"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:L/PR:L/UI:R/S:U/C:L/I:L/A:N",
                "score": 3.9
            },
            "cwes": [
                {
                    "cwe_id": "CWE-74",
                    "name": "Improper Neutralization of Special Elements in Output Used by a Downstream Component ('Injection')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "tqdm"
            },
            "severity": "low",
            "vulnerable_version_range": ">= 4.4.0, < 4.66.3",
            "first_patched_version": {
                "identifier": "4.66.3"
            }
        },
        "url": "https://api.github.com/repos/fcas/evidently/dependabot/alerts/83",
        "html_url": "https://github.com/fcas/evidently/security/dependabot/83",
        "created_at": "2024-05-24T01:34:17Z",
        "updated_at": "2024-05-24T01:34:17Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 82,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "mlflow"
            },
            "manifest_path": "examples/integrations/mlflow_monitoring/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-j62r-wxqq-f3gf",
            "cve_id": "CVE-2024-1558",
            "summary": "mlflow vulnerable to Path Traversal",
            "description": "A path traversal vulnerability exists in the `_create_model_version()` function within `server/handlers.py` of the mlflow/mlflow repository, due to improper validation of the `source` parameter. Attackers can exploit this vulnerability by crafting a `source` parameter that bypasses the `_validate_non_local_source_contains_relative_paths(source)` function's checks, allowing for arbitrary file read access on the server. The issue arises from the handling of unquoted URL characters and the subsequent misuse of the original `source` value for model version creation, leading to the exposure of sensitive files when interacting with the `/model-versions/get-artifact` handler.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-j62r-wxqq-f3gf",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-1558",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-1558"
                },
                {
                    "url": "https://huntr.com/bounties/7f4dbcc5-b6b3-43dd-b310-e2d0556a8081"
                },
                {
                    "url": "https://github.com/advisories/GHSA-j62r-wxqq-f3gf"
                }
            ],
            "published_at": "2024-04-16T00:30:33Z",
            "updated_at": "2024-04-26T05:02:10Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "mlflow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "<= 2.9.2",
                    "first_patched_version": null
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-22",
                    "name": "Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "mlflow"
            },
            "severity": "high",
            "vulnerable_version_range": "<= 2.9.2",
            "first_patched_version": null
        },
        "url": "https://api.github.com/repos/fcas/evidently/dependabot/alerts/82",
        "html_url": "https://github.com/fcas/evidently/security/dependabot/82",
        "created_at": "2024-05-24T01:34:17Z",
        "updated_at": "2024-05-24T01:34:17Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 81,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "mlflow"
            },
            "manifest_path": "examples/integrations/mlflow_monitoring/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-hq88-wg7q-gp4g",
            "cve_id": "CVE-2024-3573",
            "summary": "mlflow vulnerable to Path Traversal",
            "description": "mlflow/mlflow is vulnerable to Local File Inclusion (LFI) due to improper parsing of URIs, allowing attackers to bypass checks and read arbitrary files on the system. The issue arises from the 'is_local_uri' function's failure to properly handle URIs with empty or 'file' schemes, leading to the misclassification of URIs as non-local. Attackers can exploit this by crafting malicious model versions with specially crafted 'source' parameters, enabling the reading of sensitive files within at least two directory levels from the server's root.",
            "severity": "critical",
            "identifiers": [
                {
                    "value": "GHSA-hq88-wg7q-gp4g",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-3573",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-3573"
                },
                {
                    "url": "https://github.com/mlflow/mlflow/commit/438a450714a3ca06285eeea34bdc6cf79d7f6cbc"
                },
                {
                    "url": "https://huntr.com/bounties/8ea058a7-4ef8-4baf-9198-bc0147fc543c"
                },
                {
                    "url": "https://github.com/advisories/GHSA-hq88-wg7q-gp4g"
                }
            ],
            "published_at": "2024-04-16T00:30:34Z",
            "updated_at": "2024-04-16T18:20:37Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "mlflow"
                    },
                    "severity": "critical",
                    "vulnerable_version_range": "< 2.10.0",
                    "first_patched_version": {
                        "identifier": "2.10.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:L/A:N",
                "score": 9.3
            },
            "cwes": [
                {
                    "cwe_id": "CWE-29",
                    "name": "Path Traversal: '..filename'"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "mlflow"
            },
            "severity": "critical",
            "vulnerable_version_range": "< 2.10.0",
            "first_patched_version": {
                "identifier": "2.10.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/evidently/dependabot/alerts/81",
        "html_url": "https://github.com/fcas/evidently/security/dependabot/81",
        "created_at": "2024-05-24T01:34:17Z",
        "updated_at": "2024-05-24T01:34:17Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 80,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "mlflow"
            },
            "manifest_path": "examples/integrations/mlflow_monitoring/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-m49c-5c52-6696",
            "cve_id": "CVE-2024-1594",
            "summary": "mlflow vulnerable to Path Traversal",
            "description": "A path traversal vulnerability exists in the mlflow/mlflow repository, specifically within the handling of the `artifact_location` parameter when creating an experiment. Attackers can exploit this vulnerability by using a fragment component `#` in the artifact location URI to read arbitrary files on the server in the context of the server's process. This issue is similar to CVE-2023-6909 but utilizes a different component of the URI to achieve the same effect. ",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-m49c-5c52-6696",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-1594",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-1594"
                },
                {
                    "url": "https://huntr.com/bounties/424b6f6b-e778-4a2b-b860-39730d396f3e"
                },
                {
                    "url": "https://github.com/mlflow/mlflow/blob/b929a3e727dc48a1eb19b7e954b7897ac09ad3ec/mlflow/utils/uri.py#L246"
                },
                {
                    "url": "https://github.com/advisories/GHSA-m49c-5c52-6696"
                }
            ],
            "published_at": "2024-04-16T00:30:33Z",
            "updated_at": "2024-04-16T18:19:41Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "mlflow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "<= 2.9.2",
                    "first_patched_version": null
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-22",
                    "name": "Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "mlflow"
            },
            "severity": "high",
            "vulnerable_version_range": "<= 2.9.2",
            "first_patched_version": null
        },
        "url": "https://api.github.com/repos/fcas/evidently/dependabot/alerts/80",
        "html_url": "https://github.com/fcas/evidently/security/dependabot/80",
        "created_at": "2024-05-24T01:34:17Z",
        "updated_at": "2024-05-24T01:34:17Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 79,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "mlflow"
            },
            "manifest_path": "examples/integrations/mlflow_monitoring/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-f42m-mvfv-cgw5",
            "cve_id": "CVE-2024-1593",
            "summary": "mlflow vulnerable to Path Traversal",
            "description": "A path traversal vulnerability exists in the mlflow/mlflow repository due to improper handling of URL parameters. By smuggling path traversal sequences using the ';' character in URLs, attackers can manipulate the 'params' portion of the URL to gain unauthorized access to files or directories. This vulnerability allows for arbitrary data smuggling into the 'params' part of the URL, enabling attacks similar to those described in previous reports but utilizing the ';' character for parameter smuggling. Successful exploitation could lead to unauthorized information disclosure or server compromise.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-f42m-mvfv-cgw5",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-1593",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-1593"
                },
                {
                    "url": "https://huntr.com/bounties/dbdc6bd6-d09a-46f2-9d9c-5138a14b6e31"
                },
                {
                    "url": "https://github.com/advisories/GHSA-f42m-mvfv-cgw5"
                }
            ],
            "published_at": "2024-04-16T00:30:33Z",
            "updated_at": "2024-04-16T18:18:31Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "mlflow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "<= 2.9.2",
                    "first_patched_version": null
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-22",
                    "name": "Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "mlflow"
            },
            "severity": "high",
            "vulnerable_version_range": "<= 2.9.2",
            "first_patched_version": null
        },
        "url": "https://api.github.com/repos/fcas/evidently/dependabot/alerts/79",
        "html_url": "https://github.com/fcas/evidently/security/dependabot/79",
        "created_at": "2024-05-24T01:34:17Z",
        "updated_at": "2024-05-24T01:34:17Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 78,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "mlflow"
            },
            "manifest_path": "examples/integrations/mlflow_monitoring/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-5mvj-wmgj-7q8c",
            "cve_id": "CVE-2024-1560",
            "summary": "mlflow vulnerable to Path Traversal",
            "description": "A path traversal vulnerability exists in the mlflow/mlflow repository, specifically within the artifact deletion functionality. Attackers can bypass path validation by exploiting the double decoding process in the `_delete_artifact_mlflow_artifacts` handler and `local_file_uri_to_path` function, allowing for the deletion of arbitrary directories on the server's filesystem. This vulnerability is due to an extra unquote operation in the `delete_artifacts` function of `local_artifact_repo.py`, which fails to properly sanitize user-supplied paths. The issue is present up to version 2.9.2, despite attempts to fix a similar issue in CVE-2023-6831.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-5mvj-wmgj-7q8c",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-1560",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-1560"
                },
                {
                    "url": "https://huntr.com/bounties/4a34259c-3c8f-4872-b178-f27fbc876b98"
                },
                {
                    "url": "https://github.com/advisories/GHSA-5mvj-wmgj-7q8c"
                }
            ],
            "published_at": "2024-04-16T00:30:33Z",
            "updated_at": "2024-04-16T18:18:03Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "mlflow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "<= 2.9.2",
                    "first_patched_version": null
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:H",
                "score": 8.1
            },
            "cwes": [
                {
                    "cwe_id": "CWE-22",
                    "name": "Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "mlflow"
            },
            "severity": "high",
            "vulnerable_version_range": "<= 2.9.2",
            "first_patched_version": null
        },
        "url": "https://api.github.com/repos/fcas/evidently/dependabot/alerts/78",
        "html_url": "https://github.com/fcas/evidently/security/dependabot/78",
        "created_at": "2024-05-24T01:34:17Z",
        "updated_at": "2024-05-24T01:34:17Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 77,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "mlflow"
            },
            "manifest_path": "examples/integrations/mlflow_monitoring/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-f82r-jj5r-6g97",
            "cve_id": "CVE-2024-1483",
            "summary": "mlflow Path Traversal vulnerability",
            "description": "A path traversal vulnerability exists in mlflow/mlflow version 2.9.2, allowing attackers to access arbitrary files on the server. By crafting a series of HTTP POST requests with specially crafted 'artifact_location' and 'source' parameters, using a local URI with '#' instead of '?', an attacker can traverse the server's directory structure. The issue occurs due to insufficient validation of user-supplied input in the server's handlers.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-f82r-jj5r-6g97",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-1483",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-1483"
                },
                {
                    "url": "https://huntr.com/bounties/52a3855d-93ff-4460-ac24-9c7e4334198d"
                },
                {
                    "url": "https://github.com/advisories/GHSA-f82r-jj5r-6g97"
                }
            ],
            "published_at": "2024-04-16T00:30:32Z",
            "updated_at": "2024-04-16T18:06:16Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "mlflow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "<= 2.9.2",
                    "first_patched_version": null
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-22",
                    "name": "Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "mlflow"
            },
            "severity": "high",
            "vulnerable_version_range": "<= 2.9.2",
            "first_patched_version": null
        },
        "url": "https://api.github.com/repos/fcas/evidently/dependabot/alerts/77",
        "html_url": "https://github.com/fcas/evidently/security/dependabot/77",
        "created_at": "2024-05-24T01:34:17Z",
        "updated_at": "2024-05-24T01:34:17Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 76,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "mlflow"
            },
            "manifest_path": "examples/integrations/mlflow_monitoring/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-4qq5-mxxx-m6gg",
            "cve_id": "CVE-2023-6014",
            "summary": "MLflow authentication requirement bypass can allow a user to arbitrarily create an account",
            "description": "An attacker is able to arbitrarily create an account in MLflow bypassing any authentication requirement.",
            "severity": "critical",
            "identifiers": [
                {
                    "value": "GHSA-4qq5-mxxx-m6gg",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-6014",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-6014"
                },
                {
                    "url": "https://huntr.com/bounties/3e64df69-ddc2-463e-9809-d07c24dc1de4"
                },
                {
                    "url": "https://github.com/mlflow/mlflow/issues/9669"
                },
                {
                    "url": "https://github.com/mlflow/mlflow/pull/9700"
                },
                {
                    "url": "https://github.com/mlflow/mlflow/commit/32de2154ef9f946160e5dc01a4d8a449dd0bd259"
                },
                {
                    "url": "https://github.com/mlflow/mlflow/releases/tag/v2.8.0"
                },
                {
                    "url": "https://github.com/advisories/GHSA-4qq5-mxxx-m6gg"
                }
            ],
            "published_at": "2023-11-16T21:30:46Z",
            "updated_at": "2024-03-11T05:00:46Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "mlflow"
                    },
                    "severity": "critical",
                    "vulnerable_version_range": "< 2.8.0",
                    "first_patched_version": {
                        "identifier": "2.8.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
                "score": 9.1
            },
            "cwes": [
                {
                    "cwe_id": "CWE-598",
                    "name": "Use of GET Request Method With Sensitive Query Strings"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "mlflow"
            },
            "severity": "critical",
            "vulnerable_version_range": "< 2.8.0",
            "first_patched_version": {
                "identifier": "2.8.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/evidently/dependabot/alerts/76",
        "html_url": "https://github.com/fcas/evidently/security/dependabot/76",
        "created_at": "2024-05-24T01:34:17Z",
        "updated_at": "2024-05-24T01:34:17Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 75,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "mlflow"
            },
            "manifest_path": "examples/integrations/mlflow_monitoring/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-3v79-q7ph-j75h",
            "cve_id": "CVE-2024-27133",
            "summary": "MLFlow Cross-site Scripting vulnerability leads to client-side Remote Code Execution",
            "description": "Insufficient sanitization in MLflow leads to XSS when running a recipe that uses an untrusted dataset. This issue leads to a client-side RCE when running the recipe in Jupyter Notebook. The vulnerability stems from lack of sanitization over dataset table fields.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-3v79-q7ph-j75h",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-27133",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-27133"
                },
                {
                    "url": "https://github.com/mlflow/mlflow/pull/10893"
                },
                {
                    "url": "https://research.jfrog.com/vulnerabilities/mlflow-untrusted-dataset-xss-jfsa-2024-000631932"
                },
                {
                    "url": "https://github.com/mlflow/mlflow/commit/c43823750bffa5b6abcc086683b15a068513b67b"
                },
                {
                    "url": "https://github.com/advisories/GHSA-3v79-q7ph-j75h"
                }
            ],
            "published_at": "2024-02-24T00:30:20Z",
            "updated_at": "2024-02-27T21:57:35Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "mlflow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.10.0",
                    "first_patched_version": {
                        "identifier": "2.10.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-79",
                    "name": "Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "mlflow"
            },
            "severity": "high",
            "vulnerable_version_range": "< 2.10.0",
            "first_patched_version": {
                "identifier": "2.10.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/evidently/dependabot/alerts/75",
        "html_url": "https://github.com/fcas/evidently/security/dependabot/75",
        "created_at": "2024-05-24T01:34:17Z",
        "updated_at": "2024-05-24T01:34:17Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 74,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "mlflow"
            },
            "manifest_path": "examples/integrations/mlflow_monitoring/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-6749-m5cp-6cg7",
            "cve_id": "CVE-2024-27132",
            "summary": "Cross-site Scripting in MLFlow",
            "description": "Insufficient sanitization in MLflow leads to XSS when running an untrusted recipe.\n\nThis issue leads to a client-side RCE when running an untrusted recipe in Jupyter Notebook.\n\nThe vulnerability stems from lack of sanitization over template variables.\n\n",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-6749-m5cp-6cg7",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-27132",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-27132"
                },
                {
                    "url": "https://github.com/mlflow/mlflow/pull/10873"
                },
                {
                    "url": "https://research.jfrog.com/vulnerabilities/mlflow-untrusted-recipe-xss-jfsa-2024-000631930"
                },
                {
                    "url": "https://github.com/advisories/GHSA-6749-m5cp-6cg7"
                }
            ],
            "published_at": "2024-02-24T00:30:20Z",
            "updated_at": "2024-02-26T20:07:33Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "mlflow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.10.0",
                    "first_patched_version": {
                        "identifier": "2.10.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-79",
                    "name": "Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "mlflow"
            },
            "severity": "high",
            "vulnerable_version_range": "< 2.10.0",
            "first_patched_version": {
                "identifier": "2.10.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/evidently/dependabot/alerts/74",
        "html_url": "https://github.com/fcas/evidently/security/dependabot/74",
        "created_at": "2024-05-24T01:34:16Z",
        "updated_at": "2024-05-24T01:34:16Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 73,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "mlflow"
            },
            "manifest_path": "examples/integrations/mlflow_monitoring/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-5r3q-93q3-f978",
            "cve_id": "CVE-2023-6909",
            "summary": "MLflow Path Traversal Vulnerability",
            "description": "Path Traversal: '\\..\\filename' in GitHub repository mlflow/mlflow prior to 2.9.2.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-5r3q-93q3-f978",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-6909",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-6909"
                },
                {
                    "url": "https://github.com/mlflow/mlflow/commit/1da75dfcecd4d169e34809ade55748384e8af6c1"
                },
                {
                    "url": "https://huntr.com/bounties/11209efb-0f84-482f-add0-587ea6b7e850"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/mlflow/PYSEC-2023-252.yaml"
                },
                {
                    "url": "https://github.com/advisories/GHSA-5r3q-93q3-f978"
                }
            ],
            "published_at": "2023-12-20T06:30:25Z",
            "updated_at": "2024-02-07T15:59:14Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "mlflow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.9.2",
                    "first_patched_version": {
                        "identifier": "2.9.2"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-29",
                    "name": "Path Traversal: '..filename'"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "mlflow"
            },
            "severity": "high",
            "vulnerable_version_range": "< 2.9.2",
            "first_patched_version": {
                "identifier": "2.9.2"
            }
        },
        "url": "https://api.github.com/repos/fcas/evidently/dependabot/alerts/73",
        "html_url": "https://github.com/fcas/evidently/security/dependabot/73",
        "created_at": "2024-05-24T01:34:16Z",
        "updated_at": "2024-05-24T01:34:16Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 72,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "mlflow"
            },
            "manifest_path": "examples/integrations/mlflow_monitoring/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-wv8q-4f85-2p8p",
            "cve_id": "CVE-2023-6976",
            "summary": "MLflow Path Traversal Vulnerability",
            "description": "This vulnerability is capable of writing arbitrary files into arbitrary locations on the remote filesystem in the context of the server process.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-wv8q-4f85-2p8p",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-6976",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-6976"
                },
                {
                    "url": "https://github.com/mlflow/mlflow/commit/5044878da0c1851ccfdd5c0a867157ed9a502fbc"
                },
                {
                    "url": "https://huntr.com/bounties/2408a52b-f05b-4cac-9765-4f74bac3f20f"
                },
                {
                    "url": "https://github.com/advisories/GHSA-wv8q-4f85-2p8p"
                }
            ],
            "published_at": "2023-12-20T06:30:25Z",
            "updated_at": "2023-12-20T20:36:28Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "mlflow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.9.2",
                    "first_patched_version": {
                        "identifier": "2.9.2"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
                "score": 8.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-434",
                    "name": "Unrestricted Upload of File with Dangerous Type"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "mlflow"
            },
            "severity": "high",
            "vulnerable_version_range": "< 2.9.2",
            "first_patched_version": {
                "identifier": "2.9.2"
            }
        },
        "url": "https://api.github.com/repos/fcas/evidently/dependabot/alerts/72",
        "html_url": "https://github.com/fcas/evidently/security/dependabot/72",
        "created_at": "2024-05-24T01:34:16Z",
        "updated_at": "2024-05-24T01:34:16Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 71,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "mlflow"
            },
            "manifest_path": "examples/integrations/mlflow_monitoring/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-59v3-898r-qwhj",
            "cve_id": "CVE-2023-6974",
            "summary": "MLflow Server-Side Request Forgery (SSRF)",
            "description": "A malicious user could use this issue to access internal HTTP(s) servers and in the worst case (ie: aws instance) it could be abused to get a remote code execution on the victim machine.",
            "severity": "critical",
            "identifiers": [
                {
                    "value": "GHSA-59v3-898r-qwhj",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-6974",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-6974"
                },
                {
                    "url": "https://github.com/mlflow/mlflow/commit/8174250f83352a04c2d42079f414759060458555"
                },
                {
                    "url": "https://huntr.com/bounties/438b0524-da0e-4d08-976a-6f270c688393"
                },
                {
                    "url": "https://github.com/advisories/GHSA-59v3-898r-qwhj"
                }
            ],
            "published_at": "2023-12-20T06:30:25Z",
            "updated_at": "2024-01-02T14:53:39Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "mlflow"
                    },
                    "severity": "critical",
                    "vulnerable_version_range": "< 2.9.2",
                    "first_patched_version": {
                        "identifier": "2.9.2"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                "score": 9.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-918",
                    "name": "Server-Side Request Forgery (SSRF)"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "mlflow"
            },
            "severity": "critical",
            "vulnerable_version_range": "< 2.9.2",
            "first_patched_version": {
                "identifier": "2.9.2"
            }
        },
        "url": "https://api.github.com/repos/fcas/evidently/dependabot/alerts/71",
        "html_url": "https://github.com/fcas/evidently/security/dependabot/71",
        "created_at": "2024-05-24T01:34:16Z",
        "updated_at": "2024-05-24T01:34:16Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 70,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "mlflow"
            },
            "manifest_path": "examples/integrations/mlflow_monitoring/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-qg8p-32gr-gh6x",
            "cve_id": "CVE-2023-6977",
            "summary": "MLflow Local File Disclosure Vulnerability",
            "description": "This vulnerability enables malicious users to read sensitive files on the server.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-qg8p-32gr-gh6x",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-6977",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-6977"
                },
                {
                    "url": "https://github.com/mlflow/mlflow/commit/4bd7f27c810ba7487d53ed5ef1038fca0f8dc28c"
                },
                {
                    "url": "https://huntr.com/bounties/fe53bf71-3687-4711-90df-c26172880aaf"
                },
                {
                    "url": "https://github.com/advisories/GHSA-qg8p-32gr-gh6x"
                }
            ],
            "published_at": "2023-12-20T06:30:25Z",
            "updated_at": "2024-01-02T15:14:14Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "mlflow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.9.2",
                    "first_patched_version": {
                        "identifier": "2.9.2"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-29",
                    "name": "Path Traversal: '..filename'"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "mlflow"
            },
            "severity": "high",
            "vulnerable_version_range": "< 2.9.2",
            "first_patched_version": {
                "identifier": "2.9.2"
            }
        },
        "url": "https://api.github.com/repos/fcas/evidently/dependabot/alerts/70",
        "html_url": "https://github.com/fcas/evidently/security/dependabot/70",
        "created_at": "2024-05-24T01:34:16Z",
        "updated_at": "2024-05-24T01:34:16Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 69,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "mlflow"
            },
            "manifest_path": "examples/integrations/mlflow_monitoring/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-hh8p-p8mp-gqhm",
            "cve_id": "CVE-2023-6975",
            "summary": "MLFlow Path Traversal Vulnerability",
            "description": "A malicious user could use this issue to get command execution on the vulnerable machine and get access to data & models information.",
            "severity": "critical",
            "identifiers": [
                {
                    "value": "GHSA-hh8p-p8mp-gqhm",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-6975",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-6975"
                },
                {
                    "url": "https://github.com/mlflow/mlflow/commit/b9ab9ed77e1deda9697fe472fb1079fd428149ee"
                },
                {
                    "url": "https://huntr.com/bounties/029a3824-cee3-4cf1-b260-7138aa539b85"
                },
                {
                    "url": "https://github.com/advisories/GHSA-hh8p-p8mp-gqhm"
                }
            ],
            "published_at": "2023-12-20T06:30:25Z",
            "updated_at": "2024-01-02T15:14:39Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "mlflow"
                    },
                    "severity": "critical",
                    "vulnerable_version_range": "< 2.9.2",
                    "first_patched_version": {
                        "identifier": "2.9.2"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                "score": 9.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-29",
                    "name": "Path Traversal: '..filename'"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "mlflow"
            },
            "severity": "critical",
            "vulnerable_version_range": "< 2.9.2",
            "first_patched_version": {
                "identifier": "2.9.2"
            }
        },
        "url": "https://api.github.com/repos/fcas/evidently/dependabot/alerts/69",
        "html_url": "https://github.com/fcas/evidently/security/dependabot/69",
        "created_at": "2024-05-24T01:34:16Z",
        "updated_at": "2024-05-24T01:34:16Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 68,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "mlflow"
            },
            "manifest_path": "examples/integrations/mlflow_monitoring/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-hvc6-42vf-jhf8",
            "cve_id": "CVE-2023-6940",
            "summary": "mlflow Command Injection vulnerability",
            "description": "with only one user interaction(download a malicious config), attackers can gain full command execution on the victim system.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-hvc6-42vf-jhf8",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-6940",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-6940"
                },
                {
                    "url": "https://github.com/mlflow/mlflow/commit/5139b1087d686fa52e2b087e09da66aff86297b1"
                },
                {
                    "url": "https://huntr.com/bounties/c6f59480-ce47-4f78-a3dc-4bd8ca15029c"
                },
                {
                    "url": "https://github.com/mlflow/mlflow/pull/10676"
                },
                {
                    "url": "https://github.com/mlflow/mlflow/commit/a98a341a7222f894b7735db575ad9311ecaba4e3"
                },
                {
                    "url": "https://github.com/mlflow/mlflow/commits/v2.9.2"
                },
                {
                    "url": "https://github.com/advisories/GHSA-hvc6-42vf-jhf8"
                }
            ],
            "published_at": "2023-12-19T03:30:17Z",
            "updated_at": "2024-01-02T15:10:04Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "mlflow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.9.2",
                    "first_patched_version": {
                        "identifier": "2.9.2"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
                "score": 8.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-77",
                    "name": "Improper Neutralization of Special Elements used in a Command ('Command Injection')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "mlflow"
            },
            "severity": "high",
            "vulnerable_version_range": "< 2.9.2",
            "first_patched_version": {
                "identifier": "2.9.2"
            }
        },
        "url": "https://api.github.com/repos/fcas/evidently/dependabot/alerts/68",
        "html_url": "https://github.com/fcas/evidently/security/dependabot/68",
        "created_at": "2024-05-24T01:34:16Z",
        "updated_at": "2024-05-24T01:34:16Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 67,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "mlflow"
            },
            "manifest_path": "examples/integrations/mlflow_monitoring/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-554w-xh4j-8w64",
            "cve_id": "CVE-2023-6831",
            "summary": "Path traversal in MLflow",
            "description": "Path Traversal: '\\..\\filename' in GitHub repository mlflow/mlflow prior to 2.9.2.",
            "severity": "critical",
            "identifiers": [
                {
                    "value": "GHSA-554w-xh4j-8w64",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-6831",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-6831"
                },
                {
                    "url": "https://github.com/mlflow/mlflow/commit/1da75dfcecd4d169e34809ade55748384e8af6c1"
                },
                {
                    "url": "https://huntr.com/bounties/0acdd745-0167-4912-9d5c-02035fe5b314"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/mlflow/PYSEC-2023-253.yaml"
                },
                {
                    "url": "https://github.com/advisories/GHSA-554w-xh4j-8w64"
                }
            ],
            "published_at": "2023-12-15T03:30:18Z",
            "updated_at": "2024-02-14T15:08:05Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "mlflow"
                    },
                    "severity": "critical",
                    "vulnerable_version_range": "< 2.9.2",
                    "first_patched_version": {
                        "identifier": "2.9.2"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:C/C:N/I:H/A:H",
                "score": 10.0
            },
            "cwes": [
                {
                    "cwe_id": "CWE-22",
                    "name": "Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal')"
                },
                {
                    "cwe_id": "CWE-29",
                    "name": "Path Traversal: '..filename'"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "mlflow"
            },
            "severity": "critical",
            "vulnerable_version_range": "< 2.9.2",
            "first_patched_version": {
                "identifier": "2.9.2"
            }
        },
        "url": "https://api.github.com/repos/fcas/evidently/dependabot/alerts/67",
        "html_url": "https://github.com/fcas/evidently/security/dependabot/67",
        "created_at": "2024-05-24T01:34:16Z",
        "updated_at": "2024-05-24T01:34:16Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    }
]