[
    {
        "number": 43,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "requests"
            },
            "manifest_path": "requirements/minimal_requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-9wx4-h78v-vm56",
            "cve_id": "CVE-2024-35195",
            "summary": "Requests `Session` object does not verify requests after making first request with verify=False",
            "description": "When making requests through a Requests `Session`, if the first request is made with `verify=False` to disable cert verification, all subsequent requests to the same origin will continue to ignore cert verification regardless of changes to the value of `verify`. This behavior will continue for the lifecycle of the connection in the connection pool.\n\n### Remediation\nAny of these options can be used to remediate the current issue, we highly recommend upgrading as the preferred mitigation.\n\n* Upgrade to `requests>=2.32.0`.\n* For `requests<2.32.0`, avoid setting `verify=False` for the first request to a host while using a Requests Session.\n* For `requests<2.32.0`, call `close()` on `Session` objects to clear existing connections if `verify=False` is used.\n\n### Related Links\n* https://github.com/psf/requests/pull/6655",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-9wx4-h78v-vm56",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-35195",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56"
                },
                {
                    "url": "https://github.com/psf/requests/pull/6655"
                },
                {
                    "url": "https://github.com/psf/requests/commit/a58d7f2ffb4d00b46dca2d70a3932a0b37e22fac"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-35195"
                },
                {
                    "url": "https://github.com/advisories/GHSA-9wx4-h78v-vm56"
                }
            ],
            "published_at": "2024-05-20T20:15:00Z",
            "updated_at": "2024-05-20T22:07:29Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "requests"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 2.32.0",
                    "first_patched_version": {
                        "identifier": "2.32.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N",
                "score": 5.6
            },
            "cwes": [
                {
                    "cwe_id": "CWE-670",
                    "name": "Always-Incorrect Control Flow Implementation"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "requests"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 2.32.0",
            "first_patched_version": {
                "identifier": "2.32.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/lightly/dependabot/alerts/43",
        "html_url": "https://github.com/fcas/lightly/security/dependabot/43",
        "created_at": "2024-05-24T01:33:37Z",
        "updated_at": "2024-05-24T01:33:37Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 42,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "tqdm"
            },
            "manifest_path": "requirements/minimal_requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-g7vv-2v7x-gj9p",
            "cve_id": "CVE-2024-34062",
            "summary": "tqdm CLI arguments injection attack",
            "description": "### Impact\nAny optional non-boolean CLI arguments (e.g. `--delim`, `--buf-size`, `--manpath`) are passed through python's `eval`, allowing arbitrary code execution. Example:\n\n```sh\npython -m tqdm --manpath=\"\\\" + str(exec(\\\"import os\\nos.system('echo hi && killall python3')\\\")) + \\\"\"\n```\n\n### Patches\nhttps://github.com/tqdm/tqdm/commit/4e613f84ed2ae029559f539464df83fa91feb316 released in `tqdm>=4.66.3`\n\n### Workarounds\nNone\n\n### References\n- https://github.com/tqdm/tqdm/releases/tag/v4.66.3",
            "severity": "low",
            "identifiers": [
                {
                    "value": "GHSA-g7vv-2v7x-gj9p",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-34062",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/tqdm/tqdm/security/advisories/GHSA-g7vv-2v7x-gj9p"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-34062"
                },
                {
                    "url": "https://github.com/tqdm/tqdm/commit/4e613f84ed2ae029559f539464df83fa91feb316"
                },
                {
                    "url": "https://github.com/advisories/GHSA-g7vv-2v7x-gj9p"
                }
            ],
            "published_at": "2024-05-03T19:33:28Z",
            "updated_at": "2024-05-03T19:33:29Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tqdm"
                    },
                    "severity": "low",
                    "vulnerable_version_range": ">= 4.4.0, < 4.66.3",
                    "first_patched_version": {
                        "identifier": "4.66.3"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:L/PR:L/UI:R/S:U/C:L/I:L/A:N",
                "score": 3.9
            },
            "cwes": [
                {
                    "cwe_id": "CWE-74",
                    "name": "Improper Neutralization of Special Elements in Output Used by a Downstream Component ('Injection')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "tqdm"
            },
            "severity": "low",
            "vulnerable_version_range": ">= 4.4.0, < 4.66.3",
            "first_patched_version": {
                "identifier": "4.66.3"
            }
        },
        "url": "https://api.github.com/repos/fcas/lightly/dependabot/alerts/42",
        "html_url": "https://github.com/fcas/lightly/security/dependabot/42",
        "created_at": "2024-05-24T01:33:37Z",
        "updated_at": "2024-05-24T01:33:37Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 41,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "pydantic"
            },
            "manifest_path": "requirements/minimal_requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-mr82-8j83-vxmv",
            "cve_id": "CVE-2024-3772",
            "summary": "Pydantic regular expression denial of service",
            "description": "Regular expression denial of service in Pydantic < 2.4.0, < 1.10.13 allows remote attackers to cause denial of service via a crafted email string.\n",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-mr82-8j83-vxmv",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-3772",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-3772"
                },
                {
                    "url": "https://github.com/pydantic/pydantic/pull/7360"
                },
                {
                    "url": "https://github.com/pydantic/pydantic/commit/59d8f38fd6220e3917c53785dbc70317d6f8e631"
                },
                {
                    "url": "https://github.com/pydantic/pydantic/commit/e4393ae6145c4dadff739990bb0116c6dec3441b"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6JBZLMSH4GAZOVBMT2JUO2LXHY7M2ALI"
                },
                {
                    "url": "https://github.com/advisories/GHSA-mr82-8j83-vxmv"
                }
            ],
            "published_at": "2024-04-15T03:31:00Z",
            "updated_at": "2024-04-26T03:30:29Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "pydantic"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": ">= 2.0.0, < 2.4.0",
                    "first_patched_version": {
                        "identifier": "2.4.0"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "pydantic"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 1.10.13",
                    "first_patched_version": {
                        "identifier": "1.10.13"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 5.9
            },
            "cwes": [
                {
                    "cwe_id": "CWE-1333",
                    "name": "Inefficient Regular Expression Complexity"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "pydantic"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 1.10.13",
            "first_patched_version": {
                "identifier": "1.10.13"
            }
        },
        "url": "https://api.github.com/repos/fcas/lightly/dependabot/alerts/41",
        "html_url": "https://github.com/fcas/lightly/security/dependabot/41",
        "created_at": "2024-05-24T01:33:37Z",
        "updated_at": "2024-05-24T01:33:37Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 40,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "pillow"
            },
            "manifest_path": "requirements/minimal_requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-44wm-f244-xhp3",
            "cve_id": "CVE-2024-28219",
            "summary": "Pillow buffer overflow vulnerability",
            "description": "In _imagingcms.c in Pillow before 10.3.0, a buffer overflow exists because strcpy is used instead of strncpy.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-44wm-f244-xhp3",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-28219",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-28219"
                },
                {
                    "url": "https://pillow.readthedocs.io/en/stable/releasenotes/10.3.0.html#security"
                },
                {
                    "url": "https://github.com/python-pillow/Pillow/commit/2a93aba5cfcf6e241ab4f9392c13e3b74032c061"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2024/04/msg00008.html"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/4XLPUT3VK4GQ6EVY525TT2QNUIXNRU5M"
                },
                {
                    "url": "https://github.com/advisories/GHSA-44wm-f244-xhp3"
                }
            ],
            "published_at": "2024-04-03T03:30:30Z",
            "updated_at": "2024-04-20T05:06:18Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "pillow"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 10.3.0",
                    "first_patched_version": {
                        "identifier": "10.3.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:H/PR:L/UI:R/S:U/C:H/I:H/A:H",
                "score": 6.7
            },
            "cwes": [
                {
                    "cwe_id": "CWE-120",
                    "name": "Buffer Copy without Checking Size of Input ('Classic Buffer Overflow')"
                },
                {
                    "cwe_id": "CWE-676",
                    "name": "Use of Potentially Dangerous Function"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "pillow"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 10.3.0",
            "first_patched_version": {
                "identifier": "10.3.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/lightly/dependabot/alerts/40",
        "html_url": "https://github.com/fcas/lightly/security/dependabot/40",
        "created_at": "2024-05-24T01:33:37Z",
        "updated_at": "2024-05-24T01:33:37Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 39,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "scikit-learn"
            },
            "manifest_path": "requirements/minimal_requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-jxfp-4rvq-9h9m",
            "cve_id": "CVE-2020-28975",
            "summary": "scikit-learn Denial of Service",
            "description": "svm_predict_values in svm.cpp in Libsvm v324, as used in scikit-learn 0.23.2 and other products, allows attackers to cause a denial of service (segmentation fault) via a crafted model SVM (introduced via pickle, json, or any other model permanence standard) with a large value in the _n_support array.\nNOTE: the scikit-learn vendor's position is that the behavior can only occur if the library's API is violated by an application that changes a private attribute.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-jxfp-4rvq-9h9m",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2020-28975",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2020-28975"
                },
                {
                    "url": "https://github.com/scikit-learn/scikit-learn/issues/18891"
                },
                {
                    "url": "https://github.com/cjlin1/libsvm/blob/9a3a9708926dec87d382c43b203f2ca19c2d56a0/svm.cpp#L2501"
                },
                {
                    "url": "http://packetstormsecurity.com/files/160281/SciKit-Learn-0.23.2-Denial-Of-Service.html"
                },
                {
                    "url": "http://seclists.org/fulldisclosure/2020/Nov/44"
                },
                {
                    "url": "https://github.com/scikit-learn/scikit-learn/commit/1bf13d567d3cd74854aa8343fd25b61dd768bb85"
                },
                {
                    "url": "https://security.gentoo.org/glsa/202301-03"
                },
                {
                    "url": "https://github.com/advisories/GHSA-jxfp-4rvq-9h9m"
                }
            ],
            "published_at": "2022-05-24T17:34:40Z",
            "updated_at": "2024-02-01T20:59:17Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "scikit-learn"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 0.23.2, < 1.0.1",
                    "first_patched_version": {
                        "identifier": "1.0.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": []
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "scikit-learn"
            },
            "severity": "high",
            "vulnerable_version_range": ">= 0.23.2, < 1.0.1",
            "first_patched_version": {
                "identifier": "1.0.1"
            }
        },
        "url": "https://api.github.com/repos/fcas/lightly/dependabot/alerts/39",
        "html_url": "https://github.com/fcas/lightly/security/dependabot/39",
        "created_at": "2024-05-24T01:33:37Z",
        "updated_at": "2024-05-24T01:33:37Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 38,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "Pillow"
            },
            "manifest_path": "requirements/minimal_requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-3f63-hfp8-52jq",
            "cve_id": "CVE-2023-50447",
            "summary": "Arbitrary Code Execution in Pillow",
            "description": "Pillow through 10.1.0 allows PIL.ImageMath.eval Arbitrary Code Execution via the environment parameter, a different vulnerability than CVE-2022-22817 (which was about the expression parameter).",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-3f63-hfp8-52jq",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-50447",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-50447"
                },
                {
                    "url": "https://github.com/python-pillow/Pillow/commit/45c726fd4daa63236a8f3653530f297dc87b160a"
                },
                {
                    "url": "https://pillow.readthedocs.io/en/stable/releasenotes/10.2.0.html#security"
                },
                {
                    "url": "http://www.openwall.com/lists/oss-security/2024/01/20/1"
                },
                {
                    "url": "https://github.com/python-pillow/Pillow/releases"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2024/01/msg00019.html"
                },
                {
                    "url": "https://devhub.checkmarx.com/cve-details/CVE-2023-50447"
                },
                {
                    "url": "https://duartecsantos.github.io/2023-01-02-CVE-2023-50447"
                },
                {
                    "url": "https://duartecsantos.github.io/2024-01-02-CVE-2023-50447"
                },
                {
                    "url": "https://github.com/advisories/GHSA-3f63-hfp8-52jq"
                }
            ],
            "published_at": "2024-01-19T21:30:35Z",
            "updated_at": "2024-03-27T23:53:02Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Pillow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 10.2.0",
                    "first_patched_version": {
                        "identifier": "10.2.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H",
                "score": 8.1
            },
            "cwes": [
                {
                    "cwe_id": "CWE-94",
                    "name": "Improper Control of Generation of Code ('Code Injection')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "Pillow"
            },
            "severity": "high",
            "vulnerable_version_range": "< 10.2.0",
            "first_patched_version": {
                "identifier": "10.2.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/lightly/dependabot/alerts/38",
        "html_url": "https://github.com/fcas/lightly/security/dependabot/38",
        "created_at": "2024-05-24T01:33:36Z",
        "updated_at": "2024-05-24T01:33:36Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 37,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "pillow"
            },
            "manifest_path": "requirements/minimal_requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-8ghj-p4vj-mr35",
            "cve_id": "CVE-2023-44271",
            "summary": "Pillow Denial of Service vulnerability",
            "description": "An issue was discovered in Pillow before 10.0.0. It is a Denial of Service that uncontrollably allocates memory to process a given task, potentially causing a service to crash by having it run out of memory. This occurs for truetype in ImageFont when textlength in an ImageDraw instance operates on a long text argument.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-8ghj-p4vj-mr35",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-44271",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-44271"
                },
                {
                    "url": "https://github.com/python-pillow/Pillow/pull/7244"
                },
                {
                    "url": "https://github.com/python-pillow/Pillow/commit/1fe1bb49c452b0318cad12ea9d97c3bef188e9a7"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2023-227.yaml"
                },
                {
                    "url": "https://devhub.checkmarx.com/cve-details/CVE-2023-44271"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2024/03/msg00021.html"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/N2JOEDUJDQLCUII2LQYZYSM7RJL2I3P4"
                },
                {
                    "url": "https://github.com/advisories/GHSA-8ghj-p4vj-mr35"
                }
            ],
            "published_at": "2023-11-03T06:36:30Z",
            "updated_at": "2024-03-22T15:25:43Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "pillow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 0, < 10.0.0",
                    "first_patched_version": {
                        "identifier": "10.0.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-400",
                    "name": "Uncontrolled Resource Consumption"
                },
                {
                    "cwe_id": "CWE-770",
                    "name": "Allocation of Resources Without Limits or Throttling"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "pillow"
            },
            "severity": "high",
            "vulnerable_version_range": ">= 0, < 10.0.0",
            "first_patched_version": {
                "identifier": "10.0.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/lightly/dependabot/alerts/37",
        "html_url": "https://github.com/fcas/lightly/security/dependabot/37",
        "created_at": "2024-05-24T01:33:36Z",
        "updated_at": "2024-05-24T01:33:36Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 36,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "urllib3"
            },
            "manifest_path": "requirements/minimal_requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-g4mx-q9vg-27p4",
            "cve_id": "CVE-2023-45803",
            "summary": "urllib3's request body not stripped after redirect from 303 status changes request method to GET",
            "description": "urllib3 previously wouldn't remove the HTTP request body when an HTTP redirect response using status 303 \"See Other\" after the request had its method changed from one that could accept a request body (like `POST`) to `GET` as is required by HTTP RFCs. Although the behavior of removing the request body is not specified in the section for redirects, it can be inferred by piecing together information from different sections and we have observed the behavior in other major HTTP client implementations like curl and web browsers.\n\nFrom [RFC 9110 Section 9.3.1](https://www.rfc-editor.org/rfc/rfc9110.html#name-get):\n\n> A client SHOULD NOT generate content in a GET request unless it is made directly to an origin server that has previously indicated, in or out of band, that such a request has a purpose and will be adequately supported.\n\n## Affected usages\n\nBecause the vulnerability requires a previously trusted service to become compromised in order to have an impact on confidentiality we believe the exploitability of this vulnerability is low. Additionally, many users aren't putting sensitive data in HTTP request bodies, if this is the case then this vulnerability isn't exploitable.\n\nBoth of the following conditions must be true to be affected by this vulnerability:\n\n* If you're using urllib3 and submitting sensitive information in the HTTP request body (such as form data or JSON)\n* The origin service is compromised and starts redirecting using 303 to a malicious peer or the redirected-to service becomes compromised.\n\n## Remediation\n\nYou can remediate this vulnerability with any of the following steps:\n\n* Upgrade to a patched version of urllib3 (v1.26.18 or v2.0.7)\n* Disable redirects for services that you aren't expecting to respond with redirects with `redirects=False`.\n* Disable automatic redirects with `redirects=False` and handle 303 redirects manually by stripping the HTTP request body.\n",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-g4mx-q9vg-27p4",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-45803",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/urllib3/urllib3/security/advisories/GHSA-g4mx-q9vg-27p4"
                },
                {
                    "url": "https://github.com/urllib3/urllib3/commit/4e50fbc5db74e32cabd5ccc1ab81fc103adfe0b3"
                },
                {
                    "url": "https://github.com/urllib3/urllib3/commit/b594c5ceaca38e1ac215f916538fb128e3526a36"
                },
                {
                    "url": "https://github.com/urllib3/urllib3/releases/tag/1.26.18"
                },
                {
                    "url": "https://github.com/urllib3/urllib3/releases/tag/2.0.7"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-45803"
                },
                {
                    "url": "https://github.com/urllib3/urllib3/commit/4e98d57809dacab1cbe625fddeec1a290c478ea9"
                },
                {
                    "url": "https://www.rfc-editor.org/rfc/rfc9110.html#name-get"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PPDPLM6UUMN55ESPQWJFLLIZY4ZKCNRX/"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/urllib3/PYSEC-2023-212.yaml"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4R2Y5XK3WALSR3FNAGN7JBYV2B343ZKB/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5/"
                },
                {
                    "url": "https://github.com/advisories/GHSA-g4mx-q9vg-27p4"
                }
            ],
            "published_at": "2023-10-17T20:15:25Z",
            "updated_at": "2023-11-06T16:24:46Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "urllib3"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": ">= 2.0.0, < 2.0.7",
                    "first_patched_version": {
                        "identifier": "2.0.7"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "urllib3"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": ">= 0, < 1.26.18",
                    "first_patched_version": {
                        "identifier": "1.26.18"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:A/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N",
                "score": 4.2
            },
            "cwes": [
                {
                    "cwe_id": "CWE-200",
                    "name": "Exposure of Sensitive Information to an Unauthorized Actor"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "urllib3"
            },
            "severity": "medium",
            "vulnerable_version_range": ">= 0, < 1.26.18",
            "first_patched_version": {
                "identifier": "1.26.18"
            }
        },
        "url": "https://api.github.com/repos/fcas/lightly/dependabot/alerts/36",
        "html_url": "https://github.com/fcas/lightly/security/dependabot/36",
        "created_at": "2024-05-24T01:33:36Z",
        "updated_at": "2024-05-24T01:33:36Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 35,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "pillow"
            },
            "manifest_path": "requirements/minimal_requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-56pw-mpj4-fxww",
            "cve_id": null,
            "summary": "Bundled libwebp in Pillow vulnerable",
            "description": "Pillow versions before v10.0.1 bundled libwebp binaries in wheels that are vulnerable to CVE-2023-5129 (previously CVE-2023-4863). Pillow v10.0.1 upgrades the bundled libwebp binary to v1.3.2.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-56pw-mpj4-fxww",
                    "type": "GHSA"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-4863"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-5129"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2023-175.yaml"
                },
                {
                    "url": "https://github.com/python-pillow/Pillow/blob/main/CHANGES.rst#1001-2023-09-15"
                },
                {
                    "url": "https://github.com/advisories/GHSA-56pw-mpj4-fxww"
                }
            ],
            "published_at": "2023-10-05T00:06:58Z",
            "updated_at": "2023-10-05T00:06:58Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "pillow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 10.0.1",
                    "first_patched_version": {
                        "identifier": "10.0.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": null,
                "score": 0.0
            },
            "cwes": []
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "pillow"
            },
            "severity": "high",
            "vulnerable_version_range": "< 10.0.1",
            "first_patched_version": {
                "identifier": "10.0.1"
            }
        },
        "url": "https://api.github.com/repos/fcas/lightly/dependabot/alerts/35",
        "html_url": "https://github.com/fcas/lightly/security/dependabot/35",
        "created_at": "2024-05-24T01:33:36Z",
        "updated_at": "2024-05-24T01:33:36Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 34,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "Pillow"
            },
            "manifest_path": "requirements/minimal_requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-j7hp-h8jx-5ppr",
            "cve_id": "CVE-2023-4863",
            "summary": "libwebp: OOB write in BuildHuffmanTable",
            "description": "Heap buffer overflow in libwebp allow a remote attacker to perform an out of bounds memory write via a crafted HTML page. ",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-j7hp-h8jx-5ppr",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-4863",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-4863"
                },
                {
                    "url": "https://chromereleases.googleblog.com/2023/09/stable-channel-update-for-desktop_11.html"
                },
                {
                    "url": "https://crbug.com/1479274"
                },
                {
                    "url": "https://github.com/qnighy/libwebp-sys2-rs/pull/21"
                },
                {
                    "url": "https://github.com/qnighy/libwebp-sys2-rs/commit/4560c473a76ec8bd8c650f19ddf9d7a44f719f8b"
                },
                {
                    "url": "https://github.com/webmproject/libwebp/commit/902bc9190331343b2017211debcec8d2ab87e17a"
                },
                {
                    "url": "https://bugzilla.suse.com/show_bug.cgi?id=1215231"
                },
                {
                    "url": "https://en.bandisoft.com/honeyview/history/"
                },
                {
                    "url": "https://msrc.microsoft.com/update-guide/vulnerability/CVE-2023-4863"
                },
                {
                    "url": "https://news.ycombinator.com/item?id=37478403"
                },
                {
                    "url": "https://rustsec.org/advisories/RUSTSEC-2023-0060.html"
                },
                {
                    "url": "https://security-tracker.debian.org/tracker/CVE-2023-4863"
                },
                {
                    "url": "https://stackdiary.com/critical-vulnerability-in-webp-codec-cve-2023-4863/"
                },
                {
                    "url": "https://www.bleepingcomputer.com/news/google/google-fixes-another-chrome-zero-day-bug-exploited-in-attacks/"
                },
                {
                    "url": "https://www.mozilla.org/en-US/security/advisories/mfsa2023-40/"
                },
                {
                    "url": "https://github.com/electron/electron/pull/39823"
                },
                {
                    "url": "https://github.com/electron/electron/pull/39825"
                },
                {
                    "url": "https://github.com/electron/electron/pull/39826"
                },
                {
                    "url": "https://github.com/electron/electron/pull/39827"
                },
                {
                    "url": "https://github.com/electron/electron/pull/39828"
                },
                {
                    "url": "https://adamcaudill.com/2023/09/14/whose-cve-is-it-anyway/"
                },
                {
                    "url": "https://github.com/webmproject/libwebp/releases/tag/v1.3.2"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2023/09/msg00015.html"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2023/09/msg00016.html"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2023/09/msg00017.html"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6T655QF7CQ3DYAMPFV7IECQYGDEUIVVT/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FYYKLG6CRGEDTNRBSU26EEWAO6D6U645/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/OZDGWWMJREPAGKWCJKSCM4WYLANSKIFX/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PYZV7TMKF4QHZ54SFJX54BDN52VHGGCX/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WHOLML7N2G5KCAZXFWC5IDFFHSQS5SDB/"
                },
                {
                    "url": "https://rustsec.org/advisories/RUSTSEC-2023-0061.html"
                },
                {
                    "url": "https://security.gentoo.org/glsa/202309-05"
                },
                {
                    "url": "https://www.debian.org/security/2023/dsa-5496"
                },
                {
                    "url": "https://www.debian.org/security/2023/dsa-5497"
                },
                {
                    "url": "https://www.debian.org/security/2023/dsa-5498"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KUQ7CTX3W372X3UY56VVNAHCH6H2F4X3/"
                },
                {
                    "url": "https://blog.isosceles.com/the-webp-0day/"
                },
                {
                    "url": "http://www.openwall.com/lists/oss-security/2023/09/21/4"
                },
                {
                    "url": "http://www.openwall.com/lists/oss-security/2023/09/22/1"
                },
                {
                    "url": "http://www.openwall.com/lists/oss-security/2023/09/22/3"
                },
                {
                    "url": "http://www.openwall.com/lists/oss-security/2023/09/22/4"
                },
                {
                    "url": "http://www.openwall.com/lists/oss-security/2023/09/22/5"
                },
                {
                    "url": "http://www.openwall.com/lists/oss-security/2023/09/22/6"
                },
                {
                    "url": "http://www.openwall.com/lists/oss-security/2023/09/22/7"
                },
                {
                    "url": "http://www.openwall.com/lists/oss-security/2023/09/22/8"
                },
                {
                    "url": "http://www.openwall.com/lists/oss-security/2023/09/26/1"
                },
                {
                    "url": "http://www.openwall.com/lists/oss-security/2023/09/26/7"
                },
                {
                    "url": "http://www.openwall.com/lists/oss-security/2023/09/28/1"
                },
                {
                    "url": "http://www.openwall.com/lists/oss-security/2023/09/28/2"
                },
                {
                    "url": "http://www.openwall.com/lists/oss-security/2023/09/28/4"
                },
                {
                    "url": "https://github.com/jaredforth/webp/pull/30"
                },
                {
                    "url": "https://github.com/python-pillow/Pillow/pull/7395"
                },
                {
                    "url": "https://github.com/jaredforth/webp/commit/9d4c56e63abecc777df71c702503c3eaabd7dcbc"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WTRUIS3564P7ZLM2S2IH4Y4KZ327LI4I/"
                },
                {
                    "url": "https://pillow.readthedocs.io/en/stable/releasenotes/10.0.1.html#security"
                },
                {
                    "url": "https://security.netapp.com/advisory/ntap-20230929-0011/"
                },
                {
                    "url": "https://github.com/ImageMagick/ImageMagick/discussions/6664"
                },
                {
                    "url": "https://github.com/dlemstra/Magick.NET/releases/tag/13.3.0"
                },
                {
                    "url": "https://security.gentoo.org/glsa/202401-10"
                },
                {
                    "url": "https://sethmlarson.dev/security-developer-in-residence-weekly-report-16"
                },
                {
                    "url": "https://www.bentley.com/advisories/be-2023-0001/"
                },
                {
                    "url": "https://github.com/advisories/GHSA-j7hp-h8jx-5ppr"
                }
            ],
            "published_at": "2023-09-12T15:30:20Z",
            "updated_at": "2024-01-08T15:38:39Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "rust",
                        "name": "libwebp-sys2"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 0.1.8",
                    "first_patched_version": {
                        "identifier": "0.1.8"
                    }
                },
                {
                    "package": {
                        "ecosystem": "rust",
                        "name": "libwebp-sys"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 0.9.3",
                    "first_patched_version": {
                        "identifier": "0.9.3"
                    }
                },
                {
                    "package": {
                        "ecosystem": "npm",
                        "name": "electron"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 22.0.0, < 22.3.24",
                    "first_patched_version": {
                        "identifier": "22.3.24"
                    }
                },
                {
                    "package": {
                        "ecosystem": "npm",
                        "name": "electron"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 24.0.0, < 24.8.3",
                    "first_patched_version": {
                        "identifier": "24.8.3"
                    }
                },
                {
                    "package": {
                        "ecosystem": "npm",
                        "name": "electron"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 25.0.0, < 25.8.1",
                    "first_patched_version": {
                        "identifier": "25.8.1"
                    }
                },
                {
                    "package": {
                        "ecosystem": "npm",
                        "name": "electron"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 26.0.0, < 26.2.1",
                    "first_patched_version": {
                        "identifier": "26.2.1"
                    }
                },
                {
                    "package": {
                        "ecosystem": "npm",
                        "name": "electron"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 27.0.0-beta.1, < 27.0.0-beta.2",
                    "first_patched_version": {
                        "identifier": "27.0.0-beta.2"
                    }
                },
                {
                    "package": {
                        "ecosystem": "nuget",
                        "name": "SkiaSharp"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 2.0.0, < 2.88.6",
                    "first_patched_version": {
                        "identifier": "2.88.6"
                    }
                },
                {
                    "package": {
                        "ecosystem": "go",
                        "name": "github.com/chai2010/webp"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 1.0.0",
                    "first_patched_version": null
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Pillow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 10.0.1",
                    "first_patched_version": {
                        "identifier": "10.0.1"
                    }
                },
                {
                    "package": {
                        "ecosystem": "rust",
                        "name": "webp"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 0.2.6",
                    "first_patched_version": {
                        "identifier": "0.2.6"
                    }
                },
                {
                    "package": {
                        "ecosystem": "nuget",
                        "name": "magick.net-q16-anycpu"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 13.3.0",
                    "first_patched_version": {
                        "identifier": "13.3.0"
                    }
                },
                {
                    "package": {
                        "ecosystem": "nuget",
                        "name": "magick.net-q16-hdri-anycpu"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 13.3.0",
                    "first_patched_version": {
                        "identifier": "13.3.0"
                    }
                },
                {
                    "package": {
                        "ecosystem": "nuget",
                        "name": "magick.net-q16-x64"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 13.3.0",
                    "first_patched_version": {
                        "identifier": "13.3.0"
                    }
                },
                {
                    "package": {
                        "ecosystem": "nuget",
                        "name": "magick.net-q8-anycpu"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 13.3.0",
                    "first_patched_version": {
                        "identifier": "13.3.0"
                    }
                },
                {
                    "package": {
                        "ecosystem": "nuget",
                        "name": "magick.net-q8-openmp-x64"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 13.3.0",
                    "first_patched_version": {
                        "identifier": "13.3.0"
                    }
                },
                {
                    "package": {
                        "ecosystem": "nuget",
                        "name": "magick.net-q8-x64"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 13.3.0",
                    "first_patched_version": {
                        "identifier": "13.3.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
                "score": 8.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-787",
                    "name": "Out-of-bounds Write"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "Pillow"
            },
            "severity": "high",
            "vulnerable_version_range": "< 10.0.1",
            "first_patched_version": {
                "identifier": "10.0.1"
            }
        },
        "url": "https://api.github.com/repos/fcas/lightly/dependabot/alerts/34",
        "html_url": "https://github.com/fcas/lightly/security/dependabot/34",
        "created_at": "2024-05-24T01:33:36Z",
        "updated_at": "2024-05-24T01:33:36Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 33,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "urllib3"
            },
            "manifest_path": "requirements/minimal_requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-v845-jxx5-vc9f",
            "cve_id": "CVE-2023-43804",
            "summary": "`Cookie` HTTP header isn't stripped on cross-origin redirects",
            "description": "urllib3 doesn't treat the `Cookie` HTTP header special or provide any helpers for managing cookies over HTTP, that is the responsibility of the user. However, it is possible for a user to specify a `Cookie` header and unknowingly leak information via HTTP redirects to a different origin if that user doesn't disable redirects explicitly.\n\nUsers **must** handle redirects themselves instead of relying on urllib3's automatic redirects to achieve safe processing of the `Cookie` header, thus we decided to strip the header by default in order to further protect users who aren't using the correct approach.\n\n## Affected usages\n\nWe believe the number of usages affected by this advisory is low. It requires all of the following to be true to be exploited:\n\n* Using an affected version of urllib3 (patched in v1.26.17 and v2.0.6)\n* Using the `Cookie` header on requests, which is mostly typical for impersonating a browser.\n* Not disabling HTTP redirects\n* Either not using HTTPS or for the origin server to redirect to a malicious origin.\n\n## Remediation\n\n* Upgrading to at least urllib3 v1.26.17 or v2.0.6\n* Disabling HTTP redirects using `redirects=False` when sending requests.\n* Not using the `Cookie` header.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-v845-jxx5-vc9f",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-43804",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/urllib3/urllib3/security/advisories/GHSA-v845-jxx5-vc9f"
                },
                {
                    "url": "https://github.com/urllib3/urllib3/commit/01220354d389cd05474713f8c982d05c9b17aafb"
                },
                {
                    "url": "https://github.com/urllib3/urllib3/commit/644124ecd0b6e417c527191f866daa05a5a2056d"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-43804"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2023/10/msg00012.html"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/urllib3/PYSEC-2023-192.yaml"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/I3PR7C6RJ6JUBQKIJ644DMIJSUP36VDY/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NDAGZXYJ7H2G3SB47M453VQVNAWKAEJJ/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5/"
                },
                {
                    "url": "https://github.com/advisories/GHSA-v845-jxx5-vc9f"
                }
            ],
            "published_at": "2023-10-02T23:27:05Z",
            "updated_at": "2023-11-04T00:30:22Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "urllib3"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": ">= 2.0.0, < 2.0.6",
                    "first_patched_version": {
                        "identifier": "2.0.6"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "urllib3"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 1.26.17",
                    "first_patched_version": {
                        "identifier": "1.26.17"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:H/A:N",
                "score": 5.9
            },
            "cwes": [
                {
                    "cwe_id": "CWE-200",
                    "name": "Exposure of Sensitive Information to an Unauthorized Actor"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "urllib3"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 1.26.17",
            "first_patched_version": {
                "identifier": "1.26.17"
            }
        },
        "url": "https://api.github.com/repos/fcas/lightly/dependabot/alerts/33",
        "html_url": "https://github.com/fcas/lightly/security/dependabot/33",
        "created_at": "2024-05-24T01:33:36Z",
        "updated_at": "2024-05-24T01:33:36Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 32,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "pillow"
            },
            "manifest_path": "requirements/minimal_requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-98vv-pw6r-q6q4",
            "cve_id": "CVE-2021-23437",
            "summary": "Uncontrolled Resource Consumption in pillow",
            "description": "The package pillow 5.2.0 and before 8.3.2 are vulnerable to Regular Expression Denial of Service (ReDoS) via the getrgb function.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-98vv-pw6r-q6q4",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2021-23437",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-23437"
                },
                {
                    "url": "https://github.com/python-pillow/Pillow/commit/9e08eb8f78fdfd2f476e1b20b7cf38683754866b"
                },
                {
                    "url": "https://pillow.readthedocs.io/en/stable/releasenotes/8.3.2.html"
                },
                {
                    "url": "https://snyk.io/vuln/SNYK-PYTHON-PILLOW-1319443"
                },
                {
                    "url": "https://security.gentoo.org/glsa/202211-10"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2024/03/msg00021.html"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/RNSG6VFXTAROGF7ACYLMAZNQV4EJ6I2C"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/VKRCL7KKAKOXCVD7M6WC5OKFGL4L3SJT"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/RNSG6VFXTAROGF7ACYLMAZNQV4EJ6I2C"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/VKRCL7KKAKOXCVD7M6WC5OKFGL4L3SJT"
                },
                {
                    "url": "https://github.com/advisories/GHSA-98vv-pw6r-q6q4"
                }
            ],
            "published_at": "2021-09-07T23:08:10Z",
            "updated_at": "2024-04-22T21:11:33Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "pillow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 5.2.0, < 8.3.2",
                    "first_patched_version": {
                        "identifier": "8.3.2"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-125",
                    "name": "Out-of-bounds Read"
                },
                {
                    "cwe_id": "CWE-400",
                    "name": "Uncontrolled Resource Consumption"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "pillow"
            },
            "severity": "high",
            "vulnerable_version_range": ">= 5.2.0, < 8.3.2",
            "first_patched_version": {
                "identifier": "8.3.2"
            }
        },
        "url": "https://api.github.com/repos/fcas/lightly/dependabot/alerts/32",
        "html_url": "https://github.com/fcas/lightly/security/dependabot/32",
        "created_at": "2024-05-24T01:33:36Z",
        "updated_at": "2024-05-24T01:33:36Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 31,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "certifi"
            },
            "manifest_path": "requirements/minimal_requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-xqr8-7jwr-rhp7",
            "cve_id": "CVE-2023-37920",
            "summary": "Removal of e-Tugra root certificate",
            "description": "Certifi 2023.07.22 removes root certificates from \"e-Tugra\" from the root store. These are in the process of being removed from Mozilla's trust store.\n\n e-Tugra's root certificates are being removed pursuant to an investigation prompted by reporting of security issues in their systems. Conclusions of Mozilla's investigation can be found [here](https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/C-HrP1SEq1A).",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-xqr8-7jwr-rhp7",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-37920",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/certifi/python-certifi/security/advisories/GHSA-xqr8-7jwr-rhp7"
                },
                {
                    "url": "https://github.com/certifi/python-certifi/commit/8fb96ed81f71e7097ed11bc4d9b19afd7ea5c909"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-37920"
                },
                {
                    "url": "https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/C-HrP1SEq1A"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/certifi/PYSEC-2023-135.yaml"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5EX6NG7WUFNUKGFHLM35KHHU3GAKXRTG/"
                },
                {
                    "url": "https://github.com/advisories/GHSA-xqr8-7jwr-rhp7"
                }
            ],
            "published_at": "2023-07-25T14:43:53Z",
            "updated_at": "2023-11-09T05:05:47Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "certifi"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 2015.4.28, < 2023.7.22",
                    "first_patched_version": {
                        "identifier": "2023.7.22"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-345",
                    "name": "Insufficient Verification of Data Authenticity"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "certifi"
            },
            "severity": "high",
            "vulnerable_version_range": ">= 2015.4.28, < 2023.7.22",
            "first_patched_version": {
                "identifier": "2023.7.22"
            }
        },
        "url": "https://api.github.com/repos/fcas/lightly/dependabot/alerts/31",
        "html_url": "https://github.com/fcas/lightly/security/dependabot/31",
        "created_at": "2024-05-24T01:33:36Z",
        "updated_at": "2024-05-24T01:33:36Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 30,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "requests"
            },
            "manifest_path": "requirements/minimal_requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-j8r2-6x86-q33q",
            "cve_id": "CVE-2023-32681",
            "summary": "Unintended leak of Proxy-Authorization header in requests",
            "description": "### Impact\n\nSince Requests v2.3.0, Requests has been vulnerable to potentially leaking `Proxy-Authorization` headers to destination servers, specifically during redirects to an HTTPS origin. This is a product of how `rebuild_proxies` is used to recompute and [reattach the `Proxy-Authorization` header](https://github.com/psf/requests/blob/f2629e9e3c7ce3c3c8c025bcd8db551101cbc773/requests/sessions.py#L319-L328) to requests when redirected. Note this behavior has _only_ been observed to affect proxied requests when credentials are supplied in the URL user information component (e.g. `https://username:password@proxy:8080`).\n\n**Current vulnerable behavior(s):**\n\n1. HTTP → HTTPS: **leak**\n2. HTTPS → HTTP: **no leak**\n3. HTTPS → HTTPS: **leak**\n4. HTTP → HTTP: **no leak**\n\nFor HTTP connections sent through the proxy, the proxy will identify the header in the request itself and remove it prior to forwarding to the destination server. However when sent over HTTPS, the `Proxy-Authorization` header must be sent in the CONNECT request as the proxy has no visibility into further tunneled requests. This results in Requests forwarding the header to the destination server unintentionally, allowing a malicious actor to potentially exfiltrate those credentials.\n\nThe reason this currently works for HTTPS connections in Requests is the `Proxy-Authorization` header is also handled by urllib3 with our usage of the ProxyManager in adapters.py with [`proxy_manager_for`](https://github.com/psf/requests/blob/f2629e9e3c7ce3c3c8c025bcd8db551101cbc773/requests/adapters.py#L199-L235). This will compute the required proxy headers in `proxy_headers` and pass them to the Proxy Manager, avoiding attaching them directly to the Request object. This will be our preferred option going forward for default usage.\n\n### Patches\nStarting in Requests v2.31.0, Requests will no longer attach this header to redirects with an HTTPS destination. This should have no negative impacts on the default behavior of the library as the proxy credentials are already properly being handled by urllib3's ProxyManager.\n\nFor users with custom adapters, this _may_ be potentially breaking if you were already working around this behavior. The previous functionality of `rebuild_proxies` doesn't make sense in any case, so we would encourage any users impacted to migrate any handling of Proxy-Authorization directly into their custom adapter.\n\n### Workarounds\nFor users who are not able to update Requests immediately, there is one potential workaround.\n\nYou may disable redirects by setting `allow_redirects` to `False` on all calls through Requests top-level APIs. Note that if you're currently relying on redirect behaviors, you will need to capture the 3xx response codes and ensure a new request is made to the redirect destination.\n```\nimport requests\nr = requests.get('http://github.com/', allow_redirects=False)\n```\n\n### Credits\n\nThis vulnerability was discovered and disclosed by the following individuals.\n\nDennis Brinkrolf, Haxolot (https://haxolot.com/)\nTobias Funke, (tobiasfunke93@gmail.com)",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-j8r2-6x86-q33q",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-32681",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/psf/requests/security/advisories/GHSA-j8r2-6x86-q33q"
                },
                {
                    "url": "https://github.com/psf/requests/commit/74ea7cf7a6a27a4eeb2ae24e162bcc942a6706d5"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-32681"
                },
                {
                    "url": "https://github.com/psf/requests/releases/tag/v2.31.0"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/requests/PYSEC-2023-74.yaml"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2023/06/msg00018.html"
                },
                {
                    "url": "https://security.gentoo.org/glsa/202309-08"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/AW7HNFGYP44RT3DUDQXG2QT3OEV2PJ7Y"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KOYASTZDGQG2BWLSNBPL3TQRL2G7QYNZ"
                },
                {
                    "url": "https://github.com/advisories/GHSA-j8r2-6x86-q33q"
                }
            ],
            "published_at": "2023-05-22T20:36:32Z",
            "updated_at": "2024-03-27T20:09:55Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "requests"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": ">= 2.3.0, < 2.31.0",
                    "first_patched_version": {
                        "identifier": "2.31.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:H/I:N/A:N",
                "score": 6.1
            },
            "cwes": [
                {
                    "cwe_id": "CWE-200",
                    "name": "Exposure of Sensitive Information to an Unauthorized Actor"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "requests"
            },
            "severity": "medium",
            "vulnerable_version_range": ">= 2.3.0, < 2.31.0",
            "first_patched_version": {
                "identifier": "2.31.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/lightly/dependabot/alerts/30",
        "html_url": "https://github.com/fcas/lightly/security/dependabot/30",
        "created_at": "2024-05-24T01:33:36Z",
        "updated_at": "2024-05-24T01:33:36Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 29,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "torch"
            },
            "manifest_path": "requirements/minimal_requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-47fc-vmwq-366v",
            "cve_id": "CVE-2022-45907",
            "summary": "PyTorch vulnerable to arbitrary code execution",
            "description": "In PyTorch before trunk/89695, torch.jit.annotations.parse_type_line can cause arbitrary code execution because eval is used unsafely. The fix for this issue is available in version 1.13.1. There is a release checker in [issue #89855](https://github.com/pytorch/pytorch/issues/89855).",
            "severity": "critical",
            "identifiers": [
                {
                    "value": "GHSA-47fc-vmwq-366v",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2022-45907",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-45907"
                },
                {
                    "url": "https://github.com/pytorch/pytorch/issues/88868"
                },
                {
                    "url": "https://github.com/pytorch/pytorch/commit/767f6aa49fe20a2766b9843d01e3b7f7793df6a3"
                },
                {
                    "url": "https://github.com/pytorch/pytorch/issues/89855"
                },
                {
                    "url": "https://github.com/pytorch/pytorch/pull/89189"
                },
                {
                    "url": "https://github.com/pytorch/pytorch/releases/tag/v1.13.1"
                },
                {
                    "url": "https://github.com/advisories/GHSA-47fc-vmwq-366v"
                }
            ],
            "published_at": "2022-11-26T03:30:27Z",
            "updated_at": "2023-01-30T05:01:22Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "torch"
                    },
                    "severity": "critical",
                    "vulnerable_version_range": "<= 1.13.0",
                    "first_patched_version": {
                        "identifier": "1.13.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                "score": 9.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-77",
                    "name": "Improper Neutralization of Special Elements used in a Command ('Command Injection')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "torch"
            },
            "severity": "critical",
            "vulnerable_version_range": "<= 1.13.0",
            "first_patched_version": {
                "identifier": "1.13.1"
            }
        },
        "url": "https://api.github.com/repos/fcas/lightly/dependabot/alerts/29",
        "html_url": "https://github.com/fcas/lightly/security/dependabot/29",
        "created_at": "2024-05-24T01:33:36Z",
        "updated_at": "2024-05-24T01:33:36Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 28,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "Pillow"
            },
            "manifest_path": "requirements/minimal_requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-mvg9-xffr-p774",
            "cve_id": "CVE-2021-25291",
            "summary": "Out of bounds read in Pillow",
            "description": "An issue was discovered in Pillow before 8.2.0. In `TiffDecode.c`, there is an out-of-bounds read in `TiffreadRGBATile` via invalid tile boundaries.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-mvg9-xffr-p774",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2021-25291",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-25291"
                },
                {
                    "url": "https://github.com/python-pillow/Pillow/commit/cbdce6c5d054fccaf4af34b47f212355c64ace7a"
                },
                {
                    "url": "https://pillow.readthedocs.io/en/stable/releasenotes/8.1.1.html"
                },
                {
                    "url": "https://security.gentoo.org/glsa/202107-33"
                },
                {
                    "url": "https://github.com/python-pillow/Pillow/commit/8b8076bdcb3815be0ef0d279651d8d1342b8ea61"
                },
                {
                    "url": "https://github.com/advisories/GHSA-mvg9-xffr-p774"
                }
            ],
            "published_at": "2021-03-29T16:35:57Z",
            "updated_at": "2024-03-26T18:52:15Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Pillow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 8.2.0",
                    "first_patched_version": {
                        "identifier": "8.2.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-125",
                    "name": "Out-of-bounds Read"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "Pillow"
            },
            "severity": "high",
            "vulnerable_version_range": "< 8.2.0",
            "first_patched_version": {
                "identifier": "8.2.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/lightly/dependabot/alerts/28",
        "html_url": "https://github.com/fcas/lightly/security/dependabot/28",
        "created_at": "2024-05-24T01:33:35Z",
        "updated_at": "2024-05-24T01:33:35Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 27,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "pillow"
            },
            "manifest_path": "requirements/minimal_requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-m2vv-5vj5-2hm7",
            "cve_id": "CVE-2022-45198",
            "summary": "Pillow vulnerable to Data Amplification attack.",
            "description": "Pillow before 9.2.0 performs Improper Handling of Highly Compressed GIF Data (Data Amplification).",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-m2vv-5vj5-2hm7",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2022-45198",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-45198"
                },
                {
                    "url": "https://github.com/python-pillow/Pillow/pull/6402"
                },
                {
                    "url": "https://bugs.gentoo.org/855683"
                },
                {
                    "url": "https://cwe.mitre.org/data/definitions/409.html"
                },
                {
                    "url": "https://github.com/python-pillow/Pillow/releases/tag/9.2.0"
                },
                {
                    "url": "https://github.com/python-pillow/Pillow/pull/6402/commits/c9f1b35e981075110a23487a8d4a6cbb59a588ea"
                },
                {
                    "url": "https://github.com/python-pillow/Pillow/commit/11918eac0628ec8ac0812670d9838361ead2d6a4"
                },
                {
                    "url": "https://security.gentoo.org/glsa/202211-10"
                },
                {
                    "url": "https://github.com/advisories/GHSA-m2vv-5vj5-2hm7"
                }
            ],
            "published_at": "2022-11-14T12:00:15Z",
            "updated_at": "2023-09-05T09:35:58Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "pillow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 9.2.0",
                    "first_patched_version": {
                        "identifier": "9.2.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-409",
                    "name": "Improper Handling of Highly Compressed Data (Data Amplification)"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "pillow"
            },
            "severity": "high",
            "vulnerable_version_range": "< 9.2.0",
            "first_patched_version": {
                "identifier": "9.2.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/lightly/dependabot/alerts/27",
        "html_url": "https://github.com/fcas/lightly/security/dependabot/27",
        "created_at": "2024-05-24T01:33:35Z",
        "updated_at": "2024-05-24T01:33:35Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 26,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "numpy"
            },
            "manifest_path": "requirements/minimal_requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-fpfv-jqm9-f5jm",
            "cve_id": "CVE-2021-34141",
            "summary": "Incorrect Comparison in NumPy",
            "description": "Incomplete string comparison in the numpy.core component in NumPy1.9.x, which allows attackers to fail the APIs via constructing specific string objects.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-fpfv-jqm9-f5jm",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2021-34141",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-34141"
                },
                {
                    "url": "https://github.com/numpy/numpy/issues/18993"
                },
                {
                    "url": "https://www.oracle.com/security-alerts/cpujul2022.html"
                },
                {
                    "url": "https://github.com/numpy/numpy/issues/18993#issuecomment-1010735102"
                },
                {
                    "url": "https://github.com/advisories/GHSA-fpfv-jqm9-f5jm"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/numpy/PYSEC-2021-855.yaml"
                }
            ],
            "published_at": "2021-12-18T00:00:41Z",
            "updated_at": "2023-01-27T05:07:10Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "numpy"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 1.22",
                    "first_patched_version": {
                        "identifier": "1.22"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
                "score": 5.3
            },
            "cwes": [
                {
                    "cwe_id": "CWE-697",
                    "name": "Incorrect Comparison"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "numpy"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 1.22",
            "first_patched_version": {
                "identifier": "1.22"
            }
        },
        "url": "https://api.github.com/repos/fcas/lightly/dependabot/alerts/26",
        "html_url": "https://github.com/fcas/lightly/security/dependabot/26",
        "created_at": "2024-05-24T01:33:35Z",
        "updated_at": "2024-05-24T01:33:35Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 25,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "Pillow"
            },
            "manifest_path": "requirements/minimal_requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-4fx9-vc88-q2xc",
            "cve_id": null,
            "summary": "Infinite loop in Pillow",
            "description": "JpegImagePlugin may append an EOF marker to the end of a truncated file, so that the last segment of the data will still be processed by the decoder.\n\nIf the EOF marker is not detected as such however, this could lead to an infinite loop where JpegImagePlugin keeps trying to end the file.",
            "severity": "low",
            "identifiers": [
                {
                    "value": "GHSA-4fx9-vc88-q2xc",
                    "type": "GHSA"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/python-pillow/Pillow/commit/baae9ec4b67c68e3adaf1208cf54e8de5e38a6fd"
                },
                {
                    "url": "https://pillow.readthedocs.io/en/stable/releasenotes/9.0.0.html#ensure-jpegimageplugin-stops-at-the-end-of-a-truncated-file"
                },
                {
                    "url": "https://github.com/advisories/GHSA-4fx9-vc88-q2xc"
                }
            ],
            "published_at": "2022-03-11T23:39:27Z",
            "updated_at": "2023-01-11T05:05:44Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Pillow"
                    },
                    "severity": "low",
                    "vulnerable_version_range": "< 9.0.0",
                    "first_patched_version": {
                        "identifier": "9.0.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": null,
                "score": 0.0
            },
            "cwes": [
                {
                    "cwe_id": "CWE-400",
                    "name": "Uncontrolled Resource Consumption"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "Pillow"
            },
            "severity": "low",
            "vulnerable_version_range": "< 9.0.0",
            "first_patched_version": {
                "identifier": "9.0.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/lightly/dependabot/alerts/25",
        "html_url": "https://github.com/fcas/lightly/security/dependabot/25",
        "created_at": "2024-05-24T01:33:35Z",
        "updated_at": "2024-05-24T01:33:35Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 24,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "Pillow"
            },
            "manifest_path": "requirements/minimal_requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-8vj2-vxx3-667w",
            "cve_id": "CVE-2022-22817",
            "summary": "Arbitrary expression injection in Pillow",
            "description": "`PIL.ImageMath.eval` in Pillow before 9.0.0 allows evaluation of arbitrary expressions, such as ones that use the Python exec method `ImageMath.eval(\"exec(exit())\")`.\n\nWhile Pillow 9.0.0 restricted top-level builtins available to PIL.ImageMath.eval(), it did not prevent builtins available to lambda expressions. These are now also restricted in 9.0.1.",
            "severity": "critical",
            "identifiers": [
                {
                    "value": "GHSA-8vj2-vxx3-667w",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2022-22817",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-22817"
                },
                {
                    "url": "https://pillow.readthedocs.io/en/stable/releasenotes/9.0.0.html#restrict-builtins-available-to-imagemath-eval"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2022/01/msg00018.html"
                },
                {
                    "url": "https://www.debian.org/security/2022/dsa-5053"
                },
                {
                    "url": "https://github.com/python-pillow/Pillow/commit/8531b01d6cdf0b70f256f93092caa2a5d91afc11"
                },
                {
                    "url": "https://pillow.readthedocs.io/en/stable/releasenotes/9.0.1.html#security"
                },
                {
                    "url": "https://security.gentoo.org/glsa/202211-10"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2024/03/msg00021.html"
                },
                {
                    "url": "https://github.com/advisories/GHSA-8vj2-vxx3-667w"
                }
            ],
            "published_at": "2022-01-12T20:07:33Z",
            "updated_at": "2024-04-22T21:11:18Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Pillow"
                    },
                    "severity": "critical",
                    "vulnerable_version_range": "< 9.0.1",
                    "first_patched_version": {
                        "identifier": "9.0.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                "score": 9.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-74",
                    "name": "Improper Neutralization of Special Elements in Output Used by a Downstream Component ('Injection')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "Pillow"
            },
            "severity": "critical",
            "vulnerable_version_range": "< 9.0.1",
            "first_patched_version": {
                "identifier": "9.0.1"
            }
        },
        "url": "https://api.github.com/repos/fcas/lightly/dependabot/alerts/24",
        "html_url": "https://github.com/fcas/lightly/security/dependabot/24",
        "created_at": "2024-05-24T01:33:35Z",
        "updated_at": "2024-05-24T01:33:35Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 23,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "Pillow"
            },
            "manifest_path": "requirements/minimal_requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-9j59-75qj-795w",
            "cve_id": "CVE-2022-24303",
            "summary": "Path traversal in Pillow",
            "description": "Pillow before 9.0.1 allows attackers to delete files because spaces in temporary pathnames are mishandled.",
            "severity": "critical",
            "identifiers": [
                {
                    "value": "GHSA-9j59-75qj-795w",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2022-24303",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-24303"
                },
                {
                    "url": "https://github.com/python-pillow/Pillow/commit/427221ef5f19157001bf8b1ad7cfe0b905ca8c26"
                },
                {
                    "url": "https://pillow.readthedocs.io/en/stable/releasenotes/9.0.1.html#security"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/pillow/PYSEC-2022-168.yaml"
                },
                {
                    "url": "https://security.gentoo.org/glsa/202211-10"
                },
                {
                    "url": "https://github.com/python-pillow/Pillow/pull/6010"
                },
                {
                    "url": "https://github.com/python-pillow/Pillow/commit/10c4f75aaa383bd9671e923e3b91d391ea12d781"
                },
                {
                    "url": "https://github.com/python-pillow/Pillow/commit/143032103c9f2d55a0a7960bd3e630cb72549e8a"
                },
                {
                    "url": "https://github.com/python-pillow/Pillow/blob/e8ab5640774716c5486d3cb05167f74f742ad6ef/CHANGES.rst?plain=1#L1172"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/W4ZUXPKEX72O3E5IHBPVY5ZCPMJ4GHHV"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XR6UP2XONXOVXI4446VY72R63YRO2YTP"
                },
                {
                    "url": "https://github.com/advisories/GHSA-9j59-75qj-795w"
                }
            ],
            "published_at": "2022-03-11T23:10:32Z",
            "updated_at": "2024-04-03T19:56:24Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Pillow"
                    },
                    "severity": "critical",
                    "vulnerable_version_range": "< 9.0.1",
                    "first_patched_version": {
                        "identifier": "9.0.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:H",
                "score": 9.1
            },
            "cwes": []
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "Pillow"
            },
            "severity": "critical",
            "vulnerable_version_range": "< 9.0.1",
            "first_patched_version": {
                "identifier": "9.0.1"
            }
        },
        "url": "https://api.github.com/repos/fcas/lightly/dependabot/alerts/23",
        "html_url": "https://github.com/fcas/lightly/security/dependabot/23",
        "created_at": "2024-05-24T01:33:35Z",
        "updated_at": "2024-05-24T01:33:35Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 22,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "Pillow"
            },
            "manifest_path": "requirements/minimal_requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-xrcv-f9gm-v42c",
            "cve_id": "CVE-2022-22816",
            "summary": "Out-of-bounds Read in Pillow",
            "description": "path_getbbox in path.c in Pillow before 9.0.0 has a buffer over-read during initialization of ImagePath.Path.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-xrcv-f9gm-v42c",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2022-22816",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-22816"
                },
                {
                    "url": "https://github.com/python-pillow/Pillow/blob/c5d9223a8b5e9295d15b5a9b1ef1dae44c8499f3/src/path.c#L331"
                },
                {
                    "url": "https://pillow.readthedocs.io/en/stable/releasenotes/9.0.0.html#fixed-imagepath-path-array-handling"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2022/01/msg00018.html"
                },
                {
                    "url": "https://www.debian.org/security/2022/dsa-5053"
                },
                {
                    "url": "https://security.gentoo.org/glsa/202211-10"
                },
                {
                    "url": "https://github.com/python-pillow/Pillow/pull/5920"
                },
                {
                    "url": "https://github.com/python-pillow/Pillow/commit/5543e4e2d409cd9e409bc64cdc77be0af007a31f"
                },
                {
                    "url": "https://github.com/advisories/GHSA-xrcv-f9gm-v42c"
                }
            ],
            "published_at": "2022-01-12T20:07:41Z",
            "updated_at": "2023-09-04T16:45:20Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Pillow"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 9.0.0",
                    "first_patched_version": {
                        "identifier": "9.0.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:L",
                "score": 6.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-125",
                    "name": "Out-of-bounds Read"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "Pillow"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 9.0.0",
            "first_patched_version": {
                "identifier": "9.0.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/lightly/dependabot/alerts/22",
        "html_url": "https://github.com/fcas/lightly/security/dependabot/22",
        "created_at": "2024-05-24T01:33:35Z",
        "updated_at": "2024-05-24T01:33:35Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 21,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "Pillow"
            },
            "manifest_path": "requirements/minimal_requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-pw3c-h7wp-cvhx",
            "cve_id": "CVE-2022-22815",
            "summary": "Improper Initialization in Pillow",
            "description": "Pillow is the friendly PIL (Python Imaging Library) fork. `path_getbbox` in `path.c` in Pillow before 9.0.0 improperly initializes `ImagePath.Path`.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-pw3c-h7wp-cvhx",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2022-22815",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-22815"
                },
                {
                    "url": "https://github.com/python-pillow/Pillow/blob/c5d9223a8b5e9295d15b5a9b1ef1dae44c8499f3/src/path.c#L331"
                },
                {
                    "url": "https://pillow.readthedocs.io/en/stable/releasenotes/9.0.0.html#fixed-imagepath-path-array-handling"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2022/01/msg00018.html"
                },
                {
                    "url": "https://www.debian.org/security/2022/dsa-5053"
                },
                {
                    "url": "https://github.com/python-pillow/Pillow/commit/c48271ab354db49cdbd740bc45e13be4f0f7993c"
                },
                {
                    "url": "https://github.com/python-pillow/Pillow/pull/5920"
                },
                {
                    "url": "https://github.com/python-pillow/Pillow/commit/1e092419b6806495c683043ab3feb6ce264f3b9c"
                },
                {
                    "url": "https://github.com/python-pillow/Pillow/blob/e8ab5640774716c5486d3cb05167f74f742ad6ef/CHANGES.rst?plain=1#L1187"
                },
                {
                    "url": "https://github.com/advisories/GHSA-pw3c-h7wp-cvhx"
                }
            ],
            "published_at": "2022-01-12T20:07:43Z",
            "updated_at": "2024-04-03T20:28:19Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Pillow"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 9.0.0",
                    "first_patched_version": {
                        "identifier": "9.0.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:L",
                "score": 6.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-665",
                    "name": "Improper Initialization"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "Pillow"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 9.0.0",
            "first_patched_version": {
                "identifier": "9.0.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/lightly/dependabot/alerts/21",
        "html_url": "https://github.com/fcas/lightly/security/dependabot/21",
        "created_at": "2024-05-24T01:33:35Z",
        "updated_at": "2024-05-24T01:33:35Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 20,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "pillow"
            },
            "manifest_path": "requirements/minimal_requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-7534-mm45-c74v",
            "cve_id": "CVE-2021-34552",
            "summary": "Buffer Overflow in Pillow",
            "description": "Pillow through 8.2.0 and PIL (aka Python Imaging Library) through 1.1.7 allow an attacker to pass controlled parameters directly into a convert function to trigger a buffer overflow in Convert.c.",
            "severity": "critical",
            "identifiers": [
                {
                    "value": "GHSA-7534-mm45-c74v",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2021-34552",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-34552"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2021/07/msg00018.html"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/7V6LCG525ARIX6LX5QRYNAWVDD2MD2SV/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/VUGBBT63VL7G4JNOEIPDJIOC34ZFBKNJ/"
                },
                {
                    "url": "https://pillow.readthedocs.io/en/stable/releasenotes/8.3.0.html#buffer-overflow"
                },
                {
                    "url": "https://pillow.readthedocs.io/en/stable/releasenotes/index.html"
                },
                {
                    "url": "https://github.com/python-pillow/Pillow/pull/5567"
                },
                {
                    "url": "https://security.gentoo.org/glsa/202211-10"
                },
                {
                    "url": "https://github.com/python-pillow/Pillow/commit/31c473898c29d1b7cb6555ce67d9503a4906b83f"
                },
                {
                    "url": "https://github.com/advisories/GHSA-7534-mm45-c74v"
                }
            ],
            "published_at": "2021-10-05T20:24:41Z",
            "updated_at": "2023-04-17T18:59:57Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "pillow"
                    },
                    "severity": "critical",
                    "vulnerable_version_range": "< 8.3.0",
                    "first_patched_version": {
                        "identifier": "8.3.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                "score": 9.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-120",
                    "name": "Buffer Copy without Checking Size of Input ('Classic Buffer Overflow')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "pillow"
            },
            "severity": "critical",
            "vulnerable_version_range": "< 8.3.0",
            "first_patched_version": {
                "identifier": "8.3.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/lightly/dependabot/alerts/20",
        "html_url": "https://github.com/fcas/lightly/security/dependabot/20",
        "created_at": "2024-05-24T01:33:35Z",
        "updated_at": "2024-05-24T01:33:35Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 19,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "urllib3"
            },
            "manifest_path": "requirements/minimal_requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-wqvq-5m8c-6g24",
            "cve_id": "CVE-2020-26137",
            "summary": "CRLF injection in urllib3",
            "description": "urllib3 before 1.25.9 allows CRLF injection if the attacker controls the HTTP request method, as demonstrated by inserting CR and LF control characters in the first argument of `putrequest()`. NOTE: this is similar to CVE-2020-26116.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-wqvq-5m8c-6g24",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2020-26137",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2020-26137"
                },
                {
                    "url": "https://github.com/urllib3/urllib3/pull/1800"
                },
                {
                    "url": "https://github.com/urllib3/urllib3/commit/1dd69c5c5982fae7c87a620d487c2ebf7a6b436b"
                },
                {
                    "url": "https://bugs.python.org/issue39603"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2021/06/msg00015.html"
                },
                {
                    "url": "https://usn.ubuntu.com/4570-1/"
                },
                {
                    "url": "https://www.oracle.com/security-alerts/cpuoct2021.html"
                },
                {
                    "url": "https://www.oracle.com/security-alerts/cpujul2022.html"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2023/10/msg00012.html"
                },
                {
                    "url": "https://github.com/advisories/GHSA-wqvq-5m8c-6g24"
                }
            ],
            "published_at": "2021-06-18T18:46:43Z",
            "updated_at": "2023-11-06T10:52:49Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "urllib3"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 1.25.9",
                    "first_patched_version": {
                        "identifier": "1.25.9"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N",
                "score": 6.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-74",
                    "name": "Improper Neutralization of Special Elements in Output Used by a Downstream Component ('Injection')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "urllib3"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 1.25.9",
            "first_patched_version": {
                "identifier": "1.25.9"
            }
        },
        "url": "https://api.github.com/repos/fcas/lightly/dependabot/alerts/19",
        "html_url": "https://github.com/fcas/lightly/security/dependabot/19",
        "created_at": "2024-05-24T01:33:34Z",
        "updated_at": "2024-05-24T01:33:34Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 18,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "Pillow"
            },
            "manifest_path": "requirements/minimal_requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-7r7m-5h27-29hp",
            "cve_id": "CVE-2021-28676",
            "summary": "Potential infinite loop in Pillow",
            "description": "An issue was discovered in Pillow before 8.2.0. For FLI data, FliDecode did not properly check that the block advance was non-zero, potentially leading to an infinite loop on load.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-7r7m-5h27-29hp",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2021-28676",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-28676"
                },
                {
                    "url": "https://github.com/python-pillow/Pillow/pull/5377"
                },
                {
                    "url": "https://pillow.readthedocs.io/en/stable/releasenotes/8.2.0.html#cve-2021-28676-fix-fli-dos"
                },
                {
                    "url": "https://security.gentoo.org/glsa/202107-33"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2021/07/msg00018.html"
                },
                {
                    "url": "https://github.com/python-pillow/Pillow/commit/bb6c11fb889e6c11b0ee122b828132ee763b5856"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/MQHA5HAIBOYI3R6HDWCLAGFTIQP767FL"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MQHA5HAIBOYI3R6HDWCLAGFTIQP767FL"
                },
                {
                    "url": "https://github.com/advisories/GHSA-7r7m-5h27-29hp"
                }
            ],
            "published_at": "2021-06-08T18:48:53Z",
            "updated_at": "2024-04-22T21:11:13Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Pillow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 8.2.0",
                    "first_patched_version": {
                        "identifier": "8.2.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-835",
                    "name": "Loop with Unreachable Exit Condition ('Infinite Loop')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "Pillow"
            },
            "severity": "high",
            "vulnerable_version_range": "< 8.2.0",
            "first_patched_version": {
                "identifier": "8.2.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/lightly/dependabot/alerts/18",
        "html_url": "https://github.com/fcas/lightly/security/dependabot/18",
        "created_at": "2024-05-24T01:33:34Z",
        "updated_at": "2024-05-24T01:33:34Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 17,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "Pillow"
            },
            "manifest_path": "requirements/minimal_requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-77gc-v2xv-rvvh",
            "cve_id": "CVE-2021-25287",
            "summary": "Out-of-bounds Read in Pillow",
            "description": "An issue was discovered in Pillow before 8.2.0. There is an out-of-bounds read in J2kDecode, in j2ku_graya_la.",
            "severity": "critical",
            "identifiers": [
                {
                    "value": "GHSA-77gc-v2xv-rvvh",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2021-25287",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-25287"
                },
                {
                    "url": "https://github.com/python-pillow/Pillow/pull/5377#issuecomment-833821470"
                },
                {
                    "url": "https://github.com/python-pillow/Pillow/pull/5377/commits/3bf5eddb89afdf690eceaa52bc4d3546ba9a5f87"
                },
                {
                    "url": "https://pillow.readthedocs.io/en/stable/releasenotes/8.2.0.html#cve-2021-25287-cve-2021-25288-fix-oob-read-in-jpeg2kdecode"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MQHA5HAIBOYI3R6HDWCLAGFTIQP767FL/"
                },
                {
                    "url": "https://security.gentoo.org/glsa/202107-33"
                },
                {
                    "url": "https://github.com/python-pillow/Pillow/commit/3bf5eddb89afdf690eceaa52bc4d3546ba9a5f87"
                },
                {
                    "url": "https://github.com/advisories/GHSA-77gc-v2xv-rvvh"
                }
            ],
            "published_at": "2021-06-08T18:49:02Z",
            "updated_at": "2023-02-01T05:05:50Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Pillow"
                    },
                    "severity": "critical",
                    "vulnerable_version_range": ">= 2.4.0, < 8.2.0",
                    "first_patched_version": {
                        "identifier": "8.2.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:H",
                "score": 9.1
            },
            "cwes": [
                {
                    "cwe_id": "CWE-125",
                    "name": "Out-of-bounds Read"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "Pillow"
            },
            "severity": "critical",
            "vulnerable_version_range": ">= 2.4.0, < 8.2.0",
            "first_patched_version": {
                "identifier": "8.2.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/lightly/dependabot/alerts/17",
        "html_url": "https://github.com/fcas/lightly/security/dependabot/17",
        "created_at": "2024-05-24T01:33:34Z",
        "updated_at": "2024-05-24T01:33:34Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 16,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "Pillow"
            },
            "manifest_path": "requirements/minimal_requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-g6rj-rv7j-xwp4",
            "cve_id": "CVE-2021-28675",
            "summary": "Pillow Denial of service",
            "description": "An issue was discovered in Pillow before 8.2.0. `PSDImagePlugin.PsdImageFile` lacked a sanity check on the number of input layers relative to the size of the data block. This could lead to a DoS on `Image.open` prior to `Image.load`.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-g6rj-rv7j-xwp4",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2021-28675",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-28675"
                },
                {
                    "url": "https://github.com/python-pillow/Pillow/pull/5377/commits/22e9bee4ef225c0edbb9323f94c26cee0c623497"
                },
                {
                    "url": "https://pillow.readthedocs.io/en/stable/releasenotes/8.2.0.html#cve-2021-28675-fix-dos-in-psdimageplugin"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MQHA5HAIBOYI3R6HDWCLAGFTIQP767FL/"
                },
                {
                    "url": "https://security.gentoo.org/glsa/202107-33"
                },
                {
                    "url": "https://github.com/advisories/GHSA-g6rj-rv7j-xwp4"
                }
            ],
            "published_at": "2021-06-08T18:49:11Z",
            "updated_at": "2023-09-04T16:32:28Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Pillow"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 8.2.0",
                    "first_patched_version": {
                        "identifier": "8.2.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
                "score": 5.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-233",
                    "name": "Improper Handling of Parameters"
                },
                {
                    "cwe_id": "CWE-252",
                    "name": "Unchecked Return Value"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "Pillow"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 8.2.0",
            "first_patched_version": {
                "identifier": "8.2.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/lightly/dependabot/alerts/16",
        "html_url": "https://github.com/fcas/lightly/security/dependabot/16",
        "created_at": "2024-05-24T01:33:34Z",
        "updated_at": "2024-05-24T01:33:34Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 15,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "Pillow"
            },
            "manifest_path": "requirements/minimal_requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-hjfx-8p6c-g7gx",
            "cve_id": "CVE-2021-28678",
            "summary": "Insufficient Verification of Data Authenticity in Pillow",
            "description": "An issue was discovered in Pillow before 8.2.0. For BLP data, BlpImagePlugin did not properly check that reads (after jumping to file offsets) returned data. This could lead to a DoS where the decoder could be run a large number of times on empty data.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-hjfx-8p6c-g7gx",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2021-28678",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-28678"
                },
                {
                    "url": "https://github.com/python-pillow/Pillow/pull/5377"
                },
                {
                    "url": "https://github.com/python-pillow/Pillow/pull/5377/commits/496245aa4365d0827390bd0b6fbd11287453b3a1"
                },
                {
                    "url": "https://pillow.readthedocs.io/en/stable/releasenotes/8.2.0.html#cve-2021-28678-fix-blp-dos"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MQHA5HAIBOYI3R6HDWCLAGFTIQP767FL/"
                },
                {
                    "url": "https://security.gentoo.org/glsa/202107-33"
                },
                {
                    "url": "https://github.com/advisories/GHSA-hjfx-8p6c-g7gx"
                }
            ],
            "published_at": "2021-06-08T18:49:20Z",
            "updated_at": "2023-09-04T16:28:25Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Pillow"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": ">= 5.1.0, < 8.2.0",
                    "first_patched_version": {
                        "identifier": "8.2.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
                "score": 5.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-345",
                    "name": "Insufficient Verification of Data Authenticity"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "Pillow"
            },
            "severity": "medium",
            "vulnerable_version_range": ">= 5.1.0, < 8.2.0",
            "first_patched_version": {
                "identifier": "8.2.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/lightly/dependabot/alerts/15",
        "html_url": "https://github.com/fcas/lightly/security/dependabot/15",
        "created_at": "2024-05-24T01:33:34Z",
        "updated_at": "2024-05-24T01:33:34Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 14,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "Pillow"
            },
            "manifest_path": "requirements/minimal_requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-rwv7-3v45-hg29",
            "cve_id": "CVE-2021-25288",
            "summary": "Out-of-bounds Read",
            "description": "An issue was discovered in Pillow before 8.2.0. There is an out-of-bounds read in J2kDecode, in j2ku_gray_i. This dates to Pillow 2.4.0.",
            "severity": "critical",
            "identifiers": [
                {
                    "value": "GHSA-rwv7-3v45-hg29",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2021-25288",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-25288"
                },
                {
                    "url": "https://github.com/python-pillow/Pillow/pull/5377#issuecomment-833821470"
                },
                {
                    "url": "https://pillow.readthedocs.io/en/stable/releasenotes/8.2.0.html#cve-2021-25287-cve-2021-25288-fix-oob-read-in-jpeg2kdecode"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MQHA5HAIBOYI3R6HDWCLAGFTIQP767FL/"
                },
                {
                    "url": "https://security.gentoo.org/glsa/202107-33"
                },
                {
                    "url": "https://github.com/python-pillow/Pillow/commit/3bf5eddb89afdf690eceaa52bc4d3546ba9a5f87"
                },
                {
                    "url": "https://github.com/advisories/GHSA-rwv7-3v45-hg29"
                }
            ],
            "published_at": "2021-06-08T18:49:28Z",
            "updated_at": "2023-02-01T05:06:07Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Pillow"
                    },
                    "severity": "critical",
                    "vulnerable_version_range": ">= 2.4.0, < 8.2.0",
                    "first_patched_version": {
                        "identifier": "8.2.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:H",
                "score": 9.1
            },
            "cwes": [
                {
                    "cwe_id": "CWE-125",
                    "name": "Out-of-bounds Read"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "Pillow"
            },
            "severity": "critical",
            "vulnerable_version_range": ">= 2.4.0, < 8.2.0",
            "first_patched_version": {
                "identifier": "8.2.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/lightly/dependabot/alerts/14",
        "html_url": "https://github.com/fcas/lightly/security/dependabot/14",
        "created_at": "2024-05-24T01:33:34Z",
        "updated_at": "2024-05-24T01:33:34Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    }
]