[
    {
        "number": 59,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "requests"
            },
            "manifest_path": "examples/research_projects/visual_bert/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-9wx4-h78v-vm56",
            "cve_id": "CVE-2024-35195",
            "summary": "Requests `Session` object does not verify requests after making first request with verify=False",
            "description": "When making requests through a Requests `Session`, if the first request is made with `verify=False` to disable cert verification, all subsequent requests to the same origin will continue to ignore cert verification regardless of changes to the value of `verify`. This behavior will continue for the lifecycle of the connection in the connection pool.\n\n### Remediation\nAny of these options can be used to remediate the current issue, we highly recommend upgrading as the preferred mitigation.\n\n* Upgrade to `requests>=2.32.0`.\n* For `requests<2.32.0`, avoid setting `verify=False` for the first request to a host while using a Requests Session.\n* For `requests<2.32.0`, call `close()` on `Session` objects to clear existing connections if `verify=False` is used.\n\n### Related Links\n* https://github.com/psf/requests/pull/6655",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-9wx4-h78v-vm56",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-35195",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56"
                },
                {
                    "url": "https://github.com/psf/requests/pull/6655"
                },
                {
                    "url": "https://github.com/psf/requests/commit/a58d7f2ffb4d00b46dca2d70a3932a0b37e22fac"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-35195"
                },
                {
                    "url": "https://github.com/advisories/GHSA-9wx4-h78v-vm56"
                }
            ],
            "published_at": "2024-05-20T20:15:00Z",
            "updated_at": "2024-05-20T22:07:29Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "requests"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 2.32.0",
                    "first_patched_version": {
                        "identifier": "2.32.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N",
                "score": 5.6
            },
            "cwes": [
                {
                    "cwe_id": "CWE-670",
                    "name": "Always-Incorrect Control Flow Implementation"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "requests"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 2.32.0",
            "first_patched_version": {
                "identifier": "2.32.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/transformers/dependabot/alerts/59",
        "html_url": "https://github.com/fcas/transformers/security/dependabot/59",
        "created_at": "2024-05-21T08:36:36Z",
        "updated_at": "2024-05-21T08:36:36Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 58,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "requests"
            },
            "manifest_path": "examples/research_projects/decision_transformer/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-9wx4-h78v-vm56",
            "cve_id": "CVE-2024-35195",
            "summary": "Requests `Session` object does not verify requests after making first request with verify=False",
            "description": "When making requests through a Requests `Session`, if the first request is made with `verify=False` to disable cert verification, all subsequent requests to the same origin will continue to ignore cert verification regardless of changes to the value of `verify`. This behavior will continue for the lifecycle of the connection in the connection pool.\n\n### Remediation\nAny of these options can be used to remediate the current issue, we highly recommend upgrading as the preferred mitigation.\n\n* Upgrade to `requests>=2.32.0`.\n* For `requests<2.32.0`, avoid setting `verify=False` for the first request to a host while using a Requests Session.\n* For `requests<2.32.0`, call `close()` on `Session` objects to clear existing connections if `verify=False` is used.\n\n### Related Links\n* https://github.com/psf/requests/pull/6655",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-9wx4-h78v-vm56",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-35195",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56"
                },
                {
                    "url": "https://github.com/psf/requests/pull/6655"
                },
                {
                    "url": "https://github.com/psf/requests/commit/a58d7f2ffb4d00b46dca2d70a3932a0b37e22fac"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-35195"
                },
                {
                    "url": "https://github.com/advisories/GHSA-9wx4-h78v-vm56"
                }
            ],
            "published_at": "2024-05-20T20:15:00Z",
            "updated_at": "2024-05-20T22:07:29Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "requests"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 2.32.0",
                    "first_patched_version": {
                        "identifier": "2.32.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N",
                "score": 5.6
            },
            "cwes": [
                {
                    "cwe_id": "CWE-670",
                    "name": "Always-Incorrect Control Flow Implementation"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "requests"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 2.32.0",
            "first_patched_version": {
                "identifier": "2.32.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/transformers/dependabot/alerts/58",
        "html_url": "https://github.com/fcas/transformers/security/dependabot/58",
        "created_at": "2024-05-21T08:36:36Z",
        "updated_at": "2024-05-21T08:36:36Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 57,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "requests"
            },
            "manifest_path": "examples/research_projects/lxmert/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-9wx4-h78v-vm56",
            "cve_id": "CVE-2024-35195",
            "summary": "Requests `Session` object does not verify requests after making first request with verify=False",
            "description": "When making requests through a Requests `Session`, if the first request is made with `verify=False` to disable cert verification, all subsequent requests to the same origin will continue to ignore cert verification regardless of changes to the value of `verify`. This behavior will continue for the lifecycle of the connection in the connection pool.\n\n### Remediation\nAny of these options can be used to remediate the current issue, we highly recommend upgrading as the preferred mitigation.\n\n* Upgrade to `requests>=2.32.0`.\n* For `requests<2.32.0`, avoid setting `verify=False` for the first request to a host while using a Requests Session.\n* For `requests<2.32.0`, call `close()` on `Session` objects to clear existing connections if `verify=False` is used.\n\n### Related Links\n* https://github.com/psf/requests/pull/6655",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-9wx4-h78v-vm56",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-35195",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56"
                },
                {
                    "url": "https://github.com/psf/requests/pull/6655"
                },
                {
                    "url": "https://github.com/psf/requests/commit/a58d7f2ffb4d00b46dca2d70a3932a0b37e22fac"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-35195"
                },
                {
                    "url": "https://github.com/advisories/GHSA-9wx4-h78v-vm56"
                }
            ],
            "published_at": "2024-05-20T20:15:00Z",
            "updated_at": "2024-05-20T22:07:29Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "requests"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 2.32.0",
                    "first_patched_version": {
                        "identifier": "2.32.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N",
                "score": 5.6
            },
            "cwes": [
                {
                    "cwe_id": "CWE-670",
                    "name": "Always-Incorrect Control Flow Implementation"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "requests"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 2.32.0",
            "first_patched_version": {
                "identifier": "2.32.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/transformers/dependabot/alerts/57",
        "html_url": "https://github.com/fcas/transformers/security/dependabot/57",
        "created_at": "2024-05-21T08:36:36Z",
        "updated_at": "2024-05-21T08:36:36Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 56,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "transformers"
            },
            "manifest_path": "examples/tensorflow/language-modeling-tpu/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-37q5-v5qm-c9v8",
            "cve_id": "CVE-2024-3568",
            "summary": "Transformers Deserialization of Untrusted Data vulnerability",
            "description": "The huggingface/transformers library is vulnerable to arbitrary code execution through deserialization of untrusted data within the `load_repo_checkpoint()` function of the `TFPreTrainedModel()` class. Attackers can execute arbitrary code and commands by crafting a malicious serialized payload, exploiting the use of `pickle.load()` on data from potentially untrusted sources. This vulnerability allows for remote code execution (RCE) by deceiving victims into loading a seemingly harmless checkpoint during a normal training process, thereby enabling attackers to execute arbitrary code on the targeted machine.",
            "severity": "low",
            "identifiers": [
                {
                    "value": "GHSA-37q5-v5qm-c9v8",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-3568",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-3568"
                },
                {
                    "url": "https://github.com/huggingface/transformers/commit/693667b8ac8138b83f8adb6522ddaf42fa07c125"
                },
                {
                    "url": "https://huntr.com/bounties/b3c36992-5264-4d7f-9906-a996efafba8f"
                },
                {
                    "url": "https://github.com/advisories/GHSA-37q5-v5qm-c9v8"
                }
            ],
            "published_at": "2024-04-10T18:30:48Z",
            "updated_at": "2024-04-10T22:20:57Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "transformers"
                    },
                    "severity": "low",
                    "vulnerable_version_range": "< 4.38.0",
                    "first_patched_version": {
                        "identifier": "4.38.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.0/AV:N/AC:H/PR:N/UI:R/S:C/C:N/I:N/A:L",
                "score": 3.4
            },
            "cwes": [
                {
                    "cwe_id": "CWE-502",
                    "name": "Deserialization of Untrusted Data"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "transformers"
            },
            "severity": "low",
            "vulnerable_version_range": "< 4.38.0",
            "first_patched_version": {
                "identifier": "4.38.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/transformers/dependabot/alerts/56",
        "html_url": "https://github.com/fcas/transformers/security/dependabot/56",
        "created_at": "2024-05-16T23:41:38Z",
        "updated_at": "2024-05-16T23:41:38Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 55,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "transformers"
            },
            "manifest_path": "examples/tensorflow/language-modeling-tpu/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-3863-2447-669p",
            "cve_id": "CVE-2023-6730",
            "summary": "transformers has a Deserialization of Untrusted Data vulnerability",
            "description": "Deserialization of Untrusted Data in GitHub repository huggingface/transformers prior to 4.36.0.",
            "severity": "critical",
            "identifiers": [
                {
                    "value": "GHSA-3863-2447-669p",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-6730",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-6730"
                },
                {
                    "url": "https://github.com/huggingface/transformers/commit/1d63b0ec361e7a38f1339385e8a5a855085532ce"
                },
                {
                    "url": "https://huntr.com/bounties/423611ee-7a2a-442a-babb-3ed2f8385c16"
                },
                {
                    "url": "https://github.com/advisories/GHSA-3863-2447-669p"
                }
            ],
            "published_at": "2023-12-19T15:30:30Z",
            "updated_at": "2023-12-28T05:05:45Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "transformers"
                    },
                    "severity": "critical",
                    "vulnerable_version_range": "< 4.36.0",
                    "first_patched_version": {
                        "identifier": "4.36.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.0/AV:N/AC:L/PR:L/UI:R/S:C/C:H/I:H/A:H",
                "score": 9.0
            },
            "cwes": [
                {
                    "cwe_id": "CWE-502",
                    "name": "Deserialization of Untrusted Data"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "transformers"
            },
            "severity": "critical",
            "vulnerable_version_range": "< 4.36.0",
            "first_patched_version": {
                "identifier": "4.36.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/transformers/dependabot/alerts/55",
        "html_url": "https://github.com/fcas/transformers/security/dependabot/55",
        "created_at": "2024-05-16T23:41:38Z",
        "updated_at": "2024-05-16T23:41:38Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 54,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "transformers"
            },
            "manifest_path": "examples/tensorflow/language-modeling-tpu/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-v68g-wm8c-6x7j",
            "cve_id": "CVE-2023-7018",
            "summary": "transformers has a Deserialization of Untrusted Data vulnerability",
            "description": "Deserialization of Untrusted Data in GitHub repository huggingface/transformers prior to 4.36.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-v68g-wm8c-6x7j",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-7018",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-7018"
                },
                {
                    "url": "https://github.com/huggingface/transformers/commit/1d63b0ec361e7a38f1339385e8a5a855085532ce"
                },
                {
                    "url": "https://huntr.com/bounties/e1a3e548-e53a-48df-b708-9ee62140963c"
                },
                {
                    "url": "https://github.com/advisories/GHSA-v68g-wm8c-6x7j"
                }
            ],
            "published_at": "2023-12-20T18:30:32Z",
            "updated_at": "2024-01-02T15:27:26Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "transformers"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 4.36.0",
                    "first_patched_version": {
                        "identifier": "4.36.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
                "score": 7.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-502",
                    "name": "Deserialization of Untrusted Data"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "transformers"
            },
            "severity": "high",
            "vulnerable_version_range": "< 4.36.0",
            "first_patched_version": {
                "identifier": "4.36.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/transformers/dependabot/alerts/54",
        "html_url": "https://github.com/fcas/transformers/security/dependabot/54",
        "created_at": "2024-05-16T23:41:38Z",
        "updated_at": "2024-05-16T23:41:38Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 53,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "transformers"
            },
            "manifest_path": "examples/tensorflow/language-modeling-tpu/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-282v-666c-3fvg",
            "cve_id": "CVE-2023-2800",
            "summary": "transformers has Insecure Temporary File",
            "description": "Insecure Temporary File in GitHub repository huggingface/transformers 4.29.2 and prior. A fix is available at commit 80ca92470938bbcc348e2d9cf4734c7c25cb1c43 and has been released as part of version 4.30.0.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-282v-666c-3fvg",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-2800",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-2800"
                },
                {
                    "url": "https://github.com/huggingface/transformers/commit/80ca92470938bbcc348e2d9cf4734c7c25cb1c43"
                },
                {
                    "url": "https://huntr.dev/bounties/a3867b4e-6701-4418-8c20-3c6e7084a44a"
                },
                {
                    "url": "https://github.com/huggingface/transformers/pull/23372"
                },
                {
                    "url": "https://github.com/advisories/GHSA-282v-666c-3fvg"
                }
            ],
            "published_at": "2023-05-18T18:30:35Z",
            "updated_at": "2023-11-09T05:05:04Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "transformers"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 4.30.0",
                    "first_patched_version": {
                        "identifier": "4.30.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:U/C:N/I:N/A:H",
                "score": 4.7
            },
            "cwes": [
                {
                    "cwe_id": "CWE-377",
                    "name": "Insecure Temporary File"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "transformers"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 4.30.0",
            "first_patched_version": {
                "identifier": "4.30.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/transformers/dependabot/alerts/53",
        "html_url": "https://github.com/fcas/transformers/security/dependabot/53",
        "created_at": "2024-05-16T23:41:38Z",
        "updated_at": "2024-05-16T23:41:38Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 52,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "transformers"
            },
            "manifest_path": "examples/research_projects/vqgan-clip/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-37q5-v5qm-c9v8",
            "cve_id": "CVE-2024-3568",
            "summary": "Transformers Deserialization of Untrusted Data vulnerability",
            "description": "The huggingface/transformers library is vulnerable to arbitrary code execution through deserialization of untrusted data within the `load_repo_checkpoint()` function of the `TFPreTrainedModel()` class. Attackers can execute arbitrary code and commands by crafting a malicious serialized payload, exploiting the use of `pickle.load()` on data from potentially untrusted sources. This vulnerability allows for remote code execution (RCE) by deceiving victims into loading a seemingly harmless checkpoint during a normal training process, thereby enabling attackers to execute arbitrary code on the targeted machine.",
            "severity": "low",
            "identifiers": [
                {
                    "value": "GHSA-37q5-v5qm-c9v8",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-3568",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-3568"
                },
                {
                    "url": "https://github.com/huggingface/transformers/commit/693667b8ac8138b83f8adb6522ddaf42fa07c125"
                },
                {
                    "url": "https://huntr.com/bounties/b3c36992-5264-4d7f-9906-a996efafba8f"
                },
                {
                    "url": "https://github.com/advisories/GHSA-37q5-v5qm-c9v8"
                }
            ],
            "published_at": "2024-04-10T18:30:48Z",
            "updated_at": "2024-04-10T22:20:57Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "transformers"
                    },
                    "severity": "low",
                    "vulnerable_version_range": "< 4.38.0",
                    "first_patched_version": {
                        "identifier": "4.38.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.0/AV:N/AC:H/PR:N/UI:R/S:C/C:N/I:N/A:L",
                "score": 3.4
            },
            "cwes": [
                {
                    "cwe_id": "CWE-502",
                    "name": "Deserialization of Untrusted Data"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "transformers"
            },
            "severity": "low",
            "vulnerable_version_range": "< 4.38.0",
            "first_patched_version": {
                "identifier": "4.38.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/transformers/dependabot/alerts/52",
        "html_url": "https://github.com/fcas/transformers/security/dependabot/52",
        "created_at": "2024-05-16T23:41:38Z",
        "updated_at": "2024-05-16T23:41:38Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 51,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "transformers"
            },
            "manifest_path": "examples/research_projects/vqgan-clip/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-3863-2447-669p",
            "cve_id": "CVE-2023-6730",
            "summary": "transformers has a Deserialization of Untrusted Data vulnerability",
            "description": "Deserialization of Untrusted Data in GitHub repository huggingface/transformers prior to 4.36.0.",
            "severity": "critical",
            "identifiers": [
                {
                    "value": "GHSA-3863-2447-669p",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-6730",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-6730"
                },
                {
                    "url": "https://github.com/huggingface/transformers/commit/1d63b0ec361e7a38f1339385e8a5a855085532ce"
                },
                {
                    "url": "https://huntr.com/bounties/423611ee-7a2a-442a-babb-3ed2f8385c16"
                },
                {
                    "url": "https://github.com/advisories/GHSA-3863-2447-669p"
                }
            ],
            "published_at": "2023-12-19T15:30:30Z",
            "updated_at": "2023-12-28T05:05:45Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "transformers"
                    },
                    "severity": "critical",
                    "vulnerable_version_range": "< 4.36.0",
                    "first_patched_version": {
                        "identifier": "4.36.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.0/AV:N/AC:L/PR:L/UI:R/S:C/C:H/I:H/A:H",
                "score": 9.0
            },
            "cwes": [
                {
                    "cwe_id": "CWE-502",
                    "name": "Deserialization of Untrusted Data"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "transformers"
            },
            "severity": "critical",
            "vulnerable_version_range": "< 4.36.0",
            "first_patched_version": {
                "identifier": "4.36.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/transformers/dependabot/alerts/51",
        "html_url": "https://github.com/fcas/transformers/security/dependabot/51",
        "created_at": "2024-05-16T23:41:38Z",
        "updated_at": "2024-05-16T23:41:38Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 50,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "transformers"
            },
            "manifest_path": "examples/research_projects/vqgan-clip/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-v68g-wm8c-6x7j",
            "cve_id": "CVE-2023-7018",
            "summary": "transformers has a Deserialization of Untrusted Data vulnerability",
            "description": "Deserialization of Untrusted Data in GitHub repository huggingface/transformers prior to 4.36.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-v68g-wm8c-6x7j",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-7018",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-7018"
                },
                {
                    "url": "https://github.com/huggingface/transformers/commit/1d63b0ec361e7a38f1339385e8a5a855085532ce"
                },
                {
                    "url": "https://huntr.com/bounties/e1a3e548-e53a-48df-b708-9ee62140963c"
                },
                {
                    "url": "https://github.com/advisories/GHSA-v68g-wm8c-6x7j"
                }
            ],
            "published_at": "2023-12-20T18:30:32Z",
            "updated_at": "2024-01-02T15:27:26Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "transformers"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 4.36.0",
                    "first_patched_version": {
                        "identifier": "4.36.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
                "score": 7.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-502",
                    "name": "Deserialization of Untrusted Data"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "transformers"
            },
            "severity": "high",
            "vulnerable_version_range": "< 4.36.0",
            "first_patched_version": {
                "identifier": "4.36.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/transformers/dependabot/alerts/50",
        "html_url": "https://github.com/fcas/transformers/security/dependabot/50",
        "created_at": "2024-05-16T23:41:38Z",
        "updated_at": "2024-05-16T23:41:38Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 49,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "transformers"
            },
            "manifest_path": "examples/research_projects/vqgan-clip/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-282v-666c-3fvg",
            "cve_id": "CVE-2023-2800",
            "summary": "transformers has Insecure Temporary File",
            "description": "Insecure Temporary File in GitHub repository huggingface/transformers 4.29.2 and prior. A fix is available at commit 80ca92470938bbcc348e2d9cf4734c7c25cb1c43 and has been released as part of version 4.30.0.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-282v-666c-3fvg",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-2800",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-2800"
                },
                {
                    "url": "https://github.com/huggingface/transformers/commit/80ca92470938bbcc348e2d9cf4734c7c25cb1c43"
                },
                {
                    "url": "https://huntr.dev/bounties/a3867b4e-6701-4418-8c20-3c6e7084a44a"
                },
                {
                    "url": "https://github.com/huggingface/transformers/pull/23372"
                },
                {
                    "url": "https://github.com/advisories/GHSA-282v-666c-3fvg"
                }
            ],
            "published_at": "2023-05-18T18:30:35Z",
            "updated_at": "2023-11-09T05:05:04Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "transformers"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 4.30.0",
                    "first_patched_version": {
                        "identifier": "4.30.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:U/C:N/I:N/A:H",
                "score": 4.7
            },
            "cwes": [
                {
                    "cwe_id": "CWE-377",
                    "name": "Insecure Temporary File"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "transformers"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 4.30.0",
            "first_patched_version": {
                "identifier": "4.30.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/transformers/dependabot/alerts/49",
        "html_url": "https://github.com/fcas/transformers/security/dependabot/49",
        "created_at": "2024-05-16T23:41:38Z",
        "updated_at": "2024-05-16T23:41:38Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 48,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "idna"
            },
            "manifest_path": "examples/research_projects/visual_bert/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-jjg7-2v4v-x38h",
            "cve_id": "CVE-2024-3651",
            "summary": "Internationalized Domain Names in Applications (IDNA) vulnerable to denial of service from specially crafted inputs to idna.encode",
            "description": "### Impact\nA specially crafted argument to the `idna.encode()` function could consume significant resources. This may lead to a denial-of-service.\n\n### Patches\nThe function has been refined to reject such strings without the associated resource consumption in version 3.7.\n\n### Workarounds\nDomain names cannot exceed 253 characters in length, if this length limit is enforced prior to passing the domain to the `idna.encode()` function it should no longer consume significant resources. This is triggered by arbitrarily large inputs that would not occur in normal usage, but may be passed to the library assuming there is no preliminary input validation by the higher-level application.\n\n### References\n* https://huntr.com/bounties/93d78d07-d791-4b39-a845-cbfabc44aadb",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-jjg7-2v4v-x38h",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-3651",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/kjd/idna/security/advisories/GHSA-jjg7-2v4v-x38h"
                },
                {
                    "url": "https://github.com/advisories/GHSA-jjg7-2v4v-x38h"
                }
            ],
            "published_at": "2024-04-11T21:32:40Z",
            "updated_at": "2024-04-11T21:32:40Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "idna"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 3.7",
                    "first_patched_version": {
                        "identifier": "3.7"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 6.2
            },
            "cwes": [
                {
                    "cwe_id": "CWE-400",
                    "name": "Uncontrolled Resource Consumption"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "idna"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 3.7",
            "first_patched_version": {
                "identifier": "3.7"
            }
        },
        "url": "https://api.github.com/repos/fcas/transformers/dependabot/alerts/48",
        "html_url": "https://github.com/fcas/transformers/security/dependabot/48",
        "created_at": "2024-05-16T23:41:37Z",
        "updated_at": "2024-05-16T23:41:37Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 47,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "jupyter-core"
            },
            "manifest_path": "examples/research_projects/visual_bert/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-m678-f26j-3hrp",
            "cve_id": "CVE-2022-39286",
            "summary": "Execution with Unnecessary Privileges in JupyterApp",
            "description": "### Impact\n_What kind of vulnerability is it? Who is impacted?_\nWe’d like to disclose an arbitrary code execution vulnerability in `jupyter_core` that stems from `jupyter_core` executing untrusted files in the current working directory. This vulnerability allows one user to run code as another.\n\n\n### Patches\n_Has the problem been patched? What versions should users upgrade to?_\nUsers should upgrade to `jupyter_core>=4.11.2`.\n\n### Workarounds\n_Is there a way for users to fix or remediate the vulnerability without upgrading?_\nNo\n\n### References\n_Are there any links users can visit to find out more?_\nSimilar advisory in [IPython](https://github.com/advisories/GHSA-pq7m-3gw7-gq5x)\n\n",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-m678-f26j-3hrp",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2022-39286",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/jupyter/jupyter_core/security/advisories/GHSA-m678-f26j-3hrp"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-39286"
                },
                {
                    "url": "https://github.com/jupyter/jupyter_core/commit/1118c8ce01800cb689d51f655f5ccef19516e283"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/jupyter-core/PYSEC-2022-42974.yaml"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2022/11/msg00022.html"
                },
                {
                    "url": "https://security.gentoo.org/glsa/202301-04"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KKMP5OXXIX2QAUNVNJZ5UEQFKDYYJVBA/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YIDN7JMLK6AOMBQI4QPSW4MBQGWQ5NIN/"
                },
                {
                    "url": "https://www.debian.org/security/2023/dsa-5422"
                },
                {
                    "url": "https://github.com/advisories/GHSA-m678-f26j-3hrp"
                }
            ],
            "published_at": "2022-10-26T22:07:00Z",
            "updated_at": "2023-09-02T05:06:18Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "jupyter-core"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 4.11.2",
                    "first_patched_version": {
                        "identifier": "4.11.2"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
                "score": 8.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-250",
                    "name": "Execution with Unnecessary Privileges"
                },
                {
                    "cwe_id": "CWE-269",
                    "name": "Improper Privilege Management"
                },
                {
                    "cwe_id": "CWE-427",
                    "name": "Uncontrolled Search Path Element"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "jupyter-core"
            },
            "severity": "high",
            "vulnerable_version_range": "< 4.11.2",
            "first_patched_version": {
                "identifier": "4.11.2"
            }
        },
        "url": "https://api.github.com/repos/fcas/transformers/dependabot/alerts/47",
        "html_url": "https://github.com/fcas/transformers/security/dependabot/47",
        "created_at": "2024-05-16T23:41:37Z",
        "updated_at": "2024-05-16T23:41:37Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 46,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "transformers"
            },
            "manifest_path": "examples/research_projects/pplm/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-37q5-v5qm-c9v8",
            "cve_id": "CVE-2024-3568",
            "summary": "Transformers Deserialization of Untrusted Data vulnerability",
            "description": "The huggingface/transformers library is vulnerable to arbitrary code execution through deserialization of untrusted data within the `load_repo_checkpoint()` function of the `TFPreTrainedModel()` class. Attackers can execute arbitrary code and commands by crafting a malicious serialized payload, exploiting the use of `pickle.load()` on data from potentially untrusted sources. This vulnerability allows for remote code execution (RCE) by deceiving victims into loading a seemingly harmless checkpoint during a normal training process, thereby enabling attackers to execute arbitrary code on the targeted machine.",
            "severity": "low",
            "identifiers": [
                {
                    "value": "GHSA-37q5-v5qm-c9v8",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-3568",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-3568"
                },
                {
                    "url": "https://github.com/huggingface/transformers/commit/693667b8ac8138b83f8adb6522ddaf42fa07c125"
                },
                {
                    "url": "https://huntr.com/bounties/b3c36992-5264-4d7f-9906-a996efafba8f"
                },
                {
                    "url": "https://github.com/advisories/GHSA-37q5-v5qm-c9v8"
                }
            ],
            "published_at": "2024-04-10T18:30:48Z",
            "updated_at": "2024-04-10T22:20:57Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "transformers"
                    },
                    "severity": "low",
                    "vulnerable_version_range": "< 4.38.0",
                    "first_patched_version": {
                        "identifier": "4.38.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.0/AV:N/AC:H/PR:N/UI:R/S:C/C:N/I:N/A:L",
                "score": 3.4
            },
            "cwes": [
                {
                    "cwe_id": "CWE-502",
                    "name": "Deserialization of Untrusted Data"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "transformers"
            },
            "severity": "low",
            "vulnerable_version_range": "< 4.38.0",
            "first_patched_version": {
                "identifier": "4.38.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/transformers/dependabot/alerts/46",
        "html_url": "https://github.com/fcas/transformers/security/dependabot/46",
        "created_at": "2024-05-16T23:41:37Z",
        "updated_at": "2024-05-16T23:41:37Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 45,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "transformers"
            },
            "manifest_path": "examples/research_projects/pplm/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-3863-2447-669p",
            "cve_id": "CVE-2023-6730",
            "summary": "transformers has a Deserialization of Untrusted Data vulnerability",
            "description": "Deserialization of Untrusted Data in GitHub repository huggingface/transformers prior to 4.36.0.",
            "severity": "critical",
            "identifiers": [
                {
                    "value": "GHSA-3863-2447-669p",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-6730",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-6730"
                },
                {
                    "url": "https://github.com/huggingface/transformers/commit/1d63b0ec361e7a38f1339385e8a5a855085532ce"
                },
                {
                    "url": "https://huntr.com/bounties/423611ee-7a2a-442a-babb-3ed2f8385c16"
                },
                {
                    "url": "https://github.com/advisories/GHSA-3863-2447-669p"
                }
            ],
            "published_at": "2023-12-19T15:30:30Z",
            "updated_at": "2023-12-28T05:05:45Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "transformers"
                    },
                    "severity": "critical",
                    "vulnerable_version_range": "< 4.36.0",
                    "first_patched_version": {
                        "identifier": "4.36.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.0/AV:N/AC:L/PR:L/UI:R/S:C/C:H/I:H/A:H",
                "score": 9.0
            },
            "cwes": [
                {
                    "cwe_id": "CWE-502",
                    "name": "Deserialization of Untrusted Data"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "transformers"
            },
            "severity": "critical",
            "vulnerable_version_range": "< 4.36.0",
            "first_patched_version": {
                "identifier": "4.36.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/transformers/dependabot/alerts/45",
        "html_url": "https://github.com/fcas/transformers/security/dependabot/45",
        "created_at": "2024-05-16T23:41:37Z",
        "updated_at": "2024-05-16T23:41:37Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 44,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "transformers"
            },
            "manifest_path": "examples/research_projects/pplm/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-v68g-wm8c-6x7j",
            "cve_id": "CVE-2023-7018",
            "summary": "transformers has a Deserialization of Untrusted Data vulnerability",
            "description": "Deserialization of Untrusted Data in GitHub repository huggingface/transformers prior to 4.36.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-v68g-wm8c-6x7j",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-7018",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-7018"
                },
                {
                    "url": "https://github.com/huggingface/transformers/commit/1d63b0ec361e7a38f1339385e8a5a855085532ce"
                },
                {
                    "url": "https://huntr.com/bounties/e1a3e548-e53a-48df-b708-9ee62140963c"
                },
                {
                    "url": "https://github.com/advisories/GHSA-v68g-wm8c-6x7j"
                }
            ],
            "published_at": "2023-12-20T18:30:32Z",
            "updated_at": "2024-01-02T15:27:26Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "transformers"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 4.36.0",
                    "first_patched_version": {
                        "identifier": "4.36.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
                "score": 7.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-502",
                    "name": "Deserialization of Untrusted Data"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "transformers"
            },
            "severity": "high",
            "vulnerable_version_range": "< 4.36.0",
            "first_patched_version": {
                "identifier": "4.36.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/transformers/dependabot/alerts/44",
        "html_url": "https://github.com/fcas/transformers/security/dependabot/44",
        "created_at": "2024-05-16T23:41:37Z",
        "updated_at": "2024-05-16T23:41:37Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 43,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "transformers"
            },
            "manifest_path": "examples/research_projects/pplm/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-282v-666c-3fvg",
            "cve_id": "CVE-2023-2800",
            "summary": "transformers has Insecure Temporary File",
            "description": "Insecure Temporary File in GitHub repository huggingface/transformers 4.29.2 and prior. A fix is available at commit 80ca92470938bbcc348e2d9cf4734c7c25cb1c43 and has been released as part of version 4.30.0.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-282v-666c-3fvg",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-2800",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-2800"
                },
                {
                    "url": "https://github.com/huggingface/transformers/commit/80ca92470938bbcc348e2d9cf4734c7c25cb1c43"
                },
                {
                    "url": "https://huntr.dev/bounties/a3867b4e-6701-4418-8c20-3c6e7084a44a"
                },
                {
                    "url": "https://github.com/huggingface/transformers/pull/23372"
                },
                {
                    "url": "https://github.com/advisories/GHSA-282v-666c-3fvg"
                }
            ],
            "published_at": "2023-05-18T18:30:35Z",
            "updated_at": "2023-11-09T05:05:04Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "transformers"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 4.30.0",
                    "first_patched_version": {
                        "identifier": "4.30.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:U/C:N/I:N/A:H",
                "score": 4.7
            },
            "cwes": [
                {
                    "cwe_id": "CWE-377",
                    "name": "Insecure Temporary File"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "transformers"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 4.30.0",
            "first_patched_version": {
                "identifier": "4.30.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/transformers/dependabot/alerts/43",
        "html_url": "https://github.com/fcas/transformers/security/dependabot/43",
        "created_at": "2024-05-16T23:41:37Z",
        "updated_at": "2024-05-16T23:41:37Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 42,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "idna"
            },
            "manifest_path": "examples/research_projects/lxmert/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-jjg7-2v4v-x38h",
            "cve_id": "CVE-2024-3651",
            "summary": "Internationalized Domain Names in Applications (IDNA) vulnerable to denial of service from specially crafted inputs to idna.encode",
            "description": "### Impact\nA specially crafted argument to the `idna.encode()` function could consume significant resources. This may lead to a denial-of-service.\n\n### Patches\nThe function has been refined to reject such strings without the associated resource consumption in version 3.7.\n\n### Workarounds\nDomain names cannot exceed 253 characters in length, if this length limit is enforced prior to passing the domain to the `idna.encode()` function it should no longer consume significant resources. This is triggered by arbitrarily large inputs that would not occur in normal usage, but may be passed to the library assuming there is no preliminary input validation by the higher-level application.\n\n### References\n* https://huntr.com/bounties/93d78d07-d791-4b39-a845-cbfabc44aadb",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-jjg7-2v4v-x38h",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-3651",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/kjd/idna/security/advisories/GHSA-jjg7-2v4v-x38h"
                },
                {
                    "url": "https://github.com/advisories/GHSA-jjg7-2v4v-x38h"
                }
            ],
            "published_at": "2024-04-11T21:32:40Z",
            "updated_at": "2024-04-11T21:32:40Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "idna"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 3.7",
                    "first_patched_version": {
                        "identifier": "3.7"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 6.2
            },
            "cwes": [
                {
                    "cwe_id": "CWE-400",
                    "name": "Uncontrolled Resource Consumption"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "idna"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 3.7",
            "first_patched_version": {
                "identifier": "3.7"
            }
        },
        "url": "https://api.github.com/repos/fcas/transformers/dependabot/alerts/42",
        "html_url": "https://github.com/fcas/transformers/security/dependabot/42",
        "created_at": "2024-05-16T23:41:37Z",
        "updated_at": "2024-05-16T23:41:37Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 41,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "jupyter-core"
            },
            "manifest_path": "examples/research_projects/lxmert/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-m678-f26j-3hrp",
            "cve_id": "CVE-2022-39286",
            "summary": "Execution with Unnecessary Privileges in JupyterApp",
            "description": "### Impact\n_What kind of vulnerability is it? Who is impacted?_\nWe’d like to disclose an arbitrary code execution vulnerability in `jupyter_core` that stems from `jupyter_core` executing untrusted files in the current working directory. This vulnerability allows one user to run code as another.\n\n\n### Patches\n_Has the problem been patched? What versions should users upgrade to?_\nUsers should upgrade to `jupyter_core>=4.11.2`.\n\n### Workarounds\n_Is there a way for users to fix or remediate the vulnerability without upgrading?_\nNo\n\n### References\n_Are there any links users can visit to find out more?_\nSimilar advisory in [IPython](https://github.com/advisories/GHSA-pq7m-3gw7-gq5x)\n\n",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-m678-f26j-3hrp",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2022-39286",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/jupyter/jupyter_core/security/advisories/GHSA-m678-f26j-3hrp"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-39286"
                },
                {
                    "url": "https://github.com/jupyter/jupyter_core/commit/1118c8ce01800cb689d51f655f5ccef19516e283"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/jupyter-core/PYSEC-2022-42974.yaml"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2022/11/msg00022.html"
                },
                {
                    "url": "https://security.gentoo.org/glsa/202301-04"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KKMP5OXXIX2QAUNVNJZ5UEQFKDYYJVBA/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YIDN7JMLK6AOMBQI4QPSW4MBQGWQ5NIN/"
                },
                {
                    "url": "https://www.debian.org/security/2023/dsa-5422"
                },
                {
                    "url": "https://github.com/advisories/GHSA-m678-f26j-3hrp"
                }
            ],
            "published_at": "2022-10-26T22:07:00Z",
            "updated_at": "2023-09-02T05:06:18Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "jupyter-core"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 4.11.2",
                    "first_patched_version": {
                        "identifier": "4.11.2"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
                "score": 8.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-250",
                    "name": "Execution with Unnecessary Privileges"
                },
                {
                    "cwe_id": "CWE-269",
                    "name": "Improper Privilege Management"
                },
                {
                    "cwe_id": "CWE-427",
                    "name": "Uncontrolled Search Path Element"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "jupyter-core"
            },
            "severity": "high",
            "vulnerable_version_range": "< 4.11.2",
            "first_patched_version": {
                "identifier": "4.11.2"
            }
        },
        "url": "https://api.github.com/repos/fcas/transformers/dependabot/alerts/41",
        "html_url": "https://github.com/fcas/transformers/security/dependabot/41",
        "created_at": "2024-05-16T23:41:37Z",
        "updated_at": "2024-05-16T23:41:37Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 40,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "transformers"
            },
            "manifest_path": "examples/research_projects/deebert/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-37q5-v5qm-c9v8",
            "cve_id": "CVE-2024-3568",
            "summary": "Transformers Deserialization of Untrusted Data vulnerability",
            "description": "The huggingface/transformers library is vulnerable to arbitrary code execution through deserialization of untrusted data within the `load_repo_checkpoint()` function of the `TFPreTrainedModel()` class. Attackers can execute arbitrary code and commands by crafting a malicious serialized payload, exploiting the use of `pickle.load()` on data from potentially untrusted sources. This vulnerability allows for remote code execution (RCE) by deceiving victims into loading a seemingly harmless checkpoint during a normal training process, thereby enabling attackers to execute arbitrary code on the targeted machine.",
            "severity": "low",
            "identifiers": [
                {
                    "value": "GHSA-37q5-v5qm-c9v8",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-3568",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-3568"
                },
                {
                    "url": "https://github.com/huggingface/transformers/commit/693667b8ac8138b83f8adb6522ddaf42fa07c125"
                },
                {
                    "url": "https://huntr.com/bounties/b3c36992-5264-4d7f-9906-a996efafba8f"
                },
                {
                    "url": "https://github.com/advisories/GHSA-37q5-v5qm-c9v8"
                }
            ],
            "published_at": "2024-04-10T18:30:48Z",
            "updated_at": "2024-04-10T22:20:57Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "transformers"
                    },
                    "severity": "low",
                    "vulnerable_version_range": "< 4.38.0",
                    "first_patched_version": {
                        "identifier": "4.38.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.0/AV:N/AC:H/PR:N/UI:R/S:C/C:N/I:N/A:L",
                "score": 3.4
            },
            "cwes": [
                {
                    "cwe_id": "CWE-502",
                    "name": "Deserialization of Untrusted Data"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "transformers"
            },
            "severity": "low",
            "vulnerable_version_range": "< 4.38.0",
            "first_patched_version": {
                "identifier": "4.38.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/transformers/dependabot/alerts/40",
        "html_url": "https://github.com/fcas/transformers/security/dependabot/40",
        "created_at": "2024-05-16T23:41:37Z",
        "updated_at": "2024-05-16T23:41:37Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 39,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "transformers"
            },
            "manifest_path": "examples/research_projects/deebert/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-3863-2447-669p",
            "cve_id": "CVE-2023-6730",
            "summary": "transformers has a Deserialization of Untrusted Data vulnerability",
            "description": "Deserialization of Untrusted Data in GitHub repository huggingface/transformers prior to 4.36.0.",
            "severity": "critical",
            "identifiers": [
                {
                    "value": "GHSA-3863-2447-669p",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-6730",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-6730"
                },
                {
                    "url": "https://github.com/huggingface/transformers/commit/1d63b0ec361e7a38f1339385e8a5a855085532ce"
                },
                {
                    "url": "https://huntr.com/bounties/423611ee-7a2a-442a-babb-3ed2f8385c16"
                },
                {
                    "url": "https://github.com/advisories/GHSA-3863-2447-669p"
                }
            ],
            "published_at": "2023-12-19T15:30:30Z",
            "updated_at": "2023-12-28T05:05:45Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "transformers"
                    },
                    "severity": "critical",
                    "vulnerable_version_range": "< 4.36.0",
                    "first_patched_version": {
                        "identifier": "4.36.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.0/AV:N/AC:L/PR:L/UI:R/S:C/C:H/I:H/A:H",
                "score": 9.0
            },
            "cwes": [
                {
                    "cwe_id": "CWE-502",
                    "name": "Deserialization of Untrusted Data"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "transformers"
            },
            "severity": "critical",
            "vulnerable_version_range": "< 4.36.0",
            "first_patched_version": {
                "identifier": "4.36.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/transformers/dependabot/alerts/39",
        "html_url": "https://github.com/fcas/transformers/security/dependabot/39",
        "created_at": "2024-05-16T23:41:36Z",
        "updated_at": "2024-05-16T23:41:36Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 38,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "transformers"
            },
            "manifest_path": "examples/research_projects/deebert/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-v68g-wm8c-6x7j",
            "cve_id": "CVE-2023-7018",
            "summary": "transformers has a Deserialization of Untrusted Data vulnerability",
            "description": "Deserialization of Untrusted Data in GitHub repository huggingface/transformers prior to 4.36.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-v68g-wm8c-6x7j",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-7018",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-7018"
                },
                {
                    "url": "https://github.com/huggingface/transformers/commit/1d63b0ec361e7a38f1339385e8a5a855085532ce"
                },
                {
                    "url": "https://huntr.com/bounties/e1a3e548-e53a-48df-b708-9ee62140963c"
                },
                {
                    "url": "https://github.com/advisories/GHSA-v68g-wm8c-6x7j"
                }
            ],
            "published_at": "2023-12-20T18:30:32Z",
            "updated_at": "2024-01-02T15:27:26Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "transformers"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 4.36.0",
                    "first_patched_version": {
                        "identifier": "4.36.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
                "score": 7.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-502",
                    "name": "Deserialization of Untrusted Data"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "transformers"
            },
            "severity": "high",
            "vulnerable_version_range": "< 4.36.0",
            "first_patched_version": {
                "identifier": "4.36.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/transformers/dependabot/alerts/38",
        "html_url": "https://github.com/fcas/transformers/security/dependabot/38",
        "created_at": "2024-05-16T23:41:36Z",
        "updated_at": "2024-05-16T23:41:36Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 37,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "transformers"
            },
            "manifest_path": "examples/research_projects/deebert/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-282v-666c-3fvg",
            "cve_id": "CVE-2023-2800",
            "summary": "transformers has Insecure Temporary File",
            "description": "Insecure Temporary File in GitHub repository huggingface/transformers 4.29.2 and prior. A fix is available at commit 80ca92470938bbcc348e2d9cf4734c7c25cb1c43 and has been released as part of version 4.30.0.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-282v-666c-3fvg",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-2800",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-2800"
                },
                {
                    "url": "https://github.com/huggingface/transformers/commit/80ca92470938bbcc348e2d9cf4734c7c25cb1c43"
                },
                {
                    "url": "https://huntr.dev/bounties/a3867b4e-6701-4418-8c20-3c6e7084a44a"
                },
                {
                    "url": "https://github.com/huggingface/transformers/pull/23372"
                },
                {
                    "url": "https://github.com/advisories/GHSA-282v-666c-3fvg"
                }
            ],
            "published_at": "2023-05-18T18:30:35Z",
            "updated_at": "2023-11-09T05:05:04Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "transformers"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 4.30.0",
                    "first_patched_version": {
                        "identifier": "4.30.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:U/C:N/I:N/A:H",
                "score": 4.7
            },
            "cwes": [
                {
                    "cwe_id": "CWE-377",
                    "name": "Insecure Temporary File"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "transformers"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 4.30.0",
            "first_patched_version": {
                "identifier": "4.30.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/transformers/dependabot/alerts/37",
        "html_url": "https://github.com/fcas/transformers/security/dependabot/37",
        "created_at": "2024-05-16T23:41:36Z",
        "updated_at": "2024-05-16T23:41:36Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 36,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "aiohttp"
            },
            "manifest_path": "examples/research_projects/decision_transformer/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-5m98-qgg9-wh84",
            "cve_id": "CVE-2024-30251",
            "summary": "aiohttp vulnerable to Denial of Service when trying to parse malformed POST requests",
            "description": "### Summary\nAn attacker can send a specially crafted POST (multipart/form-data) request. When the aiohttp server processes it, the server will enter an infinite loop and be unable to process any further requests.\n\n### Impact\nAn attacker can stop the application from serving requests after sending a single request.\n\n-------\n\nFor anyone needing to patch older versions of aiohttp, the minimum diff needed to resolve the issue is (located in `_read_chunk_from_length()`):\n\n```diff\ndiff --git a/aiohttp/multipart.py b/aiohttp/multipart.py\nindex 227be605c..71fc2654a 100644\n--- a/aiohttp/multipart.py\n+++ b/aiohttp/multipart.py\n@@ -338,6 +338,8 @@ class BodyPartReader:\n         assert self._length is not None, \"Content-Length required for chunked read\"\n         chunk_size = min(size, self._length - self._read_bytes)\n         chunk = await self._content.read(chunk_size)\n+        if self._content.at_eof():\n+            self._at_eof = True\n         return chunk\n \n     async def _read_chunk_from_stream(self, size: int) -> bytes:\n```\n\nThis does however introduce some very minor issues with handling form data. So, if possible, it would be recommended to also backport the changes in:\nhttps://github.com/aio-libs/aiohttp/commit/cebe526b9c34dc3a3da9140409db63014bc4cf19\nhttps://github.com/aio-libs/aiohttp/commit/7eecdff163ccf029fbb1ddc9de4169d4aaeb6597\nhttps://github.com/aio-libs/aiohttp/commit/f21c6f2ca512a026ce7f0f6c6311f62d6a638866",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-5m98-qgg9-wh84",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-30251",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/aio-libs/aiohttp/security/advisories/GHSA-5m98-qgg9-wh84"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-30251"
                },
                {
                    "url": "https://github.com/aio-libs/aiohttp/commit/7eecdff163ccf029fbb1ddc9de4169d4aaeb6597"
                },
                {
                    "url": "https://github.com/aio-libs/aiohttp/commit/cebe526b9c34dc3a3da9140409db63014bc4cf19"
                },
                {
                    "url": "https://github.com/aio-libs/aiohttp/commit/f21c6f2ca512a026ce7f0f6c6311f62d6a638866"
                },
                {
                    "url": "http://www.openwall.com/lists/oss-security/2024/05/02/4"
                },
                {
                    "url": "https://github.com/advisories/GHSA-5m98-qgg9-wh84"
                }
            ],
            "published_at": "2024-05-03T17:29:54Z",
            "updated_at": "2024-05-03T17:30:09Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "aiohttp"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 3.9.4",
                    "first_patched_version": {
                        "identifier": "3.9.4"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-835",
                    "name": "Loop with Unreachable Exit Condition ('Infinite Loop')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "aiohttp"
            },
            "severity": "high",
            "vulnerable_version_range": "< 3.9.4",
            "first_patched_version": {
                "identifier": "3.9.4"
            }
        },
        "url": "https://api.github.com/repos/fcas/transformers/dependabot/alerts/36",
        "html_url": "https://github.com/fcas/transformers/security/dependabot/36",
        "created_at": "2024-05-16T23:41:36Z",
        "updated_at": "2024-05-16T23:41:36Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 35,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "aiohttp"
            },
            "manifest_path": "examples/research_projects/decision_transformer/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-7gpw-8wmc-pm8g",
            "cve_id": "CVE-2024-27306",
            "summary": "aiohttp Cross-site Scripting vulnerability on index pages for static file handling",
            "description": "### Summary\n\nA XSS vulnerability exists on index pages for static file handling.\n\n### Details\n\nWhen using `web.static(..., show_index=True)`, the resulting index pages do not escape file names.\n\nIf users can upload files with arbitrary filenames to the static directory, the server is vulnerable to XSS attacks.\n\n### Workaround\n\nWe have always recommended using a reverse proxy server (e.g. nginx) for serving static files. Users following the recommendation are unaffected.\n\nOther users can disable `show_index` if unable to upgrade.\n\n-----\n\nPatch: https://github.com/aio-libs/aiohttp/pull/8319/files",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-7gpw-8wmc-pm8g",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-27306",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/aio-libs/aiohttp/security/advisories/GHSA-7gpw-8wmc-pm8g"
                },
                {
                    "url": "https://github.com/aio-libs/aiohttp/pull/8319/files"
                },
                {
                    "url": "https://github.com/aio-libs/aiohttp/commit/28335525d1eac015a7e7584137678cbb6ff19397"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-27306"
                },
                {
                    "url": "https://github.com/aio-libs/aiohttp/pull/8319"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/2EXRGTN2WG7VZLUZ7WOXU5GQJKCPPHKP"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NWEI6NIHZ3G7DURDZVMRK7ZEFC2BTD3U"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZIVBMPEY7WWOFMC3CWXFBRQPFECV4SW3"
                },
                {
                    "url": "https://github.com/advisories/GHSA-7gpw-8wmc-pm8g"
                }
            ],
            "published_at": "2024-04-18T13:45:21Z",
            "updated_at": "2024-05-02T03:30:33Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "aiohttp"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 3.9.4",
                    "first_patched_version": {
                        "identifier": "3.9.4"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
                "score": 6.1
            },
            "cwes": [
                {
                    "cwe_id": "CWE-79",
                    "name": "Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "aiohttp"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 3.9.4",
            "first_patched_version": {
                "identifier": "3.9.4"
            }
        },
        "url": "https://api.github.com/repos/fcas/transformers/dependabot/alerts/35",
        "html_url": "https://github.com/fcas/transformers/security/dependabot/35",
        "created_at": "2024-05-16T23:41:36Z",
        "updated_at": "2024-05-16T23:41:36Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 34,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "idna"
            },
            "manifest_path": "examples/research_projects/decision_transformer/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-jjg7-2v4v-x38h",
            "cve_id": "CVE-2024-3651",
            "summary": "Internationalized Domain Names in Applications (IDNA) vulnerable to denial of service from specially crafted inputs to idna.encode",
            "description": "### Impact\nA specially crafted argument to the `idna.encode()` function could consume significant resources. This may lead to a denial-of-service.\n\n### Patches\nThe function has been refined to reject such strings without the associated resource consumption in version 3.7.\n\n### Workarounds\nDomain names cannot exceed 253 characters in length, if this length limit is enforced prior to passing the domain to the `idna.encode()` function it should no longer consume significant resources. This is triggered by arbitrarily large inputs that would not occur in normal usage, but may be passed to the library assuming there is no preliminary input validation by the higher-level application.\n\n### References\n* https://huntr.com/bounties/93d78d07-d791-4b39-a845-cbfabc44aadb",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-jjg7-2v4v-x38h",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-3651",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/kjd/idna/security/advisories/GHSA-jjg7-2v4v-x38h"
                },
                {
                    "url": "https://github.com/advisories/GHSA-jjg7-2v4v-x38h"
                }
            ],
            "published_at": "2024-04-11T21:32:40Z",
            "updated_at": "2024-04-11T21:32:40Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "idna"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 3.7",
                    "first_patched_version": {
                        "identifier": "3.7"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 6.2
            },
            "cwes": [
                {
                    "cwe_id": "CWE-400",
                    "name": "Uncontrolled Resource Consumption"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "idna"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 3.7",
            "first_patched_version": {
                "identifier": "3.7"
            }
        },
        "url": "https://api.github.com/repos/fcas/transformers/dependabot/alerts/34",
        "html_url": "https://github.com/fcas/transformers/security/dependabot/34",
        "created_at": "2024-05-16T23:41:36Z",
        "updated_at": "2024-05-16T23:41:36Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 33,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "pillow"
            },
            "manifest_path": "examples/research_projects/decision_transformer/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-44wm-f244-xhp3",
            "cve_id": "CVE-2024-28219",
            "summary": "Pillow buffer overflow vulnerability",
            "description": "In _imagingcms.c in Pillow before 10.3.0, a buffer overflow exists because strcpy is used instead of strncpy.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-44wm-f244-xhp3",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-28219",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-28219"
                },
                {
                    "url": "https://pillow.readthedocs.io/en/stable/releasenotes/10.3.0.html#security"
                },
                {
                    "url": "https://github.com/python-pillow/Pillow/commit/2a93aba5cfcf6e241ab4f9392c13e3b74032c061"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2024/04/msg00008.html"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/4XLPUT3VK4GQ6EVY525TT2QNUIXNRU5M"
                },
                {
                    "url": "https://github.com/advisories/GHSA-44wm-f244-xhp3"
                }
            ],
            "published_at": "2024-04-03T03:30:30Z",
            "updated_at": "2024-04-20T05:06:18Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "pillow"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 10.3.0",
                    "first_patched_version": {
                        "identifier": "10.3.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:H/PR:L/UI:R/S:U/C:H/I:H/A:H",
                "score": 6.7
            },
            "cwes": [
                {
                    "cwe_id": "CWE-120",
                    "name": "Buffer Copy without Checking Size of Input ('Classic Buffer Overflow')"
                },
                {
                    "cwe_id": "CWE-676",
                    "name": "Use of Potentially Dangerous Function"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "pillow"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 10.3.0",
            "first_patched_version": {
                "identifier": "10.3.0"
            }
        },
        "url": "https://api.github.com/repos/fcas/transformers/dependabot/alerts/33",
        "html_url": "https://github.com/fcas/transformers/security/dependabot/33",
        "created_at": "2024-05-16T23:41:36Z",
        "updated_at": "2024-05-16T23:41:36Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 32,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "cryptography"
            },
            "manifest_path": "examples/research_projects/decision_transformer/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-6vqw-3v5j-54x4",
            "cve_id": "CVE-2024-26130",
            "summary": "cryptography NULL pointer dereference with pkcs12.serialize_key_and_certificates when called with a non-matching certificate and private key and an hmac_hash override",
            "description": "If `pkcs12.serialize_key_and_certificates` is called with both:\n\n1. A certificate whose public key did not match the provided private key\n2. An `encryption_algorithm` with `hmac_hash` set (via `PrivateFormat.PKCS12.encryption_builder().hmac_hash(...)`\n\nThen a NULL pointer dereference would occur, crashing the Python process.\n\nThis has been resolved, and now a `ValueError` is properly raised.\n\nPatched in https://github.com/pyca/cryptography/pull/10423",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-6vqw-3v5j-54x4",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-26130",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/pyca/cryptography/security/advisories/GHSA-6vqw-3v5j-54x4"
                },
                {
                    "url": "https://github.com/pyca/cryptography/pull/10423"
                },
                {
                    "url": "https://github.com/pyca/cryptography/commit/97d231672763cdb5959a3b191e692a362f1b9e55"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-26130"
                },
                {
                    "url": "https://github.com/advisories/GHSA-6vqw-3v5j-54x4"
                }
            ],
            "published_at": "2024-02-21T18:04:40Z",
            "updated_at": "2024-02-21T22:45:35Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "cryptography"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 38.0.0, < 42.0.4",
                    "first_patched_version": {
                        "identifier": "42.0.4"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-476",
                    "name": "NULL Pointer Dereference"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "cryptography"
            },
            "severity": "high",
            "vulnerable_version_range": ">= 38.0.0, < 42.0.4",
            "first_patched_version": {
                "identifier": "42.0.4"
            }
        },
        "url": "https://api.github.com/repos/fcas/transformers/dependabot/alerts/32",
        "html_url": "https://github.com/fcas/transformers/security/dependabot/32",
        "created_at": "2024-05-16T23:41:36Z",
        "updated_at": "2024-05-16T23:41:36Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 31,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "cryptography"
            },
            "manifest_path": "examples/research_projects/decision_transformer/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-9v9h-cgj8-h64p",
            "cve_id": "CVE-2024-0727",
            "summary": "Null pointer dereference in PKCS12 parsing",
            "description": "Issue summary: Processing a maliciously formatted PKCS12 file may lead OpenSSL\nto crash leading to a potential Denial of Service attack\n\nImpact summary: Applications loading files in the PKCS12 format from untrusted\nsources might terminate abruptly.\n\nA file in PKCS12 format can contain certificates and keys and may come from an\nuntrusted source. The PKCS12 specification allows certain fields to be NULL, but\nOpenSSL does not correctly check for this case. This can lead to a NULL pointer\ndereference that results in OpenSSL crashing. If an application processes PKCS12\nfiles from an untrusted source using the OpenSSL APIs then that application will\nbe vulnerable to this issue.\n\nOpenSSL APIs that are vulnerable to this are: PKCS12_parse(),\nPKCS12_unpack_p7data(), PKCS12_unpack_p7encdata(), PKCS12_unpack_authsafes()\nand PKCS12_newpass().\n\nWe have also fixed a similar issue in SMIME_write_PKCS7(). However since this\nfunction is related to writing data we do not consider it security significant.\n\nThe FIPS modules in 3.2, 3.1 and 3.0 are not affected by this issue.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-9v9h-cgj8-h64p",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-0727",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-0727"
                },
                {
                    "url": "https://github.com/openssl/openssl/commit/09df4395b5071217b76dc7d3d2e630eb8c5a79c2"
                },
                {
                    "url": "https://github.com/openssl/openssl/commit/775acfdbd0c6af9ac855f34969cdab0c0c90844a"
                },
                {
                    "url": "https://github.com/openssl/openssl/commit/d135eeab8a5dbf72b3da5240bab9ddb7678dbd2c"
                },
                {
                    "url": "https://github.openssl.org/openssl/extended-releases/commit/03b3941d60c4bce58fab69a0c22377ab439bc0e8"
                },
                {
                    "url": "https://github.openssl.org/openssl/extended-releases/commit/aebaa5883e31122b404e450732dc833dc9dee539"
                },
                {
                    "url": "https://www.openssl.org/news/secadv/20240125.txt"
                },
                {
                    "url": "https://github.com/github/advisory-database/pull/3472"
                },
                {
                    "url": "https://github.com/openssl/openssl/pull/23362"
                },
                {
                    "url": "https://github.com/alexcrichton/openssl-src-rs/commit/add20f73b6b42be7451af2e1044d4e0e778992b2"
                },
                {
                    "url": "https://github.com/pyca/cryptography/commit/3519591d255d4506fbcd0d04037d45271903c64d"
                },
                {
                    "url": "https://security.netapp.com/advisory/ntap-20240208-0006"
                },
                {
                    "url": "http://www.openwall.com/lists/oss-security/2024/03/11/1"
                },
                {
                    "url": "https://github.com/advisories/GHSA-9v9h-cgj8-h64p"
                }
            ],
            "published_at": "2024-01-26T09:30:23Z",
            "updated_at": "2024-05-12T05:03:47Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "cryptography"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 42.0.2",
                    "first_patched_version": {
                        "identifier": "42.0.2"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
                "score": 5.5
            },
            "cwes": []
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "cryptography"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 42.0.2",
            "first_patched_version": {
                "identifier": "42.0.2"
            }
        },
        "url": "https://api.github.com/repos/fcas/transformers/dependabot/alerts/31",
        "html_url": "https://github.com/fcas/transformers/security/dependabot/31",
        "created_at": "2024-05-16T23:41:36Z",
        "updated_at": "2024-05-16T23:41:36Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 30,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "aiohttp"
            },
            "manifest_path": "examples/research_projects/decision_transformer/requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-5h86-8mv2-jq9f",
            "cve_id": "CVE-2024-23334",
            "summary": "aiohttp is vulnerable to directory traversal",
            "description": "### Summary\nImproperly configuring static resource resolution in aiohttp when used as a web server can result in the unauthorized reading of arbitrary files on the system.\n\n### Details\nWhen using aiohttp as a web server and configuring static routes, it is necessary to specify the root path for static files. Additionally, the option 'follow_symlinks' can be used to determine whether to follow symbolic links outside the static root directory. When 'follow_symlinks' is set to True, there is no validation to check if a given file path is within the root directory.This can lead to directory traversal vulnerabilities, resulting in unauthorized access to arbitrary files on the system, even when symlinks are not present.\n\ni.e. An application is only vulnerable with setup code like:\n```\napp.router.add_routes([\n    web.static(\"/static\", \"static/\", follow_symlinks=True),  # Remove follow_symlinks to avoid the vulnerability\n])\n```\n\n### Impact\nThis is a directory traversal vulnerability with CWE ID 22. When using aiohttp as a web server and enabling static resource resolution with `follow_symlinks` set to True, it can lead to this vulnerability. This vulnerability has been present since the introduction of the `follow_symlinks` parameter.\n\n### Workaround\nEven if upgrading to a patched version of aiohttp, we recommend following these steps regardless.\n\nIf using `follow_symlinks=True` outside of a restricted local development environment, disable the option immediately. This option is NOT needed to follow symlinks which point to a location _within_ the static root directory, it is _only_ intended to allow a symlink to break out of the static directory. Even with this CVE fixed, there is still a substantial risk of misconfiguration when using this option on a server that accepts requests from remote users.\n\nAdditionally, aiohttp has always recommended using a reverse proxy server (such as nginx) to handle static resources and _not_ to use these static resources in aiohttp for production environments. Doing so also protects against this vulnerability, and is why we expect the number of affected users to be very low.\n\n-----\n\nPatch: https://github.com/aio-libs/aiohttp/pull/8079/files",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-5h86-8mv2-jq9f",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-23334",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/aio-libs/aiohttp/security/advisories/GHSA-5h86-8mv2-jq9f"
                },
                {
                    "url": "https://github.com/aio-libs/aiohttp/pull/8079/files"
                },
                {
                    "url": "https://github.com/aio-libs/aiohttp/commit/1c335944d6a8b1298baf179b7c0b3069f10c514b"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-23334"
                },
                {
                    "url": "https://github.com/aio-libs/aiohttp/pull/8079"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/aiohttp/PYSEC-2024-24.yaml"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XXWVZIVAYWEBHNRIILZVB3R3SDQNNAA7/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ICUOCFGTB25WUT336BZ4UNYLSZOUVKBD/"
                },
                {
                    "url": "https://github.com/advisories/GHSA-5h86-8mv2-jq9f"
                }
            ],
            "published_at": "2024-01-29T22:31:03Z",
            "updated_at": "2024-02-18T05:08:00Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "aiohttp"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": ">= 1.0.5, < 3.9.2",
                    "first_patched_version": {
                        "identifier": "3.9.2"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N",
                "score": 5.9
            },
            "cwes": [
                {
                    "cwe_id": "CWE-22",
                    "name": "Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "aiohttp"
            },
            "severity": "medium",
            "vulnerable_version_range": ">= 1.0.5, < 3.9.2",
            "first_patched_version": {
                "identifier": "3.9.2"
            }
        },
        "url": "https://api.github.com/repos/fcas/transformers/dependabot/alerts/30",
        "html_url": "https://github.com/fcas/transformers/security/dependabot/30",
        "created_at": "2024-05-16T23:41:35Z",
        "updated_at": "2024-05-16T23:41:35Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    }
]