[
    {
        "number": 3,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "torch"
            },
            "manifest_path": "setup.py",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-5pcm-hx3q-hm94",
            "cve_id": "CVE-2024-31580",
            "summary": "PyTorch heap buffer overflow vulnerability",
            "description": "PyTorch before v2.2.0 was discovered to contain a heap buffer overflow vulnerability in the component /runtime/vararg_functions.cpp. This vulnerability allows attackers to cause a Denial of Service (DoS) via a crafted input.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-5pcm-hx3q-hm94",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-31580",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-31580"
                },
                {
                    "url": "https://github.com/pytorch/pytorch/commit/b5c3a17c2c207ebefcb85043f0cf94be9b2fef81"
                },
                {
                    "url": "https://gist.github.com/1047524396/038c78f2f007345e6f497698ace2aa3d"
                },
                {
                    "url": "https://security.snyk.io/vuln/SNYK-PYTHON-TORCH-6649934"
                },
                {
                    "url": "https://github.com/advisories/GHSA-5pcm-hx3q-hm94"
                }
            ],
            "published_at": "2024-04-17T21:30:48Z",
            "updated_at": "2024-08-04T05:06:42Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "torch"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.2.0",
                    "first_patched_version": {
                        "identifier": "2.2.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cvss_severities": {
                "cvss_v3": {
                    "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                    "score": 7.5
                },
                "cvss_v4": {
                    "vector_string": "CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:N/VA:H/SC:N/SI:N/SA:N",
                    "score": 8.7
                }
            },
            "cwes": [
                {
                    "cwe_id": "CWE-122",
                    "name": "Heap-based Buffer Overflow"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "torch"
            },
            "severity": "high",
            "vulnerable_version_range": "< 2.2.0",
            "first_patched_version": {
                "identifier": "2.2.0"
            }
        },
        "url": "https://api.github.com/repos/username/garage/dependabot/alerts/3",
        "html_url": "https://github.com/username/garage/security/dependabot/3",
        "created_at": "2024-07-25T11:54:07Z",
        "updated_at": "2024-07-25T11:54:07Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 2,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "torch"
            },
            "manifest_path": "setup.py",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-pg7h-5qx3-wjr3",
            "cve_id": "CVE-2024-31583",
            "summary": "Pytorch use-after-free vulnerability",
            "description": "Pytorch before version v2.2.0 was discovered to contain a use-after-free vulnerability in torch/csrc/jit/mobile/interpreter.cpp.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-pg7h-5qx3-wjr3",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-31583",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-31583"
                },
                {
                    "url": "https://github.com/pytorch/pytorch/commit/9c7071b0e324f9fb68ab881283d6b8d388a4bcd2"
                },
                {
                    "url": "https://gist.github.com/1047524396/43e19a41f2b36503a4a228c32cdbc176"
                },
                {
                    "url": "https://github.com/pytorch/pytorch/blob/v2.1.2/torch/csrc/jit/mobile/interpreter.cpp#L132"
                },
                {
                    "url": "https://security.snyk.io/vuln/SNYK-PYTHON-TORCH-6619806"
                },
                {
                    "url": "https://github.com/advisories/GHSA-pg7h-5qx3-wjr3"
                }
            ],
            "published_at": "2024-04-17T21:30:48Z",
            "updated_at": "2024-07-25T10:11:09Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "torch"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.2.0",
                    "first_patched_version": {
                        "identifier": "2.2.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
                "score": 7.8
            },
            "cvss_severities": {
                "cvss_v3": {
                    "vector_string": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
                    "score": 7.8
                },
                "cvss_v4": {
                    "vector_string": null,
                    "score": 0.0
                }
            },
            "cwes": [
                {
                    "cwe_id": "CWE-416",
                    "name": "Use After Free"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "torch"
            },
            "severity": "high",
            "vulnerable_version_range": "< 2.2.0",
            "first_patched_version": {
                "identifier": "2.2.0"
            }
        },
        "url": "https://api.github.com/repos/username/garage/dependabot/alerts/2",
        "html_url": "https://github.com/username/garage/security/dependabot/2",
        "created_at": "2024-07-25T11:53:58Z",
        "updated_at": "2024-07-25T11:53:58Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 1,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "torch"
            },
            "manifest_path": "setup.py",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-47fc-vmwq-366v",
            "cve_id": "CVE-2022-45907",
            "summary": "PyTorch vulnerable to arbitrary code execution",
            "description": "In PyTorch before trunk/89695, torch.jit.annotations.parse_type_line can cause arbitrary code execution because eval is used unsafely. The fix for this issue is available in version 1.13.1. There is a release checker in [issue #89855](https://github.com/pytorch/pytorch/issues/89855).",
            "severity": "critical",
            "identifiers": [
                {
                    "value": "GHSA-47fc-vmwq-366v",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2022-45907",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-45907"
                },
                {
                    "url": "https://github.com/pytorch/pytorch/issues/88868"
                },
                {
                    "url": "https://github.com/pytorch/pytorch/commit/767f6aa49fe20a2766b9843d01e3b7f7793df6a3"
                },
                {
                    "url": "https://github.com/pytorch/pytorch/issues/89855"
                },
                {
                    "url": "https://github.com/pytorch/pytorch/pull/89189"
                },
                {
                    "url": "https://github.com/pytorch/pytorch/releases/tag/v1.13.1"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/torch/PYSEC-2022-43015.yaml"
                },
                {
                    "url": "https://github.com/advisories/GHSA-47fc-vmwq-366v"
                }
            ],
            "published_at": "2022-11-26T03:30:27Z",
            "updated_at": "2024-11-13T22:52:23Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "torch"
                    },
                    "severity": "critical",
                    "vulnerable_version_range": "<= 1.13.0",
                    "first_patched_version": {
                        "identifier": "1.13.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                "score": 9.8
            },
            "cvss_severities": {
                "cvss_v3": {
                    "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                    "score": 9.8
                },
                "cvss_v4": {
                    "vector_string": "CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N",
                    "score": 9.3
                }
            },
            "cwes": [
                {
                    "cwe_id": "CWE-77",
                    "name": "Improper Neutralization of Special Elements used in a Command ('Command Injection')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "torch"
            },
            "severity": "critical",
            "vulnerable_version_range": "<= 1.13.0",
            "first_patched_version": {
                "identifier": "1.13.1"
            }
        },
        "url": "https://api.github.com/repos/username/garage/dependabot/alerts/1",
        "html_url": "https://github.com/username/garage/security/dependabot/1",
        "created_at": "2024-05-24T01:34:43Z",
        "updated_at": "2024-05-24T01:34:43Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    }
]