[
    {
        "number": 2,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "numpy"
            },
            "manifest_path": "rtd_requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-fpfv-jqm9-f5jm",
            "cve_id": "CVE-2021-34141",
            "summary": "Incorrect Comparison in NumPy",
            "description": "Incomplete string comparison in the numpy.core component in NumPy1.9.x, which allows attackers to fail the APIs via constructing specific string objects.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-fpfv-jqm9-f5jm",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2021-34141",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-34141"
                },
                {
                    "url": "https://github.com/numpy/numpy/issues/18993"
                },
                {
                    "url": "https://www.oracle.com/security-alerts/cpujul2022.html"
                },
                {
                    "url": "https://github.com/numpy/numpy/issues/18993#issuecomment-1010735102"
                },
                {
                    "url": "https://github.com/advisories/GHSA-fpfv-jqm9-f5jm"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/numpy/PYSEC-2021-855.yaml"
                }
            ],
            "published_at": "2021-12-18T00:00:41Z",
            "updated_at": "2023-01-27T05:07:10Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "numpy"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 1.22",
                    "first_patched_version": {
                        "identifier": "1.22"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
                "score": 5.3
            },
            "cvss_severities": {
                "cvss_v3": {
                    "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
                    "score": 5.3
                },
                "cvss_v4": {
                    "vector_string": null,
                    "score": 0.0
                }
            },
            "cwes": [
                {
                    "cwe_id": "CWE-697",
                    "name": "Incorrect Comparison"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "numpy"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 1.22",
            "first_patched_version": {
                "identifier": "1.22"
            }
        },
        "url": "https://api.github.com/repos/fcas/modAL/dependabot/alerts/2",
        "html_url": "https://github.com/fcas/modAL/security/dependabot/2",
        "created_at": "2024-05-24T01:34:01Z",
        "updated_at": "2024-05-24T01:34:01Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 1,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "numpy"
            },
            "manifest_path": "rtd_requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-6p56-wp2h-9hxr",
            "cve_id": "CVE-2021-33430",
            "summary": "NumPy Buffer Overflow (Disputed)",
            "description": "A Buffer Overflow vulnerability exists in NumPy 1.9.x in the PyArray_NewFromDescr_int function of ctors.c when specifying arrays of large dimensions (over 32) from Python code, which could let a malicious user cause a Denial of Service.\n\nNOTE: The vendor does not agree this is a vulnerability; In (very limited) circumstances a user may be able provoke the buffer overflow, the user is most likely already privileged to at least provoke denial of service by exhausting memory. Triggering this further requires the use of uncommon API (complicated structured dtypes), which is very unlikely to be available to an unprivileged user.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-6p56-wp2h-9hxr",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2021-33430",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-33430"
                },
                {
                    "url": "https://github.com/numpy/numpy/issues/18939"
                },
                {
                    "url": "https://github.com/numpy/numpy/commit/ae317fd9ff3e79c0eac357d723bfc29cbd625f2e"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/numpy/PYSEC-2021-854.yaml"
                },
                {
                    "url": "https://github.com/advisories/GHSA-6p56-wp2h-9hxr"
                }
            ],
            "published_at": "2022-01-07T00:09:39Z",
            "updated_at": "2024-09-26T14:21:10Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "numpy"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": ">= 1.9.0, < 1.21",
                    "first_patched_version": {
                        "identifier": "1.21"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:N/I:N/A:H",
                "score": 5.3
            },
            "cvss_severities": {
                "cvss_v3": {
                    "vector_string": "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:N/I:N/A:H",
                    "score": 5.3
                },
                "cvss_v4": {
                    "vector_string": "CVSS:4.0/AV:N/AC:H/AT:N/PR:L/UI:N/VC:N/VI:N/VA:H/SC:N/SI:N/SA:N",
                    "score": 6.0
                }
            },
            "cwes": [
                {
                    "cwe_id": "CWE-120",
                    "name": "Buffer Copy without Checking Size of Input ('Classic Buffer Overflow')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "numpy"
            },
            "severity": "medium",
            "vulnerable_version_range": ">= 1.9.0, < 1.21",
            "first_patched_version": {
                "identifier": "1.21"
            }
        },
        "url": "https://api.github.com/repos/fcas/modAL/dependabot/alerts/1",
        "html_url": "https://github.com/fcas/modAL/security/dependabot/1",
        "created_at": "2024-05-24T01:34:00Z",
        "updated_at": "2024-05-24T01:34:00Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    }
]