[
    {
        "number": 35,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "Werkzeug"
            },
            "manifest_path": "requirements_lock_3_10.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-f9vj-2wh5-fj8j",
            "cve_id": "CVE-2024-49766",
            "summary": "Werkzeug safe_join not safe on Windows",
            "description": "On Python < 3.11 on Windows, `os.path.isabs()` does not catch UNC paths like `//server/share`. Werkzeug's `safe_join()` relies on this check, and so can produce a path that is not safe, potentially allowing unintended access to data. Applications using Python >= 3.11, or not using Windows, are not vulnerable.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-f9vj-2wh5-fj8j",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-49766",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/pallets/werkzeug/security/advisories/GHSA-f9vj-2wh5-fj8j"
                },
                {
                    "url": "https://github.com/pallets/werkzeug/commit/2767bcb10a7dd1c297d812cc5e6d11a474c1f092"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-49766"
                },
                {
                    "url": "https://github.com/pallets/werkzeug/releases/tag/3.0.6"
                },
                {
                    "url": "https://github.com/advisories/GHSA-f9vj-2wh5-fj8j"
                }
            ],
            "published_at": "2024-10-25T19:43:41Z",
            "updated_at": "2024-10-26T03:47:04Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Werkzeug"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "<= 3.0.5",
                    "first_patched_version": {
                        "identifier": "3.0.6"
                    }
                }
            ],
            "cvss": {
                "vector_string": null,
                "score": 0.0
            },
            "cvss_severities": {
                "cvss_v3": {
                    "vector_string": null,
                    "score": 0.0
                },
                "cvss_v4": {
                    "vector_string": "CVSS:4.0/AV:N/AC:H/AT:N/PR:N/UI:N/VC:L/VI:N/VA:N/SC:N/SI:N/SA:N",
                    "score": 6.3
                }
            },
            "cwes": [
                {
                    "cwe_id": "CWE-22",
                    "name": "Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "Werkzeug"
            },
            "severity": "medium",
            "vulnerable_version_range": "<= 3.0.5",
            "first_patched_version": {
                "identifier": "3.0.6"
            }
        },
        "url": "https://api.github.com/repos/username/tensorflow/dependabot/alerts/35",
        "html_url": "https://github.com/username/tensorflow/security/dependabot/35",
        "created_at": "2024-10-26T00:02:48Z",
        "updated_at": "2024-10-26T00:02:48Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 34,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "Werkzeug"
            },
            "manifest_path": "requirements_lock_3_9.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-f9vj-2wh5-fj8j",
            "cve_id": "CVE-2024-49766",
            "summary": "Werkzeug safe_join not safe on Windows",
            "description": "On Python < 3.11 on Windows, `os.path.isabs()` does not catch UNC paths like `//server/share`. Werkzeug's `safe_join()` relies on this check, and so can produce a path that is not safe, potentially allowing unintended access to data. Applications using Python >= 3.11, or not using Windows, are not vulnerable.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-f9vj-2wh5-fj8j",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-49766",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/pallets/werkzeug/security/advisories/GHSA-f9vj-2wh5-fj8j"
                },
                {
                    "url": "https://github.com/pallets/werkzeug/commit/2767bcb10a7dd1c297d812cc5e6d11a474c1f092"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-49766"
                },
                {
                    "url": "https://github.com/pallets/werkzeug/releases/tag/3.0.6"
                },
                {
                    "url": "https://github.com/advisories/GHSA-f9vj-2wh5-fj8j"
                }
            ],
            "published_at": "2024-10-25T19:43:41Z",
            "updated_at": "2024-10-26T03:47:04Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Werkzeug"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "<= 3.0.5",
                    "first_patched_version": {
                        "identifier": "3.0.6"
                    }
                }
            ],
            "cvss": {
                "vector_string": null,
                "score": 0.0
            },
            "cvss_severities": {
                "cvss_v3": {
                    "vector_string": null,
                    "score": 0.0
                },
                "cvss_v4": {
                    "vector_string": "CVSS:4.0/AV:N/AC:H/AT:N/PR:N/UI:N/VC:L/VI:N/VA:N/SC:N/SI:N/SA:N",
                    "score": 6.3
                }
            },
            "cwes": [
                {
                    "cwe_id": "CWE-22",
                    "name": "Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "Werkzeug"
            },
            "severity": "medium",
            "vulnerable_version_range": "<= 3.0.5",
            "first_patched_version": {
                "identifier": "3.0.6"
            }
        },
        "url": "https://api.github.com/repos/username/tensorflow/dependabot/alerts/34",
        "html_url": "https://github.com/username/tensorflow/security/dependabot/34",
        "created_at": "2024-10-26T00:02:48Z",
        "updated_at": "2024-10-26T00:02:48Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 33,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "Werkzeug"
            },
            "manifest_path": "requirements_lock_3_12.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-f9vj-2wh5-fj8j",
            "cve_id": "CVE-2024-49766",
            "summary": "Werkzeug safe_join not safe on Windows",
            "description": "On Python < 3.11 on Windows, `os.path.isabs()` does not catch UNC paths like `//server/share`. Werkzeug's `safe_join()` relies on this check, and so can produce a path that is not safe, potentially allowing unintended access to data. Applications using Python >= 3.11, or not using Windows, are not vulnerable.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-f9vj-2wh5-fj8j",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-49766",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/pallets/werkzeug/security/advisories/GHSA-f9vj-2wh5-fj8j"
                },
                {
                    "url": "https://github.com/pallets/werkzeug/commit/2767bcb10a7dd1c297d812cc5e6d11a474c1f092"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-49766"
                },
                {
                    "url": "https://github.com/pallets/werkzeug/releases/tag/3.0.6"
                },
                {
                    "url": "https://github.com/advisories/GHSA-f9vj-2wh5-fj8j"
                }
            ],
            "published_at": "2024-10-25T19:43:41Z",
            "updated_at": "2024-10-26T03:47:04Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Werkzeug"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "<= 3.0.5",
                    "first_patched_version": {
                        "identifier": "3.0.6"
                    }
                }
            ],
            "cvss": {
                "vector_string": null,
                "score": 0.0
            },
            "cvss_severities": {
                "cvss_v3": {
                    "vector_string": null,
                    "score": 0.0
                },
                "cvss_v4": {
                    "vector_string": "CVSS:4.0/AV:N/AC:H/AT:N/PR:N/UI:N/VC:L/VI:N/VA:N/SC:N/SI:N/SA:N",
                    "score": 6.3
                }
            },
            "cwes": [
                {
                    "cwe_id": "CWE-22",
                    "name": "Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "Werkzeug"
            },
            "severity": "medium",
            "vulnerable_version_range": "<= 3.0.5",
            "first_patched_version": {
                "identifier": "3.0.6"
            }
        },
        "url": "https://api.github.com/repos/username/tensorflow/dependabot/alerts/33",
        "html_url": "https://github.com/username/tensorflow/security/dependabot/33",
        "created_at": "2024-10-26T00:02:48Z",
        "updated_at": "2024-10-26T00:02:48Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 32,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "Werkzeug"
            },
            "manifest_path": "requirements_lock_3_11.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-f9vj-2wh5-fj8j",
            "cve_id": "CVE-2024-49766",
            "summary": "Werkzeug safe_join not safe on Windows",
            "description": "On Python < 3.11 on Windows, `os.path.isabs()` does not catch UNC paths like `//server/share`. Werkzeug's `safe_join()` relies on this check, and so can produce a path that is not safe, potentially allowing unintended access to data. Applications using Python >= 3.11, or not using Windows, are not vulnerable.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-f9vj-2wh5-fj8j",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-49766",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/pallets/werkzeug/security/advisories/GHSA-f9vj-2wh5-fj8j"
                },
                {
                    "url": "https://github.com/pallets/werkzeug/commit/2767bcb10a7dd1c297d812cc5e6d11a474c1f092"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-49766"
                },
                {
                    "url": "https://github.com/pallets/werkzeug/releases/tag/3.0.6"
                },
                {
                    "url": "https://github.com/advisories/GHSA-f9vj-2wh5-fj8j"
                }
            ],
            "published_at": "2024-10-25T19:43:41Z",
            "updated_at": "2024-10-26T03:47:04Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Werkzeug"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "<= 3.0.5",
                    "first_patched_version": {
                        "identifier": "3.0.6"
                    }
                }
            ],
            "cvss": {
                "vector_string": null,
                "score": 0.0
            },
            "cvss_severities": {
                "cvss_v3": {
                    "vector_string": null,
                    "score": 0.0
                },
                "cvss_v4": {
                    "vector_string": "CVSS:4.0/AV:N/AC:H/AT:N/PR:N/UI:N/VC:L/VI:N/VA:N/SC:N/SI:N/SA:N",
                    "score": 6.3
                }
            },
            "cwes": [
                {
                    "cwe_id": "CWE-22",
                    "name": "Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "Werkzeug"
            },
            "severity": "medium",
            "vulnerable_version_range": "<= 3.0.5",
            "first_patched_version": {
                "identifier": "3.0.6"
            }
        },
        "url": "https://api.github.com/repos/username/tensorflow/dependabot/alerts/32",
        "html_url": "https://github.com/username/tensorflow/security/dependabot/32",
        "created_at": "2024-10-26T00:02:47Z",
        "updated_at": "2024-10-26T00:02:47Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 31,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "werkzeug"
            },
            "manifest_path": "requirements_lock_3_10.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-q34m-jh98-gwm2",
            "cve_id": "CVE-2024-49767",
            "summary": "Werkzeug possible resource exhaustion when parsing file data in forms",
            "description": "Applications using Werkzeug to parse `multipart/form-data` requests are vulnerable to resource exhaustion. A specially crafted form body can bypass the `Request.max_form_memory_size` setting.\n\n\nThe `Request.max_content_length` setting, as well as resource limits provided by deployment software and platforms, are also available to limit the resources used during a request. This vulnerability does not affect those settings. All three types of limits should be considered and set appropriately when deploying an application.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-q34m-jh98-gwm2",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-49767",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/pallets/werkzeug/security/advisories/GHSA-q34m-jh98-gwm2"
                },
                {
                    "url": "https://github.com/pallets/quart/commit/5e78c4169b8eb66b91ead3e62d44721b9e1644ee"
                },
                {
                    "url": "https://github.com/pallets/werkzeug/commit/50cfeebcb0727e18cc52ffbeb125f4a66551179b"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-49767"
                },
                {
                    "url": "https://github.com/pallets/werkzeug/releases/tag/3.0.6"
                },
                {
                    "url": "https://github.com/pallets/quart/commit/abb04a512496206de279225340ed022852fbf51f"
                },
                {
                    "url": "https://github.com/advisories/GHSA-q34m-jh98-gwm2"
                }
            ],
            "published_at": "2024-10-25T19:44:43Z",
            "updated_at": "2024-12-27T21:53:30Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "werkzeug"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "<= 3.0.5",
                    "first_patched_version": {
                        "identifier": "3.0.6"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Quart"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 0.20.0",
                    "first_patched_version": {
                        "identifier": "0.20.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cvss_severities": {
                "cvss_v3": {
                    "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                    "score": 7.5
                },
                "cvss_v4": {
                    "vector_string": "CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:N/VA:L/SC:N/SI:N/SA:N",
                    "score": 6.9
                }
            },
            "cwes": [
                {
                    "cwe_id": "CWE-400",
                    "name": "Uncontrolled Resource Consumption"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "werkzeug"
            },
            "severity": "medium",
            "vulnerable_version_range": "<= 3.0.5",
            "first_patched_version": {
                "identifier": "3.0.6"
            }
        },
        "url": "https://api.github.com/repos/username/tensorflow/dependabot/alerts/31",
        "html_url": "https://github.com/username/tensorflow/security/dependabot/31",
        "created_at": "2024-10-26T00:02:46Z",
        "updated_at": "2024-10-26T00:02:46Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 30,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "werkzeug"
            },
            "manifest_path": "requirements_lock_3_9.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-q34m-jh98-gwm2",
            "cve_id": "CVE-2024-49767",
            "summary": "Werkzeug possible resource exhaustion when parsing file data in forms",
            "description": "Applications using Werkzeug to parse `multipart/form-data` requests are vulnerable to resource exhaustion. A specially crafted form body can bypass the `Request.max_form_memory_size` setting.\n\n\nThe `Request.max_content_length` setting, as well as resource limits provided by deployment software and platforms, are also available to limit the resources used during a request. This vulnerability does not affect those settings. All three types of limits should be considered and set appropriately when deploying an application.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-q34m-jh98-gwm2",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-49767",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/pallets/werkzeug/security/advisories/GHSA-q34m-jh98-gwm2"
                },
                {
                    "url": "https://github.com/pallets/quart/commit/5e78c4169b8eb66b91ead3e62d44721b9e1644ee"
                },
                {
                    "url": "https://github.com/pallets/werkzeug/commit/50cfeebcb0727e18cc52ffbeb125f4a66551179b"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-49767"
                },
                {
                    "url": "https://github.com/pallets/werkzeug/releases/tag/3.0.6"
                },
                {
                    "url": "https://github.com/pallets/quart/commit/abb04a512496206de279225340ed022852fbf51f"
                },
                {
                    "url": "https://github.com/advisories/GHSA-q34m-jh98-gwm2"
                }
            ],
            "published_at": "2024-10-25T19:44:43Z",
            "updated_at": "2024-12-27T21:53:30Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "werkzeug"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "<= 3.0.5",
                    "first_patched_version": {
                        "identifier": "3.0.6"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Quart"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 0.20.0",
                    "first_patched_version": {
                        "identifier": "0.20.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cvss_severities": {
                "cvss_v3": {
                    "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                    "score": 7.5
                },
                "cvss_v4": {
                    "vector_string": "CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:N/VA:L/SC:N/SI:N/SA:N",
                    "score": 6.9
                }
            },
            "cwes": [
                {
                    "cwe_id": "CWE-400",
                    "name": "Uncontrolled Resource Consumption"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "werkzeug"
            },
            "severity": "medium",
            "vulnerable_version_range": "<= 3.0.5",
            "first_patched_version": {
                "identifier": "3.0.6"
            }
        },
        "url": "https://api.github.com/repos/username/tensorflow/dependabot/alerts/30",
        "html_url": "https://github.com/username/tensorflow/security/dependabot/30",
        "created_at": "2024-10-26T00:02:46Z",
        "updated_at": "2024-10-26T00:02:46Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 29,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "werkzeug"
            },
            "manifest_path": "requirements_lock_3_12.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-q34m-jh98-gwm2",
            "cve_id": "CVE-2024-49767",
            "summary": "Werkzeug possible resource exhaustion when parsing file data in forms",
            "description": "Applications using Werkzeug to parse `multipart/form-data` requests are vulnerable to resource exhaustion. A specially crafted form body can bypass the `Request.max_form_memory_size` setting.\n\n\nThe `Request.max_content_length` setting, as well as resource limits provided by deployment software and platforms, are also available to limit the resources used during a request. This vulnerability does not affect those settings. All three types of limits should be considered and set appropriately when deploying an application.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-q34m-jh98-gwm2",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-49767",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/pallets/werkzeug/security/advisories/GHSA-q34m-jh98-gwm2"
                },
                {
                    "url": "https://github.com/pallets/quart/commit/5e78c4169b8eb66b91ead3e62d44721b9e1644ee"
                },
                {
                    "url": "https://github.com/pallets/werkzeug/commit/50cfeebcb0727e18cc52ffbeb125f4a66551179b"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-49767"
                },
                {
                    "url": "https://github.com/pallets/werkzeug/releases/tag/3.0.6"
                },
                {
                    "url": "https://github.com/pallets/quart/commit/abb04a512496206de279225340ed022852fbf51f"
                },
                {
                    "url": "https://github.com/advisories/GHSA-q34m-jh98-gwm2"
                }
            ],
            "published_at": "2024-10-25T19:44:43Z",
            "updated_at": "2024-12-27T21:53:30Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "werkzeug"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "<= 3.0.5",
                    "first_patched_version": {
                        "identifier": "3.0.6"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Quart"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 0.20.0",
                    "first_patched_version": {
                        "identifier": "0.20.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cvss_severities": {
                "cvss_v3": {
                    "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                    "score": 7.5
                },
                "cvss_v4": {
                    "vector_string": "CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:N/VA:L/SC:N/SI:N/SA:N",
                    "score": 6.9
                }
            },
            "cwes": [
                {
                    "cwe_id": "CWE-400",
                    "name": "Uncontrolled Resource Consumption"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "werkzeug"
            },
            "severity": "medium",
            "vulnerable_version_range": "<= 3.0.5",
            "first_patched_version": {
                "identifier": "3.0.6"
            }
        },
        "url": "https://api.github.com/repos/username/tensorflow/dependabot/alerts/29",
        "html_url": "https://github.com/username/tensorflow/security/dependabot/29",
        "created_at": "2024-10-26T00:02:46Z",
        "updated_at": "2024-10-26T00:02:46Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 28,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "werkzeug"
            },
            "manifest_path": "requirements_lock_3_11.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-q34m-jh98-gwm2",
            "cve_id": "CVE-2024-49767",
            "summary": "Werkzeug possible resource exhaustion when parsing file data in forms",
            "description": "Applications using Werkzeug to parse `multipart/form-data` requests are vulnerable to resource exhaustion. A specially crafted form body can bypass the `Request.max_form_memory_size` setting.\n\n\nThe `Request.max_content_length` setting, as well as resource limits provided by deployment software and platforms, are also available to limit the resources used during a request. This vulnerability does not affect those settings. All three types of limits should be considered and set appropriately when deploying an application.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-q34m-jh98-gwm2",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-49767",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/pallets/werkzeug/security/advisories/GHSA-q34m-jh98-gwm2"
                },
                {
                    "url": "https://github.com/pallets/quart/commit/5e78c4169b8eb66b91ead3e62d44721b9e1644ee"
                },
                {
                    "url": "https://github.com/pallets/werkzeug/commit/50cfeebcb0727e18cc52ffbeb125f4a66551179b"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-49767"
                },
                {
                    "url": "https://github.com/pallets/werkzeug/releases/tag/3.0.6"
                },
                {
                    "url": "https://github.com/pallets/quart/commit/abb04a512496206de279225340ed022852fbf51f"
                },
                {
                    "url": "https://github.com/advisories/GHSA-q34m-jh98-gwm2"
                }
            ],
            "published_at": "2024-10-25T19:44:43Z",
            "updated_at": "2024-12-27T21:53:30Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "werkzeug"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "<= 3.0.5",
                    "first_patched_version": {
                        "identifier": "3.0.6"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Quart"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 0.20.0",
                    "first_patched_version": {
                        "identifier": "0.20.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cvss_severities": {
                "cvss_v3": {
                    "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                    "score": 7.5
                },
                "cvss_v4": {
                    "vector_string": "CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:N/VA:L/SC:N/SI:N/SA:N",
                    "score": 6.9
                }
            },
            "cwes": [
                {
                    "cwe_id": "CWE-400",
                    "name": "Uncontrolled Resource Consumption"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "werkzeug"
            },
            "severity": "medium",
            "vulnerable_version_range": "<= 3.0.5",
            "first_patched_version": {
                "identifier": "3.0.6"
            }
        },
        "url": "https://api.github.com/repos/username/tensorflow/dependabot/alerts/28",
        "html_url": "https://github.com/username/tensorflow/security/dependabot/28",
        "created_at": "2024-10-26T00:02:46Z",
        "updated_at": "2024-10-26T00:02:46Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 27,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "grpcio"
            },
            "manifest_path": "ci/official/containers/linux_arm64/devel.usertools/test.requirements.txt",
            "scope": "development"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-496j-2rq6-j6cc",
            "cve_id": "CVE-2023-33953",
            "summary": "Excessive Iteration in gRPC",
            "description": "gRPC contains a vulnerability that allows hpack table accounting errors could lead to unwanted disconnects between clients and servers in exceptional cases/ Three vectors were found that allow the following DOS attacks:\n\n- Unbounded memory buffering in the HPACK parser\n- Unbounded CPU consumption in the HPACK parser\n\nThe unbounded CPU consumption is down to a copy that occurred per-input-block in the parser, and because that could be unbounded due to the memory copy bug we end up with an O(n^2) parsing loop, with n selected by the client.\n\nThe unbounded memory buffering bugs:\n\n- The header size limit check was behind the string reading code, so we needed to first buffer up to a 4 gigabyte string before rejecting it as longer than 8 or 16kb.\n- HPACK varints have an encoding quirk whereby an infinite number of 0’s can be added at the start of an integer. gRPC’s hpack parser needed to read all of them before concluding a parse.\n- gRPC’s metadata overflow check was performed per frame, so that the following sequence of frames could cause infinite buffering: HEADERS: containing a: 1 CONTINUATION: containing a: 2 CONTINUATION: containing a: 3 etc…",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-496j-2rq6-j6cc",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-33953",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-33953"
                },
                {
                    "url": "https://cloud.google.com/support/bulletins#gcp-2023-022"
                },
                {
                    "url": "https://security.snyk.io/vuln/SNYK-RUBY-GRPC-5834442"
                },
                {
                    "url": "https://github.com/advisories/GHSA-496j-2rq6-j6cc"
                },
                {
                    "url": "https://github.com/rubysec/ruby-advisory-db/blob/master/gems/grpc/CVE-2023-33953.yml"
                }
            ],
            "published_at": "2023-08-09T15:30:15Z",
            "updated_at": "2024-07-30T21:37:54Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "grpcio"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 1.53.2",
                    "first_patched_version": {
                        "identifier": "1.53.2"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "grpcio"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 1.54.0, < 1.54.3",
                    "first_patched_version": {
                        "identifier": "1.54.3"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "grpcio"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 1.55.0, < 1.55.2",
                    "first_patched_version": {
                        "identifier": "1.55.2"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "grpcio"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 1.56.0, < 1.56.2",
                    "first_patched_version": {
                        "identifier": "1.56.2"
                    }
                },
                {
                    "package": {
                        "ecosystem": "rubygems",
                        "name": "grpc"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 1.53.2",
                    "first_patched_version": {
                        "identifier": "1.53.2"
                    }
                },
                {
                    "package": {
                        "ecosystem": "rubygems",
                        "name": "grpc"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 1.54.0, < 1.54.3",
                    "first_patched_version": {
                        "identifier": "1.54.3"
                    }
                },
                {
                    "package": {
                        "ecosystem": "rubygems",
                        "name": "grpc"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 1.55.0, < 1.55.2",
                    "first_patched_version": {
                        "identifier": "1.55.2"
                    }
                },
                {
                    "package": {
                        "ecosystem": "rubygems",
                        "name": "grpc"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 1.56.0, < 1.56.2",
                    "first_patched_version": {
                        "identifier": "1.56.2"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cvss_severities": {
                "cvss_v3": {
                    "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                    "score": 7.5
                },
                "cvss_v4": {
                    "vector_string": null,
                    "score": 0.0
                }
            },
            "cwes": [
                {
                    "cwe_id": "CWE-770",
                    "name": "Allocation of Resources Without Limits or Throttling"
                },
                {
                    "cwe_id": "CWE-789",
                    "name": "Memory Allocation with Excessive Size Value"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "grpcio"
            },
            "severity": "high",
            "vulnerable_version_range": "< 1.53.2",
            "first_patched_version": {
                "identifier": "1.53.2"
            }
        },
        "url": "https://api.github.com/repos/username/tensorflow/dependabot/alerts/27",
        "html_url": "https://github.com/username/tensorflow/security/dependabot/27",
        "created_at": "2024-07-30T11:30:14Z",
        "updated_at": "2024-07-30T11:30:14Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 26,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "setuptools"
            },
            "manifest_path": "requirements_lock_3_10.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-cx63-2mw6-8hw5",
            "cve_id": "CVE-2024-6345",
            "summary": "setuptools vulnerable to Command Injection via package URL",
            "description": "A vulnerability in the `package_index` module of pypa/setuptools versions up to 69.1.1 allows for remote code execution via its download functions. These functions, which are used to download packages from URLs provided by users or retrieved from package index servers, are susceptible to code injection. If these functions are exposed to user-controlled inputs, such as package URLs, they can execute arbitrary commands on the system. The issue is fixed in version 70.0.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-cx63-2mw6-8hw5",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-6345",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-6345"
                },
                {
                    "url": "https://github.com/pypa/setuptools/commit/88807c7062788254f654ea8c03427adc859321f0"
                },
                {
                    "url": "https://huntr.com/bounties/d6362117-ad57-4e83-951f-b8141c6e7ca5"
                },
                {
                    "url": "https://github.com/pypa/setuptools/pull/4332"
                },
                {
                    "url": "https://github.com/advisories/GHSA-cx63-2mw6-8hw5"
                }
            ],
            "published_at": "2024-07-15T03:30:57Z",
            "updated_at": "2024-08-04T05:03:40Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "setuptools"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 70.0.0",
                    "first_patched_version": {
                        "identifier": "70.0.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
                "score": 8.8
            },
            "cvss_severities": {
                "cvss_v3": {
                    "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
                    "score": 8.8
                },
                "cvss_v4": {
                    "vector_string": "CVSS:4.0/AV:N/AC:L/AT:P/PR:N/UI:A/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N",
                    "score": 7.5
                }
            },
            "cwes": [
                {
                    "cwe_id": "CWE-94",
                    "name": "Improper Control of Generation of Code ('Code Injection')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "setuptools"
            },
            "severity": "high",
            "vulnerable_version_range": "< 70.0.0",
            "first_patched_version": {
                "identifier": "70.0.0"
            }
        },
        "url": "https://api.github.com/repos/username/tensorflow/dependabot/alerts/26",
        "html_url": "https://github.com/username/tensorflow/security/dependabot/26",
        "created_at": "2024-07-15T19:01:19Z",
        "updated_at": "2024-07-15T19:01:19Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 25,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "setuptools"
            },
            "manifest_path": "requirements_lock_3_9.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-cx63-2mw6-8hw5",
            "cve_id": "CVE-2024-6345",
            "summary": "setuptools vulnerable to Command Injection via package URL",
            "description": "A vulnerability in the `package_index` module of pypa/setuptools versions up to 69.1.1 allows for remote code execution via its download functions. These functions, which are used to download packages from URLs provided by users or retrieved from package index servers, are susceptible to code injection. If these functions are exposed to user-controlled inputs, such as package URLs, they can execute arbitrary commands on the system. The issue is fixed in version 70.0.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-cx63-2mw6-8hw5",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-6345",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-6345"
                },
                {
                    "url": "https://github.com/pypa/setuptools/commit/88807c7062788254f654ea8c03427adc859321f0"
                },
                {
                    "url": "https://huntr.com/bounties/d6362117-ad57-4e83-951f-b8141c6e7ca5"
                },
                {
                    "url": "https://github.com/pypa/setuptools/pull/4332"
                },
                {
                    "url": "https://github.com/advisories/GHSA-cx63-2mw6-8hw5"
                }
            ],
            "published_at": "2024-07-15T03:30:57Z",
            "updated_at": "2024-08-04T05:03:40Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "setuptools"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 70.0.0",
                    "first_patched_version": {
                        "identifier": "70.0.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
                "score": 8.8
            },
            "cvss_severities": {
                "cvss_v3": {
                    "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
                    "score": 8.8
                },
                "cvss_v4": {
                    "vector_string": "CVSS:4.0/AV:N/AC:L/AT:P/PR:N/UI:A/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N",
                    "score": 7.5
                }
            },
            "cwes": [
                {
                    "cwe_id": "CWE-94",
                    "name": "Improper Control of Generation of Code ('Code Injection')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "setuptools"
            },
            "severity": "high",
            "vulnerable_version_range": "< 70.0.0",
            "first_patched_version": {
                "identifier": "70.0.0"
            }
        },
        "url": "https://api.github.com/repos/username/tensorflow/dependabot/alerts/25",
        "html_url": "https://github.com/username/tensorflow/security/dependabot/25",
        "created_at": "2024-07-15T19:01:19Z",
        "updated_at": "2024-07-15T19:01:19Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 24,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "setuptools"
            },
            "manifest_path": "requirements_lock_3_12.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-cx63-2mw6-8hw5",
            "cve_id": "CVE-2024-6345",
            "summary": "setuptools vulnerable to Command Injection via package URL",
            "description": "A vulnerability in the `package_index` module of pypa/setuptools versions up to 69.1.1 allows for remote code execution via its download functions. These functions, which are used to download packages from URLs provided by users or retrieved from package index servers, are susceptible to code injection. If these functions are exposed to user-controlled inputs, such as package URLs, they can execute arbitrary commands on the system. The issue is fixed in version 70.0.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-cx63-2mw6-8hw5",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-6345",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-6345"
                },
                {
                    "url": "https://github.com/pypa/setuptools/commit/88807c7062788254f654ea8c03427adc859321f0"
                },
                {
                    "url": "https://huntr.com/bounties/d6362117-ad57-4e83-951f-b8141c6e7ca5"
                },
                {
                    "url": "https://github.com/pypa/setuptools/pull/4332"
                },
                {
                    "url": "https://github.com/advisories/GHSA-cx63-2mw6-8hw5"
                }
            ],
            "published_at": "2024-07-15T03:30:57Z",
            "updated_at": "2024-08-04T05:03:40Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "setuptools"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 70.0.0",
                    "first_patched_version": {
                        "identifier": "70.0.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
                "score": 8.8
            },
            "cvss_severities": {
                "cvss_v3": {
                    "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
                    "score": 8.8
                },
                "cvss_v4": {
                    "vector_string": "CVSS:4.0/AV:N/AC:L/AT:P/PR:N/UI:A/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N",
                    "score": 7.5
                }
            },
            "cwes": [
                {
                    "cwe_id": "CWE-94",
                    "name": "Improper Control of Generation of Code ('Code Injection')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "setuptools"
            },
            "severity": "high",
            "vulnerable_version_range": "< 70.0.0",
            "first_patched_version": {
                "identifier": "70.0.0"
            }
        },
        "url": "https://api.github.com/repos/username/tensorflow/dependabot/alerts/24",
        "html_url": "https://github.com/username/tensorflow/security/dependabot/24",
        "created_at": "2024-07-15T19:01:19Z",
        "updated_at": "2024-07-15T19:01:19Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 23,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "setuptools"
            },
            "manifest_path": "requirements_lock_3_11.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-cx63-2mw6-8hw5",
            "cve_id": "CVE-2024-6345",
            "summary": "setuptools vulnerable to Command Injection via package URL",
            "description": "A vulnerability in the `package_index` module of pypa/setuptools versions up to 69.1.1 allows for remote code execution via its download functions. These functions, which are used to download packages from URLs provided by users or retrieved from package index servers, are susceptible to code injection. If these functions are exposed to user-controlled inputs, such as package URLs, they can execute arbitrary commands on the system. The issue is fixed in version 70.0.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-cx63-2mw6-8hw5",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-6345",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-6345"
                },
                {
                    "url": "https://github.com/pypa/setuptools/commit/88807c7062788254f654ea8c03427adc859321f0"
                },
                {
                    "url": "https://huntr.com/bounties/d6362117-ad57-4e83-951f-b8141c6e7ca5"
                },
                {
                    "url": "https://github.com/pypa/setuptools/pull/4332"
                },
                {
                    "url": "https://github.com/advisories/GHSA-cx63-2mw6-8hw5"
                }
            ],
            "published_at": "2024-07-15T03:30:57Z",
            "updated_at": "2024-08-04T05:03:40Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "setuptools"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 70.0.0",
                    "first_patched_version": {
                        "identifier": "70.0.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
                "score": 8.8
            },
            "cvss_severities": {
                "cvss_v3": {
                    "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
                    "score": 8.8
                },
                "cvss_v4": {
                    "vector_string": "CVSS:4.0/AV:N/AC:L/AT:P/PR:N/UI:A/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N",
                    "score": 7.5
                }
            },
            "cwes": [
                {
                    "cwe_id": "CWE-94",
                    "name": "Improper Control of Generation of Code ('Code Injection')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "setuptools"
            },
            "severity": "high",
            "vulnerable_version_range": "< 70.0.0",
            "first_patched_version": {
                "identifier": "70.0.0"
            }
        },
        "url": "https://api.github.com/repos/username/tensorflow/dependabot/alerts/23",
        "html_url": "https://github.com/username/tensorflow/security/dependabot/23",
        "created_at": "2024-07-15T19:01:19Z",
        "updated_at": "2024-07-15T19:01:19Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 22,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "zipp"
            },
            "manifest_path": "requirements_lock_3_9.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-jfmj-5v4g-7637",
            "cve_id": "CVE-2024-5569",
            "summary": "zipp Denial of Service vulnerability",
            "description": "A Denial of Service (DoS) vulnerability exists in the jaraco/zipp library, affecting all versions prior to 3.19.1. The vulnerability is triggered when processing a specially crafted zip file that leads to an infinite loop. This issue also impacts the zipfile module of CPython, as features from the third-party zipp library are later merged into CPython, and the affected code is identical in both projects. The infinite loop can be initiated through the use of functions affecting the `Path` module in both zipp and zipfile, such as `joinpath`, the overloaded division operator, and `iterdir`. Although the infinite loop is not resource exhaustive, it prevents the application from responding. The vulnerability was addressed in version 3.19.1 of jaraco/zipp.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-jfmj-5v4g-7637",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-5569",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-5569"
                },
                {
                    "url": "https://github.com/jaraco/zipp/commit/fd604bd34f0343472521a36da1fbd22e793e14fd"
                },
                {
                    "url": "https://huntr.com/bounties/be898306-11f9-46b4-b28c-f4c4aa4ffbae"
                },
                {
                    "url": "https://github.com/advisories/GHSA-jfmj-5v4g-7637"
                }
            ],
            "published_at": "2024-07-09T00:31:40Z",
            "updated_at": "2024-08-08T05:06:36Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "zipp"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 3.19.1",
                    "first_patched_version": {
                        "identifier": "3.19.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.0/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 6.2
            },
            "cvss_severities": {
                "cvss_v3": {
                    "vector_string": "CVSS:3.0/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                    "score": 6.2
                },
                "cvss_v4": {
                    "vector_string": "CVSS:4.0/AV:L/AC:L/AT:N/PR:N/UI:N/VC:N/VI:N/VA:H/SC:N/SI:N/SA:N",
                    "score": 6.9
                }
            },
            "cwes": [
                {
                    "cwe_id": "CWE-400",
                    "name": "Uncontrolled Resource Consumption"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "zipp"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 3.19.1",
            "first_patched_version": {
                "identifier": "3.19.1"
            }
        },
        "url": "https://api.github.com/repos/username/tensorflow/dependabot/alerts/22",
        "html_url": "https://github.com/username/tensorflow/security/dependabot/22",
        "created_at": "2024-07-09T19:08:39Z",
        "updated_at": "2024-07-09T19:08:39Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 21,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "certifi"
            },
            "manifest_path": "tensorflow/tools/ci_build/release/requirements_mac.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-248v-346w-9cwc",
            "cve_id": "CVE-2024-39689",
            "summary": "Certifi removes GLOBALTRUST root certificate",
            "description": "Certifi 2024.07.04 removes root certificates from \"GLOBALTRUST\" from the root store. These are in the process of being removed from Mozilla's trust store.\n\nGLOBALTRUST's root certificates are being removed pursuant to an investigation which identified \"long-running and unresolved compliance issues\". Conclusions of Mozilla's investigation can be found [here]( https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/XpknYMPO8dI).",
            "severity": "low",
            "identifiers": [
                {
                    "value": "GHSA-248v-346w-9cwc",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-39689",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/certifi/python-certifi/security/advisories/GHSA-248v-346w-9cwc"
                },
                {
                    "url": "https://github.com/certifi/python-certifi/commit/bd8153872e9c6fc98f4023df9c2deaffea2fa463"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-39689"
                },
                {
                    "url": "https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/XpknYMPO8dI"
                },
                {
                    "url": "https://security.netapp.com/advisory/ntap-20241206-0001"
                },
                {
                    "url": "https://github.com/advisories/GHSA-248v-346w-9cwc"
                }
            ],
            "published_at": "2024-07-05T20:06:40Z",
            "updated_at": "2024-12-06T18:22:48Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "certifi"
                    },
                    "severity": "low",
                    "vulnerable_version_range": ">= 2021.05.30, < 2024.07.04",
                    "first_patched_version": {
                        "identifier": "2024.07.04"
                    }
                }
            ],
            "cvss": {
                "vector_string": null,
                "score": 0.0
            },
            "cvss_severities": {
                "cvss_v3": {
                    "vector_string": null,
                    "score": 0.0
                },
                "cvss_v4": {
                    "vector_string": null,
                    "score": 0.0
                }
            },
            "cwes": [
                {
                    "cwe_id": "CWE-345",
                    "name": "Insufficient Verification of Data Authenticity"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "certifi"
            },
            "severity": "low",
            "vulnerable_version_range": ">= 2021.05.30, < 2024.07.04",
            "first_patched_version": {
                "identifier": "2024.07.04"
            }
        },
        "url": "https://api.github.com/repos/username/tensorflow/dependabot/alerts/21",
        "html_url": "https://github.com/username/tensorflow/security/dependabot/21",
        "created_at": "2024-07-06T02:31:48Z",
        "updated_at": "2024-07-06T02:31:48Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 20,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "certifi"
            },
            "manifest_path": "requirements_lock_3_10.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-248v-346w-9cwc",
            "cve_id": "CVE-2024-39689",
            "summary": "Certifi removes GLOBALTRUST root certificate",
            "description": "Certifi 2024.07.04 removes root certificates from \"GLOBALTRUST\" from the root store. These are in the process of being removed from Mozilla's trust store.\n\nGLOBALTRUST's root certificates are being removed pursuant to an investigation which identified \"long-running and unresolved compliance issues\". Conclusions of Mozilla's investigation can be found [here]( https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/XpknYMPO8dI).",
            "severity": "low",
            "identifiers": [
                {
                    "value": "GHSA-248v-346w-9cwc",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-39689",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/certifi/python-certifi/security/advisories/GHSA-248v-346w-9cwc"
                },
                {
                    "url": "https://github.com/certifi/python-certifi/commit/bd8153872e9c6fc98f4023df9c2deaffea2fa463"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-39689"
                },
                {
                    "url": "https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/XpknYMPO8dI"
                },
                {
                    "url": "https://security.netapp.com/advisory/ntap-20241206-0001"
                },
                {
                    "url": "https://github.com/advisories/GHSA-248v-346w-9cwc"
                }
            ],
            "published_at": "2024-07-05T20:06:40Z",
            "updated_at": "2024-12-06T18:22:48Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "certifi"
                    },
                    "severity": "low",
                    "vulnerable_version_range": ">= 2021.05.30, < 2024.07.04",
                    "first_patched_version": {
                        "identifier": "2024.07.04"
                    }
                }
            ],
            "cvss": {
                "vector_string": null,
                "score": 0.0
            },
            "cvss_severities": {
                "cvss_v3": {
                    "vector_string": null,
                    "score": 0.0
                },
                "cvss_v4": {
                    "vector_string": null,
                    "score": 0.0
                }
            },
            "cwes": [
                {
                    "cwe_id": "CWE-345",
                    "name": "Insufficient Verification of Data Authenticity"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "certifi"
            },
            "severity": "low",
            "vulnerable_version_range": ">= 2021.05.30, < 2024.07.04",
            "first_patched_version": {
                "identifier": "2024.07.04"
            }
        },
        "url": "https://api.github.com/repos/username/tensorflow/dependabot/alerts/20",
        "html_url": "https://github.com/username/tensorflow/security/dependabot/20",
        "created_at": "2024-07-06T02:04:05Z",
        "updated_at": "2024-07-06T02:04:05Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 19,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "certifi"
            },
            "manifest_path": "requirements_lock_3_9.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-248v-346w-9cwc",
            "cve_id": "CVE-2024-39689",
            "summary": "Certifi removes GLOBALTRUST root certificate",
            "description": "Certifi 2024.07.04 removes root certificates from \"GLOBALTRUST\" from the root store. These are in the process of being removed from Mozilla's trust store.\n\nGLOBALTRUST's root certificates are being removed pursuant to an investigation which identified \"long-running and unresolved compliance issues\". Conclusions of Mozilla's investigation can be found [here]( https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/XpknYMPO8dI).",
            "severity": "low",
            "identifiers": [
                {
                    "value": "GHSA-248v-346w-9cwc",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-39689",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/certifi/python-certifi/security/advisories/GHSA-248v-346w-9cwc"
                },
                {
                    "url": "https://github.com/certifi/python-certifi/commit/bd8153872e9c6fc98f4023df9c2deaffea2fa463"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-39689"
                },
                {
                    "url": "https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/XpknYMPO8dI"
                },
                {
                    "url": "https://security.netapp.com/advisory/ntap-20241206-0001"
                },
                {
                    "url": "https://github.com/advisories/GHSA-248v-346w-9cwc"
                }
            ],
            "published_at": "2024-07-05T20:06:40Z",
            "updated_at": "2024-12-06T18:22:48Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "certifi"
                    },
                    "severity": "low",
                    "vulnerable_version_range": ">= 2021.05.30, < 2024.07.04",
                    "first_patched_version": {
                        "identifier": "2024.07.04"
                    }
                }
            ],
            "cvss": {
                "vector_string": null,
                "score": 0.0
            },
            "cvss_severities": {
                "cvss_v3": {
                    "vector_string": null,
                    "score": 0.0
                },
                "cvss_v4": {
                    "vector_string": null,
                    "score": 0.0
                }
            },
            "cwes": [
                {
                    "cwe_id": "CWE-345",
                    "name": "Insufficient Verification of Data Authenticity"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "certifi"
            },
            "severity": "low",
            "vulnerable_version_range": ">= 2021.05.30, < 2024.07.04",
            "first_patched_version": {
                "identifier": "2024.07.04"
            }
        },
        "url": "https://api.github.com/repos/username/tensorflow/dependabot/alerts/19",
        "html_url": "https://github.com/username/tensorflow/security/dependabot/19",
        "created_at": "2024-07-06T02:04:05Z",
        "updated_at": "2024-07-06T02:04:05Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 18,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "certifi"
            },
            "manifest_path": "requirements_lock_3_12.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-248v-346w-9cwc",
            "cve_id": "CVE-2024-39689",
            "summary": "Certifi removes GLOBALTRUST root certificate",
            "description": "Certifi 2024.07.04 removes root certificates from \"GLOBALTRUST\" from the root store. These are in the process of being removed from Mozilla's trust store.\n\nGLOBALTRUST's root certificates are being removed pursuant to an investigation which identified \"long-running and unresolved compliance issues\". Conclusions of Mozilla's investigation can be found [here]( https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/XpknYMPO8dI).",
            "severity": "low",
            "identifiers": [
                {
                    "value": "GHSA-248v-346w-9cwc",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-39689",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/certifi/python-certifi/security/advisories/GHSA-248v-346w-9cwc"
                },
                {
                    "url": "https://github.com/certifi/python-certifi/commit/bd8153872e9c6fc98f4023df9c2deaffea2fa463"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-39689"
                },
                {
                    "url": "https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/XpknYMPO8dI"
                },
                {
                    "url": "https://security.netapp.com/advisory/ntap-20241206-0001"
                },
                {
                    "url": "https://github.com/advisories/GHSA-248v-346w-9cwc"
                }
            ],
            "published_at": "2024-07-05T20:06:40Z",
            "updated_at": "2024-12-06T18:22:48Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "certifi"
                    },
                    "severity": "low",
                    "vulnerable_version_range": ">= 2021.05.30, < 2024.07.04",
                    "first_patched_version": {
                        "identifier": "2024.07.04"
                    }
                }
            ],
            "cvss": {
                "vector_string": null,
                "score": 0.0
            },
            "cvss_severities": {
                "cvss_v3": {
                    "vector_string": null,
                    "score": 0.0
                },
                "cvss_v4": {
                    "vector_string": null,
                    "score": 0.0
                }
            },
            "cwes": [
                {
                    "cwe_id": "CWE-345",
                    "name": "Insufficient Verification of Data Authenticity"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "certifi"
            },
            "severity": "low",
            "vulnerable_version_range": ">= 2021.05.30, < 2024.07.04",
            "first_patched_version": {
                "identifier": "2024.07.04"
            }
        },
        "url": "https://api.github.com/repos/username/tensorflow/dependabot/alerts/18",
        "html_url": "https://github.com/username/tensorflow/security/dependabot/18",
        "created_at": "2024-07-06T02:04:05Z",
        "updated_at": "2024-07-06T02:04:05Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 17,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "certifi"
            },
            "manifest_path": "requirements_lock_3_11.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-248v-346w-9cwc",
            "cve_id": "CVE-2024-39689",
            "summary": "Certifi removes GLOBALTRUST root certificate",
            "description": "Certifi 2024.07.04 removes root certificates from \"GLOBALTRUST\" from the root store. These are in the process of being removed from Mozilla's trust store.\n\nGLOBALTRUST's root certificates are being removed pursuant to an investigation which identified \"long-running and unresolved compliance issues\". Conclusions of Mozilla's investigation can be found [here]( https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/XpknYMPO8dI).",
            "severity": "low",
            "identifiers": [
                {
                    "value": "GHSA-248v-346w-9cwc",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-39689",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/certifi/python-certifi/security/advisories/GHSA-248v-346w-9cwc"
                },
                {
                    "url": "https://github.com/certifi/python-certifi/commit/bd8153872e9c6fc98f4023df9c2deaffea2fa463"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-39689"
                },
                {
                    "url": "https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/XpknYMPO8dI"
                },
                {
                    "url": "https://security.netapp.com/advisory/ntap-20241206-0001"
                },
                {
                    "url": "https://github.com/advisories/GHSA-248v-346w-9cwc"
                }
            ],
            "published_at": "2024-07-05T20:06:40Z",
            "updated_at": "2024-12-06T18:22:48Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "certifi"
                    },
                    "severity": "low",
                    "vulnerable_version_range": ">= 2021.05.30, < 2024.07.04",
                    "first_patched_version": {
                        "identifier": "2024.07.04"
                    }
                }
            ],
            "cvss": {
                "vector_string": null,
                "score": 0.0
            },
            "cvss_severities": {
                "cvss_v3": {
                    "vector_string": null,
                    "score": 0.0
                },
                "cvss_v4": {
                    "vector_string": null,
                    "score": 0.0
                }
            },
            "cwes": [
                {
                    "cwe_id": "CWE-345",
                    "name": "Insufficient Verification of Data Authenticity"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "certifi"
            },
            "severity": "low",
            "vulnerable_version_range": ">= 2021.05.30, < 2024.07.04",
            "first_patched_version": {
                "identifier": "2024.07.04"
            }
        },
        "url": "https://api.github.com/repos/username/tensorflow/dependabot/alerts/17",
        "html_url": "https://github.com/username/tensorflow/security/dependabot/17",
        "created_at": "2024-07-06T02:04:05Z",
        "updated_at": "2024-07-06T02:04:05Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 16,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "urllib3"
            },
            "manifest_path": "requirements_lock_3_10.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-34jh-p97f-mpxf",
            "cve_id": "CVE-2024-37891",
            "summary": "urllib3's Proxy-Authorization request header isn't stripped during cross-origin redirects",
            "description": "When using urllib3's proxy support with `ProxyManager`, the `Proxy-Authorization` header is only sent to the configured proxy, as expected.\n\nHowever, when sending HTTP requests *without* using urllib3's proxy support, it's possible to accidentally configure the `Proxy-Authorization` header even though it won't have any effect as the request is not using a forwarding proxy or a tunneling proxy. In those cases, urllib3 doesn't treat the `Proxy-Authorization` HTTP header as one carrying authentication material and thus doesn't strip the header on cross-origin redirects.\n\nBecause this is a highly unlikely scenario, we believe the severity of this vulnerability is low for almost all users. Out of an abundance of caution urllib3 will automatically strip the `Proxy-Authorization` header during cross-origin redirects to avoid the small chance that users are doing this on accident.\n\nUsers should use urllib3's proxy support or disable automatic redirects to achieve safe processing of the `Proxy-Authorization` header, but we still decided to strip the header by default in order to further protect users who aren't using the correct approach.\n\n## Affected usages\n\nWe believe the number of usages affected by this advisory is low. It requires all of the following to be true to be exploited:\n\n* Setting the `Proxy-Authorization` header without using urllib3's built-in proxy support.\n* Not disabling HTTP redirects.\n* Either not using an HTTPS origin server or for the proxy or target origin to redirect to a malicious origin.\n\n## Remediation\n\n* Using the `Proxy-Authorization` header with urllib3's `ProxyManager`.\n* Disabling HTTP redirects using `redirects=False` when sending requests.\n* Not using the `Proxy-Authorization` header.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-34jh-p97f-mpxf",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-37891",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/urllib3/urllib3/security/advisories/GHSA-34jh-p97f-mpxf"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-37891"
                },
                {
                    "url": "https://github.com/urllib3/urllib3/commit/40b6d1605814dd1db0a46e202d6e56f2e4c9a468"
                },
                {
                    "url": "https://github.com/urllib3/urllib3/commit/accff72ecc2f6cf5a76d9570198a93ac7c90270e"
                },
                {
                    "url": "https://github.com/advisories/GHSA-34jh-p97f-mpxf"
                }
            ],
            "published_at": "2024-06-17T21:37:20Z",
            "updated_at": "2024-12-18T22:20:27Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "urllib3"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 1.26.19",
                    "first_patched_version": {
                        "identifier": "1.26.19"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "urllib3"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": ">= 2.0.0, < 2.2.2",
                    "first_patched_version": {
                        "identifier": "2.2.2"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N",
                "score": 4.4
            },
            "cvss_severities": {
                "cvss_v3": {
                    "vector_string": "CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N",
                    "score": 4.4
                },
                "cvss_v4": {
                    "vector_string": null,
                    "score": 0.0
                }
            },
            "cwes": [
                {
                    "cwe_id": "CWE-669",
                    "name": "Incorrect Resource Transfer Between Spheres"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "urllib3"
            },
            "severity": "medium",
            "vulnerable_version_range": ">= 2.0.0, < 2.2.2",
            "first_patched_version": {
                "identifier": "2.2.2"
            }
        },
        "url": "https://api.github.com/repos/username/tensorflow/dependabot/alerts/16",
        "html_url": "https://github.com/username/tensorflow/security/dependabot/16",
        "created_at": "2024-06-17T22:46:02Z",
        "updated_at": "2024-06-17T22:46:02Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 15,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "urllib3"
            },
            "manifest_path": "requirements_lock_3_9.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-34jh-p97f-mpxf",
            "cve_id": "CVE-2024-37891",
            "summary": "urllib3's Proxy-Authorization request header isn't stripped during cross-origin redirects",
            "description": "When using urllib3's proxy support with `ProxyManager`, the `Proxy-Authorization` header is only sent to the configured proxy, as expected.\n\nHowever, when sending HTTP requests *without* using urllib3's proxy support, it's possible to accidentally configure the `Proxy-Authorization` header even though it won't have any effect as the request is not using a forwarding proxy or a tunneling proxy. In those cases, urllib3 doesn't treat the `Proxy-Authorization` HTTP header as one carrying authentication material and thus doesn't strip the header on cross-origin redirects.\n\nBecause this is a highly unlikely scenario, we believe the severity of this vulnerability is low for almost all users. Out of an abundance of caution urllib3 will automatically strip the `Proxy-Authorization` header during cross-origin redirects to avoid the small chance that users are doing this on accident.\n\nUsers should use urllib3's proxy support or disable automatic redirects to achieve safe processing of the `Proxy-Authorization` header, but we still decided to strip the header by default in order to further protect users who aren't using the correct approach.\n\n## Affected usages\n\nWe believe the number of usages affected by this advisory is low. It requires all of the following to be true to be exploited:\n\n* Setting the `Proxy-Authorization` header without using urllib3's built-in proxy support.\n* Not disabling HTTP redirects.\n* Either not using an HTTPS origin server or for the proxy or target origin to redirect to a malicious origin.\n\n## Remediation\n\n* Using the `Proxy-Authorization` header with urllib3's `ProxyManager`.\n* Disabling HTTP redirects using `redirects=False` when sending requests.\n* Not using the `Proxy-Authorization` header.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-34jh-p97f-mpxf",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-37891",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/urllib3/urllib3/security/advisories/GHSA-34jh-p97f-mpxf"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-37891"
                },
                {
                    "url": "https://github.com/urllib3/urllib3/commit/40b6d1605814dd1db0a46e202d6e56f2e4c9a468"
                },
                {
                    "url": "https://github.com/urllib3/urllib3/commit/accff72ecc2f6cf5a76d9570198a93ac7c90270e"
                },
                {
                    "url": "https://github.com/advisories/GHSA-34jh-p97f-mpxf"
                }
            ],
            "published_at": "2024-06-17T21:37:20Z",
            "updated_at": "2024-12-18T22:20:27Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "urllib3"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 1.26.19",
                    "first_patched_version": {
                        "identifier": "1.26.19"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "urllib3"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": ">= 2.0.0, < 2.2.2",
                    "first_patched_version": {
                        "identifier": "2.2.2"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N",
                "score": 4.4
            },
            "cvss_severities": {
                "cvss_v3": {
                    "vector_string": "CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N",
                    "score": 4.4
                },
                "cvss_v4": {
                    "vector_string": null,
                    "score": 0.0
                }
            },
            "cwes": [
                {
                    "cwe_id": "CWE-669",
                    "name": "Incorrect Resource Transfer Between Spheres"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "urllib3"
            },
            "severity": "medium",
            "vulnerable_version_range": ">= 2.0.0, < 2.2.2",
            "first_patched_version": {
                "identifier": "2.2.2"
            }
        },
        "url": "https://api.github.com/repos/username/tensorflow/dependabot/alerts/15",
        "html_url": "https://github.com/username/tensorflow/security/dependabot/15",
        "created_at": "2024-06-17T22:46:02Z",
        "updated_at": "2024-06-17T22:46:02Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 14,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "urllib3"
            },
            "manifest_path": "requirements_lock_3_12.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-34jh-p97f-mpxf",
            "cve_id": "CVE-2024-37891",
            "summary": "urllib3's Proxy-Authorization request header isn't stripped during cross-origin redirects",
            "description": "When using urllib3's proxy support with `ProxyManager`, the `Proxy-Authorization` header is only sent to the configured proxy, as expected.\n\nHowever, when sending HTTP requests *without* using urllib3's proxy support, it's possible to accidentally configure the `Proxy-Authorization` header even though it won't have any effect as the request is not using a forwarding proxy or a tunneling proxy. In those cases, urllib3 doesn't treat the `Proxy-Authorization` HTTP header as one carrying authentication material and thus doesn't strip the header on cross-origin redirects.\n\nBecause this is a highly unlikely scenario, we believe the severity of this vulnerability is low for almost all users. Out of an abundance of caution urllib3 will automatically strip the `Proxy-Authorization` header during cross-origin redirects to avoid the small chance that users are doing this on accident.\n\nUsers should use urllib3's proxy support or disable automatic redirects to achieve safe processing of the `Proxy-Authorization` header, but we still decided to strip the header by default in order to further protect users who aren't using the correct approach.\n\n## Affected usages\n\nWe believe the number of usages affected by this advisory is low. It requires all of the following to be true to be exploited:\n\n* Setting the `Proxy-Authorization` header without using urllib3's built-in proxy support.\n* Not disabling HTTP redirects.\n* Either not using an HTTPS origin server or for the proxy or target origin to redirect to a malicious origin.\n\n## Remediation\n\n* Using the `Proxy-Authorization` header with urllib3's `ProxyManager`.\n* Disabling HTTP redirects using `redirects=False` when sending requests.\n* Not using the `Proxy-Authorization` header.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-34jh-p97f-mpxf",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-37891",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/urllib3/urllib3/security/advisories/GHSA-34jh-p97f-mpxf"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-37891"
                },
                {
                    "url": "https://github.com/urllib3/urllib3/commit/40b6d1605814dd1db0a46e202d6e56f2e4c9a468"
                },
                {
                    "url": "https://github.com/urllib3/urllib3/commit/accff72ecc2f6cf5a76d9570198a93ac7c90270e"
                },
                {
                    "url": "https://github.com/advisories/GHSA-34jh-p97f-mpxf"
                }
            ],
            "published_at": "2024-06-17T21:37:20Z",
            "updated_at": "2024-12-18T22:20:27Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "urllib3"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 1.26.19",
                    "first_patched_version": {
                        "identifier": "1.26.19"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "urllib3"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": ">= 2.0.0, < 2.2.2",
                    "first_patched_version": {
                        "identifier": "2.2.2"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N",
                "score": 4.4
            },
            "cvss_severities": {
                "cvss_v3": {
                    "vector_string": "CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N",
                    "score": 4.4
                },
                "cvss_v4": {
                    "vector_string": null,
                    "score": 0.0
                }
            },
            "cwes": [
                {
                    "cwe_id": "CWE-669",
                    "name": "Incorrect Resource Transfer Between Spheres"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "urllib3"
            },
            "severity": "medium",
            "vulnerable_version_range": ">= 2.0.0, < 2.2.2",
            "first_patched_version": {
                "identifier": "2.2.2"
            }
        },
        "url": "https://api.github.com/repos/username/tensorflow/dependabot/alerts/14",
        "html_url": "https://github.com/username/tensorflow/security/dependabot/14",
        "created_at": "2024-06-17T22:46:02Z",
        "updated_at": "2024-06-17T22:46:02Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 13,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "urllib3"
            },
            "manifest_path": "requirements_lock_3_11.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-34jh-p97f-mpxf",
            "cve_id": "CVE-2024-37891",
            "summary": "urllib3's Proxy-Authorization request header isn't stripped during cross-origin redirects",
            "description": "When using urllib3's proxy support with `ProxyManager`, the `Proxy-Authorization` header is only sent to the configured proxy, as expected.\n\nHowever, when sending HTTP requests *without* using urllib3's proxy support, it's possible to accidentally configure the `Proxy-Authorization` header even though it won't have any effect as the request is not using a forwarding proxy or a tunneling proxy. In those cases, urllib3 doesn't treat the `Proxy-Authorization` HTTP header as one carrying authentication material and thus doesn't strip the header on cross-origin redirects.\n\nBecause this is a highly unlikely scenario, we believe the severity of this vulnerability is low for almost all users. Out of an abundance of caution urllib3 will automatically strip the `Proxy-Authorization` header during cross-origin redirects to avoid the small chance that users are doing this on accident.\n\nUsers should use urllib3's proxy support or disable automatic redirects to achieve safe processing of the `Proxy-Authorization` header, but we still decided to strip the header by default in order to further protect users who aren't using the correct approach.\n\n## Affected usages\n\nWe believe the number of usages affected by this advisory is low. It requires all of the following to be true to be exploited:\n\n* Setting the `Proxy-Authorization` header without using urllib3's built-in proxy support.\n* Not disabling HTTP redirects.\n* Either not using an HTTPS origin server or for the proxy or target origin to redirect to a malicious origin.\n\n## Remediation\n\n* Using the `Proxy-Authorization` header with urllib3's `ProxyManager`.\n* Disabling HTTP redirects using `redirects=False` when sending requests.\n* Not using the `Proxy-Authorization` header.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-34jh-p97f-mpxf",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-37891",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/urllib3/urllib3/security/advisories/GHSA-34jh-p97f-mpxf"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-37891"
                },
                {
                    "url": "https://github.com/urllib3/urllib3/commit/40b6d1605814dd1db0a46e202d6e56f2e4c9a468"
                },
                {
                    "url": "https://github.com/urllib3/urllib3/commit/accff72ecc2f6cf5a76d9570198a93ac7c90270e"
                },
                {
                    "url": "https://github.com/advisories/GHSA-34jh-p97f-mpxf"
                }
            ],
            "published_at": "2024-06-17T21:37:20Z",
            "updated_at": "2024-12-18T22:20:27Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "urllib3"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 1.26.19",
                    "first_patched_version": {
                        "identifier": "1.26.19"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "urllib3"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": ">= 2.0.0, < 2.2.2",
                    "first_patched_version": {
                        "identifier": "2.2.2"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N",
                "score": 4.4
            },
            "cvss_severities": {
                "cvss_v3": {
                    "vector_string": "CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N",
                    "score": 4.4
                },
                "cvss_v4": {
                    "vector_string": null,
                    "score": 0.0
                }
            },
            "cwes": [
                {
                    "cwe_id": "CWE-669",
                    "name": "Incorrect Resource Transfer Between Spheres"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "urllib3"
            },
            "severity": "medium",
            "vulnerable_version_range": ">= 2.0.0, < 2.2.2",
            "first_patched_version": {
                "identifier": "2.2.2"
            }
        },
        "url": "https://api.github.com/repos/username/tensorflow/dependabot/alerts/13",
        "html_url": "https://github.com/username/tensorflow/security/dependabot/13",
        "created_at": "2024-06-17T22:46:02Z",
        "updated_at": "2024-06-17T22:46:02Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 12,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "requests"
            },
            "manifest_path": "requirements_lock_3_10.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-9wx4-h78v-vm56",
            "cve_id": "CVE-2024-35195",
            "summary": "Requests `Session` object does not verify requests after making first request with verify=False",
            "description": "When making requests through a Requests `Session`, if the first request is made with `verify=False` to disable cert verification, all subsequent requests to the same origin will continue to ignore cert verification regardless of changes to the value of `verify`. This behavior will continue for the lifecycle of the connection in the connection pool.\n\n### Remediation\nAny of these options can be used to remediate the current issue, we highly recommend upgrading as the preferred mitigation.\n\n* Upgrade to `requests>=2.32.0`.\n* For `requests<2.32.0`, avoid setting `verify=False` for the first request to a host while using a Requests Session.\n* For `requests<2.32.0`, call `close()` on `Session` objects to clear existing connections if `verify=False` is used.\n\n### Related Links\n* https://github.com/psf/requests/pull/6655",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-9wx4-h78v-vm56",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-35195",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56"
                },
                {
                    "url": "https://github.com/psf/requests/pull/6655"
                },
                {
                    "url": "https://github.com/psf/requests/commit/a58d7f2ffb4d00b46dca2d70a3932a0b37e22fac"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-35195"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IYLSNK5TL46Q6XPRVMHVWS63MVJQOK4Q"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N7WP6EYDSUOCOJYHDK5NX43PYZ4SNHGZ"
                },
                {
                    "url": "https://github.com/advisories/GHSA-9wx4-h78v-vm56"
                }
            ],
            "published_at": "2024-05-20T20:15:00Z",
            "updated_at": "2024-06-10T18:31:04Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "requests"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 2.32.0",
                    "first_patched_version": {
                        "identifier": "2.32.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N",
                "score": 5.6
            },
            "cvss_severities": {
                "cvss_v3": {
                    "vector_string": "CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N",
                    "score": 5.6
                },
                "cvss_v4": {
                    "vector_string": null,
                    "score": 0.0
                }
            },
            "cwes": [
                {
                    "cwe_id": "CWE-670",
                    "name": "Always-Incorrect Control Flow Implementation"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "requests"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 2.32.0",
            "first_patched_version": {
                "identifier": "2.32.0"
            }
        },
        "url": "https://api.github.com/repos/username/tensorflow/dependabot/alerts/12",
        "html_url": "https://github.com/username/tensorflow/security/dependabot/12",
        "created_at": "2024-05-21T08:36:34Z",
        "updated_at": "2024-05-21T08:36:34Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 11,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "requests"
            },
            "manifest_path": "requirements_lock_3_9.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-9wx4-h78v-vm56",
            "cve_id": "CVE-2024-35195",
            "summary": "Requests `Session` object does not verify requests after making first request with verify=False",
            "description": "When making requests through a Requests `Session`, if the first request is made with `verify=False` to disable cert verification, all subsequent requests to the same origin will continue to ignore cert verification regardless of changes to the value of `verify`. This behavior will continue for the lifecycle of the connection in the connection pool.\n\n### Remediation\nAny of these options can be used to remediate the current issue, we highly recommend upgrading as the preferred mitigation.\n\n* Upgrade to `requests>=2.32.0`.\n* For `requests<2.32.0`, avoid setting `verify=False` for the first request to a host while using a Requests Session.\n* For `requests<2.32.0`, call `close()` on `Session` objects to clear existing connections if `verify=False` is used.\n\n### Related Links\n* https://github.com/psf/requests/pull/6655",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-9wx4-h78v-vm56",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-35195",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56"
                },
                {
                    "url": "https://github.com/psf/requests/pull/6655"
                },
                {
                    "url": "https://github.com/psf/requests/commit/a58d7f2ffb4d00b46dca2d70a3932a0b37e22fac"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-35195"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IYLSNK5TL46Q6XPRVMHVWS63MVJQOK4Q"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N7WP6EYDSUOCOJYHDK5NX43PYZ4SNHGZ"
                },
                {
                    "url": "https://github.com/advisories/GHSA-9wx4-h78v-vm56"
                }
            ],
            "published_at": "2024-05-20T20:15:00Z",
            "updated_at": "2024-06-10T18:31:04Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "requests"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 2.32.0",
                    "first_patched_version": {
                        "identifier": "2.32.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N",
                "score": 5.6
            },
            "cvss_severities": {
                "cvss_v3": {
                    "vector_string": "CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N",
                    "score": 5.6
                },
                "cvss_v4": {
                    "vector_string": null,
                    "score": 0.0
                }
            },
            "cwes": [
                {
                    "cwe_id": "CWE-670",
                    "name": "Always-Incorrect Control Flow Implementation"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "requests"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 2.32.0",
            "first_patched_version": {
                "identifier": "2.32.0"
            }
        },
        "url": "https://api.github.com/repos/username/tensorflow/dependabot/alerts/11",
        "html_url": "https://github.com/username/tensorflow/security/dependabot/11",
        "created_at": "2024-05-21T08:36:34Z",
        "updated_at": "2024-05-21T08:36:34Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 10,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "requests"
            },
            "manifest_path": "requirements_lock_3_12.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-9wx4-h78v-vm56",
            "cve_id": "CVE-2024-35195",
            "summary": "Requests `Session` object does not verify requests after making first request with verify=False",
            "description": "When making requests through a Requests `Session`, if the first request is made with `verify=False` to disable cert verification, all subsequent requests to the same origin will continue to ignore cert verification regardless of changes to the value of `verify`. This behavior will continue for the lifecycle of the connection in the connection pool.\n\n### Remediation\nAny of these options can be used to remediate the current issue, we highly recommend upgrading as the preferred mitigation.\n\n* Upgrade to `requests>=2.32.0`.\n* For `requests<2.32.0`, avoid setting `verify=False` for the first request to a host while using a Requests Session.\n* For `requests<2.32.0`, call `close()` on `Session` objects to clear existing connections if `verify=False` is used.\n\n### Related Links\n* https://github.com/psf/requests/pull/6655",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-9wx4-h78v-vm56",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-35195",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56"
                },
                {
                    "url": "https://github.com/psf/requests/pull/6655"
                },
                {
                    "url": "https://github.com/psf/requests/commit/a58d7f2ffb4d00b46dca2d70a3932a0b37e22fac"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-35195"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IYLSNK5TL46Q6XPRVMHVWS63MVJQOK4Q"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N7WP6EYDSUOCOJYHDK5NX43PYZ4SNHGZ"
                },
                {
                    "url": "https://github.com/advisories/GHSA-9wx4-h78v-vm56"
                }
            ],
            "published_at": "2024-05-20T20:15:00Z",
            "updated_at": "2024-06-10T18:31:04Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "requests"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 2.32.0",
                    "first_patched_version": {
                        "identifier": "2.32.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N",
                "score": 5.6
            },
            "cvss_severities": {
                "cvss_v3": {
                    "vector_string": "CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N",
                    "score": 5.6
                },
                "cvss_v4": {
                    "vector_string": null,
                    "score": 0.0
                }
            },
            "cwes": [
                {
                    "cwe_id": "CWE-670",
                    "name": "Always-Incorrect Control Flow Implementation"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "requests"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 2.32.0",
            "first_patched_version": {
                "identifier": "2.32.0"
            }
        },
        "url": "https://api.github.com/repos/username/tensorflow/dependabot/alerts/10",
        "html_url": "https://github.com/username/tensorflow/security/dependabot/10",
        "created_at": "2024-05-21T08:36:34Z",
        "updated_at": "2024-05-21T08:36:34Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 9,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "requests"
            },
            "manifest_path": "requirements_lock_3_11.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-9wx4-h78v-vm56",
            "cve_id": "CVE-2024-35195",
            "summary": "Requests `Session` object does not verify requests after making first request with verify=False",
            "description": "When making requests through a Requests `Session`, if the first request is made with `verify=False` to disable cert verification, all subsequent requests to the same origin will continue to ignore cert verification regardless of changes to the value of `verify`. This behavior will continue for the lifecycle of the connection in the connection pool.\n\n### Remediation\nAny of these options can be used to remediate the current issue, we highly recommend upgrading as the preferred mitigation.\n\n* Upgrade to `requests>=2.32.0`.\n* For `requests<2.32.0`, avoid setting `verify=False` for the first request to a host while using a Requests Session.\n* For `requests<2.32.0`, call `close()` on `Session` objects to clear existing connections if `verify=False` is used.\n\n### Related Links\n* https://github.com/psf/requests/pull/6655",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-9wx4-h78v-vm56",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-35195",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56"
                },
                {
                    "url": "https://github.com/psf/requests/pull/6655"
                },
                {
                    "url": "https://github.com/psf/requests/commit/a58d7f2ffb4d00b46dca2d70a3932a0b37e22fac"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-35195"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IYLSNK5TL46Q6XPRVMHVWS63MVJQOK4Q"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N7WP6EYDSUOCOJYHDK5NX43PYZ4SNHGZ"
                },
                {
                    "url": "https://github.com/advisories/GHSA-9wx4-h78v-vm56"
                }
            ],
            "published_at": "2024-05-20T20:15:00Z",
            "updated_at": "2024-06-10T18:31:04Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "requests"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 2.32.0",
                    "first_patched_version": {
                        "identifier": "2.32.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N",
                "score": 5.6
            },
            "cvss_severities": {
                "cvss_v3": {
                    "vector_string": "CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N",
                    "score": 5.6
                },
                "cvss_v4": {
                    "vector_string": null,
                    "score": 0.0
                }
            },
            "cwes": [
                {
                    "cwe_id": "CWE-670",
                    "name": "Always-Incorrect Control Flow Implementation"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "requests"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 2.32.0",
            "first_patched_version": {
                "identifier": "2.32.0"
            }
        },
        "url": "https://api.github.com/repos/username/tensorflow/dependabot/alerts/9",
        "html_url": "https://github.com/username/tensorflow/security/dependabot/9",
        "created_at": "2024-05-21T08:36:33Z",
        "updated_at": "2024-05-21T08:36:33Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 8,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "certifi"
            },
            "manifest_path": "tensorflow/tools/ci_build/release/requirements_mac.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-xqr8-7jwr-rhp7",
            "cve_id": "CVE-2023-37920",
            "summary": "Removal of e-Tugra root certificate",
            "description": "Certifi 2023.07.22 removes root certificates from \"e-Tugra\" from the root store. These are in the process of being removed from Mozilla's trust store.\n\n e-Tugra's root certificates are being removed pursuant to an investigation prompted by reporting of security issues in their systems. Conclusions of Mozilla's investigation can be found [here](https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/C-HrP1SEq1A).",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-xqr8-7jwr-rhp7",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-37920",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/certifi/python-certifi/security/advisories/GHSA-xqr8-7jwr-rhp7"
                },
                {
                    "url": "https://github.com/certifi/python-certifi/commit/8fb96ed81f71e7097ed11bc4d9b19afd7ea5c909"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-37920"
                },
                {
                    "url": "https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/C-HrP1SEq1A"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/certifi/PYSEC-2023-135.yaml"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5EX6NG7WUFNUKGFHLM35KHHU3GAKXRTG/"
                },
                {
                    "url": "https://github.com/advisories/GHSA-xqr8-7jwr-rhp7"
                }
            ],
            "published_at": "2023-07-25T14:43:53Z",
            "updated_at": "2023-11-09T05:05:47Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "certifi"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 2015.4.28, < 2023.7.22",
                    "first_patched_version": {
                        "identifier": "2023.7.22"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
                "score": 7.5
            },
            "cvss_severities": {
                "cvss_v3": {
                    "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
                    "score": 7.5
                },
                "cvss_v4": {
                    "vector_string": null,
                    "score": 0.0
                }
            },
            "cwes": [
                {
                    "cwe_id": "CWE-345",
                    "name": "Insufficient Verification of Data Authenticity"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "certifi"
            },
            "severity": "high",
            "vulnerable_version_range": ">= 2015.4.28, < 2023.7.22",
            "first_patched_version": {
                "identifier": "2023.7.22"
            }
        },
        "url": "https://api.github.com/repos/username/tensorflow/dependabot/alerts/8",
        "html_url": "https://github.com/username/tensorflow/security/dependabot/8",
        "created_at": "2024-05-16T22:09:34Z",
        "updated_at": "2024-05-16T22:09:34Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 7,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "Werkzeug"
            },
            "manifest_path": "requirements_lock_3_9.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-2g68-c3qc-8985",
            "cve_id": "CVE-2024-34069",
            "summary": "Werkzeug debugger vulnerable to remote execution when interacting with attacker controlled domain",
            "description": "The debugger in affected versions of Werkzeug can allow an attacker to execute code on a developer's machine under some circumstances. This requires the attacker to get the developer to interact with a domain and subdomain they control, and enter the debugger PIN, but if they are successful it allows access to the debugger even if it is only running on localhost. This also requires the attacker to guess a URL in the developer's application that will trigger the debugger.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-2g68-c3qc-8985",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-34069",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/pallets/werkzeug/security/advisories/GHSA-2g68-c3qc-8985"
                },
                {
                    "url": "https://github.com/pallets/werkzeug/commit/3386395b24c7371db11a5b8eaac0c91da5362692"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-34069"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/H4SH32AM3CTPMAAEOIDAN7VU565LO4IR"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HFERFN7PINV4MOGMGA3DPIXJPDCYOEJZ"
                },
                {
                    "url": "https://security.netapp.com/advisory/ntap-20240614-0004"
                },
                {
                    "url": "https://github.com/advisories/GHSA-2g68-c3qc-8985"
                }
            ],
            "published_at": "2024-05-06T14:21:27Z",
            "updated_at": "2024-06-14T15:31:25Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Werkzeug"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 3.0.3",
                    "first_patched_version": {
                        "identifier": "3.0.3"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H",
                "score": 7.5
            },
            "cvss_severities": {
                "cvss_v3": {
                    "vector_string": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H",
                    "score": 7.5
                },
                "cvss_v4": {
                    "vector_string": null,
                    "score": 0.0
                }
            },
            "cwes": [
                {
                    "cwe_id": "CWE-352",
                    "name": "Cross-Site Request Forgery (CSRF)"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "Werkzeug"
            },
            "severity": "high",
            "vulnerable_version_range": "< 3.0.3",
            "first_patched_version": {
                "identifier": "3.0.3"
            }
        },
        "url": "https://api.github.com/repos/username/tensorflow/dependabot/alerts/7",
        "html_url": "https://github.com/username/tensorflow/security/dependabot/7",
        "created_at": "2024-05-16T22:09:34Z",
        "updated_at": "2024-05-16T22:09:34Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 6,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "Werkzeug"
            },
            "manifest_path": "requirements_lock_3_12.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-2g68-c3qc-8985",
            "cve_id": "CVE-2024-34069",
            "summary": "Werkzeug debugger vulnerable to remote execution when interacting with attacker controlled domain",
            "description": "The debugger in affected versions of Werkzeug can allow an attacker to execute code on a developer's machine under some circumstances. This requires the attacker to get the developer to interact with a domain and subdomain they control, and enter the debugger PIN, but if they are successful it allows access to the debugger even if it is only running on localhost. This also requires the attacker to guess a URL in the developer's application that will trigger the debugger.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-2g68-c3qc-8985",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-34069",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/pallets/werkzeug/security/advisories/GHSA-2g68-c3qc-8985"
                },
                {
                    "url": "https://github.com/pallets/werkzeug/commit/3386395b24c7371db11a5b8eaac0c91da5362692"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-34069"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/H4SH32AM3CTPMAAEOIDAN7VU565LO4IR"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HFERFN7PINV4MOGMGA3DPIXJPDCYOEJZ"
                },
                {
                    "url": "https://security.netapp.com/advisory/ntap-20240614-0004"
                },
                {
                    "url": "https://github.com/advisories/GHSA-2g68-c3qc-8985"
                }
            ],
            "published_at": "2024-05-06T14:21:27Z",
            "updated_at": "2024-06-14T15:31:25Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Werkzeug"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 3.0.3",
                    "first_patched_version": {
                        "identifier": "3.0.3"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H",
                "score": 7.5
            },
            "cvss_severities": {
                "cvss_v3": {
                    "vector_string": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H",
                    "score": 7.5
                },
                "cvss_v4": {
                    "vector_string": null,
                    "score": 0.0
                }
            },
            "cwes": [
                {
                    "cwe_id": "CWE-352",
                    "name": "Cross-Site Request Forgery (CSRF)"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "Werkzeug"
            },
            "severity": "high",
            "vulnerable_version_range": "< 3.0.3",
            "first_patched_version": {
                "identifier": "3.0.3"
            }
        },
        "url": "https://api.github.com/repos/username/tensorflow/dependabot/alerts/6",
        "html_url": "https://github.com/username/tensorflow/security/dependabot/6",
        "created_at": "2024-05-16T22:09:34Z",
        "updated_at": "2024-05-16T22:09:34Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 5,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "Werkzeug"
            },
            "manifest_path": "requirements_lock_3_11.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-2g68-c3qc-8985",
            "cve_id": "CVE-2024-34069",
            "summary": "Werkzeug debugger vulnerable to remote execution when interacting with attacker controlled domain",
            "description": "The debugger in affected versions of Werkzeug can allow an attacker to execute code on a developer's machine under some circumstances. This requires the attacker to get the developer to interact with a domain and subdomain they control, and enter the debugger PIN, but if they are successful it allows access to the debugger even if it is only running on localhost. This also requires the attacker to guess a URL in the developer's application that will trigger the debugger.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-2g68-c3qc-8985",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-34069",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/pallets/werkzeug/security/advisories/GHSA-2g68-c3qc-8985"
                },
                {
                    "url": "https://github.com/pallets/werkzeug/commit/3386395b24c7371db11a5b8eaac0c91da5362692"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-34069"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/H4SH32AM3CTPMAAEOIDAN7VU565LO4IR"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HFERFN7PINV4MOGMGA3DPIXJPDCYOEJZ"
                },
                {
                    "url": "https://security.netapp.com/advisory/ntap-20240614-0004"
                },
                {
                    "url": "https://github.com/advisories/GHSA-2g68-c3qc-8985"
                }
            ],
            "published_at": "2024-05-06T14:21:27Z",
            "updated_at": "2024-06-14T15:31:25Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Werkzeug"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 3.0.3",
                    "first_patched_version": {
                        "identifier": "3.0.3"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H",
                "score": 7.5
            },
            "cvss_severities": {
                "cvss_v3": {
                    "vector_string": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H",
                    "score": 7.5
                },
                "cvss_v4": {
                    "vector_string": null,
                    "score": 0.0
                }
            },
            "cwes": [
                {
                    "cwe_id": "CWE-352",
                    "name": "Cross-Site Request Forgery (CSRF)"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "Werkzeug"
            },
            "severity": "high",
            "vulnerable_version_range": "< 3.0.3",
            "first_patched_version": {
                "identifier": "3.0.3"
            }
        },
        "url": "https://api.github.com/repos/username/tensorflow/dependabot/alerts/5",
        "html_url": "https://github.com/username/tensorflow/security/dependabot/5",
        "created_at": "2024-05-16T22:09:34Z",
        "updated_at": "2024-05-16T22:09:34Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 4,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "Werkzeug"
            },
            "manifest_path": "requirements_lock_3_10.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-2g68-c3qc-8985",
            "cve_id": "CVE-2024-34069",
            "summary": "Werkzeug debugger vulnerable to remote execution when interacting with attacker controlled domain",
            "description": "The debugger in affected versions of Werkzeug can allow an attacker to execute code on a developer's machine under some circumstances. This requires the attacker to get the developer to interact with a domain and subdomain they control, and enter the debugger PIN, but if they are successful it allows access to the debugger even if it is only running on localhost. This also requires the attacker to guess a URL in the developer's application that will trigger the debugger.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-2g68-c3qc-8985",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2024-34069",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/pallets/werkzeug/security/advisories/GHSA-2g68-c3qc-8985"
                },
                {
                    "url": "https://github.com/pallets/werkzeug/commit/3386395b24c7371db11a5b8eaac0c91da5362692"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-34069"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/H4SH32AM3CTPMAAEOIDAN7VU565LO4IR"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HFERFN7PINV4MOGMGA3DPIXJPDCYOEJZ"
                },
                {
                    "url": "https://security.netapp.com/advisory/ntap-20240614-0004"
                },
                {
                    "url": "https://github.com/advisories/GHSA-2g68-c3qc-8985"
                }
            ],
            "published_at": "2024-05-06T14:21:27Z",
            "updated_at": "2024-06-14T15:31:25Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "Werkzeug"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 3.0.3",
                    "first_patched_version": {
                        "identifier": "3.0.3"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H",
                "score": 7.5
            },
            "cvss_severities": {
                "cvss_v3": {
                    "vector_string": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H",
                    "score": 7.5
                },
                "cvss_v4": {
                    "vector_string": null,
                    "score": 0.0
                }
            },
            "cwes": [
                {
                    "cwe_id": "CWE-352",
                    "name": "Cross-Site Request Forgery (CSRF)"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "Werkzeug"
            },
            "severity": "high",
            "vulnerable_version_range": "< 3.0.3",
            "first_patched_version": {
                "identifier": "3.0.3"
            }
        },
        "url": "https://api.github.com/repos/username/tensorflow/dependabot/alerts/4",
        "html_url": "https://github.com/username/tensorflow/security/dependabot/4",
        "created_at": "2024-05-16T22:09:34Z",
        "updated_at": "2024-05-16T22:09:34Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 3,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "grpcio"
            },
            "manifest_path": "ci/official/containers/linux_arm64/devel.usertools/test.requirements.txt",
            "scope": "development"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-9hxf-ppjv-w6rq",
            "cve_id": "CVE-2023-32732",
            "summary": "gRPC connection termination issue",
            "description": "gRPC contains a vulnerability whereby a client can cause a termination of connection between a HTTP2 proxy and a gRPC server: a base64 encoding error for `-bin` suffixed headers will result in a disconnection by the gRPC server, but is typically allowed by HTTP2 proxies. We recommend upgrading beyond the commit in https://github.com/grpc/grpc/pull/32309.\n",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-9hxf-ppjv-w6rq",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-32732",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-32732"
                },
                {
                    "url": "https://github.com/grpc/grpc/pull/32309"
                },
                {
                    "url": "https://github.com/grpc/grpc/releases/tag/v1.53.1"
                },
                {
                    "url": "https://github.com/rubysec/ruby-advisory-db/blob/master/gems/grpc/CVE-2023-32732.yml"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/37IDNVY5AWVH7JDMM2SDTL24ZPPZJNSY/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/VWE44J5FG7THHL7XVEVTNIGEYBNKJBLL/"
                },
                {
                    "url": "https://github.com/advisories/GHSA-9hxf-ppjv-w6rq"
                }
            ],
            "published_at": "2023-07-06T21:15:08Z",
            "updated_at": "2023-11-11T05:06:16Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "maven",
                        "name": "io.grpc:grpc-protobuf"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 1.53.0",
                    "first_patched_version": {
                        "identifier": "1.53.0"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "grpcio"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 1.53.0",
                    "first_patched_version": {
                        "identifier": "1.53.0"
                    }
                },
                {
                    "package": {
                        "ecosystem": "rubygems",
                        "name": "grpc"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 1.53.0",
                    "first_patched_version": {
                        "identifier": "1.53.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
                "score": 5.3
            },
            "cvss_severities": {
                "cvss_v3": {
                    "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
                    "score": 5.3
                },
                "cvss_v4": {
                    "vector_string": null,
                    "score": 0.0
                }
            },
            "cwes": [
                {
                    "cwe_id": "CWE-440",
                    "name": "Expected Behavior Violation"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "grpcio"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 1.53.0",
            "first_patched_version": {
                "identifier": "1.53.0"
            }
        },
        "url": "https://api.github.com/repos/username/tensorflow/dependabot/alerts/3",
        "html_url": "https://github.com/username/tensorflow/security/dependabot/3",
        "created_at": "2024-05-16T22:09:34Z",
        "updated_at": "2024-05-16T22:09:34Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 2,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "grpcio"
            },
            "manifest_path": "ci/official/containers/linux_arm64/devel.usertools/test.requirements.txt",
            "scope": "development"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-6628-q6j9-w8vg",
            "cve_id": "CVE-2023-1428",
            "summary": "gRPC Reachable Assertion issue",
            "description": "There exists an vulnerability causing an abort() to be called in gRPC. \nThe following headers cause gRPC's C++ implementation to abort() when called via http2:\n\nte: x (x != trailers)\n\n:scheme: x (x != http, https)\n\ngrpclb_client_stats: x (x == anything)\n\nOn top of sending one of those headers, a later header must be sent that gets the total header size past 8KB. We recommend upgrading past git commit 2485fa94bd8a723e5c977d55a3ce10b301b437f8 or v1.53 and above.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-6628-q6j9-w8vg",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-1428",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-1428"
                },
                {
                    "url": "https://github.com/grpc/grpc/commit/2485fa94bd8a723e5c977d55a3ce10b301b437f8"
                },
                {
                    "url": "https://github.com/grpc/grpc/issues/33463"
                },
                {
                    "url": "https://github.com/rubysec/ruby-advisory-db/blob/master/gems/grpc/CVE-2023-1428.yml"
                },
                {
                    "url": "https://github.com/advisories/GHSA-6628-q6j9-w8vg"
                }
            ],
            "published_at": "2023-07-06T21:15:08Z",
            "updated_at": "2023-11-10T05:00:50Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "maven",
                        "name": "io.grpc:grpc-protobuf"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 1.53.0",
                    "first_patched_version": {
                        "identifier": "1.53.0"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "grpcio"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 1.53.0",
                    "first_patched_version": {
                        "identifier": "1.53.0"
                    }
                },
                {
                    "package": {
                        "ecosystem": "rubygems",
                        "name": "grpc"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 1.53.0",
                    "first_patched_version": {
                        "identifier": "1.53.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cvss_severities": {
                "cvss_v3": {
                    "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                    "score": 7.5
                },
                "cvss_v4": {
                    "vector_string": null,
                    "score": 0.0
                }
            },
            "cwes": [
                {
                    "cwe_id": "CWE-617",
                    "name": "Reachable Assertion"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "grpcio"
            },
            "severity": "high",
            "vulnerable_version_range": "< 1.53.0",
            "first_patched_version": {
                "identifier": "1.53.0"
            }
        },
        "url": "https://api.github.com/repos/username/tensorflow/dependabot/alerts/2",
        "html_url": "https://github.com/username/tensorflow/security/dependabot/2",
        "created_at": "2024-05-16T22:09:34Z",
        "updated_at": "2024-05-16T22:09:34Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 1,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "grpcio"
            },
            "manifest_path": "ci/official/containers/linux_arm64/devel.usertools/test.requirements.txt",
            "scope": "development"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-cfgp-2977-2fmm",
            "cve_id": "CVE-2023-32731",
            "summary": "Connection confusion in gRPC",
            "description": "When gRPC HTTP2 stack raised a header size exceeded error, it skipped parsing the rest of the HPACK frame. This caused any HPACK table mutations to also be skipped, resulting in a desynchronization of HPACK tables between sender and receiver. If leveraged, say, between a proxy and a backend, this could lead to requests from the proxy being interpreted as containing headers from different proxy clients - leading to an information leak that can be used for privilege escalation or data exfiltration. We recommend upgrading beyond the commit contained in  https://github.com/grpc/grpc/pull/32309",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-cfgp-2977-2fmm",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-32731",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-32731"
                },
                {
                    "url": "https://github.com/grpc/grpc/pull/32309"
                },
                {
                    "url": "https://github.com/grpc/grpc/pull/33005"
                },
                {
                    "url": "https://github.com/grpc/grpc/issues/33463"
                },
                {
                    "url": "https://github.com/rubysec/ruby-advisory-db/blob/master/gems/grpc/CVE-2023-32731.yml"
                },
                {
                    "url": "https://github.com/advisories/GHSA-cfgp-2977-2fmm"
                }
            ],
            "published_at": "2023-07-05T19:12:51Z",
            "updated_at": "2023-11-10T05:00:35Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "maven",
                        "name": "io.grpc:grpc-protobuf"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 1.53.0",
                    "first_patched_version": {
                        "identifier": "1.53.0"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "grpcio"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 1.53.0",
                    "first_patched_version": {
                        "identifier": "1.53.0"
                    }
                },
                {
                    "package": {
                        "ecosystem": "rubygems",
                        "name": "grpc"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 1.53.0",
                    "first_patched_version": {
                        "identifier": "1.53.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:H",
                "score": 7.4
            },
            "cvss_severities": {
                "cvss_v3": {
                    "vector_string": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:H",
                    "score": 7.4
                },
                "cvss_v4": {
                    "vector_string": null,
                    "score": 0.0
                }
            },
            "cwes": [
                {
                    "cwe_id": "CWE-440",
                    "name": "Expected Behavior Violation"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "grpcio"
            },
            "severity": "high",
            "vulnerable_version_range": "< 1.53.0",
            "first_patched_version": {
                "identifier": "1.53.0"
            }
        },
        "url": "https://api.github.com/repos/username/tensorflow/dependabot/alerts/1",
        "html_url": "https://github.com/username/tensorflow/security/dependabot/1",
        "created_at": "2024-05-16T22:09:33Z",
        "updated_at": "2024-05-16T22:09:33Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    }
]